### ISSUE TITLE
Provide custom logical format in col_logical()

### ISSUE THREAD

**Issue by kiernann** [tidyverse/readr#1005]
(Read feature request)

It would be cool if you could provide the character format for logical variables (like you can for dates).

The [`batman::to_logical()`](https://github.com/Ironholds/batman/blob/master/R/batman.R) function is pretty good for this after the fact, but it would be _awesome_ if you could do it all in the initial `readr` function.

Something like this:

```
read_csv(
  file = "x\nY\nN\nY\nY\nN",
  col_types = cols(x = col_logical(true = "Y", false = "N"))
)
```

Or maybe this:

```
read_csv(
  file = "x\nY\nN\nY\nY\nN",
  col_types = cols(x = col_logical(format = "Y/N"))
)
```

**Comment by jimhester** [comment]
Unfortunately I don't think it is worth the complexity cost to implement this in readr, so I am going to close this issue.
