### ISSUE TITLE
Why parse_number() removes decimal digits if there are at least 7 digits in the number?

### ISSUE THREAD

**Issue by GegznaV** [tidyverse/readr#1007]
See the code from the examples section of `readr::parse_number` documentation (https://readr.tidyverse.org/reference/parse_number.html#examples): 

``` r
readr::parse_number("1,234,567.78")
#> [1] 1234568
```

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I noticed two digits `7` and `7` which were around `.` are gone. I expect 1234567.78 as the answer. The further investigation gave these results:

``` r
readr::parse_number("12,345.12") # OK
#> [1] 12345.12
readr::parse_number("12345.12") # OK
#> [1] 12345.12
readr::parse_number("123456.12") # 2 is missing
#> [1] 123456.1
readr::parse_number("1234567.12") # .12 is missing
#> [1] 1234567
readr::parse_number("1,234,567.12") # rounded, NOT OK
#> [1] 1234567
readr::parse_number("12,345.123456789") # rounded, NOT OK
#> [1] 12345.12
readr::parse_number("0.123456789") # rounded, NOT OK
#> [1] 0.1234568
```

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

 It seems that some rounding is taking place if more than 7 digits are present in the number. Is it expected? How can it be controlled? I expect warning in case the precision of the data is changed. At least, this behavior should be well documented. 

Is number 7 somehow magical? 

`readr` version 1.3.1

**Comment by jimhester** [comment]
7 is not magical, it just happens to be the default value of `options("digits")`, which R uses to display the maximum number of digits in the default print method. The values are actually being read fully, R is just rounding them for display when printing.

``` r
x <- readr::parse_number("1,234,567.78")
x
#> [1] 1234568
print(x, digits = 10)
#> [1] 1234567.78
```

<sup>Created on 2019-07-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
