### ISSUE TITLE
Readr install fails on OpenBSD

### ISSUE THREAD

**Issue by chipkoziara** [tidyverse/readr#1008]
I cannot get readr to install on OpenBSD. I tried installing readr via install.packages and devtools.

Here's the error I receive:
```
** testing if installed package can be loaded
Error: package or namespace load failed for ‘readr’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/chip/R/x86_64-unknown-openbsd6.5-library/3.5/readr/libs/readr.so':
  Cannot load specified object
Error: loading failed
Execution halted
ERROR: loading failed
```

If helpful, here is the [entire output](https://github.com/tidyverse/readr/files/3365684/readr_output.txt) I receive.

My session info is:
```
R version 3.5.3 (2019-03-11)
Platform: x86_64-unknown-openbsd6.5 (64-bit)
Running under: OpenBSD 6.5 GENERIC#3 amd64

Matrix products: default
BLAS: /usr/local/lib/R/lib/libRblas.so.34.2
LAPACK: /usr/local/lib/R/lib/libRlapack.so.34.2

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.5.3
```

I installed a R on fresh install of OpenBSD 6.5 and all other R packages (including the tidyverse) build without issue.

This appears to be related to [Issue #919](https://github.com/tidyverse/readr/issues/919), but I wasn't able to resolve this with any of the suggestions in that thread.

I am able to install readr 1.2.1, but both 1.3.0 and 1.3.1 produce the above error.

Any suggestions or fixes are greatly appreciated! Thank you!

**Comment by zeloff** [comment]
Fixed by e08d1324fa83c94c3cbaa2d64e4f77e8ba98203b
