### ISSUE TITLE
Return tibble with zero rows when file is empty

### ISSUE THREAD

**Issue by knausb** [tidyverse/readr#1015]
Hello and thank you for readr! I'm encountering the below issue. The reason for the error is that the file is empty, so there is nothing to read in. This is frustrating for me because this directory contains 225 of these files, most of which do have contents. (This file with no contents is a bad sample.) My opinion is that a friendlier behaviour would be to return a tibble with zero rows. In my example I have specified that there are 6 columns, so a tibble with 6 columns and zero rows could be returned. This would allow me to handle these bad samples instead of generating errors which break my loop. My guestimate is that processing the whole directory will take around 7 hours, so it would be nice to be able to walk away from it or process it over night. Instead, it requires attention each time I encounter one of these bad samples.

Thank you!

[nanopore_Abad_contig0001.pileup.gz](https://github.com/tidyverse/readr/files/3422767/nanopore_Abad_contig0001.pileup.gz)

``` r
library(readr)
dp <- read_tsv("mpileup2/nanopore_Abad_contig0001.pileup.gz", col_names = FALSE,
               col_types = "cicicc", n_max = Inf, guess_max = 10,
               progress = FALSE)
#> Error: 'mpileup2/nanopore_Abad_contig0001.pileup.gz' does not exist in current working directory ('/tmp/RtmpxBszRi/reprex363020c560ef').
sessionInfo()
#> R version 3.6.0 (2019-04-26)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 16.04.6 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/libblas/libblas.so.3.6.0
#> LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] readr_1.3.1
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.1      crayon_1.3.4    digest_0.6.18   R6_2.3.0       
#>  [5] magrittr_1.5    evaluate_0.14   pillar_1.4.1    highr_0.7      
#>  [9] rlang_0.3.0.1   stringi_1.2.4   rmarkdown_1.13  tools_3.6.0    
#> [13] stringr_1.3.1   hms_0.4.2       xfun_0.7        yaml_2.2.0     
#> [17] compiler_3.6.0  pkgconfig_2.0.2 htmltools_0.3.6 knitr_1.23     
#> [21] tibble_2.1.3
```

<sup>Created on 2019-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
This only happens when trying to read gzipped files, normal files will return a 0x0 tibble in this case.

You could also use [vroom](https://vroom.r-lib.org), which returns a 0x0 tibble for both the compressed and uncompressed cases.

Alternatively you could use purpose built tools for the pileup format, e.g. `Rsamtools::readPileup()`.

**Comment by knausb** [comment]
Thanks for the speedy response! I've never heard of vroom, so I'll have to give it a look. Curiously, while I use samtools regularly, I've never tried Rsamtools. Didn't even consider it because the file is tabular. So I'll give that a look see too. Thanks!
