### ISSUE TITLE
type_convert doesn't doesn't convert 

### ISSUE THREAD

**Issue by vnijs** [tidyverse/readr#1019]
`type_convert` doesn't make changes but also doesn't throw an error or warning. See example below.

Note: There is an example on Data Camp in the readr course that uses this approach but it is not clear how this is supposed to work.

https://campus.datacamp.com/courses/reading-data-into-r-with-readr/parsing-data-with-readr?ex=1

``` r
tbl <- tibble::tibble(
  Girth = rnorm(100, 9, 1),
  Height = round(rnorm(100, 70, 10), 0),
  Volume = rnorm(100, 15, 5)
)

library(readr)
type_convert(
  tbl, 
  col_types = cols(
    Girth = col_double(),
    Height = col_integer(),
    Volume = col_double()
  )
)
#> # A tibble: 100 x 3
#>    Girth Height Volume
#>    <dbl>  <dbl>  <dbl>
#>  1  8.90     75  13.9 
#>  2  8.02     67  14.0 
#>  3  9.59     58  11.2 
#>  4  7.92     85  17.0 
#>  5  7.95     71  16.6 
#>  6  7.26     79  11.5 
#>  7 10.5      74  13.6 
#>  8  9.34     79   9.55
#>  9  8.51     84  17.6 
#> 10  9.88     72  11.3 
#> # … with 90 more rows

type_convert(
  tbl, 
  col_types = cols(
    Girth = "d",
    Height = "i",
    Volume = "d"
  )
)
#> # A tibble: 100 x 3
#>    Girth Height Volume
#>    <dbl>  <dbl>  <dbl>
#>  1  8.90     75  13.9 
#>  2  8.02     67  14.0 
#>  3  9.59     58  11.2 
#>  4  7.92     85  17.0 
#>  5  7.95     71  16.6 
#>  6  7.26     79  11.5 
#>  7 10.5      74  13.6 
#>  8  9.34     79   9.55
#>  9  8.51     84  17.6 
#> 10  9.88     72  11.3 
#> # … with 90 more rows
```

<sup>Created on 2019-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
Type convert is for converting characters to other types, it doesn't support converting anything to anything else.

**Comment by vnijs** [comment]
Thanks for the clarification @jimhester. Does it make sense for `type_convert` to print a warning in  cases like the above?

**Comment by jimhester** [comment]
Maybe it would, could you open a new issue suggesting we have a warning if there are no character inputs or the supplied classes are different than the actual classes?
