### ISSUE TITLE
read_delim accept data frame

### ISSUE THREAD

**Issue by jxu** [tidyverse/readr#1021]
A not uncommon task for me is to parse an entire data frame of strings into columns of the correct type. This can be done by writing a string and reading it, or transforming `parse_guess` with `plyr::colwise`, but this would be cleaner if we had a `read_delim` method that took in a data frame / tibble.

**Comment by jennybc** [comment]
I think `readr::type_convert()` might be what you're looking for.

**Comment by jxu** [comment]
You're absolutely right. I guess the naming is a little confusing because base R `type.convert` takes in a character vector.
