### ISSUE TITLE
Automatically convert github links to follow the raw link???

### ISSUE THREAD

**Issue by jimhester** [tidyverse/readr#1023]
Maybe readr should detect GitHub links and automatically convert them to the raw links, so you don't have to copy paste the raw link, e.g. 
```r
# This
readr::read_csv("https://github.com/zonination/pokemon-chart/blob/master/chart.csv")

# rather than this
readr::read_csv("https://raw.githubusercontent.com/zonination/pokemon-chart/master/chart.csv")
```

Many people may not be aware of the distinction, and not understand why readr is unable to parse the former, as the URL makes it look like CSV even though it is actually HTML.

**Comment by msberends** [comment]
Great! Then please also support GitLab, that uses this url logic:

```
# This
https://gitlab.com/zonination/pokemon-chart/blob/master/chart.csv

# rather than this
https://gitlab.com/zonination/pokemon-chart/raw/master/chart.csv
```

I think tidyverse could embrace GitLab a bit more 😊

**Comment by centilmen2020** [comment]
#EXTM3U
#EXTINF:-1,TRT 4K 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/22852
#EXTINF:-1,TRT 1 FHD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14230
#EXTINF:-1,STAR TV FHD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14223
#EXTINF:-1,KANAL D FHD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14222
#EXTINF:-1,ATV FHD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14221
#EXTINF:-1,SHOW TV FHD
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14226
#EXTINF:-1,FOX FHD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14224
#EXTINF:-1,TV8 FHD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14225
#EXTINF:-1,TV 8.5 HD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14436
#EXTINF:-1,TEVE 2 HD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14228
#EXTINF:-1,A2 FHD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/16827
#EXTINF:-1,BEYAZ TV FHD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14229
#EXTINF:-1,TV 360 FHD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/5114
#EXTINF:-1,A HABER FHD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14232
#EXTINF:-1,HABER TURK HD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14235
#EXTINF:-1,CNN TÜRK HD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14234
#EXTINF:-1,TRT Haber 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/27121
#EXTINF:-1,TV 100 HD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/28201
#EXTINF:-1,NTV FHD 
http://mag.rapidswiss.hitv.one:80/onl9q1p3205/DhBi9t8642/14233

**Comment by jimhester** [comment]
While this would be useful, I don't think it is a big problem for most people in practice.
