### ISSUE TITLE
Enable writing to textConnection objects

### ISSUE THREAD

**Issue by antoine-sachet** [tidyverse/readr#1026]
I am writing an API that can return data formatted as CSV, and for that I want to be able to save CSV data in a string (that I can put in a request) rather than a file.

I am aware I could write to a temporary file then read the file as a string, however it seems more natural to write directly to a string.

With `write.csv`, this can be achieved with a `textConnection`

``` r
write.csv(head(mtcars), textConnection("str1", open = "w"))
str1
#> [1] "\"\",\"mpg\",\"cyl\",\"disp\",\"hp\",\"drat\",\"wt\",\"qsec\",\"vs\",\"am\",\"gear\",\"carb\""
#> [2] "\"Mazda RX4\",21,6,160,110,3.9,2.62,16.46,0,1,4,4"                                            
#> [3] "\"Mazda RX4 Wag\",21,6,160,110,3.9,2.875,17.02,0,1,4,4"                                       
#> [4] "\"Datsun 710\",22.8,4,108,93,3.85,2.32,18.61,1,1,4,1"                                         
#> [5] "\"Hornet 4 Drive\",21.4,6,258,110,3.08,3.215,19.44,1,0,3,1"                                   
#> [6] "\"Hornet Sportabout\",18.7,8,360,175,3.15,3.44,17.02,0,0,3,2"                                 
#> [7] "\"Valiant\",18.1,6,225,105,2.76,3.46,20.22,1,0,3,1"
```

<sup>Created on 2019-09-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This however does not work with `readr::write_csv`

``` r
readr::write_csv(head(mtcars), textConnection("str2", open = "w"))
#> Error in stream_delim_(df, path, ..., bom = bom, quote_escape = quote_escape): 'write' not enabled for this connection
str2
#> character(0)
```

<sup>Created on 2019-09-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Why not? Can it be enabled?

**Comment by cjyetman** [comment]
You could probably use `format_csv` instead...
```r
str2 <- readr::format_csv(head(mtcars))
str2
#> [1] "mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb\n21,6,160,110,3.9,2.62,16.46,0,1,4,4\n21,6,160,110,3.9,2.875,17.02,0,1,4,4\n22.8,4,108,93,3.85,2.32,18.61,1,1,4,1\n21.4,6,258,110,3.08,3.215,19.44,1,0,3,1\n18.7,8,360,175,3.15,3.44,17.02,0,0,3,2\n18.1,6,225,105,2.76,3.46,20.22,1,0,3,1\n"
```

**Comment by jimhester** [comment]
R's connection API only works with binary mode connections, I think `write.csv()` has special logic to handle text connections.

**Comment by antoine-sachet** [comment]
@cjyetman Wow `format_csv`  is _exactly_ what I needed. Even better than writing to a textConnection.

Closing since there really is no point writing to a `textConnection` when you can just get the csv string with `format_csv`.
