### ISSUE TITLE
read_excel with a URL downloads a corrupt file with default settings on Windows

### ISSUE THREAD

**Issue by firasm** [tidyverse/readr#1031]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

## Brief description of the problem

Downloading an excel file from a URL using the default settings with read_excel results in a corrupted/unreadable file when opening it in excel (RStudio throws no errors or warnings).

## Reprex
```r
## running this will download a corrupt .xls file on a PC
download.file(url="http://gattonweb.uky.edu/sheather/book/docs/datasets/GreatestGivers.xls",destfile="h.xls")

## running this will result in a functional file on a PC
download.file(url="http://gattonweb.uky.edu/sheather/book/docs/datasets/GreatestGivers.xls",destfile="h.xls",method="curl")
```

## Related issues

Two potentially related issues: #205 and #163 but they seem to be closed now... 

**update**: More similar (closed) issues found: #884 and #987 ?

**Comment by jennybc** [comment]
It looks like you are actually talking about the readxl package, not readr.

And also I suspect you may be stumbling into a classic gotcha.

On windows, you must do `download.file(..., mode="wb")`.

See

https://github.com/HenrikBengtsson/Wishlist-for-R/issues/30

https://github.com/HenrikBengtsson/Wishlist-for-R/issues/30#issuecomment-379145981

**Comment by firasm** [comment]
Yikes - classic gotcha indeed.

Thanks @jennybc ! 

P.S. I was actually teaching students `read_excel()` and running into this issue before they could even load it in and for some reason thought I could solve it by changing arguments in read_excel.

Thanks for helping anyway! Much appreciated.
