### ISSUE TITLE
should `type_convert()` erase the 'spec' attribute?

### ISSUE THREAD

**Issue by wibeasley** [tidyverse/readr#1032]
When [`readr::type_convert()`](https://github.com/tidyverse/readr/blob/master/R/type_convert.R) is applied to a data.frame, should it update the 'spec' attribute?  Currently, it does not, and potentially returns a misleading result.

```r
library(magrittr); library(readr)
d1 <- 
  read_csv(
    readr_example("mtcars.csv"),
    col_types = cols(.default = col_character())
  )
str(d1)
```

After the initial creation, the data.frame's spec attribute is correct (*i.e.*, all columns are character).
```
Classes ‘spec_tbl_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	32 obs. of  11 variables:
 $ mpg : chr  "21" "21" "22.8" "21.4" ...
 ...
 $ carb: chr  "4" "4" "1" "1" ...
 - attr(*, "spec")=
  .. cols(
  ..   .default = col_character(),
  ..   mpg = col_character(),
  ..   cyl = col_character(),
  ...
  ..   carb = col_character()
  .. )
```

Then  `type_convert()` correctly converts everything to doubles.

```r
d2 <- data %>% 
  type_convert()
```

```
Parsed with column specification:
cols(
  mpg = col_double(),
  cyl = col_double(),
  ...
  carb = col_double()
)
```

But the spec still shows the character vectors.

```r
spec(d2)
```
```
cols(
  .default = col_character(),
  mpg = col_character(),
  cyl = col_character(),
  ...
  carb = col_character()
)
```

BTW, I really like this function.  It was nice when I was stacking a bunch of dataframe on top of each other, but some columns in some sub-dataframes were empty to the data types weren't compatible during the stack.

**Comment by jimhester** [comment]
`spec()` is really meant to capture the specification of the original import, I don't think we should change it after the fact.

**Comment by wibeasley** [comment]
@jimhester, makes sense to me.  I changed the issue title to reflect that.

Do you want me to try a PR?

**Comment by jimhester** [comment]
Sure, you can actually just change the last line to be `df[]` and it should drop the spec attribute.

**Comment by wibeasley** [comment]
@jimhester, thanks for the suggestion.  I forgot that was even an option.  Would you prefer instead `attr(df, "spec") <- NULL`?  (Placed immediately before `df` is returned to the caller?)

Does `df[]` drop all attributes, including others that you may want to retain?  (Even if they hadn't been programmed yet.)  I'm wondering if someone might call `readr::type_convert()` on datasets created by  something like haven, where they do want to keep those attributes.

**Comment by jimhester** [comment]
Fair questions, I am fine with doing `attr(df, "spec") <- NULL` as it is more explicit.
