### ISSUE TITLE
User id and Password feature!

### ISSUE THREAD

**Issue by ashuchawla** [tidyverse/readr#1040]
Hi,

I was wondering if there is a way to access password protected links(of the data file) through readr? I used to use http links to read in tsv files via read_tsv function earlier until my institution made those links password protected and hence all my scripts broke. This feature if available or could be made possible will be very helpful.

Thanks,

Ashu

**Comment by cderv** [comment]
I don't think readr can work with such link by default without help. 
Usually, I think the best way is a two step process: 
1. Download the file in a temp file (using `httr` or `curl` that knows how to deal with auth mechanism)
2. Read the file. 

Also, if your url is using [Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side), you should be able to pass in headers an encoded key.

Here is an example of how it could work with readr. I used `httpbin.org` as demo, as you can get a url with basic auth. User is `tom` here, and Password is `tomPwd`. 
``` r
# an exemple to get a auth url
# this is protected with user tom and password tomPwd
url_text <- "https://httpbin.org/hidden-basic-auth/tom/tomPwd"

# create a connection without auth
con <- url(url_text)
# this does not work
readr::read_lines(con)
#> Warning in open.connection(con, "rb"): cannot open URL 'https://
#> httpbin.org/hidden-basic-auth/tom/tomPwd': HTTP status was '404 NOT FOUND'
#> Error in open.connection(con, "rb"): impossible d'ouvrir la connexion
# create a connection with auth
con <- url(url_text,
           headers = c(
             Authorization = glue::glue("Basic {key}",
                                        key = openssl::base64_encode("tom:tomPwd"))
           ))
# readr can now read the content
readr::read_lines(con)
#> [1] "{"                           "  \"authenticated\": true, "
#> [3] "  \"user\": \"tom\""         "}"
```

<sup>Created on 2019-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

For a real password, I suggest to use a mechanism to not write it in a script in plain text. Several ideas: 

1. An environment variable : `Sys.getenv("MY_PWD") or directly the encoded string `Sys.getenv("BASIC_AUTH_KEY")`
2. A prompt for the use: see `askpass` 📦 
3. A credential store : see `keyring` 📦 
4. Any other mechanism that secures your password. 

Know that your url can also be secure by another mechanism (like Oauth2, or ntml , or other). 

Hope it helps

**Comment by jimhester** [comment]
You don't actually need to download the file, you can use a `curl::curl()` handle or `url()` connection directly and pass it to readr.
