### ISSUE TITLE
Read compressed file

### ISSUE THREAD

**Issue by Ben-Cox** [tidyverse/readr#1042]
Issue #163 was supposed to have fixed the problem of reading compressed files from urls. However, I am getting an error when trying to read files from this ftp server. The result is not the .csv file inside the .zip file. When I download the .zip first, and then `read_csv()` from local folder, it works.

```r
read_csv("ftp://ftp.rmpc.org/pub/data/CS041_ODFW_2017.zip")
```

**Comment by jimhester** [comment]
Only gz compressed tarballs can be read directly from URLs, not zip files. This is simply due to the limitations of the connection types in R.
