### ISSUE TITLE
write_csv2/format_csv2 adds leading whitespace to numbers

### ISSUE THREAD

**Issue by keesdeschepper** [tidyverse/readr#1046]
When using write_csv2 or format_csv2, leading whitespace is added to values in a number column if the numbers are of different length:

```r
readr::format_csv(tibble(x = c(6, 66)))
# "x\n6\n66\n"
readr::format_csv2(tibble(x = c(6, 66)))
# "x\n 6\n66\n"
```
This is against the csv format (whitespace is significant). Perhaps add `trim = TRUE` to `format` in `change_decimal_separator`?

**Comment by jimhester** [comment]
You are correct, want to submit a PR?

**Comment by keesdeschepper** [comment]
Sure
