### ISSUE TITLE
Keeping the local timezone with parse_datetime

### ISSUE THREAD

**Issue by jokedurnez** [tidyverse/readr#1049]
I am analyzing a dataset that can have multiple different timezones and it I want to group the datetimes by day.  However, however I set up `locale()`, it is transforming all timezones into the same timezone, which messes up the midnight-limit.

How could I make sure I read in the datetimes with their local timezone?

```r
> time = parse_datetime("2018-07-31 17:24:09.329000-07:00")
> print(time)
[1] "2018-08-01 00:24:09 UTC"
> time = parse_datetime("2018-07-31 17:24:09.329000+07:00")
> print(time)
[1] "2018-07-31 10:24:09 UTC"
```

**Comment by batpigandme** [comment]
From the [locale vignette](https://readr.tidyverse.org/articles/locales.html):
> Unless otherwise specified, readr assumes that times are in UTC, the Universal Coordinated Time (this is a successor to GMT and for almost all intents is identical). UTC is most suitable for data because it doesn’t have daylight savings - this avoids a whole class of potential problems. If your data isn’t already in UTC, you’ll need to supply a tz in the locale:

You have to do this using the `locale` argument:
```r
parse_datetime("2001-10-10 20:10")
#> [1] "2001-10-10 20:10:00 UTC"
parse_datetime("2001-10-10 20:10", locale = locale(tz = "Pacific/Auckland"))
#> [1] "2001-10-10 20:10:00 NZDT"
parse_datetime("2001-10-10 20:10", locale = locale(tz = "Europe/Dublin"))
#> [1] "2001-10-10 20:10:00 IST"
```

If this doesn't answer your query, you might ask over on https://community.rstudio.com, since I don't think this is a bug in readr (and we try to use GitHub for feature requests and bugs). If it _does_ turn out to be a readr bug, I can come back and reopen this issue.

**Comment by jokedurnez** [comment]
Sorry, I may not have made my case very clear...
This is about parsing a date that has a timezone *in the ISO-string*, like `2018-07-31 17:24:09.329000-07:00`, where the `-07:00` indicates the timezone.   Readr is apparently able to read out that timezone, but then transforms the datetime into UTC. It would make sense that with a timezone in the string, the `tz` would not default to UTC, but it should take the `tz` from the string.  Or at least there should be an option to do so.

So observed behavior:
```
> parse_datetime("2018-07-31 17:24:09.329000-07:00")
"2018-08-01 00:24:09 UTC"
```

Expected behavior
```
> parse_datetime("2018-07-31 17:24:09.329000-07:00")
"2018-08-01 17:24:09 CDT"
```

Right now, I am reading in a dataset that have strings with multiple timezones, and I want to keep those.  The only way to do this right now would be to:
1) read in the csv with datetimes as strings
2) mutate the strings as to take out the timezones (split by `-` and take the last)
3) parse the datetime
4) mutate the datetimes with the timezones in another column
But I think given that the timezone *is* specified in the string, readr should be able to deal with this?

**Comment by batpigandme** [comment]
OK, pretty sure this is a feature request, then (though @jimhester will know for sure).

**Comment by jimhester** [comment]
I understand the request, but it is not really possible. The tzone is for `POSIXct` objects is stored as an attribute for the whole vector, you cannot have different timezones for different values. e.g. you can make all date times in a vector display in `CDT`, but not the first value in `EDT`, second in `CDT`, ect. 

Also note the timezone attribute is only used to _display_ the time, the instant the value corresponds to is irrespective of the display timezone.

Parsing the date times _without_ the timezone as you suggest will result in incorrect values, as the times without timezones are parsed in the locale. See the difference between the first two values and the second two.

``` r
library(readr)
a <- parse_datetime("2018-07-31 17:24:09.329000-07:00", locale = locale(tz = "UTC"))
b <- parse_datetime("2018-07-31 17:24:09.329000-07:00", locale = locale(tz = "US/Central"))
a
#> [1] "2018-08-01 00:24:09 UTC"
b
#> [1] "2018-07-31 19:24:09 CDT"
a == b
#> Warning in check_tzones(e1, e2): 'tzone' attributes are inconsistent
#> [1] TRUE

c <- parse_datetime("2018-07-31 17:24:09.329000", locale = locale(tz = "UTC"))
d <- parse_datetime("2018-07-31 17:24:09.329000", locale = locale(tz = "US/Central"))
c
#> [1] "2018-07-31 17:24:09 UTC"
d
#> [1] "2018-07-31 17:24:09 CDT"
c == d
#> Warning in check_tzones(e1, e2): 'tzone' attributes are inconsistent
#> [1] FALSE
```

<sup>Created on 2019-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jokedurnez** [comment]
Ok, that makes sense. Thanks !
However, is there a way to extract the timezone from the string? 
How would I be able to extract the fact that `-07:00` is CDT?

**Comment by jimhester** [comment]
[-07:00](https://en.wikipedia.org/wiki/UTC%E2%88%9207:00) is actually either mountain time during standard time or pacific time during daylight savings.

There isn't really any way I am aware of to do this mapping built into R, you would likely have to write it yourself, but is is going to be pretty tricky to do, there are a [_lot_ of timezones](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations), they are not very well standardized and the timezone databases vary across operating systems.

**Comment by jokedurnez** [comment]
thanks for the correction. This kind of confusion is why we need to parse that out ;-) 

Ok, I'm fine with closing this.  Will do it manually.
Although reading in a file with standard ISO-strings, and knowing exactly which rows are which date in the local time registered seems like basic functionally. 

Other languages have local datetime object types without timezone, which would be helpful here. 
 The only thing I can now think of to overcome all of this is reading in the dates assuming UTC, cutting off the timezone, then apply a delta on the the UTC-dates to make them "fake local" and comparable to midnight.

**Comment by jimhester** [comment]
So I think this function should do what you want, I unfortunately do not know of a better or more straightforward way to do this.

``` r
times <- c("2018-07-31 17:24:09.329000-07:00", "2018-07-31 17:24:09.329000+07:00")

to_local_date <- function(x) {
  # Extract timezone offsets from character inputs
  tz_offsets <- sub(".*([-+]\\d\\d):00", "\\1", x)

  # Convert them to Olson timezone names
  tzones <- sprintf("Etc/GMT%+i", as.numeric(tz_offsets))

  # Parse the times as UTC times
  utc_times <- as.POSIXct(x, tz = "UTC")

  # Create the local date from the UTC time and local timezone
  res <- numeric(length(x))
  for (i in seq_along(x)) {
    res[[i]] <- as.Date(utc_times[[i]], tz = tzones[[i]])
  }

  # Return a Date vector
  .Date(res)
}

to_local_date(times)
#> [1] "2018-08-01" "2018-07-31"
```

<sup>Created on 2019-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jokedurnez** [comment]
oh, thanks !!!
