### ISSUE TITLE
`read_delim()` and `write_delim()` treats empty string and NA value inconsistently

### ISSUE THREAD

**Issue by zenggyu** [tidyverse/readr#1054]
See comments in the reprex.

```r
library(readr)
library(tibble)

# there is an empty string and an NA value in the data
dat <- tibble(
  x = c(NA, ""),
  y = c(1, 1)
)

print(dat)
#> # A tibble: 2 x 2
#>   x         y
#>   <chr> <dbl>
#> 1 <NA>      1
#> 2 ""        1

write_delim(dat,
            "dat.csv",
            delim = ",",
            na = "",
            col_names = F)

dat <- readLines("dat.csv")

# write_delim() creates a csv file where the empty string is quoted, while the NA value is not
cat(dat, sep = "\n")
#> ,1
#> "",1

# however, read_delim() does not respect the difference, and treats both as NAs
dat <- read_delim(
  "dat.csv",
  col_names = c("x", "y"),
  col_types = cols(x = col_character(),
                   y = col_double()),
  locale = locale(encoding = "UTF8"),
  delim = ",",
  quote = "\"",
  na = ""
)

print(dat)
#> # A tibble: 2 x 2
#>   x         y
#>   <chr> <dbl>
#> 1 <NA>      1
#> 2 <NA>      1
```

**Comment by jimhester** [comment]
While I agree that this is inconsistent and arguably a bug, it unfortunately is not trivial to disambiguate between a quoted empty field and a unquoted empty field in the parser.

So while again I agree this is not quite correct, I think this case is uncommon enough and would require significant enough changes that we will not address it.

As a workaround I would suggest you use a non-empty value for `na` so there is no ambiguity.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:
