### ISSUE TITLE
Use of utils::unzip with default "internal" method prevents read_csv from effectively reading .zip files > 4 GB

### ISSUE THREAD

**Issue by dwachsmuth** [tidyverse/readr#1056]
When I try to use read_csv to read a .zip file which is larger than 4 GB, the import appears to succeed, but is accompanied by a warning:

```
Warning message:
In (function (con, what, n = 1L, size = NA_integer_, signed = TRUE,  :
  possible truncation of >= 4GB file

```

And indeed only the first 4 GB of the file has been read. It appears that read_csv is using the utils::unzip function with its default unzip = "internal" argument.

Would it be possible to add some method for passing through the `unzip` argument to utils::unzip? Without being able to pass through unzip = "unzip" (or whatever else), read_csv effectively can't read from large zip files, which is ironic given the utility of storing large CSVs in a compressed format!

**Comment by jimhester** [comment]
It is using `base::unz()`, which seems to have the same 4Gb limitation.

If you want to use larger files you will need to either unzip it manually before reading or use a package that supplies a connection that supports zip files of greater than 4Gb, such as https://github.com/jimhester/archive/

**Comment by dwachsmuth** [comment]
Ok, thanks for the clarification, and for the pointer to your archive package!
