### ISSUE TITLE
read_table2 silently drops commas leading to wrong numerical values

### ISSUE THREAD

**Issue by frousseu** [tidyverse/readr#1059]
Hello

When reading numerical data where commas are wrongfully used instead of points, `read_table2` seems to be silently removing commas leading to a modification of numerical values. For example, `read_table2` turns the value "19,1" to 191 without any warning (line 38 of the original dataset):

```r
library(readr)
sparrows <- read_table2("https://raw.githubusercontent.com/frousseu/ECL749/master/data/sparrows.txt",n_max=50)

## Parsed with column specification:
## cols(
##  `"Sex"` = col_character(),
## `"wingcrd"` = col_double(),
## `"wt"` = col_number()
## )

sparrows[38,]

##  A tibble: 1 x 3
##  `"Sex"` `"wingcrd"` `"wt"`
##  <chr>         <dbl>  <dbl>
##  1 "\"m\""          57    191

```
Thanks!

**Comment by jimhester** [comment]
This because that column is using the flexible numeric parser `col_number()`, which ignores commas. If you want it to be more strict specify the column type as double, e.g.

``` r
sparrows <- readr::read_table2("https://raw.githubusercontent.com/frousseu/ECL749/master/data/sparrows.txt",n_max=50, col_types = "cdd")
#> Warning: 1 parsing failure.
#> row  col               expected actual                                                                         file
#>  38 "wt" no trailing characters     ,1 'https://raw.githubusercontent.com/frousseu/ECL749/master/data/sparrows.txt'

sparrows[38,]
#> # A tibble: 1 x 3
#>   `"Sex"` `"wingcrd"` `"wt"`
#>   <chr>         <dbl>  <dbl>
#> 1 "\"m\""          57     NA
```

<sup>Created on 2020-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So this seems to be working as intended.

**Comment by frousseu** [comment]
I must admit I don't now much about the readr package and indeed it works as intended. I noticed this while helping a student import an intentionally messed up dataset. The student naturally went to the import dataset tool in RStudio and chose the readr option to import it with the whitespace delimiter. That the default behaviour of the function leads to a change in a numerical value without warning seems to me like a dangerous behaviour. It seems to me that at least a warning should be issued.
