### ISSUE TITLE
read_csv2 doesn't accept user's locale decimal mark

### ISSUE THREAD

**Issue by damianooldoni** [tidyverse/readr#1061]
I found that `read_csv2` doesn't allow users to use dot as decimal: it uses always the default comma as decimal mark. See here below an example of what I mean. Any idea about it?

``` r
library(readr)
df1 <- read_csv2("a;b\n1.0;2.0", locale = locale(decimal_mark = "."))
#> Using ',' as decimal and '.' as grouping mark. Use read_delim() for more control.
df1
#> # A tibble: 1 x 2
#>       a     b
#>   <dbl> <dbl>
#> 1    10    20
```

I am using readr 1.3.1. from CRAN.

Thanks for the nice support and fantastic work!

<sup>Created on 2020-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cderv** [comment]
I think this is definetly on purpose. The doc says 
> read_csv2() uses ; for the field separator and , for the decimal point. This is common in some European countries.

it is just a variant of `read_csv` with those default you can't change.
https://github.com/tidyverse/readr/blob/cd68d4ab6009109cf94d31c49bdfe04c2f7cf36c/R/read_delim.R#L147-L151

Also, you have as in your example a clear message to use `read_delim` if you want to change the default.
> #> Using ',' as decimal and '.' as grouping mark. Use read_delim() for more control.

So you just can use `read_delim` to customize all you want. 

Hope it helps clarify.

**Comment by damianooldoni** [comment]
Thanks @cderv.
