### ISSUE TITLE
Readr does not support locale and/or time-zone on Android

### ISSUE THREAD

**Issue by Fernal73** [tidyverse/readr#1062]
https://github.com/termux/termux-packages/issues/4810#issuecomment-576064047

"This can be more like issue of https://github.com/tidyverse/readr than of R implementation.

Function at https://github.com/tidyverse/readr/blob/master/src/localtime.c#L324 should be patched in order to be compatible with Android time zone data format."

Brief description of the problem
readr does not support time zones as used by Android. The following link describes the issue encountered while executing readr on Termux.

Kindly refer to the linked issue for R code to reproduce the error. 

https://github.com/termux/termux-packages/issues/4810

**Comment by jimhester** [comment]
We unfortunately do not have the bandwidth or time to support and maintain readr for Android. If you or others want android support you will have to submit a pull request with the necessary changes.

**Comment by Fernal73** [comment]
https://github.com/its-pointless/its-pointless.github.io/issues/46

**Comment by jimhester** [comment]
Fixed by #1172
