### ISSUE TITLE
parse_number appears to ignore its trim_ws argument

### ISSUE THREAD

**Issue by cdhowe** [tidyverse/readr#1071]
The documentation for parse_number defines a trim_ws argument as follows 

trim_ws -- Should leading and trailing whitespace be trimmed from each field before parsing it?

However, trim_ws seems to be ignored as shown by the reprex below.
```r
library(readr)

## trim_ws appears to always be TRUE,
## as demonstrated by the following
## statements generating the same output

number_vector <- c("  1", "2  ", "  3  ")
white_space_trimmed <- 
  parse_number(number_vector, trim_ws = TRUE)
no_trim <- 
  parse_number(number_vector, trim_ws = FALSE)
white_space_trimmed == no_trim
#> [1] TRUE TRUE TRUE
```
<sup>Created on 2020-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
```

**Comment by jimhester** [comment]
That is simply because the numeric parser is very flexible and _also_ trims whitespace. The less flexible `double_parser()` show the behavior maybe you were expecting.

``` r
library(readr)
number_vector <- c("  1", "2  ", "  3  ")

parse_double(number_vector, trim_ws = TRUE)
#> [1] 1 2 3
parse_double(number_vector, trim_ws = FALSE)
#> Warning: 3 parsing failures.
#> row col               expected actual
#>   1  -- a double                  1  
#>   2  -- no trailing characters       
#>   3  -- a double                  3
#> [1] NA NA NA
#> attr(,"problems")
#> # A tibble: 3 x 4
#>     row   col expected               actual 
#>   <int> <int> <chr>                  <chr>  
#> 1     1    NA a double               "  1"  
#> 2     2    NA no trailing characters "  "   
#> 3     3    NA a double               "  3  "
```

<sup>Created on 2020-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In any case I think this is working as designed.
