### ISSUE TITLE
read_csv fails with cryptic error when trying to read a csv with > 2 billion rows

### ISSUE THREAD

**Issue by dwachsmuth** [tidyverse/readr#1073]
I'm trying to use read_csv to read a CSV with 2.5 billion rows, and am greeted with the following error message:

`Error in read_tokens_(data, tokenizer, col_specs, col_names, locale_,  : 
  invalid value`

Browsing through the read_delim source file clued me in to the idea that the problem might be related to having a number of rows greater than the 32-bit integer limit.

So one question is whether there is any way around the integer limit. Obviously reading 2.5 billion row CSVs isn't a common use case, but I've got the RAM to handle the files.

The second question is whether a more informative error could be thrown, since a relatively easy workaround (at least for cases where total rows are under 2 * integer limit) is to use n_max and skip to read the file in pieces. But it's hard to arrive at this solution without knowing what is causing the error.

**Comment by jimhester** [comment]
You may want to try using the [vroom](https://vroom.r-lib.org/) package to read this dataset, it has full support for reading data of this size.

**Comment by dwachsmuth** [comment]
Thanks for the reply. Unfortunately, I've found vroom to be unreliable at readings these files—it retrieves fewer rows than read_csv, and exhibits very large discrepancies between the gzip and decompressed version of the same table.

Hence my desire to use read_csv despite the gigantic file sizes.

You've motivated me to go file the vroom issue, though, which I'll do momentarily.
