### ISSUE TITLE
Feature request: "tryFormats" option for readr functions

### ISSUE THREAD

**Issue by TrentLobdell** [tidyverse/readr#1074]
It is common for me to import data from csv's and excel files with inconsistent date formats -- but a small distinct number of potential formats. I use as.Date(tryFormats = c()) to solve this issue, but it would generally be more desirable for this cleaning to happen during importation. My hope is for some functionality like col_date(tryFormats = c()). Please, let me know if more clarity is needed or if you have any other questions!

I appreciate the work you've already done and are doing!

Best,

Trent

**Comment by cderv** [comment]
Let's not for reference that this feature request is related to a question in the community
https://community.rstudio.com/t/tryformats-for-readr/51564

**Comment by jimhester** [comment]
I think this is unlikely to happen in readr, I would encourage you to read these columns as characters and use another package to convert them into dates.
