### ISSUE TITLE
readr fails to build / install

### ISSUE THREAD

**Issue by archenemies** [tidyverse/readr#1076]
Also see #919.

I have two issues, the first is that `readr` fails to install with my favorite configure options:

        CC="ccache gcc" \
          CFLAGS="-ggdb -pipe -std=gnu99 -Wall -pedantic" \
          CXX="ccache g++" \
          CXXFLAGS="-ggdb -pipe -Wall -pedantic" \
          FC="ccache gfortran" \
          F77="ccache gfortran" \
          MAKE="make -j8" \
          STRIP=true \
          ../configure \
          --prefix=$PREFIX \
          --enable-R-shlib \
          --cache-file=config.cache \
          --enable-memory-profiling \
          --with-blas \
          --with-lapack \
          --with-readline

Here is what I get, it seems that g++ has run out of memory? It is somewhat cryptic "g++: fatal error: Killed signal terminated program cc1plus":

    > install.packages("readr",repos="http://cloud.r-project.org/", type="source")
    Installing package into ‘/home/user/.local/lib/x86_64/R/packages’
    (as ‘lib’ is unspecified)
    trying URL 'http://cloud.r-project.org/src/contrib/readr_1.3.1.tar.gz'
    Content type 'application/x-gzip' length 268853 bytes (262 KB)
    ==================================================
    downloaded 262 KB

    * installing *source* package ‘readr’ ...
    ** package ‘readr’ successfully unpacked and MD5 sums checked
    ** using staged installation
    ** libs
    ccache g++ -std=gnu++11 -I"/home/user/.local/lib64/R/include" -DNDEBUG  -I'/home/user/.local/lib/x86_64/R/packages/Rcpp/include' -I'/home/user/.local/lib/x86_64/R/packages/BH/include' -I/usr/local/include  -I. -Ircon -fpic  -ggdb -pipe -Wall -pedantic  -c Collector.cpp -o Collector.o
    ccache g++ -std=gnu++11 -I"/home/user/.local/lib64/R/include" -DNDEBUG  -I'/home/user/.local/lib/x86_64/R/packages/Rcpp/include' -I'/home/user/.local/lib/x86_64/R/packages/BH/include' -I/usr/local/include  -I. -Ircon -fpic  -ggdb -pipe -Wall -pedantic  -c CollectorGuess.cpp -o CollectorGuess.o
    ccache g++ -std=gnu++11 -I"/home/user/.local/lib64/R/include" -DNDEBUG  -I'/home/user/.local/lib/x86_64/R/packages/Rcpp/include' -I'/home/user/.local/lib/x86_64/R/packages/BH/include' -I/usr/local/include  -I. -Ircon -fpic  -ggdb -pipe -Wall -pedantic  -c Iconv.cpp -o Iconv.o
    ccache g++ -std=gnu++11 -I"/home/user/.local/lib64/R/include" -DNDEBUG  -I'/home/user/.local/lib/x86_64/R/packages/Rcpp/include' -I'/home/user/.local/lib/x86_64/R/packages/BH/include' -I/usr/local/include  -I. -Ircon -fpic  -ggdb -pipe -Wall -pedantic  -c LocaleInfo.cpp -o LocaleInfo.o
    ccache g++ -std=gnu++11 -I"/home/user/.local/lib64/R/include" -DNDEBUG  -I'/home/user/.local/lib/x86_64/R/packages/Rcpp/include' -I'/home/user/.local/lib/x86_64/R/packages/BH/include' -I/usr/local/include  -I. -Ircon -fpic  -ggdb -pipe -Wall -pedantic  -c RcppExports.cpp -o RcppExports.o
    ccache g++ -std=gnu++11 -I"/home/user/.local/lib64/R/include" -DNDEBUG  -I'/home/user/.local/lib/x86_64/R/packages/Rcpp/include' -I'/home/user/.local/lib/x86_64/R/packages/BH/include' -I/usr/local/include  -I. -Ircon -fpic  -ggdb -pipe -Wall -pedantic  -c Reader.cpp -o Reader.o
    ccache g++ -std=gnu++11 -I"/home/user/.local/lib64/R/include" -DNDEBUG  -I'/home/user/.local/lib/x86_64/R/packages/Rcpp/include' -I'/home/user/.local/lib/x86_64/R/packages/BH/include' -I/usr/local/include  -I. -Ircon -fpic  -ggdb -pipe -Wall -pedantic  -c Source.cpp -o Source.o
    ccache g++ -std=gnu++11 -I"/home/user/.local/lib64/R/include" -DNDEBUG  -I'/home/user/.local/lib/x86_64/R/packages/Rcpp/include' -I'/home/user/.local/lib/x86_64/R/packages/BH/include' -I/usr/local/include  -I. -Ircon -fpic  -ggdb -pipe -Wall -pedantic  -c Tokenizer.cpp -o Tokenizer.o
    ccache g++ -std=gnu++11 -I"/home/user/.local/lib64/R/include" -DNDEBUG  -I'/home/user/.local/lib/x86_64/R/packages/Rcpp/include' -I'/home/user/.local/lib/x86_64/R/packages/BH/include' -I/usr/local/include  -I. -Ircon -fpic  -ggdb -pipe -Wall -pedantic  -c TokenizerDelim.cpp -o TokenizerDelim.o
    ccache g++ -std=gnu++11 -I"/home/user/.local/lib64/R/include" -DNDEBUG  -I'/home/user/.local/lib/x86_64/R/packages/Rcpp/include' -I'/home/user/.local/lib/x86_64/R/packages/BH/include' -I/usr/local/include  -I. -Ircon -fpic  -ggdb -pipe -Wall -pedantic  -c TokenizerFwf.cpp -o TokenizerFwf.o
    ccache g++ -std=gnu++11 -I"/home/user/.local/lib64/R/include" -DNDEBUG  -I'/home/user/.local/lib/x86_64/R/packages/Rcpp/include' -I'/home/user/.local/lib/x86_64/R/packages/BH/include' -I/usr/local/include  -I. -Ircon -fpic  -ggdb -pipe -Wall -pedantic  -c TokenizerWs.cpp -o TokenizerWs.o
    g++: fatal error: Killed signal terminated program cc1plus
    compilation terminated.
    make: *** [/home/user/.local/lib64/R/etc/Makeconf:175: Reader.o] Error 1
    make: *** Waiting for unfinished jobs....
    g++: fatal error: Killed signal terminated program cc1plus
    compilation terminated.
    make: *** [/home/user/.local/lib64/R/etc/Makeconf:175: Tokenizer.o] Error 1
    g++: fatal error: Killed signal terminated program cc1plus
    compilation terminated.
    make: *** [/home/user/.local/lib64/R/etc/Makeconf:175: Collector.o] Error 1
    ERROR: compilation failed for package ‘readr’
    * removing ‘/home/user/.local/lib/x86_64/R/packages/readr’

    The downloaded source packages are in
            ‘/tmp/RtmpyuHRXb/downloaded_packages’
    Warning message:
    In install.packages("readr", repos = "http://cloud.r-project.org/",  :
      installation of package ‘readr’ had non-zero exit status

When I try to use different configure args, here is the result:

    $ cd /tmp/RtmpSAu4UP/downloaded_packages
    $ R CMD INSTALL --configure-args="CFLAGS=-g CXXFLAGS=-g MAKE=make" readr
    * installing to library ‘/home/user/.local/lib/x86_64/R/packages’
    * installing *source* package ‘readr’ ...
    ** package ‘readr’ successfully unpacked and MD5 sums checked
    ** using staged installation
    ** libs
    make: Nothing to be done for 'all'.
    installing via 'install.libs.R' to /home/user/.local/lib/x86_64/R/packages/00LOCK-readr/00new/readr
    ** R
    ** inst
    ** byte-compile and prepare package for lazy loading
    ** help
    *** installing help indices
    *** copying figures
    ** building package indices
    ** installing vignettes
    ** testing if installed package can be loaded from temporary location
    Error: package or namespace load failed for ‘readr’ in dyn.load(file, DLLpath = DLLpath, ...):
     unable to load shared object '/home/user/.local/lib/x86_64/R/packages/00LOCK-readr/00new/readr/libs/readr.so':
      /home/user/.local/lib/x86_64/R/packages/00LOCK-readr/00new/readr/libs/readr.so: undefined symbol: _ZTV18CollectorCharacter
    Error: loading failed
    Execution halted
    ERROR: loading failed
    * removing ‘/home/user/.local/lib/x86_64/R/packages/readr’
    [1]

**Comment by archenemies** [comment]
By the way, it is Arch Linux:

    $ uname -a
    Linux hostname 5.4.8-arch1-1 #1 SMP PREEMPT Sat, 04 Jan 2020 23:46:18 +0000 x86_64 GNU/Linux

the latest R from https://github.com/wch/r-source/

    $ R --version
    R Under development (unstable) (2020-02-12 r77798) -- "Unsuffered Consequences"
    Copyright (C) 2020 The R Foundation for Statistical Computing
    Platform: x86_64-pc-linux-gnu (64-bit)

    R is free software and comes with ABSOLUTELY NO WARRANTY.
    You are welcome to redistribute it under the terms of the
    GNU General Public License versions 2 or 3.
    For more information about these matters see
    https://www.gnu.org/licenses/.

**Comment by jimhester** [comment]
Yes, wherever you are running this does not have enough memory to compile readr. Increase the amount of memory.

**Comment by archenemies** [comment]
Thank you, I was able to fix this by changing "make -j8" to "make -j4" in my R configuration.
