### ISSUE TITLE
Improved description of fwf_* functions

### ISSUE THREAD

**Issue by kvittingseerup** [tidyverse/readr#1077]
I recently ran into fixed with files and was happy to find that ```readr``` support importing such files into R. 

The documentation around these functions are however a bit lacking. Specifically it is not described what ```fwf_empty```, ```fwf_widths```, ```fwf_positions``` and ```fwf_cols``` actually do. 

Some of them you can guess, but the lack of documentation is a shame - especially for ```fwf_empty()``` which might be the most useful but also the one where people (or at least I) cannot guess what does form its name and usage. I actually though I had to implement such a function myself until I stumbled upon it in a comment for a stackoverflow post.

A short description of each function, like you have for ```?read_table``` would improve the usage of these functions.

Cheers
Kristoffer

**Comment by jimhester** [comment]
Thanks for opening the issue, we have tried to improve the documentation around these functions.
