### ISSUE TITLE
Encoding is lost through tokenize

### ISSUE THREAD

**Issue by NFA** [tidyverse/readr#1079]
Hello,

Encoding information of strings is lost when returned from tokenize(). This is on Windows so when attempting to print the result it falls back to default system locale.

``` r
library(stringi)
library(readr)

(str <- stringi::stri_encode("glödförlust\n", to = "UTF-8"))
#> [1] "glödförlust\n"
Encoding(str)
#> [1] "UTF-8"
(res <- readr::tokenize(str, readr::tokenizer_fwf(begin = c(0), end = c(NA))))
#> [[1]]
#> [1] "glÃ¶dfÃ¶rlust"
Encoding(res[[1]][1])
#> [1] "unknown"
Encoding(res[[1]][1]) <- "UTF-8"
res
#> [[1]]
#> [1] "glödförlust"
```

<sup>Created on 2020-03-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
Generally `tokenize` is an internal function mainly used for testing, it is not meant to handle complicated non-ASCII locales. While it would be possible to fix I don't think it is worth the development effort for us to do it.
