### ISSUE TITLE
encoding = "ISO-8859-1" much slower than encoding = "UTF-8"

### ISSUE THREAD

**Issue by georgevbsantiago** [tidyverse/readr#1080]
I found that the readr function configured with encoding = "UTF-8" is almost 15 times faster than with encoding = "ISO-8859-1".

Would it be possible to speed up the reading when the encoding is different from "UTF-8"?

OBS: The file "[K3241.K03200DV.D00124.L00001](https://onedrive.live.com/download?resid=758C804985145E0F!480632&authkey=!AE444CSMQcWi3rE&e=KIWKUl)" used in the reprex has the encoding "ISO-8859-1" and can be [downloaded here](https://onedrive.live.com/download?resid=758C804985145E0F!480632&authkey=!AE444CSMQcWi3rE&e=KIWKUl). It has 267 Mg compressed. I unzipped it (5Gb) for use in the function.

OBS2: You cannot use the "UTF-8" encoding in the file above, as it fails to identify the letter "Ç", in the word "PRAÇA" in the string. The file is only read correctly with the encoding in "ISO-8859-1".

```r
microbenchmark::microbenchmark(

readr_locate_default = {readr_locate_default <- readr::read_lines("K3241.K03200DV.D00124.L00001",
                                          locale = readr::locale(encoding = "UTF-8"),
                                          n_max = 100000)},

readr_locate_iso88591 = {readr_locate_iso88591 <-  readr::read_lines("K3241.K03200DV.D00124.L00001",
                                          locale = readr::locale(encoding = "ISO-8859-1"),
                                          n_max = 100000)},
times = 5

)
#> Unit: milliseconds
#>                   expr       min        lq      mean     median        uq
#>   readr_locate_default  621.0475  692.9164  797.8256   716.3754   845.799
#>  readr_locate_iso88591 7971.4062 8215.8596 9349.1556 10091.6453 10114.416
#>        max neval
#>   1112.989     5
#>  10352.451     5
```

**Comment by jimhester** [comment]
No, it is not really possible to speed anything up. the slowdown comes from using iconv to convert the encoding from ISO-8859-1 to UTF-8, and there is no real way to avoid that.
