### ISSUE TITLE
force quoting strings in write_csv (and similars)

### ISSUE THREAD

**Issue by mmuurr** [tidyverse/readr#1083]
Is there any plan to add a 'forced-quoting' option for strings in `write_csv` (and variants)?
The use case is this: some identifiers appear as numbers (e.g. integers), but should be _treated_ in code as strings.
When writing these strings out from one program (using `write_csv`), then reading those strings into another program (using `read_csv`), they may get read as numerics, despite careful formatting options for their string representation in the first program (e.g. not relying on the standard numeric-as-a-string formatting).

To be clear, this option would simply force quoting strings (instead of the current check `write_csv` makes to decide whether or not to quote a particular string).

**Comment by schuffr** [comment]
This is a huge gap. Is there a timeline or decision as to whether it will be implelemented?
