### ISSUE TITLE
"memory allocation or access error" with `read_lines_chuncked()`

### ISSUE THREAD

**Issue by huashan** [tidyverse/readr#1086]
Hi, I am using `read_lines_chucked()` for a very large text file (>50GB). My code runs OK in Windows but fails in Ubuntu system with 160G memory.

Its always raise "memory allocation or access error" when the `chunk_size` parameter is greater than 30000000 (about 2GB text size) . This message raises approximately at the end of reading first chunk. The system has enough memories(160GB) and most of them are available.

Any thoughts to get this error away?

**Comment by jimhester** [comment]
I would suggest using a smaller chunk size.
