### ISSUE TITLE
spec() does not show column specifications

### ISSUE THREAD

**Issue by frahimov** [tidyverse/readr#1093]

**Comment by frahimov** [comment]
my_tibble <- distinct(read_tsv(file = "table.txt", col_names = TRUE, guess_max = 5000))
spec(my_tibble)
> spec(my_tibble)
NULL

**Comment by jimhester** [comment]
The specifactions are removed once the tibble is subset in any way. In this example `distict()` subsets the object, so this is the expected behavior.
