### ISSUE TITLE
"readr" installation error on AIX7.2

### ISSUE THREAD

**Issue by bergen288** [tidyverse/readr#1097]
I am trying to install R packages (R base is 3.6.1) on AIX7.2 server with no internet access.  Below is my R CMD INSTALL statement:
	R CMD INSTALL -l /software/R/site-library pkg-source-files/readr_1.3.1.tar.gz
However, I got the following error message.  Can someone please help me to figure out what's wrong with it?  

* installing *source* package 'readr' ...
** package 'readr' successfully unpacked and MD5 sums checked
** using staged installation
** libs
"Makevars", line 3: make: 1254-055 Dependency line needs colon or double colon operator.
"Makevars", line 5: make: 1254-055 Dependency line needs colon or double colon operator.
"Makevars", line 7: make: 1254-055 Dependency line needs colon or double colon operator.
"Makevars", line 20: make: 1254-055 Dependency line needs colon or double colon operator.
"Makevars", line 24: make: 1254-055 Dependency line needs colon or double colon operator.
"Makevars", line 28: make: 1254-055 Dependency line needs colon or double colon operator.
make: 1254-058 Fatal errors encountered -- cannot continue.
ERROR: compilation failed for package 'readr'
* removing '/software/R/site-library/readr'

**Comment by bergen288** [comment]
I extracted readr tar file.  The Makevars file is inside src subdirectory as below.  Line 3 is "ifeq" statement and line 5 is "else" statement.  Line 28 is the last "endif".

# If R_ARCH exists the shared library will be in e.g. pkgdir/libs/32/readr.so,
# so we need to go up 2 levels. Otherwise only 1
ifeq "$(R_ARCH)" ""
RPATH = '../rcon$(R_ARCH)'
else
RPATH = '../../rcon$(R_ARCH)'
endif

PKG_LIBS = -L. -lrcon -L$(RCON_DIR) -Wl,-rpath,'$$ORIGIN/$(RPATH)'
PKG_CXXFLAGS = -I. -Ircon

LIBRCON = ../inst/rcon$(R_ARCH)/librcon.so
RCON_DIR = ../inst/rcon$(R_ARCH)

all: $(SHLIB)

$(SHLIB): $(LIBRCON)

UNAME:=$(shell uname -s)
ifeq ($(UNAME), Darwin)
$(LIBRCON): rcon/connection.o
	mkdir -p $(RCON_DIR)
	$(SHLIB_LINK) -o $(LIBRCON) $^ -Wl,-install_name,@loader_path/$(RPATH)/librcon.so
else
$(LIBRCON): rcon/connection.o
	mkdir -p $(RCON_DIR)
	$(SHLIB_LINK) -o $(LIBRCON) rcon/connection.o
endif

clean:
	rm -f rcon/connection.o $(LIBRCON)

**Comment by jimhester** [comment]
The development version of readr doesn't have any Makevars file, so this is already 'fixed'.

**Comment by bergen288** [comment]
Can you tell me how to get readr dev version?

Thanks.

Xiaobo.

**Comment by jimhester** [comment]
https://github.com/tidyverse/readr#installation
