### ISSUE TITLE
Tabs are not trimmed when trim_ws = TRUE using *read_delim*

### ISSUE THREAD

**Issue by jennahamlin** [tidyverse/readr#1100]
It appears that the read_delim function doesn't trim white space for extra tabs. 

Here there are five tabs, and the expected number is three. In theory, should it trim the tab after the new line call which generates the NA in the X1 column along with the final tab (after \6)

```r
> library(readr)
> packageVersion("readr")
[1] ‘1.3.1’

read_delim("1\t2\t3\n\t4\t5\t6\t", col_names = FALSE, delim="\t", trim_ws = T)

Warning: 1 parsing failure.
row col  expected    actual         file
  2  -- 3 columns 5 columns literal data

# A tibble: 2 x 3
     X1    X2    X3
  <dbl> <dbl> <dbl>
1     1     2     3
2    NA     4     5
```

**Comment by jimhester** [comment]
A tab cannot be both the delimiter and considered whitespace, I think this is working as intended.

**Comment by jennahamlin** [comment]
ahh that makes sense :)
