### ISSUE TITLE
Warning message: Missing column names filled in: 'X1' [1] 

### ISSUE THREAD

**Issue by jssa98** [tidyverse/readr#1103]
Hello, I wanted to open with read_csv() a documento, but when doing it there comes a legend in the console saying:

```r
Warning message:
Missing column names filled in: 'X1' [1] 
```
The thing, there wasn´t a 'X1' column in the original document (before saving it with write_csv()) and it's appearing now. What should I do in order to solve the problem?

**Comment by richelbilderbeek** [comment]
I have the same error. In my case it is caused when saving a CSV with base R, for a data frame with rownames, after which that file is loaded with readr.

I will helpfully supply a reprex:

```
t <- data.frame(x = c(3, 4), row.names = c(1, 2))
filename <- tempfile()
write.csv(x = t, file = filename)
u <- readr::read_csv(
  filename,
  col_types = readr::cols(
    X1 = readr::col_double(),  
    x = readr::col_double()
  )
)
```

The warning I get is exactly the same. How do I get rid of that warning (except for `suppressWarnings` :grin:)?

**Comment by jimhester** [comment]
You just need to use `suppressWarnings()`, there is no way to for readr to handle this type of data without a warning.

**Comment by richelbilderbeek** [comment]
Clear, I can work with that! Thanks!
