### ISSUE TITLE
read_lines() on tarball produces extra lines

### ISSUE THREAD

**Issue by kiernann** [tidyverse/readr#1105]
Reading a tarball file produces two errors:
1. The first element is replaced with the content path
2. the last (added) element is an empty string

``` r
library(tidyverse)
library(fs)
tmp <- file_temp(ext = "txt")
write_lines(LETTERS[1:3], tmp)
tgz <- file_temp(ext = "tar.xz")
tar(tgz, tmp, compression = "xz", tar = "tar")
read_lines(tmp)
#> [1] "A" "B" "C"
read_lines(tgz)
#> [1] "tmp/Rtmp3w6Oub/fileb8f14e9e2d52.txt" "B"                                  
#> [3] "C"                                   ""
```

<sup>Created on 2020-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
readr does not support reading from tar archives, you would need to extract the file first.

Alternatively you could use the `archive` package to get a connection to the file within the tarball.

``` r
library(readr)
library(fs)

tmp <- file_temp(ext = "txt")
write_lines(LETTERS[1:3], tmp)
tgz <- file_temp(ext = "tar.xz")
tar(tgz, tmp, compression = "xz", tar = "tar")

# remotes::install_github("jimhester/archive")
read_lines(archive::archive_read(tgz))
#> [1] "A" "B" "C"
```

<sup>Created on 2020-09-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
