### ISSUE TITLE
wchar_t Unicode warning on Solaris

### ISSUE THREAD

**Issue by wch** [tidyverse/readr#1106]
Filing this issue since @cpsievert saw the same thing for htmltools and figured out the problem and thought you'd want to know. 

On Solaris, readr currently has this warning:

```
checking for unstated dependencies in ‘tests’ ... WARNING
Warning in deparse(e[[2L]]) :
  it is not known that wchar_t is Unicode on this platform
Warning in deparse(e[[2L]]) :
  it is not known that wchar_t is Unicode on this platform
Warning in deparse(e[[2L]]) :
  it is not known that wchar_t is Unicode on this platform
Warning in deparse(e[[2L]]) :
  it is not known that wchar_t is Unicode on this platform
```

We had that warning for htmltools when checked with `--as-cran` on Solaris.

We found that it happens when a high-valued Unicode character is printed. For example:

```
> "\U0001F937"
[1] "\U0001f937"
Warning message:
it is not known that wchar_t is Unicode on this platform 
```

However, for lower-valued Unicode characters, it seems to be OK.

```
> "\Uff \U4E2d"
[1] "ÿ 中"
```

In htmltools, we didn't print the weird character in the tests, but it probably happened when the test fails (because perhaps Solaris isn't representing the character correctly), and then it tries to print the character. We worked around it by just disabling the relevant test on Solaris.

**Comment by jimhester** [comment]
Thanks, I now skip these tests on solaris.
