### ISSUE TITLE
Add optional End Of Line (EOL) parameter for write functions 

### ISSUE THREAD

**Issue by nogeel** [tidyverse/readr#1108]
One challenge for using readr for writing files to be processed by other software is the lack of ability to define a Windows or Unix end of line characters. Adding a parameter for defining the EOL, like in read.table, would allow scripts to have consistent output regardless of the operating system the script is executed on.

**Comment by jimhester** [comment]
This was done in https://github.com/tidyverse/readr/commit/938ca0c944f63eaf3dce9b6367a82d44e60f3420 and is already in the devel version of readr, it is just not yet on CRAN.
