### ISSUE TITLE
`type_convert()` ignores `cols()` specification without warning when not able to convert

### ISSUE THREAD

**Issue by StevenMMortimer** [tidyverse/readr#1115]
### Overview
It appears that the function `type_convert()` will not convert a column unless it is `character`. It would be helpful to have a warning message or a `verbose` argument in the function to control warnings when `type_convert()` is unable to enforce the supplied `cols()` specification.

----
### Reproducing the issue

``` r
suppressPackageStartupMessages(library(dplyr))
library(readr)

# Specify the desired data structure, a 2-column data frame with one column a 
# double and the other a datetime
desired_column_spec <- cols(v1="d", v2="T")

# SITUATION 1 (GOOD): Enforce desired spec on load, even when values are all NA
read_csv("v1,v2\nNA,NA\nNA,NA", col_types = desired_column_spec)
#> # A tibble: 2 x 2
#>      v1 v2                 
#>   <dbl> <dttm>             
#> 1    NA NA                 
#> 2    NA NA

# SITUATION 2 (GOOD): Use a "generic spec", essentially forcing specific columns as 
# character, which type_convert supports to convert to numeric and datetime
df <- read_csv("v1,v2\nNA,NA\nNA,NA", col_types = cols(v1="c", v2="c"))
df %>% type_convert(col_types = desired_column_spec)
#> # A tibble: 2 x 2
#>      v1 v2                 
#>   <dbl> <dttm>             
#> 1    NA NA                 
#> 2    NA NA

# SITUATION 3 (NOT GOOD): Load without spec, which causes columns to be logical, then 
# you can't use type_convert() at all, and what's worse is that there is no warning message 
# that nothing was converted
df <- read_csv("v1,v2\nNA,NA\nNA,NA")
df %>% type_convert(col_types = desired_column_spec)
#> # A tibble: 2 x 2
#>   v1    v2   
#>   <lgl> <lgl>
#> 1 NA    NA   
#> 2 NA    NA
```

In SITUATION 3 you can't convert a logical column back to a double or character, even if that is a possible datatype to cast from the existing values in the column. It is important to note that warnings do appear when trying to cast a `character` to another datatype when it is not possible (e.g. `character` to `numeric` column). One could hope to get a similar type of warning if the `logical` column is specified in `cols()` but not actually being converted.

``` r
suppressPackageStartupMessages(library(dplyr))
library(readr)

df <- read_csv("v1,v2\nhi,NA\nNA,NA")
# this prints an warning message at least!
df %>% type_convert(col_types = cols(v1="d", v2="c"))
#> Warning in type_convert_col(char_cols[[i]], specs$cols[[i]], which(is_character)
#> [i], : [0, 1]: expected a double, but got 'hi'
#> # A tibble: 2 x 2
#>      v1 v2   
#>   <dbl> <lgl>
#> 1    NA NA   
#> 2    NA NA
```

----
### Discussion of potential solutions

I'm starting to confuse myself a bit on whether the desired behavior for `type_convert()` is to essentially replicate `type.convert` in the sense that only character columns will be converted `vs.` being able to use the `col_types` argument like we do with `read_csv()` to enforce a specific datatype for each column. The latter seems like useful functionality for `type_convert()` to have, and if not, then potentially in a separate function.

----
### Current Workaround

If you can't enforce the column datatypes on load (e.g. via read_csv), then convert all columns to strings and then use type_convert from there.

``` r
suppressPackageStartupMessages(library(dplyr))
library(readr)
df <- read_csv("v1,v2\nNA,NA\nNA,NA") # assume you can't enforce spec here on load
# cast the columns
df %>% 
  mutate_at(c("v1"), ~parse_double(as.character(.x))) %>% 
  mutate_at(c("v2"), ~parse_datetime(as.character(.x)))
#> # A tibble: 2 x 2
#>      v1 v2                 
#>   <dbl> <dttm>             
#> 1    NA NA                 
#> 2    NA NA
```

**Why you need to use this workaround**
You have to use this workaround if you're not sure whether the column will contain all `NA` values. In the example below, the columns in `df2` are not all `NA`, so we don't really need to use the `mutate_at`, but if we don't know ahead of time, then we still have to do it this way. Otherwise, we'll get trapped into uncastable `logical` column types.

``` r
suppressPackageStartupMessages(library(dplyr))
library(readr)

df1 <- read_csv("v1,v2\nNA,NA\nNA,NA")
df1 %>% 
  mutate_at(c("v1"), ~parse_double(as.character(.x))) %>% 
  mutate_at(c("v2"), ~parse_datetime(as.character(.x)))
#> # A tibble: 2 x 2
#>      v1 v2                 
#>   <dbl> <dttm>             
#> 1    NA NA                 
#> 2    NA NA

df2 <- read_csv("v1,v2\n1,1979-10-14T10:11:12\nNA,NA")
df2 %>% 
  mutate_at(c("v1"), ~parse_double(as.character(.x))) %>% 
  mutate_at(c("v2"), ~parse_datetime(as.character(.x)))
#> # A tibble: 2 x 2
#>      v1 v2                 
#>   <dbl> <dttm>             
#> 1     1 1979-10-14 10:11:12
#> 2    NA NA

bind_rows(df1, df2)
#> # A tibble: 4 x 2
#>      v1 v2                 
#>   <dbl> <dttm>             
#> 1    NA NA                 
#> 2    NA NA                 
#> 3     1 1979-10-14 10:11:12
#> 4    NA NA
```

<sup>Created on 2020-07-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
Yes, `type_convert` only does conversions from character columns. I think doing anything else (include checking if the input type matches the `col_types` for that column) is out of scope for what we want `type_convert` to do.

**Comment by StevenMMortimer** [comment]
@jimhester Sounds good, but the way the documentation reads, it seems like you're allowed to control the column types like you're able to with `read_csv()`. In the case you mention, it seems like the `col_types` argument is not very helpful, thus the function doesn't do much beyond `type.convert()`.

**Comment by jimhester** [comment]
You can control the column types like you are able to with `read_csv()`, just like with `read_csv()` all column inputs are characters, and you specify what types you want them to turn into. e.g. these two calls are basically equivalent as far as the type conversion go 

``` r
writeLines("a,b,c\n1,2.5,foo", "data.csv")

library(readr)
x <- read_csv("data.csv", col_types = "idf")
x
#> # A tibble: 1 x 3
#>       a     b c    
#>   <int> <dbl> <fct>
#> 1     1   2.5 foo

y <- read_csv("data.csv", col_types = list(.default = "c"))
y <- type_convert(y, col_types = "idf")
y
#> # A tibble: 1 x 3
#>       a     b c    
#>   <int> <dbl> <fct>
#> 1     1   2.5 foo

# subset with nothing to drop the spec attribute
all.equal(x[], y[])
#> [1] TRUE
```

<sup>Created on 2020-07-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by StevenMMortimer** [comment]
@jimhester Yeah, the key assumption you're making is that the two calls are only equivalent iff **all column inputs to `type_convert()` are characters**. 

The two things I had hoped to highlight with this issue, but probably failed to synthesize are:

1. The function doesn't alert the user that columns will not being converted if they are not character even when the user provides a  `cols()` spec. This is fine, but not great from a user perspective since it is silently not doing anything for you. A warning would be nice (e.g. `"Columns X, Y, Z were not converted because they are not character."` or if nothing is done: `"No values converted. All columns must be character."`)

2. This issue probably falls closer on the spectrum of feature request rather than bug report. It would be handy to have a function that can attempt to cast columns according to a `cols()` spec without requiring them to be character. The `type_convert()` function is just a special case of what I'm describing, so it makes logical sense to to take functionality already provided in the package and make more robust/generalizable.

---

### Example
Below is a simpler example where the same data parsed in `read_csv()` will not yield the same result as a `tbl_df` of the same data to be processed using the same `cols()` spec  in a call to `type_convert()`.

``` r
writeLines("a,b,c\nNA,2.5,foo", "data.csv")

library(readr)
x <- read_csv("data.csv", col_types = "idf")
x
#> # A tibble: 1 x 3
#>       a     b c    
#>   <int> <dbl> <fct>
#> 1    NA   2.5 foo


# the line below this comment yields the same tbl_df as: 
#    y <- read_csv("data.csv") 
# but I am including it here to show that the user many not always be 
# starting from a CSV,  but potentially a data frame already 
# existing in the environment
y <- dplyr::tibble(a = NA, b=2.5, c="foo")
y <- type_convert(y, col_types = "idf")
y
#> # A tibble: 1 x 3
#>   a         b c    
#>   <lgl> <dbl> <fct>
#> 1 NA      2.5 foo

# subset with nothing to drop the spec attribute
all.equal(x[], y[])
#> [1] "Component \"a\": Modes: numeric, logical"              
#> [2] "Component \"a\": target is numeric, current is logical"
```

<sup>Created on 2020-07-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
