### ISSUE TITLE
Need option to ignore terminator at end of each line instead of parsing failure per line?

### ISSUE THREAD

**Issue by EarlGlynn** [tidyverse/readr#1117]
`read_delim` works OK with files that use field "terminators" instead of "separators", but why not give a way to ignore a warning per line because of an unexpected terminator on each line?  Perhaps a new option like `ignore_terminator = TRUE`, where the default now is FALSE.

In a file I'm processing, I get 52426 parsing failures -- one for each line:

```
Warning: 52426 parsing failures.
row col   expected     actual                                                   file
  1  -- 45 columns 44 columns '../../../Data/2020-07-26/8871-Form-Record-Header.txt'
  2  -- 45 columns 44 columns '../../../Data/2020-07-26/8871-Form-Record-Header.txt'
```

I took care of the phantom column created by the unexpected terminators in this kludgy way:

```
organizations <- 
  read_delim(
              filename, 
              delim = "|",                       # pipe delimiter
              quote = "",                        # not quote delimited
              na = character(),                  # no missing values
              col_types = cols(.default = "c")   # all character types for now
            )     %>%
  select(-X45)                                   # phantom column because "|" terminator after last field
```

I cannot "fix" the files since they are created by a government agency.  Thanks for your consideration.

**Comment by jimhester** [comment]
I would suggest you use `suppressWarnings()` when reading these files.
