### ISSUE TITLE
Memory use accumulates over multiple callbacks with chunked read function

### ISSUE THREAD

**Issue by we-hop** [tidyverse/readr#1120]
---

Using read_tsv_chunked() to read in a large file (>20GB). Read in 100K lines per callback and using dbWriteTable() to
write to a table already created in Sqlite database. This was done when the data size was increased 11X
over what it was.

By viewing the process using top, the memory size continually increases over the course of the read. My suspicion
is that the memory used to pass in the chunk to the callback function  is allocated for each call and not properly deallocated;
the process size increases as it did when reading the entire file in at once.

I'd look at the code myself given some indication where it is defined.

```r
  r2rChunk <- function(r2r.chunk.df, pos) {
    # pos is passed in, but not needed
    # message(str_c(geo.file, " chunk position: ", pos))
    
    RSQLite::dbWriteTable(dbcon, "netflow_table", r2r.chunk.df, append = TRUE, row.names = FALSE)
    
    # perhaps this will release memory from earlier chunks passed in - it seems to accumulate given process size
    gc()
  }
  
  # specify the columns that must be overridden from the guess
  r2r.cols <- readr::cols(
    dstASN = readr::col_number(), # skips non-digits before and after, and grouping marks
    ipbusBytes = readr::col_double()
  )
  
  readr::read_tsv_chunked(
    file = nf.file,
    callback = readr::SideEffectChunkCallback$new(r2rChunk),
    chunk_size = 100000,
    na = c("null", ""),
    col_types = r2r.cols
  )

```

**Comment by jimhester** [comment]
Should be fixed by https://github.com/tidyverse/readr/commit/9fe20f693050239383c3dcdc48688d07c81bb05c

**Comment by we-hop** [comment]
Thanks!

When do you expect the fix to be available?

Bill Hopkins

**Comment by daniel-hain** [comment]
Hello,

just wanted to follow up on that, since I have currently the same problem. I am trying to feed a large cvs chunkwise in a PostgresSQL. While doing so, the memory usage slowly accumulates from some mb to 20 GB. 

I use the code:

`
### Helper function to write chunked csv into SQL
to_sql_chunked <- function(con, 
                           tbl_name, 
                           append = TRUE, 
                           overwrite = FALSE) {
  function(x, pos) {
    
    dbWriteTable(conn = con, 
                 name = tbl_name, 
                 value = x, 
                 append = append,
                 overwrite = overwrite,
                 row.names = FALSE)
  }
}

### loads a series of csvinto PostgreSQL
patstat_import_postgre <- function(con,
                                  tbl_path,
                                  tbl_name = NULL,
                                  append = TRUE,
                                  overwrite = FALSE,
                                  chunk_size = 5000000,
                                  ...) {
  
  read_csv_chunked(file = tbl_path,
                   callback = SideEffectChunkCallback$new(to_sql_chunked(con = con, tbl_name = tbl_name, append = append, overwrite = overwrite)),
                   chunk_size = chunk_size,
                   col_names = TRUE,
                   quoted_na = FALSE,
    )
  }
`

**Comment by arthurgailes** [comment]
Having the same problem as above, also with Postgres
