### ISSUE TITLE
Add col_names argument to type_convert()

### ISSUE THREAD

**Issue by kiernann** [tidyverse/readr#1121]
I often use `readr::type_convert()` when scraping an HTML table via `rvest::html_table()` to parse it as a tibble. 

HTML tables often use weird `NA` values (_check_), bad column types (_check_), and bad column names (_missing_).

**Comment by kiernann** [comment]
A `skip` argument like `readr::read_delim(skip = 1)` would also be useful for messy HTML tables like [this from Wikipedia](https://w.wiki/fGx).

**Comment by jimhester** [comment]
Thanks for filing this issue! Unfortunately, I think this would cause more confusion for other use cases than it would help here. You could use `stats::setNames()` to set the column names before passing to `type_convert()`.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:
