### ISSUE TITLE
col_datetime should allow specifying time zone

### ISSUE THREAD

**Issue by DarwinAwardWinner** [tidyverse/readr#1122]
I have recently had the misfortune of having to read a csv file containing multiple datetime columns stored in *different time zones*. As far as I can tell, readr does not directly support this case, instead requiring me to read all the datetime columns as `col_character()` and parse the dates manually. Is it possible to add a time zone argument to `col_datetime()` to allow me to specify time zones per-column?

**Comment by jimhester** [comment]
No this is not easily possible, and unfortunately I don't believe we can invest the time or additional code complexity to support it.

I think your workaround of parsing them as character and post processing them is the best thing to do.
