### ISSUE TITLE
Error message in R

### ISSUE THREAD

**Issue by jasyael** [tidyverse/readr#1131]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

We are trying to run a forest plot and keep getting this problem. Any suggestions?

```r
Warning: Error in : Assigned data `as.list(newrow)` must be compatible with existing data.
i Error occurred for column `moa`.
x Can't convert <character> to <double>.
  68: <Anonymous>

```

**Comment by jimhester** [comment]
I don't believe this error is coming from readr.

I would suggest you post this sort of question on <https://community.rstudio.com> . Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
