### ISSUE TITLE
News link is broken

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/readr#1134]
The News link at gives a 404 error, and it looks like the latest commit eb2f24c17c8cdbabdb6870a4bc8e902d5e68081b isn't reflected since the latest news is 1.3.1.

**Comment by damianooldoni** [comment]
It seems that all links to the versions are broken. below a screenshot when clicking on Version 1.3.1 under News
![image](https://user-images.githubusercontent.com/33662631/108327647-f1905580-71cb-11eb-9865-909b71b7813a.png)

And then, any other link doesn't work anymore as the site is stuck in the specified version, i.e. all links start with `https://readr.tidyverse.org/articles/2018/12/readr-x-x-x/articles/` prefix, e.g. https://readr.tidyverse.org/articles/2018/12/readr-1-3-1/articles/reference/articles/reference/index.html

Maybe a problem in the [pkgdown yml ](https://github.com/tidyverse/readr/blob/master/_pkgdown.yml)?
