### ISSUE TITLE
parse_number imprecise output

### ISSUE THREAD

**Issue by Dana996** [tidyverse/readr#1135]
When applying `parse_number` to certain strings, the result varies slightly from the desired numerical value. For instance
```{r}
parse_number('123,345.12') - 123345.12
```
outputs 1.455192e-11 instead of 0. Note that, if I where to instead clean up the string and apply `as.numeric`, I would obtain a more precise answer. Indeed,
```{r}
as.numeric('123345.12') - 123345.12
```
outputs 0.

**Comment by jimhester** [comment]
This is http://www.hep.by/gnu/r-patched/r-faq/R-FAQ_82.html

**Comment by Dana996** [comment]
I thought that since this is a relatively simple number which doesn't need to be rounded in a standard float representation, there might be an issue.

**Comment by jimhester** [comment]
If look at the bit sequences of these two values you will see they differ in only the least significant bit.

``` r
x <- readr::parse_number('123,345.12')
y <- 123345.12

pryr::bits(x)
#> [1] "01000000 11111110 00011101 00010001 11101011 10000101 00011110 10111001"
pryr::bits(y)
#> [1] "01000000 11111110 00011101 00010001 11101011 10000101 00011110 10111000"
```

<sup>Created on 2020-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As mentioned in the FAQ the only fractions that can be represented exactly with IEEE doubles are numbers that are evenly divisible by powers of 2. 3/25 (e.g. 0.12) is unfortunately not one of these.

I don't believe there is an problem with this, so I will close this issue.

**Comment by Dana996** [comment]
Thank you for the detailed answer!
