### ISSUE TITLE
Please use `deprecate_soft` before `deprecate_warn`

### ISSUE THREAD

**Issue by antoine-sachet** [tidyverse/readr#1137]
Several of our packages depending on `readr` started throwing warnings because of the recent `path` -> `file` argument renaming. 

Can I please ask you to use `deprecate_soft` before `deprecate_warn` next time, especially when there is no urgency.
It gives us developers a chance to catch the update in our automated tests while not bothering our end users. 

Thanks,
Antoine

**Comment by jimhester** [comment]
Ok, we will bare it in mind.

**Comment by jan-glx** [comment]
And please always deprecate instead of just changing the name. What was that
https://github.com/tidyverse/readr/commit/1870a76b9a73bbbf3c723f556f224f7a6a95d34d ??
