### ISSUE TITLE
The is.character() check in parse_number() seems unnecessary.

### ISSUE THREAD

**Issue by BrianOB** [tidyverse/readr#1139]
If you give parse_number() a vector that includes numbers in both numeric and character format, it returns an all-numeric vector without complaint.

> readr::parse_number(c(10,'15','12,345'))
[1]    10    15 12345

If you give it a vector that's all numeric, it throws an error:

> readr::parse_number(c(10,15,20))
Error in parse_vector(x, col_number(), na = na, locale = locale, trim_ws = trim_ws) : 
  is.character(x) is not TRUE

In the following real-world example, reading the sample county-by-county election results in Pennsylvania results in a list of dataframes where the Votes column is usually in character format, since they contain comma-delimited vote totals but some of the smaller counties have Votes columns in integers. Ideally, you want them all to be integers for analysis, but running parse_number() on them produces the error because of the few that are in integer format.

What's the issue the is.character() test is designed to prevent?

``` r
library(tidyverse)

payload <- xml2::read_html("https://electionreturns.pa.gov/electionFeed.aspx?ID=23&FeedName=2020+Primary+Election+by+County")

df <- payload %>%
  rvest::html_nodes("table") %>%
  rvest::html_table(header = TRUE, fill = TRUE)

df <- purrr::imap(df, ~mutate(.x, Votes = readr::parse_number(Votes)))
#> Error: Problem with `mutate()` input `Votes`.
#> x is.character(x) is not TRUE
#> i Input `Votes` is `readr::parse_number(Votes)`.
```

<sup>Created on 2020-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
There is no point to calling `parse_number() `on a non-character vector, there is nothing to parse in that case.

The best case you will waste time converting your numbers to characters and then parsing them back to the same numbers. 

The worst case you lose precision on the roundtrip and end up with close but not equal numbers.

You can change your code to something like this

```r
df <- purrr::imap(df, ~mutate(.x, Votes = if (is.character(Votes) readr::parse_number(Votes) else Votes))
