### ISSUE TITLE
write_csv (and any other in the write_delim family) can't export NaN anymore

### ISSUE THREAD

**Issue by jonasfoe** [tidyverse/readr#1146]
Hi,
I have an issue with the commit ccc4dea68fe8c0cb1e19d3e279c532ccebed5775 for readr 1.4.0:
* `write_*()` functions now output any NaN values in the same way as NA values,
  controlled by the `na=` argument. (#1082).

I can't export `NaN` anymore, which I was using for my work.
Since this was is in line with `write.csv()` and `data.table::fwrite()`, I can't export `NaN` in any user friendly function right now.

So this breaking change is very unfortunate for me.
Would you be interested in a pull request that adds a function argument `nan=`, which defaults to the `na=` argument?
This would add back the functionality while keeping the latest change intact.

**Comment by jimhester** [comment]
Thanks for filing this issue! Unfortunately, we need to restrict the arguments to only be those used by a significant fraction of users.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

I would suggest you format your data in the way you desire prior to calling any of the write functions.

e.g. convert all the numeric columns to character data, handling NaN in whatever method you need, then call the writing function.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:
