### ISSUE TITLE
[BUG] read_csv, read_delim, read_csv2 unable to read entire document when .1 (or other number) files with " in it.

### ISSUE THREAD

**Issue by KnutEBakke** [tidyverse/readr#1148]
Hi,

I am reading in data from files with the format name1.vis.1, name2.vis.1, name1.vis.2 (etc...).

Everything works fine, except for one file, containing a " character.

The readr functions are unable to see data after this character when using the "skip" attribute.

---

Brief description of the problem

```r
library(tidyverse)


data1 <- read_csv(paste(getwd(),"/test.1", sep = ""),col_names = FALSE, skip = 0)


data2 <- read_csv(paste(getwd(),"/test.1", sep = ""),col_names = FALSE, skip = 3)
```

Test is a .1 file with the following inside:

abc

"

abc

**Comment by jimhester** [comment]
Fixed by #1172
