### ISSUE TITLE
Update cheat sheet: `path` → `file` 

### ISSUE THREAD

**Issue by GegznaV** [tidyverse/readr#1149]
Please, update `readr` cheatsheet so that argument `file` was used instead of `path`.

**Comment by jimhester** [comment]
The cheatsheets are actually managed in a separate repository [rstudio/cheatsheets](https://github.com/rstudio/cheatsheets/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) would you mind opening an issue there?

**Comment by GegznaV** [comment]
I opened rstudio/cheatsheets#152
