### ISSUE TITLE
Using ISO 8601 week format in parse_datetime() crashes R

### ISSUE THREAD

**Issue by cboettig** [tidyverse/readr#1159]
I know that the docs say ISO8601 week format is not supported.  Still an error message would be better, currently if I try parsing that with the specified format string it consistently crashes my R session instead:

```r
readr::parse_datetime("2020-W44-1", format = "%Y-W%V-%d")
```

reprex says:

```r
> reprex::reprex ( readr::parse_datetime("2020-W44-1", format = "%Y-W%V-%d") )
Rendering reprex...
Error in get_result(output = out, options) : 
  callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
Type .Last.error.trace to see where the error occured
```

I'd also like to voice my support for #105, since I do see this data format in the wild and haven't been able to figure out any way to parse this format in R.  (I realize this part of the standard is seen as a rare edge case, but just wanted to note it's not addressed by `strptime` or `lubridate` either, even though in those cases the documentation is not so clear about it and the functions just silently give the wrong date).  Thanks for considering!

**Comment by cboettig** [comment]
a ha, just a footnote here that https://cran.r-project.org/web/packages/ISOweek/index.html appears to provide a mechanism for this (even though it would be really nice not to need a unique package for a single datetime format!)

**Comment by jimhester** [comment]
The crash was a bug already fixed in the devel version of readr. (https://github.com/tidyverse/readr/commit/97186a8ac29d2058762d85b13b169e8b4ca5da71)

I understand this could be useful, possibly we could consider supporting it if we revamp the date time handling in the future.
