### ISSUE TITLE
read_csv fails on an empty gzip'd file

### ISSUE THREAD

**Issue by mgperry** [tidyverse/readr#1160]
Create and gzip an empty file:

```sh
touch example.csv
gzip -k example.csv
```

Uncompressed version is read fine, compressed version crashes:

```r
read_csv("example.csv") # 0x0 table
read_csv("example.csv.gz") # Error in guess_header_(datasource, tokenizer, locale) : Cannot read file /priavte/[*tmp*]: Invalid Argument
```

Base R functions either return an error due to the empty table, or work fine, so it's not a corruption issue:

```r
read.csv("example.csv.gz") # Error: no lines available in input
readLines("example.csv.gz") # character(0)
```

PS I know writing empty tables with no header is bad practice, these crashes came from unexpected output of one of our tools :)

**Comment by jimhester** [comment]
Fixed by #1172
