### ISSUE TITLE
Grouping Boxplots

### ISSUE THREAD

**Issue by CTMCBP** [tidyverse/readr#1162]
I have this code:

SSDTN <- ggplot(SSD, aes(x = Stream_name, y = TN_mgL, fill = Bay_seg)) + 
  geom_boxplot()

SSDTN<-SSDTN + theme(axis.text.x = element_text(angle = 90))
  
plot(SSDTN)

that produces this plot:

![image](https://user-images.githubusercontent.com/76133826/102416312-92de0e00-3fc7-11eb-92c2-e5a5e4a2915e.png)

My goal is to group the streams and there boxplots by the Bay_seg. In other words, instead of the x-axis having the streams in alphabetical order, I need all the streams and their boxplots organized so they are grouped together by their associated Bay_seg. How do I edit my code to do that?

I appreciate any help!

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
