### ISSUE TITLE
guess_encoding: pkgdown Page not found (404) error

### ISSUE THREAD

**Issue by MikeJohnPage** [tidyverse/readr#1166]
The pkgdown site is failing to find the `guess_encoding` documentation: https://readr.tidyverse.org/reference/guess_encoding.html

I've had a quick check of the roxygen comments and can't spot anything out of place so I am not sure if this is intentional. Thought I should flag it just in case.

**Comment by batpigandme** [comment]
Looks like the URL for the `guess_encoding()` function is at …encoding.html
https://readr.tidyverse.org/reference/encoding.html

**Comment by MikeJohnPage** [comment]
Ah, good spot.

The reason I stumbled on the 404 error was becasue in the locales vignette on the pkgdown site, the link to the `guess_encodings` function redirects you to https://readr.tidyverse.org/reference/guess_encoding.html

I've submitted a PR #1167 with a fixed link, but I don't think this is addressing the root of the problem (I am not entirely sure how pkgdown works / generates links).

**Comment by jimhester** [comment]
Fixed by https://github.com/tidyverse/readr/pull/1167
