### ISSUE TITLE
Documentation rendering for parse_datetime is broken

### ISSUE THREAD

**Issue by DarwinAwardWinner** [tidyverse/readr#1176]
The rendered help text for `readr::parse_datetime` contains a systematic formatting issue that makes the "Format specification" section useless. I'm not sure what causes this, as the [source](https://github.com/tidyverse/readr/blob/master/R/collectors.R#L259-L294) appears to be properly formatted.

```r
library(readr)
help("parse_datetime")
```

Whether at the console, in RStudio, or even on https://readr.tidyverse.org/reference/parse_datetime.html, the documentation looks like this:

<img width="648" alt="Window 2021-01-28 at 10 58 48" src="https://user-images.githubusercontent.com/228145/106164434-f4ad9e00-6157-11eb-8002-a2b4d63acc7e.png">
<img width="667" alt="Window 2021-01-28 at 10 57 59" src="https://user-images.githubusercontent.com/228145/106164456-f9725200-6157-11eb-9d21-d279247eee9c.png">
<img width="881" alt="Window 2021-01-28 at 10 59 29" src="https://user-images.githubusercontent.com/228145/106164466-fc6d4280-6157-11eb-9278-700224932e8b.png">

Oddly, the documentation renders correctly on https://www.rdocumentation.org/packages/readr/versions/1.3.1/topics/parse_datetime:

<img width="907" alt="Window 2021-01-28 at 11 01 53" src="https://user-images.githubusercontent.com/228145/106164661-3b9b9380-6158-11eb-9522-c46b1b046b0a.png">

**Comment by DarwinAwardWinner** [comment]
Here is my session info. I notice that I have readr 1.4.0 (after running `update.packages` today) while the correctly rendered documentation on rdocumentation.org corresponds to 1.3.1. This site does not appear to have 1.4.0 at all.

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin19.6.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /usr/local/Cellar/openblas/0.3.13/lib/libopenblasp-r0.3.13.dylib
LAPACK: /usr/local/Cellar/r/4.0.3_2/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] readr_1.4.0

loaded via a namespace (and not attached):
 [1] compiler_4.0.3  magrittr_2.0.1  ellipsis_0.3.1  R6_2.5.0
 [5] hms_1.0.0       tools_4.0.3     pillar_1.4.7    tibble_3.0.5
 [9] crayon_1.3.4    vctrs_0.3.6     lifecycle_0.2.0 pkgconfig_2.0.3
[13] rlang_0.4.10
```

**Comment by DarwinAwardWinner** [comment]
The formatting issue also appears in the PDF documentation on CRAN: https://cloud.r-project.org/web/packages/readr/readr.pdf

<img width="704" alt="Screen Region 2021-01-28 at 12 23 51" src="https://user-images.githubusercontent.com/228145/106175079-b322f000-6163-11eb-89c6-68eeaacb6b49.png">

**Comment by jennybc** [comment]
This has already been fixed in dev (note the `dev` in this URL):

https://readr.tidyverse.org/dev/reference/parse_datetime.html

In this commit: e3b34233

The fix will propagate to all the rendered products you are looking upon release.
