### ISSUE TITLE
write_delim: German locale with numeric column: ~ 3 out of 300 values have comma instead of dot decimal separator

### ISSUE THREAD

**Issue by messersc** [tidyverse/readr#1179]
I have a tibble with 300 entries and 3 columns, one of the numeric (double). When I ```write_delim()``` (or write_tsv) to a file, I get 2 or 3 rows where the decimal separator is a comma instead of a dot. This leads to problems downstream, obviously. This only seems to happen when the locale is set to something that prints decimal numbers with a comma instead of a dot like German.

# Data

The tibble itself appears to be fine. It looks like this:

```{r}
> head(genes)
# A tibble: 6 x 3
  gene         pathway z_value
  <chr>        <chr>     <dbl>
1 VAT1L        Wnt      -27.3 
2 PSMD6        Wnt      -23.8 
3 FMN2         Wnt      -23.0 
4 LOC105374338 Wnt      -20.9 
5 COLEC12      Wnt      -14.3 
6 LOC100505585 Wnt       -8.11

```

# Expected behaviour

I would expect consistent use of the decimal separator for all rows.

# ReprEx

I was unable to reproduce the issue with the same data.frame in a new session and can therefore not provide a reprex at this point.

**Comment by jimhester** [comment]
Thanks for opening the issue! However we will need a reproducible example to have any hope of figuring out the cause. 

From what you told us above and what I know of the readr code I don't see how this behavior could be possible, so possibly the data was different than you believe.

**Comment by messersc** [comment]
Dear Jim,

I totally understand. Already trying to reproduce this (and failing) makes me wonder if this is a [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug). The bug need not be in readr either, maybe it was in tibble or something else.

I pasted the sessionInfo below, although the locale info is probably wrong now because I changed it around when I discovered the behaviour. Maybe readr 1.4.0 is fine. I will let you know if there are any news.

Best,
Clemens

```{r}
>     sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: openSUSE Leap 15.2

Matrix products: default
BLAS/LAPACK: /vol/home-vol3/wbi/messersc/miniconda3/envs/r_env/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=de_DE.UTF-8          LC_NUMERIC=C                 
 [3] LC_TIME=C                     LC_COLLATE=C                 
 [5] LC_MONETARY=C                 LC_MESSAGES=de_DE.UTF-8      
 [7] LC_PAPER=de_DE.UTF-8          LC_NAME=de_DE.UTF-8          
 [9] LC_ADDRESS=de_DE.UTF-8        LC_TELEPHONE=de_DE.UTF-8     
[11] LC_MEASUREMENT=de_DE.UTF-8    LC_IDENTIFICATION=de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] speed2_0.1.2    cowplot_1.0.0   rjson_0.2.20    forcats_0.5.0  
 [5] stringr_1.4.0   dplyr_1.0.0     purrr_0.3.4     readr_1.3.1    
 [9] tidyr_1.1.0     tibble_3.0.3    ggplot2_3.3.2   tidyverse_1.3.0
```
