### ISSUE TITLE
parse_number parses numbers with incorrect thousands separators

### ISSUE THREAD

**Issue by tmalsburg** [tidyverse/readr#1181]
`parse_number("1,500")` yields 1500 as expected.  However `parse_number("1,5")` yields 15 even though it is non-sense. If a number specification doesn't follow the conventional syntax, `parse_number` should return NA or NaN.  The current behavior is documented in the man page but that doesn't make it correct :)

**Comment by jimhester** [comment]
This is true, but we don't have plans to complicate the number parser further to handle this case.

**Comment by tmalsburg** [comment]
No need to complicate the parser. Just check whether the input matches a regexp and return NA + warning if not. Otherwise use the existing parser. Doesn’t sound too complicated to me.

The current implementation violates any reasonable expectation that users might have and can therefore wreak serious havoc.

**Comment by jimhester** [comment]
Ok, you now have a two pass algorithm and doubled (at least) the parsing time.

**Comment by tmalsburg** [comment]
I find your tone condescending.  What makes you think that I don't understand there is a cost? There is almost always a cost for making an implementation behave correctly. That doesn't usually stop us.  But never mind, I'm out.
