### ISSUE TITLE
make writing dttm timezones configurable - or at least provide a warning

### ISSUE THREAD

**Issue by sebneus** [tidyverse/readr#1184]
It would be great if it would be possible to write dttm as local time. Or at least provide a warning, if times are converted to UTC. Then I could remember to convert the time variables to strings myself before writing the data.frame.

Some programs which work with the output might not be able to handle timezones (correctly). I know it's not readr fault and the behaviour itself is correct. But as it is, I must remember either not to use readr::write_* or to convert the dttm variables to strings before writing them with readr.

**Comment by jimhester** [comment]
If you always want the timezones to be written with the local time you can define a `output_column.POSIXt` function to do this.

e.g. (my local timezone is America/New_York)

``` r
library(readr)
data <- tibble::tibble(
  index = 1:2,
  time = as.POSIXct(c("2021-01-02 05:04:03", "2020-11-23 09:08:07"))
)

format_csv(data)
#> [1] "index,time\n1,2021-01-02T10:04:03Z\n2,2020-11-23T14:08:07Z\n"

output_column.POSIXt <- function(x) {
  format(x, usetz = TRUE, justify = "none")
}

# Due to recent changes in method lookup you need to register the S3 method
registerS3method("output_column", "POSIXt", output_column.POSIXt)

format_csv(data)
#> [1] "index,time\n1,2021-01-02 05:04:03 EST\n2,2020-11-23 09:08:07 EST\n"
```

<sup>Created on 2021-05-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
