### ISSUE TITLE
Allow "skip" to specify multiple ranges

### ISSUE THREAD

**Issue by binkleym** [tidyverse/readr#1198]
Brief description of the problem

I'm trying to read in old US Census data from the 1860's.  Here's an example file:

http://us-census.org/pub/usgenweb/census/xtn/cheatham/1860/indx-a-b.txt

I've tried to read in the data using read_table:

    data <- read_table("http://us-census.org/pub/usgenweb/census/xtn/cheatham/1860/indx-a-b.txt", skip = 25)

The problem is, they use a long "VVVVVVV" line to delineate the header row, so if I start reading at row 25, the long "VVVV" string prevents read_table from defining the col_types correctly.

It would be useful if I could specify multiple skip ranges.   So to skip the first 25 lines, read one line, then skip the next line, something like "skip = c(25, 1)", or whatever makes sense.    

Or otherwise, tell read_table to skip any line that has "VVVVV" in it.  I tried to do this using the "comment" function but it didn't work.   It correctly plucks out the comment, but still auto-creates the col_types using the "VVVVV" line instead of the following lines.

    data <-   read_table("http://us-census.org/pub/usgenweb/census/xtn/cheatham/1860/indx-a-b.txt", skip = 25, comment = "VVVVV")

Hope that makes sense.

**Comment by jimhester** [comment]
I would suggest you use a custom function to read these files rather than adding additional complexity to readr.

``` r
library(readr)
read_census <- function(url) {
  tf <- tempfile()
  download.file(url, tf)
  on.exit(unlink(tf))
  nms <- strsplit(trimws(read_lines(tf, skip = 25, n_max = 1)), "[[:space:]]+")[[1]]
  read_table(tf, skip = 27, col_names = nms)
}

read_census("http://us-census.org/pub/usgenweb/census/xtn/cheatham/1860/indx-a-b.txt")
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   NAME = col_character(),
#>   AGE = col_character(),
#>   SEX = col_character(),
#>   RACE = col_character(),
#>   `PAGE-FAMILY` = col_character(),
#>   `FILE-NAME` = col_character()
#> )
#> # A tibble: 641 x 6
#>    NAME                AGE   SEX   RACE  `PAGE-FAMILY` `FILE-NAME`
#>    <chr>               <chr> <chr> <chr> <chr>         <chr>      
#>  1 ABBERNATHY, E.      19    F     W     P129-26       pg120.txt  
#>  2 ABBERNATHY, Ella L. 8     F     W     P002-11       pg001.txt  
#>  3 ABBERNATHY, Ellen   4     F     W     P005-19       pg001.txt  
#>  4 ABBERNATHY, Etty    5     F     W     P002-11       pg001.txt  
#>  5 ABBERNATHY, G. W.   11    M     W     P005-19       pg001.txt  
#>  6 ABBERNATHY, G. W.   30    M     W     P002-11       pg001.txt  
#>  7 ABBERNATHY, H. H.   9/12  M     W     P008-33       pg001.txt  
#>  8 ABBERNATHY, Jas.    4/12  M     W     P005-19       pg001.txt  
#>  9 ABBERNATHY, Jas. M. 43    M     W     P005-19       pg001.txt  
#> 10 ABBERNATHY, L.      18    F     W     P005-19       pg001.txt  
#> # … with 631 more rows
```

<sup>Created on 2021-04-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
