### ISSUE TITLE
[Bug report] read_delim()

### ISSUE THREAD

**Issue by mewu3** [tidyverse/readr#1205]
I got a problem when I tried to use read_delim in R studio, the same code work fine thought in commanded line with Rstript. 

Here is an example of the file allOligo_before.tsv
```
	oligo	kmerCount	CG%	Entropy	Tm	homodimer-dG	hairpin-dG	start	end
23526	CTCCCACCGTACA	2	61.538	0.835	38.408	-2688.954	0.0	45933	46057
12427	CTCCCACCGTACA	2	61.538	0.835	38.408	-2688.954	0.0	45682	46057
22710	GGAGACTTGGAAA	2	46.154	0.88	32.1	-1364.491	0.0	45431	45932
33357	ACGTCAATGGAAA	2	38.462	0.917	28.946	-1955.659	0.0	45180	45681
``` 

```r
> read_delim(file="allOligo_before.tsv", delim="\t")
Error in if (dark) { : valeur manquante là où TRUE / FALSE est requis
```

**Comment by batpigandme** [comment]
Is everything else working normally for you in RStudio? It occured to me when I read that error message that it sounds like a problem with the theme (for syntax highlighting).

I know it sounds like a long shot, but could you try switching themes and seeing if you're having the same problem? See how here: https://support.rstudio.com/hc/en-us/articles/115011846747-Using-RStudio-Themes

**Comment by jimhester** [comment]
If you could call `traceback()` in the console after you see this error I think it would help.

If I had to guess I would say the error is happening in the cli package.

**Comment by mewu3** [comment]
> Is everything else working normally for you in RStudio? It occured to me when I read that error message that it sounds like a problem with the theme (for syntax highlighting).
> 
> I know it sounds like a long shot, but could you try switching themes and seeing if you're having the same problem? See how here: https://support.rstudio.com/hc/en-us/articles/115011846747-Using-RStudio-Themes

I have switched the theme and as a matter of fact it works again ! Thank you very mush !
