### ISSUE TITLE
Feature request: let `skip` be a prefix or a function

### ISSUE THREAD

**Issue by deeenes** [tidyverse/readr#1213]
Currently, `read_delim` and co. accept integers for their `skip` argument, which is "the number of lines to skip before reading data". I would find it highly useful if we could pass either a prefix or a function.

**Prefix**
In case of a prefix, the lines starting with the prefix would be skipped. For example, `read_delim(..., skip = '!')` would result the lines starting with "!" to be skipped.

**Function**
This would give full flexibility, the lines for which the function returns `TRUE` would be skipped. For example, `read_delim(..., skip = function(x){str_count('\t') < 5})` would result, in a tab separated file, the lines with less than 6 fields to be skipped.

It's a question whether these should be applied only to the top lines, i.e. after the first good line read all the rest, or test all the lines, which would allow to skip comments in the middle of the file. I think the former should be much easier to implement and would already address most of the use cases.

If you find this a good idea, I am happy to try a pull request.

```r
library(readr)
contents <- '# comment\n# comment\n# comment\nA\tB\tC\n1\t7\t9\n5\t2\t6\n'
# this works currently, but we need to know in advance the number of rows to be skipped:
tbl <- read_tsv(contents, skip = 3)

# the suggested new features:
# 1) the string passed to skip used as a prefix:
tbl <- read_tsv(contents, skip = '#')
# 2) the function passed to skip used to test the lines:
tbl <- read_tsv(contents, skip = function(x){grepl('comment', x)})
```

**Comment by jimhester** [comment]
While I agree this would give readr a lot of flexibility, I am not sure the added complexity is worth it.

Note with the development version you can actually implement this fairly efficiently without changing any code in readr itself (I used CSV instead of TSV so the example was a little less noisy. e.g.

``` r
library(readr)
with_skip_fun <- function(f, file, ...) {
  con <- file(file, "rb")
  pos <- seek(con)
  line <- readLines(con, n = 1)

  while(isTRUE(f(line))) {
    pos <- seek(con)
    line <- readLines(con, n = 1)
  }
  seek(con, pos)
  on.exit(close(con))

  read_delim(con, ...)
}

contents <- 
"a,b
1,2
A,B,C
1,7,9
5,2,6"

f <- tempfile()
write_lines(contents, f)

with_skip_fun(function(x) { stringr::str_count(x, ",") < 2 }, f)
#> Rows: 2 Columns: 3
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> dbl (3): A, B, C
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 2 x 3
#>       A     B     C
#>   <dbl> <dbl> <dbl>
#> 1     1     7     9
#> 2     5     2     6
```

<sup>Created on 2021-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
