### ISSUE TITLE
feature request: add arguments to write_excel_csv to write sheet name

### ISSUE THREAD

**Issue by idshklein** [tidyverse/readr#1219]
xlsx package includes the ability of writing specific sheets in an excel file (write.xlsx, sheetname parameter). adding an argument to include a sheet name will harness the relative advantage of excel, for example - by grouping a dataframe and writing each group in a different sheet.

**Comment by jimhester** [comment]
Slight clarification, `write_excel_csv()` does not write a excel file, it writes a CSV file that is compatible with excel.

I don't believe there is anyway to specify a sheet name in this case.
