### ISSUE TITLE
Feature request: allow `cols_only()` to read unquote-spliced arguments

### ISSUE THREAD

**Issue by Raesu** [tidyverse/readr#1220]
I have become used to creating lists or named vectors of arguments that can then be inserted into many Tidyverse functions with the `!!!` operator or `!!` operator.

The `cols_only()` function, used as the assignment of `col_types` in `read_csv`, does not seem to understand this syntax.

---

```r
# These work
df <- read_csv(filePath, col_types=cols_only(colA=col_character())
df <- read_csv(filePath, col_types=cols_only(colA='c'))

# This does not work
cols <- list(colA='c')
df <- read_csv(filePath, col_types=cols_only(!!!cols))

# Here is a solution I found on SO, using `do.call`
# https://stackoverflow.com/questions/67642816/readrread-csv-use-cols-only-with-spliced-list
df <- read_csv(file.choose(), col_types = do.call(cols_only, cols))
```

I don't have the expertise to implement this myself, but thought it would be a good update and more consistent with other Tidyverse methods.

**Comment by jimhester** [comment]
What you want to do will already work in the current dev version of readr and next CRAN release of readr.

``` r
cols <- list(hp = "i", gear="f")

library(readr)
read_csv(readr_example("mtcars.csv"), col_types = cols_only(!!!cols))
#> # A tibble: 32 x 2
#>       hp gear 
#>    <int> <fct>
#>  1   110 4    
#>  2   110 4    
#>  3    93 4    
#>  4   110 3    
#>  5   175 3    
#>  6   105 3    
#>  7   245 3    
#>  8    62 4    
#>  9    95 4    
#> 10   123 4    
#> # … with 22 more rows
```

<sup>Created on 2021-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Raesu** [comment]
Great news, thanks.
