### ISSUE TITLE
Reading only the first line of a 50GB file ends up reading all of the file(?)

### ISSUE THREAD

**Issue by HenrikBengtsson** [tidyverse/readr#1221]
# Background

Hi. I've got a 50 GB delimited file with 160 million entries. I've already got the rows indexed, i.e. I know where row 'n' begins and ends (in file byte positions).  My plan was to use `readr::read_tsv()` to read, say, row 1000, using something like:

```r
con <- file("huge.tsv", open = "rb")
seek(con, where = start_of_row[1000])
data <- readr::read_tsv(con, n_max = 1)
close(con)
```

# Issue

The above works, but it takes much much longer than I anticipated.  It appears to be worse when reading a row near the top of the file than a row near the bottom of the file.  Using `strace`, it looks like `read_tsv()` reads beyond a single line.

# Troubleshooting / Question / Suggestion

Steping through `readr:::read_delimited()` and watching `strace`, I spotted a temporary file.  Following the R source code, `readr:::read_delimited()` -> `readr:::datasource_connection()` -> `readr:::read_connection()` -> `readr:::read_connection_()`, I end up at

```r
read_connection_(con, tempfile(), chunk_size)
```

Does this copy _all_ the content of the connection to a temporary file, regardless of `n_max`?

If so, wouldn't it make sense to pass down `n_max` to `read_connection_()` and make that count lines copied and end early when a chunk reads beyond `n_max`?

# Session info

```r
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

> packageVersion("readr")
[1] ‘1.4.0’
```

**Comment by jimhester** [comment]
Yes, readr 1.4.0 will read the entire file into memory when reading form connections.

readr 2.0.0 (the current dev version) will do what you want.

**Comment by HenrikBengtsson** [comment]
> Yes, readr 1.4.0 will first read the entire file into a temporary file when reading from connections.

Thanks for confirming.

> readr 2.0.0 (the current dev version) will do what you want.

Brilliant.
