### ISSUE TITLE
pkgdown site doesn't reflect latest release

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/readr#1222]
Site was last built on GH pages `2021-06-21T18:11Z`, and [1.4.0 release](https://github.com/tidyverse/readr/releases/tag/v1.4.0) was 2020-10-06, so the [changelog](https://readr.tidyverse.org/news/index.html) shouldn't be listing 1.4.0 as unreleased, but it is. (The current anchor link is <https://readr.tidyverse.org/news/index.html#readr-1-4-0-unreleased>).

I'm trying to figure this out for generating the right links for a newsletter/digest, so, if it's non-obvious, I'm happy to look into it.

*edit* Possibly a pkgdown issue because [dev version of documentation](https://readr.tidyverse.org/dev/news/index.html#readr-1-4-0-2020-10-05) has 1.4.0 as it should be, so it might be tagging the top item as unreleased.

**Comment by jimhester** [comment]
It is happening because the release pkgdown site was automatically built after 1.4.0 was added to the DESCRIPTION, but before it was accepted by CRAN.

**Comment by jimhester** [comment]
We could fix it by re-building the 1.4.0 site

**Comment by batpigandme** [comment]
Oooh, OK. This is good to know, because I imagine this isn't the only package where that happens, I just happened to look at readr's news as an example.

**Comment by jimhester** [comment]
Ok I rebuilt it and it seems all good now.
