### ISSUE TITLE
Strange blank line in dev version of `readr`

### ISSUE THREAD

**Issue by niheaven** [tidyverse/readr#1223]
I'm sorry that `reprex` erase these blank line output, and I'll use screenshots to illustrate my problem.

``` r
sessioninfo::package_info("readr", dependencies = FALSE)
#>  package * version    date       lib source                          
#>  readr     1.9.9.9000 2021-07-05 [1] Github (tidyverse/readr@aa8a502)
#> 
#> [1] E:/Documents/R/win-library/4.1
#> [2] D:/Scoop/apps/r/4.1.0/library
x <- tibble::tribble( ~ x, ~ y, ~ z,
                      1, 2, 3,
                      4, 5, 6,
                      7, 8, 9)
readr::write_csv(x, "test.csv", col_names = FALSE)
a <- readr::read_csv("test.csv",
                     col_names = c("a", "b"),
                     col_types = "-ii")
readr::read_csv("test.csv",
                col_names = c("a", "b"),
                col_types = "-ii")
#> # A tibble: 3 x 2
#>       a     b
#>   <int> <int>
#> 1     2     3
#> 2     5     6
#> 3     8     9
```

Actual output is:

![image](https://user-images.githubusercontent.com/5832170/124502090-5eac2c80-ddf5-11eb-9c74-e6bd51bfe2ad.png)

Notice two blank lines below assignment and one blank line below `# A tibble: 3 x 2`.

This is due to `vroom` but I cannot figure out why.

![image](https://user-images.githubusercontent.com/5832170/124501920-05dc9400-ddf5-11eb-90b7-3ede0b97d116.png)

**Comment by jimhester** [comment]
It is due to the progress bar, there is a bug in RStudio that it incorrectly adds a newline even if there isn't one (https://github.com/rstudio/rstudio/issues/7650)

You can use `progress = FALSE` or set `options(readr.show_progress = FALSE)` to disable it.
