### ISSUE TITLE
read_file marked deprecated

### ISSUE THREAD

**Issue by lpiep** [tidyverse/readr#1231]
In readr 2.0.0, `read_file` has a deprecated badge in its help file, but I don't see any warning about this when running it, and I don't see any suggestion on what to use instead in the help file. Is it truly deprecated or is this badge an error? 

```r
writeLines('text to read', tf <- tempfile())
lifecycle::expect_deprecated(readr::read_file(tf))
```

```
# Error: `readr::read_file(tf)` did not produce any warnings.     
```

Edit: Sorry, apparently not thinking straight this morning. I now see that the deprecated flag applied only to the "path" argument. I don't appear to be able to delete this issue, but it should be removed. 

Passes:
```
lifecycle::expect_deprecated(readr::write_file(x = 'text to write', path = tf))
```

**Comment by jimhester** [comment]
Just the `path` argument is deprecated, not the whole function. You just need to use `file` instead of `path`.

**Comment by jimhester** [comment]
Ok, glad you have sorted it out!
