### ISSUE TITLE
README.md Alternatives section not updated for 2.0.0

### ISSUE THREAD

**Issue by eutwt** [tidyverse/readr#1235]
- The comparison to `fread` says that readr "Forces you to supply all parameters, where `fread()` saves you work by automatically guessing the delimiter".  Now that `readr::read_delim` will automatically guess the delimiter, the comparison can be updated to remove mention of this feature as a difference between the two packages. 
- It's probably more accurate to say `data.table::fread` is "similar to `read_delim()`" rather than the current description that `fread` is "similar to `read_csv()`"

**Comment by jimhester** [comment]
Thanks, would you be interested in doing a PR to update the language?

**Comment by eutwt** [comment]
When opening the issue I thought this was a quick change. On reflection it occurs to me that the 2.0.0 release probably requires at least a few other updates to the alternatives comparison, e.g. as mentioning lazy reading, so I think it's best to leave that to you. Apologies for adding an unnecessary issue for something you probably already planned to do.
