### ISSUE TITLE
Parsing error with literal text with quote-protected commas

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readr#1237]
Prior to readr 2.0.0, `read_csv()` gave the same result as `read.csv()` is giving here.

``` r
library(readr)

read_csv('
  "X1", "X2"
   "a",  "b"
', show_col_types = FALSE)
#> # A tibble: 1 x 2
#>   X1    X2   
#>   <chr> <chr>
#> 1 a     b

read_csv('
    "X1",   "X2"
   "a,b",  "c,d"
', show_col_types = FALSE)
#> Warning: One or more parsing issues, see `problems()` for details
#> # A tibble: 1 x 2
#>   X1    X2             
#>   <chr> <chr>          
#> 1 a     "b\",  \"c,d\""

read.csv(text = '
  "X1", "X2"
   "a",  "b"
')
#>     X1  X2
#> 1    a   b

read.csv(text = '
    "X1",   "X2"
   "a,b",  "c,d"
')
#>       X1    X2
#> 1    a,b   c,d
```

<sup>Created on 2021-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

(discovered because some internal documentation started to fail in googlesheets4's pkgdown site)

**Comment by jimhester** [comment]
quoted fields ideally need to be next to the newline or field delimiters. e.g.

``` r
readr::read_csv('"X1","X2"
"a,b","c,d"', show_col_types = FALSE)
#> # A tibble: 1 x 2
#>   X1    X2   
#>   <chr> <chr>
#> 1 a,b   c,d
```

There is code to support spaces between the field delimiters and the quotes, but not between line delimiters, so the leading whitespace on each line is messing things up.

**Comment by jennybc** [comment]
I am OK if you tell me this is a wontfix and you close it.

Just for context, here's what I'm doing. It might help explain why I have the whitespace. I want to inline this data AND make it easy to inspect as a human. But this is documentation I have written for myself and I am happy to use `read.csv()` or something else in this case.

https://github.com/tidyverse/googlesheets4/blob/b04fa8b258d5e06aeb1ab9d492475b3cc8226054/vignettes/articles/range-specification.Rmd#L81-L98

**Comment by jimhester** [comment]
I think just using `read.csv()` is probably the best solution for now.

I will leave this issue open for now, perhaps we could handle this case better, though it is somewhat tricky to do efficiently.

**Comment by jennybc** [comment]
I just re-read this while thinking about #1350. Based on what I'm seeing, this comment doesn't seem to be true:

> There is code to support spaces between the field delimiters and the quotes, but not between line delimiters, so the leading whitespace on each line is messing things up.

But I might just be misinterpreting it? (Or it's a readr 1e vs readr 2e / vroom matter.) However it also seems to contradict another comment just above:

> quoted fields ideally need to be next to the newline or field delimiters

Again, based on what I'm seeing, that is really the bottom line. If you're using quotes to delimit fields, it's best to remove extraneous whitespace around the quoted items.

**Comment by jennybc** [comment]
Tracking in vroom: https://github.com/r-lib/vroom/issues/397
