### ISSUE TITLE
`read_delim` documentation for `file` arg is inaccurate

### ISSUE THREAD

**Issue by tarheel** [tidyverse/readr#1238]
From the docs for the `file` argument: "Literal data is most useful for examples and tests. It must contain at least one new line to be recognised as data (instead of a path) or be a vector of greater than length 1."

It fails to note that in the new edition, a multi-element vector will now be interpreted as a list of paths unless you wrap it with `I()`.

**Comment by jimhester** [comment]
Thanks, you are correct! Would you be interested on opening a pull request to improve the documentation? The place that would need to change is https://github.com/tidyverse/readr/blob/df90fb9d6279c63146005f0490f75488c9487a21/R/source.R#L12-L14
