### ISSUE TITLE
Cyrillic column names in write_delim

### ISSUE THREAD

**Issue by Darxor** [tidyverse/readr#1242]
Newer version of readr (both 2.0.0 CRAN release and current development version) seems to mess up non-ASCII (particularly Cyrillic) characters in colnames when writing with `write_delim` and related functions (`write_csv`, `write_excel_csv2`, etc.) when said colnames are in native non-UTF8 encoding.

## Example 

```r
library(readr)

df <- data.frame(
  "русский_заголовок" = 1:10
)

write_delim(df, "test.csv")
```

With this code and Windows1251 as native encoding resulting csv looks like this:

```
русский_з
1
2
3
4
5
6
7
8
9
10
```

Its fixed by switching to 1st edition with `readr::local_edition(1)` or by converting colnames to utf8 before writing.

```r
colnames(df) <- enc2utf8(colnames(df))
```

<details>
<summary>Session info</summary>
<pre>
- Session info -----------------
 setting  value                       
 version  R version 4.1.0 (2021-05-18)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Russian_Russia.1251         
 ctype    Russian_Russia.1251         
 tz       Europe/Moscow               
 date     2021-07-22                  

- Packages ----------
 package     * version date       lib source        
 bit           4.0.4   2020-08-04 [1] CRAN (R 4.1.0)
 bit64         4.0.5   2020-08-30 [1] CRAN (R 4.1.0)
 cli           3.0.1   2021-07-17 [1] CRAN (R 4.1.0)
 clipr         0.7.1   2020-10-08 [1] CRAN (R 4.1.0)
 crayon        1.4.1   2021-02-08 [1] CRAN (R 4.1.0)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
 fansi         0.5.0   2021-05-25 [1] CRAN (R 4.1.0)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.1.0)
 hms           1.1.0   2021-05-17 [1] CRAN (R 4.1.0)
 lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.1.0)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
 pillar        1.6.1   2021-05-16 [1] CRAN (R 4.1.0)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
 R6            2.5.0   2020-10-28 [1] CRAN (R 4.1.0)
 readr       * 2.0.0   2021-07-20 [1] CRAN (R 4.1.0)
 rlang         0.4.11  2021-04-30 [1] CRAN (R 4.1.0)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.0)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.1.0)
 tibble        3.1.2   2021-05-16 [1] CRAN (R 4.1.0)
 tidyselect    1.1.1   2021-04-30 [1] CRAN (R 4.1.0)
 tzdb          0.1.2   2021-07-20 [1] CRAN (R 4.1.0)
 utf8          1.2.1   2021-03-12 [1] CRAN (R 4.1.0)
 vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.1.0)
 vroom         1.5.3   2021-07-14 [1] CRAN (R 4.1.0)
 withr         2.4.2   2021-04-18 [1] CRAN (R 4.1.0)
</pre>
</details>

**Comment by jimhester** [comment]
Thanks for opening the issue with a reproducible example!

This ended up being a more pernicious issue than I originally thought.
We were converting the data (including column names) to UTF-8 when writing, but we mistakenly were using the length of the unconverted string. So if the UTF-8 translation was longer than the native encoding we would truncate the string, which is what you were observing.

This actually was occuring for both the headers and the data, but it should now be fixed for both cases.
