### ISSUE TITLE
read_fwf() won't accept character vector as input

### ISSUE THREAD

**Issue by palderman** [tidyverse/readr#1243]
I'm the author of another package that uses `read_fwf()` internally to parse files read in as character vectors. I was sent an email from CRAN that my package is failing checks. I isolated the problem to a point where I am passing a character vector into `read_fwf()`, but it seems to be interpreting it as a file name and throwing an error. The problem only seems to manifest on the following test environments:

- r-devel-linux-x86_64-debian-gcc
- r-devel-linux-x86_64-fedora-clang
- r-devel-linux-x86_64-fedora-gcc
- r-patched-solaris-x86

Reprex:

```r
read_fwf(c(" col1   col2 col3","first middle last"), col_positions=fwf_widths(c(5,7,5)))
```

**Comment by sophof** [comment]
I have a similar problem (I think) and it only happens on the linux devel version ( R version 4.1.0 (2021-05-18) ). As you can see not exactly the same, but I suspect it is the same cause, since it also deals with a character vector and read_fwf(). I have done the following to reproduce the problem (similar to a unit test in my package that fails):

```
datafile = tempfile(fileext = '.asc')
df = dplyr::tibble(A = rep(" ", 10))

# shows one column with an empty character vector of 10 as expected
df 

readr::write_delim(df, datafile, delim="", col_names=FALSE)

# As expected, a 10 vector of single spaces
readLines(datafile) 
# returns a tibble with just a single empty row.
readr::read_fwf(datafile, readr::fwf_positions(1,NA, "A"), readr::cols_only(A = readr::col_character())) 
# The same, but with a single _empty_ vector
readr::read_fwf(datafile, readr::fwf_positions(1,NA, "A"), readr::cols_only(A = readr::col_character()), na = character()) 
```

**Comment by palderman** [comment]
I should clarify that in the case I described above, `read_fwf()` errors out and produces no output:

> Error: ' col1   col2 col3' does not exist in current working directory ('/').

More complete reprex:

```{r}
# Generates error:
read_fwf(c(" col1   col2 col3","first middle last"), col_positions=fwf_widths(c(5,7,5)))

# Same data from file works fine:
exfile = tempfile(fileext = ".txt")
writeLines( text = c(" col1   col2 col3","first middle last"),
                   con = exfile)
readLines(exfile)
read_fwf(exfile, col_positions=fwf_widths(c(5,7,5)))
```

**Comment by jimhester** [comment]
In the 2nd edition of readr you need to flag literal data with `I()` as mentioned in the news https://github.com/tidyverse/readr/blob/master/NEWS.md#literal-data.

``` r
library(readr)
read_fwf(I(c(" col1   col2 col3","first middle last")), col_positions=fwf_widths(c(5,7,5)))
#> Rows: 2 Columns: 3
#> ── Column specification ────────────────────────────────────────────────────────
#> 
#> chr (3): X1, X2, X3
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 2 x 3
#>   X1    X2     X3   
#>   <chr> <chr>  <chr>
#> 1 col1  col2   col3 
#> 2 first middle last
```

<sup>Created on 2021-07-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by palderman** [comment]
@jimhester, Many thanks for the clarification. I somehow missed this detail. I am confident this solves the problem, but I will confirm before closing this issue.
