### ISSUE TITLE
read_delim in readr 2.0: new lines problem

### ISSUE THREAD

**Issue by mkvasnicka** [tidyverse/readr#1246]
Hi!

It seems read_delim() sometimes misses new lines -- at least on Linux. This code

```r
library(tidyverse)
country_codes <- read_csv("http://www.correlatesofwar.org/data-sets/cow-country-codes/cow-country-codes",
    col_types = "cic")
```

produces a tibble with 0 rows and 489 columns. The column names are "StateAbb", "CCode", "StateNme\rUSA", "2", "United States of America\rCAN" etc. -- see each third name -- it includes "\r".

Happening on Ubuntu 21.04, kernel 5.11.0-25-generic, R version 4.1.0, tidyverse version 1.3.1

Best wishes,
Michal

**Comment by jimhester** [comment]
This file uses only carriage returns `\r` to delimit lines.

This type of file has been out of use since 2001 and is no longer supported in the 2nd edition of readr.

See https://github.com/tidyverse/readr/issues/1236#issuecomment-884210536 for some potential workarounds.

**Comment by mkvasnicka** [comment]
Thanks for your answer. I understand your point. However, this format is still used in the wild. Some support (e.g. via a parameter) would be nice.
