### ISSUE TITLE
Missing documentation on which edition is used

### ISSUE THREAD

**Issue by svraka** [tidyverse/readr#1249]
After trying out readr 2.0 it is confusing to me when **readr** falls back to the first edition parser. The `read_*_chunked()` functions seem to always use the first edition, at least based on CPU usage, and how the column specifications are printed. Is this because **vroom** [doesn't support chunked reading](https://github.com/r-lib/vroom/issues/151)? Are there other cases when the first edition is used?

Is this documented somewhere? I can't find anything on this topic.

**Comment by jimhester** [comment]
You will have to look at the code to see the details I am afraid.

**Comment by svraka** [comment]
OK, thanks.
