### ISSUE TITLE
read_csv not converting number to NA

### ISSUE THREAD

**Issue by timothyslau** [tidyverse/readr#1251]
readr version 1.4.0
R version 4.1.0

1. readr::read_csv can automatically unpack zip files and it can read files from the internet, but it can't do both:
`readr::read_csv(file = "https://storage.googleapis.com/tensorflow/tf-keras-datasets/jena_climate_2009_2016.csv.zip")`
2. if you download the file onto your system and read the data, you'll notice there's some missing values in the wind columns (`max. wv (m/s)`, `wv (m/s)`), which if you put the matching values into the "na" argument of read_csv, doesn't change them to NA:
```
library(dplyr)
readr::read_csv(file = "/rwd/jena_climate_2009_2016.csv.zip", na = c("", "NA", -9999.00, -9999))[343578:343597,] %>% View()
```

This seems similar to issue:
https://github.com/tidyverse/readr/issues/210

**Comment by jimhester** [comment]
Sorry, I cannot reproduce the 2nd issue with the current readr release (2.0.0)

``` r
download.file("https://storage.googleapis.com/tensorflow/tf-keras-datasets/jena_climate_2009_2016.csv.zip", "jena_climate_2009_2016.csv.zip")
readr::read_csv("jena_climate_2009_2016.csv.zip", na = c("", "NA", "-9999.00", "-9999"))[343578:343597,c("max. wv (m/s)", "wv (m/s)")]
#> Rows: 420551 Columns: 15
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr  (1): Date Time
#> dbl (14): p (mbar), T (degC), Tpot (K), Tdew (degC), rh (%), VPmax (mbar), V...
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 20 × 2
#>    `max. wv (m/s)` `wv (m/s)`
#>              <dbl>      <dbl>
#>  1              NA       6.16
#>  2              NA      NA   
#>  3              NA      NA   
#>  4              NA      NA   
#>  5              NA      NA   
#>  6              NA      NA   
#>  7              NA      NA   
#>  8              NA      NA   
#>  9              NA      NA   
#> 10              NA      NA   
#> 11              NA      NA   
#> 12              NA      NA   
#> 13              NA      NA   
#> 14              NA      NA   
#> 15              NA      NA   
#> 16              NA      NA   
#> 17              NA      NA   
#> 18              NA      NA   
#> 19              NA      NA   
#> 20              NA      28.5
```

<sup>Created on 2021-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The first behavior is expected, base R does not provide a `gzcon()` equivalent for zip archives. `base::unz()` only works on local files.

**Comment by timothyslau** [comment]
updated to 2.0 and problem is solved.
