### ISSUE TITLE
Would you consider removing the internal tag for the chunked documentation?

### ISSUE THREAD

**Issue by boshek** [tidyverse/readr#1253]
Thank you for the super useful updates to readr recently. What a package. 

Would you consider removing the "internal" tag to the chunked family of functions? This would be the `melt*` and `read*` functions as well as the Call back classes. 

I see it was done here: https://github.com/tidyverse/readr/commit/66210dad0e8a2b5416ae041779eaf086a8e3cccd

I just had the experience of trying to find documentation for chunked reading and struggled for a bit to get these pages:

https://readr.tidyverse.org/reference/read_delim_chunked.html
https://readr.tidyverse.org/reference/callback.html

Chunked reading is a secret super power readr and I think exposing the documentation would help folks. Happy to contribute the PR if you like.

**Comment by boshek** [comment]
I see now that this has already been discussed here: https://github.com/tidyverse/readr/issues/1165

So I guess this issue is now just to advocate for the value of chunked reading.

**Comment by jimhester** [comment]
Thank you for the feedback, we will definitely keep it in mind for future developments of readr and vroom.

For now however having this documentation be internal is intended, so we will leave it as-is.
