### ISSUE TITLE
Changed behavior for duplicated column names

### ISSUE THREAD

**Issue by ibombonato** [tidyverse/readr#1259]
In `2.0.0` When reading files with duplicated columns, the behavior now is to change the column to its index besides its duplicated number. 

I think the 1.4.0 behavior is way better to deal with when munging the data.

Reading duplicated columns in `1.4.0` duplicated columns "A" became `A_1`,` A_2`, `A_3` and so on...:
`'A' => 'A_1' [9], 'A' => 'A_2' [11]`

```r
require(devtools)
install_version("readr", version = "1.4.0", repos = "http://cran.us.r-project.org")
library(readr)

filename = tempfile("data", fileext = c(".csv"))
fileConn<-file(filename)
writeLines("A;B;C;D;E;F;G;H;A;Z;A", fileConn)
close(fileConn)

readr::read_csv2(filename)
```
Output:
```
ℹ Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.

Warning message:
“Duplicated column names deduplicated: 'A' => 'A_1' [9], 'A' => 'A_2' [11]”

── Column specification ────────────────────────────────────────────────────────
cols(
  A = col_character(),
  B = col_character(),
  C = col_character(),
  D = col_character(),
  E = col_character(),
  F = col_character(),
  G = col_character(),
  H = col_character(),
  A_1 = col_character(),
  Z = col_character(),
  A_2 = col_character()
)
```

Now reading duplicated columns in `2.0.0`, column A, becomes `A_...{INDEX}`, in this case `A...1`, `A...9` and `A...11` which imo is worse to deal than the older way and also is a breaking change...

```r
require(devtools)
install_version("readr", version = "2.0.0", repos = "http://cran.us.r-project.org")
library(readr)

filename = tempfile("data", fileext = c(".csv"))
fileConn<-file(filename)
writeLines("A;B;C;D;E;F;G;H;A;Z;A", fileConn)
close(fileConn)

readr::read_csv2(filename)
```

Output:
```
ℹ Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.

New names:
* A -> A...1
* A -> A...9
* A -> A...11

Rows: 0 Columns: 11

── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (11): A...1, B, C, D, E, F, G, H, A...9, Z, A...11
```

I would like you to consider go back to the previous behavior, where columns was renamed to match its duplicated position, not its index.

**Comment by jimhester** [comment]
The default behavior is the same as the name repair behavior of tibbles, so it is not going to change.

However you do have full control over this behavior with the `name_repair` argument, so you can do as base R does (or however else) if you would like. e.g.

``` r
writeLines("A;B;C;D;E;F;G;H;A;Z;A", "out.csv")
readr::read_csv2("out.csv", name_repair = function(x) make.names(x, unique=TRUE))
#> ℹ Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.
#> Rows: 0 Columns: 11
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ";"
#> chr (11): A, B, C, D, E, F, G, H, A.1, Z, A.2
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 0 × 11
#> # … with 11 variables: A <chr>, B <chr>, C <chr>, D <chr>, E <chr>, F <chr>,
#> #   G <chr>, H <chr>, A.1 <chr>, Z <chr>, A.2 <chr>
```

<sup>Created on 2021-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by zberry37** [comment]
Thanks for clarifying this @jimhester . I'm wondering if you have a tip on the best way to use this "name_repair" argument to order duplicate columns with an underscore rather than an ellipsis or even a period? So if I have moral1 then the next time this column appears in my dataset it should be moral1_1. Any tip here would be greatly appreciated.

**Comment by jimhester** [comment]
One way is to use `janitor::make_clean_names` e.g.

``` r
writeLines("A;B;C;D;E;F;G;H;A;Z;A", "out.csv")
names(readr::read_csv2("out.csv", name_repair = janitor::make_clean_names, show_col_types = FALSE))
#> ℹ Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.
#>  [1] "a"   "b"   "c"   "d"   "e"   "f"   "g"   "h"   "a_2" "z"   "a_3"
```

<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by zberry37** [comment]
@jimhester this is super helpful, thank you so much!

**Comment by vieruodu** [comment]
I just wondering why `ℹ Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.

New names:
* A -> A...1
* A -> A...9
* A -> A...11

Rows: 0 Columns: 11

── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (11): A...1, B, C, D, E, F, G, H, A...9, Z, A...11`

**Comment by jennybc** [comment]
The rationale is laid out here:

https://design.tidyverse.org/names-attribute.html

vctrs offers a legacy name repair function that might be closer to what you want, which you could provide to the `name_repair` argument:

https://vctrs.r-lib.org/reference/vec_as_names_legacy.html?q=legacy#null
