### ISSUE TITLE
read_* on rawConnection breaks the connection

### ISSUE THREAD

**Issue by nik-humphries** [tidyverse/readr#1261]
readr 2.0.0 acts different to readr 1.4.0.

Using read_* on a rawConnection makes the connection invalid instead of closing it / not touching it.

The following example does not impact the con in 1.4.0, but breaks it in 2.0.0.

Supplying lazy = T/F makes no difference.

```r
con <- rawConnection(raw(0), "r+")
writeBin("hiya", con)
readr::read_csv(con)

con
# A connection, specifically, ‘rawConnection’, but invalid.

close(con)
# Error in close.connection(con) : invalid connection
```

**Comment by jimhester** [comment]
R reports closed connections in this way, readr is closing the connection.

readr / vroom automatically close connections after they have been read if they are not already opened.

However raw connections are always reported as opened, so they are always closed.

Is there a reason you need to explicitly keep this raw connection open after reading?

**Comment by nik-humphries** [comment]
Ah, I was unaware that a closed connection was reported in that way. I could have easily checked that myself I guess.

I believe in readr 1.4.0 the raw connections were not closed, so the Azure/AzureStor package made sure to `on,exit(close(con))` when readr'ing a raw connection.

I raised an issue against that repo here: https://github.com/Azure/AzureStor/issues/95

I assume that this was actually a bug with previous versions of readr that AzureStor was working around?

**Comment by jimhester** [comment]
raw connections are kind of weird in this respect because it isn't possible to have one that is not open. e.g. `rawConnection(raw(), "")` still opens the connection. But I do think it makes sense for readr to close them automatically.

**Comment by nik-humphries** [comment]
Yeah think it's all fair enough. The issue has been resolved in the package that this was affecting and I think this is all working as intended so I would consider this closed. Just be known to anybody reading this that this probably niche usecase has changed from 1.4.0 to 2.0.0.

**Comment by jimhester** [comment]
Ok, great! Sorry about the changed behavior, but I think where we are now is a better place :)
