### ISSUE TITLE
Fields with newline character fail to parse when using non-default `quote` argument in `read_csv`.

### ISSUE THREAD

**Issue by rdinnager** [tidyverse/readr#1262]
I'm trying to read literal csv data that contains multi-line fields, but they are enclosed in single quotes instead of double quotes. If I try and use the `quote` argument of `read_csv`, the data is not parsed correctly. If I convert single quotes to double quotes, then `read_csv` works as expected (see below reprex). This is a bug in `readr` edition 2 only.

``` r
library(readr)
#> Warning: package 'readr' was built under R version 4.0.5
```

This works fine:

``` r
text <- c('1,"I
am
sam"',
'2,"sam
I
am"')

test <- read_csv(paste0(text, "\n", collapse = ""), col_names = FALSE, show_col_types = FALSE)

test
#> # A tibble: 2 x 2
#>      X1 X2          
#>   <dbl> <chr>       
#> 1     1 "I\nam\nsam"
#> 2     2 "sam\nI\nam"
```

Exactly the same as above, except for using `'` instead of `"` as the quote character

``` r
text <- c("1,'I
am
sam'",
"2,'sam
I
am'")

test <- read_csv(paste0(text, "\n", collapse = ""), col_names = FALSE, show_col_types = FALSE,
                 quote = "\'")
```

Parsing now fails, getting confused by the newlines:

``` r
test
#> Warning: One or more parsing issues, see `problems()` for details
#> # A tibble: 4 x 1
#>   X1              
#>   <chr>           
#> 1 "1"             
#> 2 "am"            
#> 3 "sam'"          
#> 4 "2,'sam\nI\nam'"
problems(test)
#> # A tibble: 1 x 5
#>     row   col expected  actual    file                                
#>   <int> <int> <chr>     <chr>     <chr>                               
#> 1     4     2 1 columns 2 columns F:/Rtemp/RtmpYjcKso/file2f683fa07040
```

Works in edition one though:

``` r
with_edition(1,
             test <- read_csv(paste0(text, "\n", collapse = ""), col_names = FALSE, show_col_types = FALSE,
                              quote = "\'"))

test
#> # A tibble: 2 x 2
#>      X1 X2          
#>   <dbl> <chr>       
#> 1     1 "I\nam\nsam"
#> 2     2 "sam\nI\nam"
```

<sup>Created on 2021-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jimhester** [comment]
Thank you for opening the issue and for supplying a reproducible example, it is a big help!

This was a bug, we have functions in vroom which find the first two lines of the file, and these functions were not properly taking into account the `quote` parameter. So if you had specified `quote` as something other than a double quote and you had quoted fields in the first two lines there would be issues (as you showed above).

It should now be fixed in the development version of vroom.

**Comment by rdinnager** [comment]
Great! Thanks for the quick work on that. This was breaking a package of mine that relies on `readr`. I have a not so elegant work-around in place for now, but good to know I can remove it as soon as this fix finds its way onto CRAN.
