### ISSUE TITLE
Suggestion: Set `lazy = FALSE` by default on Windows?

### ISSUE THREAD

**Issue by christopherkenny** [tidyverse/readr#1266]
Hello!

The new speed is great with version 2.0.0. Thank you guys for all you do for the R community.

I've noticed across a few command checks unexpected issues with using `readr`, especially with tempfiles on Windows. For example, [PL94171](https://cran.r-project.org/web/checks/check_results_PL94171.html), which we are submitting an update using `lazy = FALSE`. We see a similar issue within the `redist` package where a tempfile is written and can't be overwritten once opened with `readr`.  (That particular test is skipped on CRAN because it's time consuming.)

After some looking around, I found that this is explained and expected, see [the readr 2.0.0 post](https://www.tidyverse.org/blog/2021/07/readr-2-0-0/#lazy-reading)

I was wondering if you would ever consider setting `lazy = FALSE` by default if it's a Windows machine. One approach could be a simple function, like the following:

```r
is_windows <- function() {
    Sys.info()[['sysname']] == 'Windows'
}
```
Then the default for `lazy` would be `lazy = !is_windows()`

I understand if this type of change could cause other concerns, so feel free to disregard it.

Thanks,
Chris

This is loosely related to #1263.

**Comment by Robinlovelace** [comment]
I'm not 100% sure but suspect this issue that would be fixed in this suggestion is the same that caused tests to fail on GitHub Actions on 2 of my packages.

The fix implemented (credit: @agila5 ) there was to add the following lines before using `readr` code: 

```r
  # Set the local edition for readr.
  # See https://github.com/ropensci/stats19/issues/205
  if (.Platform$OS.type == "windows" && utils::packageVersion("readr") >= "2.0.0") {
    readr::local_edition(1)
  }
```

I think an upstream fix would be ideal to prevent others being affected by this platform-specific and potentially hard to diagnose issue so big :+1: on the suggestion.

**Comment by Robinlovelace** [comment]
Commits that stopped `readr` code from failing in case of use: https://github.com/ropensci/stats19/commit/23e61a162214adfe749492f2ae6b7f5cec0f940c and https://github.com/ITSLeeds/pct/commit/80354344518b8dd34fa8821e0e09d6868879c845

**Comment by jimhester** [comment]
Why did you not just put `lazy = FALSE` in your calls?

**Comment by Robinlovelace** [comment]
> Why did you not just put `lazy = FALSE` in your calls?

It was a suggestion from @agila5 and it fixed the failing actions: https://github.com/ropensci/stats19/pull/206

Do you think updating the relevant section would be better? Happy to update the code in both packages if so if an upstream fix on the `readr` side is not planned. 

Are you considering implementing @christophergandrud's suggestion?

**Comment by andoomcz** [comment]
This is a similar suggestion but instead of having `lazy = FALSE` would it be possible to create a function that kills the lazy reading without having to restart the session?

**Comment by jimhester** [comment]
@andoomcz you can currently use the unexported `vroom:::vroom_materialize()` function to eagerly read the rest of the data. It is possible we could supply a function in readr to call this.

**Comment by natbprice** [comment]
I am often finding that readr is locking files. After reading a file in R and editing the file I find I cannot save the file again: "Error: Cannot open file for writing". How do I close the file connection and unlock the file so it can be overwritten?

**Comment by natbprice** [comment]
@jimhester Thanks. What are the arguments for `vroom:::vroom_materialize()`? It looks like it wants an argument `x` and an argument `replace`.

Do you have any ideas for making this more seamless? Would it be possible to catch the file lock error and retry after calling `vroom:::vroom_materialize()`?

**Comment by jimhester** [comment]
You should just use `lazy = FALSE` when you read the file.

**Comment by natbprice** [comment]
After the file is locked it is too late to set `lazy = FALSE`. To add some context, this is not a minor issue for me. Reading files is a low level workhorse function and if the defaults are not reasonable and/or maintainers are not open to developing a fix (@hadley), I will probably just find another package to use.

1) Is there a way to unlock a file which `readr` has locked without killing my R session? Is `vroom:::vroom_materialize()` the suggested workaround and if so what are the arguments? 

2) Would you be open to using `options(...)` to override the default `lazy = TRUE` argument?

**Comment by hadley** [comment]
@natbprice if using `lazy = FALSE` is not possible for you, it definitely sounds like another package might be a good fit for your needs. `data.table::fread()` is also very very fast.

**Comment by jimhester** [comment]
I added a `readr.read_lazy` global option to control the default behavior of lazy reading

**Comment by natbprice** [comment]
@jimhester Thanks for your help. I was not aware of `readr.read_lazy` option.

@hadley I honestly don't understand how opening a file connection which locks a file and then having no option to close the connection is not seen as problematic. I feel like I must be misunderstanding something pretty basic if you and @jimhester agree it is a non-issue. It seems like closing the connection and releasing the file again is one of the basic functions of a package to read files.

**Comment by christopherkenny** [comment]
Thank you @jimhester! The `readr.read_lazy` option should fix my concern, which is focused on when `readr` is used within a package, rather than directly.
