### ISSUE TITLE
Is there a reason why `write_rds()` doesn't include/pass the `ascii` param?

### ISSUE THREAD

**Issue by jmobrien** [tidyverse/readr#1270]
Unlike `saveRDS()` in base R, `write_rds()` includes no option for writing in ASCII rather than in binary.  Is there a reason why that was left out?  In my particular use case having the option for ascii writing using the more standardized `readr` functions would be nice.

(wrote RDA rather than RDS for some reason, amended)

**Comment by jimhester** [comment]
Thanks for opening the issue, I added a `text` argument to `write_rds()`, which is analogous to the `ascii` argument in `saveRDS`.

**Comment by jmobrien** [comment]
Great!  Noticed something else last week related to this--in `saveRDS()`, `ascii=TRUE` (or, here, `text=TRUE`) drops any tagged NA's that were loaded/created by `haven`.   Binary saves work just fine.

I assume there's nothing to be done about that, but since it's a variation in behavior with relevance to other tidyverse packages, I thought it was worth mentioning in case that's the sort of thing the team wants to document.  

(For what it's worth, nothing in the docs of either `saveRDS()` or `save()` would clearly suggest this behavior either)
