### ISSUE TITLE
linebreaks within fields problem with read 2.0.0

### ISSUE THREAD

**Issue by HedvigS** [tidyverse/readr#1272]
My issue is that readr 2.0.0 treats line breaks within fields differently than earlier versions. I'd like it to treat anything within the text delim markers as the content of one field, but now it breaks it up into different rows. This wasn't a problem for me with files with this type of data until I updated to readr 2.0.0. Those earlier scripts are now breaking and I'm replacing instances of `readr::read_*()` with` data.table::fread().`

Below I've constructed a reprex which illustrates the problem and compares it to `data.table::fread()`. I was trying to make a reprex explicitly with an older version of `readr `using the package `groundhog`, but I ran into complications with versions of R so I'm comparing to `data.table::fread()` instead.

```r
library(readr)
library(data.table)

#making a csv string that the functions can read in, the cell in the second column second row has line breaks within it. 

csv_string <- '
  "X1", "X2"
   "a",  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 

Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 

Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

#reading in string above with readr.
test_readr <- readr::read_csv(csv_string)

#the above line gives a tibble with 4 rows (excl header) and 2 cols and it's clear that the linebreaks within the fourth cell are being distributed into new rows.

test_readr
# A tibble: 4 × 2
  X1                                                                 X2                                                                           
  <chr>                                                              <chr>                                                                        
1 a                                                                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp…
2 Ut enim ad minim veniam                                            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo cons…
3 Duis aute irure dolor in reprehenderit in voluptate velit esse ci… NA                                                                           
4 Excepteur sint occaecat cupidatat non proident                     sunt in culpa qui officia deserunt mollit anim id est laborum.              


#reading in the same string with fread instead
test_fread <- data.table::fread(  csv_string,
  encoding = 'UTF-8', 
  quote = "\"", 
  fill = T, 
  header = TRUE, 
  sep = ","
)

 # this gives a data frame as I expect it with 2 columns and 1 row
test_fread
X1
1:  a
X2
1: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \n\nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. \n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. \n\n“Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

I hope the issue is clear. If the solution is a wontfix that'd be great to know.  I understand that readr wishes to encourage certain best practices of data formats, so perhaps it's seen as a feature and not a bug that read_* does this. For me though, since it didn't use to expect this it's causing trouble.

**Comment by jimhester** [comment]
Try setting `num_threads = 1` when you read the files and it should work how you were expecting. Using multiple threads is unfortunately incompatible with newlines within fields.

Also you can use the first edition parser with the current version of readr by setting `local_edition(1)` at the top of your script, or using `with_edition(1, { # my code })` to use the first edition temporarily for a given call.

**Comment by HedvigS** [comment]
Hm, right. Thanks @jimhester . I hope the extra argument works, because while I appreciate the functionality of local_edition() it seems it would complexity my code too much.

Do you know why it used to work and now doesn't? I know things are allowed to break when stepping from 1 -> 2, this one just surprised me and caught me of guard.
