### ISSUE TITLE
read_lines produces an empty line when `progress = FALSE`

### ISSUE THREAD

**Issue by richelbilderbeek** [tidyverse/readr#1278]
When I read a short file using `read_lines` and store the results to a variable, I expect no output to the console. 

Since a couple of days, however, an empty line is written to the console. 

Here is a nice reprex:

```r
filename <- tempfile()
readr::write_lines(x = "test", file = filename)

# Produces an empty line on the console
text <- readr::read_lines(file = filename)

# As a test, which fails
testthat::expect_silent(text <- readr::read_lines(file = filename))

# Works as expected
text <- readr::read_lines(file = filename, progress = FALSE)

# As a test, which passes
testthat::expect_silent(text <- readr::read_lines(file = filename, progress = FALSE))

```

This breaks quite some `expect_silent` tests in packages that use `read_lines`. 

A workaround is to set `progress = FALSE` in each call to `read_lines`.

**Comment by jimhester** [comment]
This is an RStudio bug, there unfortunately isn't anything we can change in readr to fix it.

https://github.com/rstudio/rstudio/issues/7650

**Comment by richelbilderbeek** [comment]
Thanks, than I will close this Issue and use the workaround :+1:
