### ISSUE TITLE
Can't pipe text to read_* in readr 2.0.0

### ISSUE THREAD

**Issue by stephenturner** [tidyverse/readr#1281]
I maintain an internal package that reads a bespoke text file generated by an instrument into a tibble. The text has several header lines (variable number), and a footer that I don't want. There's a keyword (here, "headerends") that I use to figure out where the real data starts and the junk header ends. The junk header doesn't have anything I can use in `comment=` to remove. 

The way I'd previously handled this problem is to read in the whole text file with `read_lines`, then figure out where the real data starts by looking for that keyword. I then use head/tail to strip off the junk header and footer, and pipe that text directly into `read_*`. 

Here's an example text file:

```
This is junk header without comments	
More	Junk
headerends	
person	value
sam	1
bill	2
sue	3
sally	4
more junk here	
```

I'd `read_lines("thatfile.txt")`, which would give me this character vector to work with that I've created with `c()` for the reprex below.

With readr 1.4.0:

``` r
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(dplyr))

# This is what I would have after a read_lines
rawtext <-
  c("This is junk header without comments\t",
  "More\tJunk",
  "headerends\t",
  "person\tvalue",
  "sam\t1",
  "bill\t2",
  "sue\t3",
  "sally\t4",
  "more junk here\t")
rawtext
#> [1] "This is junk header without comments\t"
#> [2] "More\tJunk"                            
#> [3] "headerends\t"                          
#> [4] "person\tvalue"                         
#> [5] "sam\t1"                                
#> [6] "bill\t2"                               
#> [7] "sue\t3"                                
#> [8] "sally\t4"                              
#> [9] "more junk here\t"

# Figure out where the header ends
headerends <- grep("headerends", rawtext)
headerends
#> [1] 3

# Read in the data
rawtext %>%
  # Remove the footer
  head(-1) %>%
  # Remove the header
  tail(-headerends) %>%
  read_tsv()
#> # A tibble: 4 x 2
#>   person value
#>   <chr>  <dbl>
#> 1 sam        1
#> 2 bill       2
#> 3 sue        3
#> 4 sally      4
```

With readr 2.0.0 I get the following error:

```
Error: 'person	value' does not exist in current working directory ('/Users/...').
```

I can fix the problem with `readr::local_edition(1)` but as I understand from the release notes, this is going away eventually.

**Comment by jimhester** [comment]
As mentioned in the release notes you need to mark the literal text with `I()` https://github.com/tidyverse/readr/blob/master/NEWS.md#literal-data

**Comment by stephenturner** [comment]
Ah, sorry for missing that @jimhester! Confirmed this works.

**Comment by jimhester** [comment]
Great, glad you got it working!
