### ISSUE TITLE
`show_col_types` causes unfinished console output to be erased

### ISSUE THREAD

**Issue by pieterjanvc** [tidyverse/readr#1284]
Hi,

Recently the option to show or suppress column types when reading a file (read_csv, read_delim, ...) have been added, but the output (or suppression of it) causes issues when there is an unfinished line of output at the console. 

What happens is that when the file is sourced, any output written to the console that has not been ended by a return yet will be erased when a read_ function is run in the code.

Note that when show_col_types = T, the output will also erase the unfinished line.

REPREX
```r
# RUN ONCE TO CREATE DUMMY DATA
# myData = data.frame(
#   x = 1:10, y = LETTERS[1:10]
# )
# 
# write.csv(myData, "myData.csv", row.names = F)

#First part of line gets erased
cat("Loading file ...")
myData = read_csv("myData.csv", show_col_types = F)
cat("done\n")

#Expected behaviour
cat("Loading file ...")
myData = read.csv("myData.csv")
cat("done\n")
```

OUTPUT
```
done  
                                                                                                                                           
Loading file ...done
```

Feel free to ask for more info if needed and thanks for looking into it!

PJ

**Comment by jimhester** [comment]
This is not due to `show_col_types` it is due to the progress bar. Set `progress = FALSE` along with `show_col_types = FALSE` and it should resolve your issue.

**Comment by pieterjanvc** [comment]
It did the trick indeed.
Thanks for the clarification!
