### ISSUE TITLE
Option to view full column spec on read please

### ISSUE THREAD

**Issue by MilesMcBain** [tidyverse/readr#1286]
I much preferred the old style display of the full `spec()` on read. The primary issue with the new default behaviour is that it crops column names if it cant fit them all on one line. This is inconvenient. A vertical list is a more natural way to view column names without cropping/line break issues.

Compare: 
![image](https://user-images.githubusercontent.com/9996346/130556138-1640c6bd-943e-492f-962e-8cbf4f771adc.png)

With:
![image](https://user-images.githubusercontent.com/9996346/130556265-6b28e662-03b0-482f-af85-bc085fe07bdc.png)

Could we get an option to turn the old behaviour back on please?

**Comment by jimhester** [comment]
Use `print(spec(xyz))` if you want to see it.

**Comment by jimhester** [comment]
Or if you want to make it the default for yourself you can define a small helper function.

```r
my_read_csv <- function(...) {
  x <- readr::read_csv(..., show_col_spec = FALSE)
  print(readr::spec(x))
  x
}
```
