### ISSUE TITLE
read_delim documentation error for second edition

### ISSUE THREAD

**Issue by sbachstein** [tidyverse/readr#1287]
https://github.com/tidyverse/readr/blob/866decae4ea18835f89c53a114363f4fce0abcbe/R/read_delim.R#L25

With the first edition parser, NA columns would be replaced by `X1, X2, ...` For the second edition parser (vroom), however, NA columns are replaced by `...1, ...2, ...`.

**Comment by jimhester** [comment]
Closing in favor of #1275, which this duplicates
