### ISSUE TITLE
Infinite loop in write_rds() when filename basename is "con"

### ISSUE THREAD

**Issue by fernandovmacedo** [tidyverse/readr#1289]
When writing a file with the basename "con" with `write_rds()` R, at least in version 4.1, enters on an infinite loop. The bug is actually not in the `readr` package, but in the `file()` function of base R, so I was not sure where or how to report it.

``` r
word <- "test"

saveRDS(word, "con.rds") # this is ok
saveRDS(word, "con.txt") # also ok
saveRDS(word, "con") # also ok

#readr::write_rds(word, "con.rds") # infinite loop
#readr::write_rds(word, "con.txt") # infinite loop
#readr::write_rds(word, "con") # infitine loop
```

<sup>Created on 2021-08-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 4.1.0 (2021-05-18)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19043)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252   
#> [3] LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C                      
#> [5] LC_TIME=Portuguese_Brazil.1252    
#> system code page: 65001
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.33        magrittr_2.0.1    rlang_0.4.11      fansi_0.5.0      
#>  [5] stringr_1.4.0     styler_1.5.1      highr_0.9         tools_4.1.0      
#>  [9] xfun_0.23         utf8_1.2.1        withr_2.4.2       htmltools_0.5.1.1
#> [13] ellipsis_0.3.2    yaml_2.2.1        digest_0.6.27     tibble_3.1.2     
#> [17] lifecycle_1.0.0   crayon_1.4.1      purrr_0.3.4       vctrs_0.3.8      
#> [21] fs_1.5.0          glue_1.4.2        evaluate_0.14     rmarkdown_2.8    
#> [25] reprex_2.0.1      stringi_1.6.1     compiler_4.1.0    pillar_1.6.1     
#> [29] backports_1.2.1   pkgconfig_2.0.3
```

</details>

**Comment by jimhester** [comment]
I cannot reproduce this, can you describe what the infinite loop is? e.g. what function calls are looping?

**Comment by fernandovmacedo** [comment]
The call to `file()` inside `write_rds()` causes the problem and, as I've discovered later, is OS specific. Windows OS does not allow for filename such as `"con.txt"`, `"aux.txt"` (a more detailed list is documented [here](https://www.helpndoc.com/documentation/html/Windowsreservedfilenames.html)). So when base R try to create a `"con.txt"` file with `file()` windows OS gives an error that probably is not properly treated inside `file(),` so R enters an infinite loop.

**Comment by jimhester** [comment]
So if you run `bug.report()` it will tell you where to file bugs in base R functions and packages (it is https://bugs.r-project.org/index.cgi) so the R core team members could look at it.

But as this seems to be an OS limitation I don't think much can be done, either in readr or in the base R code.
