### ISSUE TITLE
write_csv, write_excel_csv and others crashing on Windows, when there are latin1 strings in the dataframe

### ISSUE THREAD

**Issue by jcarbaut** [tidyverse/readr#1291]
On Windows, when writing a dataframe that has strings encoded in latin1, R crashes. When writing the same data with strings converted to UTF-8 with iconv, no problem.

Versions: Windows 10, R 4.1.1, readr 2.0.1.

The following code crashes. The string is built with iconv and intToUtf8 in order to make sure the encoding is latin1, but it also happens with data from other sources. The string is just "10 à 20" (french for "10 to 20").

With the commented line instead, write_csv does not crash.
Moreover, the number of rows seems to be significant: with the program below, up to 13634 it doesn't crash on my computer, at 13635 or more it does.

```r
s <- iconv(intToUtf8(c(49, 48, 32, 224, 32, 50, 48)), "UTF-8", "latin1")
#s <- intToUtf8(c(49, 48, 32, 224, 32, 50, 48))

s
Encoding(s)

test <- data.frame(x = rep(s, 100000))

library(readr)
write_csv(test, "test.csv")
```

**Comment by jimhester** [comment]
This should be fixed by installing the latest version of vroom 1.5.5

**Comment by pmschauer** [comment]
The proposed solution of vroom 1.5.5 does not resolve the issue. In the same environment as jcarbaut the above code sample causes an instant crash, even with vroom installed. If you use the commented line or convert it back to UTF-8 prior to write_csv() then it works correctly.
