### ISSUE TITLE
read_csv fails to work in shiny environment "Error in vroom::vroom: unused arguments"

### ISSUE THREAD

**Issue by alon-sarid** [tidyverse/readr#1301]
Hi. 

Ever since the last update the read_csv function crush with the following error:

"Error in vroom::vroom: unused arguments (skip_empty_rows = skip_empty_rows, show_col_types = show_col_types)"

I attach simple CSV files that crush. 

[crashing_csv.csv](https://github.com/tidyverse/readr/files/7135601/crashing_csv.csv)
[crashing_csv2.csv](https://github.com/tidyverse/readr/files/7135609/crashing_csv2.csv)

Any help would be appreciated.

vroom version 1.5.4
reader version 2.0.1
tidyverse version 1.3.0

```r
library(shiny)
library(tidyverse)
library(vroom)


ui <- fluidPage(
  actionButton("crush_btn", "Crush this app"),
  
)

server <- function(input, output, session) {
  
  
  
 
  observeEvent(input$crush_btn,{
    
    cat("\ncrushing!\n")
    
    # read_csv("qa/crashing_csv.csv")
    b <- read_csv("qa/crashing_csv.csv")
    
  })
  
  
  
  
}

shinyApp(ui, server)
```

**Comment by jimhester** [comment]
I think you must be mistaken with what version of vroom is running within shiny and it must be a version of vroom prior to 1.5.0.

**Comment by alon-sarid** [comment]
Thanks you were right. Closing this issue
