### ISSUE TITLE
Bug after package update in read_delim with empty file

### ISSUE THREAD

**Issue by ShinyFabio** [tidyverse/readr#1305]
Hi, yesterday I updated many packages (and I think also yours) and my shiny app broke. When reading multiple txt files with `read_delim()` function, R freezes and I could close it only from task manager. 

After a day digging on the problem, I've found that the problem occurs when I try to read files that contain only the header with no data. I solved the problem changing the parameter `n_max` setting it to a big number (i.e. 100000). The default value was `Inf` and so I suspect that if the file doesn't have any data, `read_delim()` continue to read forever searching for some data (that doesn't exist). I don't know why few days ago worked and yesterday didn't work anymore, but I wrote here my solution that maybe could be useful to somebody.

**Comment by jimhester** [comment]
This is similar to https://github.com/tidyverse/readr/issues/1297, perhaps a duplicate, though I think in the other case the file was completely empty, whereas here you have just a header row.

**Comment by ShinyFabio** [comment]
I didn't find that problem. However I can close since I solved my problem with that parameter. I will suggest this solution to the other guy. Maybe could be useful.
