### ISSUE TITLE
read_csv fails in readr 2.0.1 if a comment contains an un-terminated quote

### ISSUE THREAD

**Issue by a-hurst** [tidyverse/readr#1307]
Hi there,

I think I've run into a pretty weird edge case bug: after updating to readr 2.0.1, I can no longer import files where the header comments contain an un-terminated quote.

For example, running `read_csv(filename, comment = "#")` on the following example file returns 0 rows and 0 columns:
```
# This is a header
# This is a quote: "

col_a,col_b,col_c
1,2,3
4,5,6
```
However, removing the quote character from the second line (or adding a second one) allows the file to import just fine. This works perfectly fine if I use the edition functions to use the old readr backend.

The reason this is an issue is that I have a ton of data files with headers specifying the runtime information of the program that collected the data, including the computer's screen size in inches:

```
# EXPERIMENT SETTINGS
#  > Trials Per Block: 20
#  > Blocks Per Experiment: 5
#
# SYSTEM INFO
#  > Operating System: macOS 10.14.6
#  > Python Version: 2.7.15
#
# DISPLAY INFO
#  > Screen Size: 24" diagonal
#  > Resolution: 1920x1080 @ 60Hz
#  > View Distance: 57 cm
```

Thanks in advance, and thank you for maintaining this excellent package!

**Comment by jimhester** [comment]
Thank you for opening the issue and including a reproducible example!

I can confirm the issue, a possible workaround would be to turn off quoting with `quote = ""` when reading these files, assuming it doesn't use quoting in the data.

We may not fix this bug immediately, as we are currently shifting focus to other packages, but I assure you we will get to it in time.

**Comment by untergeekDE** [comment]
Can confirm, came here to report that very issue. [Sample file with German election data here](https://share.ard-zdf-box.de/s/5bW7QCyeJR9XewQ), this stops after line 932 without any error message or warning - had a very interesting night on Sunday. :) File read with 
```
read_delim(fname, delim = ";",
                                 escape_double = FALSE,
                                 locale = locale(date_names = "de",
                                                 decimal_mark = ",",
                                                 grouping_mark = ".",
                                                 encoding = "WINDOWS-1252"),
                                 trim_ws = TRUE  
                                 skip = 1)
```
Side issue: If you import a text cell containing matching quotes, the first will go missing: 
`Dieses Wahlergebnis enthält Stimmen aus: Hirschhagen, Gasthaus "Zum Rohrbachtal"`
is returned as
`"Dieses Wahlergebnis enth\xe4lt Stimmen aus: Hirschhagen, Gasthaus \"Zum Rohrbachtal\"\""`

**Comment by jimhester** [comment]
Should be fixed in the next release version of vroom.
