### ISSUE TITLE
odd behavior of parsing error message for `readr::read_csv`?

### ISSUE THREAD

**Issue by oharac** [tidyverse/readr#1311]
Hi,

Our students encountered a parsing error in an assignment task that seems to demonstrate an odd/confusing behavior; I am seeing this in `readr` version 2.0.2 (in R 4.1.1).  The parsing error message does not show up after the `read_csv` call as I believe it did in prior versions of `readr` and is the most helpful place for the message, but instead shows up the next time you try to do something with the column that created the parsing error.  

In the reprex below, `read_csv` accesses a data set from my GitHub since I couldn't seem to replicate it when feeding `read_csv` a simple dataset as a line of text...  Note how the parsing error `Warning: One or more parsing issues, see problems() for details` doesn't show up until trying to use the offending column in a calculation, instead of immediately after `read_csv` which I think would be the expected behavior.

``` r
library(readr)

data_path <- 'https://raw.githubusercontent.com/oharac/test_data/main/knz_bison_weight.csv'

df <- read_csv(data_path)
#> Rows: 8325 Columns: 9
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (3): DataCode, AnimalCode, AnimalSex
#> dbl (6): RecType, RecYear, RecMonth, RecDay, AnimalWeight, AnimalYOB
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

df$mean_wt  = mean(df$AnimalWeight, na.rm = TRUE)
#> Warning: One or more parsing issues, see `problems()` for details
```

<sup>Created on 2021-10-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

In this next reprex, I call `problems(df)` immediately after `read_csv` even though the parsing error message has not yet occurred.  Upon the `problems(df)` call, the message now occurs, and then lists out the offending parse problem.

``` r
library(readr)

data_path <- 'https://raw.githubusercontent.com/oharac/test_data/main/knz_bison_weight.csv'
df <- read_csv(data_path)
#> Rows: 8325 Columns: 9
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (3): DataCode, AnimalCode, AnimalSex
#> dbl (6): RecType, RecYear, RecMonth, RecDay, AnimalWeight, AnimalYOB
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

problems(df)
#> Warning: One or more parsing issues, see `problems()` for details
#> # A tibble: 1 × 5
#>     row   col expected actual file 
#>   <int> <int> <chr>    <chr>  <chr>
#> 1  8237     8 a double .      ""
```

<sup>Created on 2021-10-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

In this reprex, the parsing error message occurs after the first `mean()` call, but not after the second identical one, which makes me suspect it is a weird artifact from `read_csv`.

``` r
library(readr)

data_path <- 'https://raw.githubusercontent.com/oharac/test_data/main/knz_bison_weight.csv'

df <- read_csv(data_path)
#> Rows: 8325 Columns: 9
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (3): DataCode, AnimalCode, AnimalSex
#> dbl (6): RecType, RecYear, RecMonth, RecDay, AnimalWeight, AnimalYOB
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

df$mean_wt  = mean(df$AnimalWeight, na.rm = TRUE)
#> Warning: One or more parsing issues, see `problems()` for details

df$mean_wt2  = mean(df$AnimalWeight, na.rm = TRUE)
```

<sup>Created on 2021-10-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Session info:
```
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13 knitr_1.34      magrittr_2.0.1  R6_2.5.1        rlang_0.4.11    fastmap_1.1.0   fansi_0.5.0    
 [8] highr_0.9       tools_4.1.1     xfun_0.26       utf8_1.2.2      cli_3.0.1       clipr_0.7.1     withr_2.4.2    
[15] htmltools_0.5.2 ellipsis_0.3.2  yaml_2.2.1      digest_0.6.28   tibble_3.1.4    lifecycle_1.0.1 crayon_1.4.1   
[22] processx_3.5.2  callr_3.7.0     vctrs_0.3.8     fs_1.5.0        ps_1.6.0        glue_1.4.2      evaluate_0.14  
[29] rmarkdown_2.11  reprex_2.0.1    compiler_4.1.1  pillar_1.6.3    pkgconfig_2.0.3
```

**Comment by jimhester** [comment]
This is expected, vroom 2.0+ uses a lazy parser by default, all the data is not read when you first call the function, so parse errors in the data can only be detected when the particular cell is accessed.

If you use `lazy = FALSE` when you read the data it will read the files eagerly and you should see similar behavior as previous versions of readr.
