### ISSUE TITLE
`read_csv2` reads wrong data from file with bad line-endings and gives misleading problem message

### ISSUE THREAD

**Issue by AshesITR** [tidyverse/readr#1315]
When downloading a file with CR line-endings on a Windows machine using `download.file(...)` without `mode = "wb"`, one can obtain files with `\r\r\n` as line endings.

These used to work (tm) in `readr` without a problem and still work with base R and with data.table.
readr however gives a peculiar error message and reads garbled content.
In one particular instance it even consistently crashed R (try downloading https://people.math.ethz.ch/~wmario/Lecture/MTPL_data.csv to a windows machine with `mode = "w"` and use `readr::read_delim(file, delim = ";")`; then look at `problems()` or try to use the complete data frame).

Here is an MWE in which I would expect one of two behaviors:

1. correctly read the data as base R and data.table do.
2. raise an informative error message pointing towards the bad line endings.

``` r
tmp <- tempfile()
num_rows <- 200000
bad_content <- paste(
  c("a;b", rep("1;1", num_rows)),
  collapse = "\r\r\n"
)
readr::write_file(bad_content, tmp)
nrow(base <- read.csv2(tmp))
#> [1] 200000
nrow(dt <- data.table::fread(tmp))
#> [1] 200000
nrow(readr <- readr::read_csv2(tmp))
#> i Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.
#> Rows: 200001 Columns: 2
#> -- Column specification --------------------------------------------------------
#> Delimiter: ";"
#> dbl (2): a, b
#> 
#> i Use `spec()` to retrieve the full column specification for this data.
#> i Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> [1] 200001

all(base$a == 1)
#> [1] TRUE
all(base$b == 1)
#> [1] TRUE
all(dt$a == 1)
#> [1] TRUE
all(dt$b == 1)
#> [1] TRUE
all(readr$a == 1)
#> Warning: One or more parsing issues, see `problems()` for details
#> [1] NA
all(readr$b == 1)
#> [1] NA

first_bad <- which.max(is.na(readr$a))
first_bad
#> [1] 109226

readr::problems(readr)
#> # A tibble: 1 x 5
#>      row   col expected  actual    file 
#>    <int> <int> <chr>     <chr>     <chr>
#> 1 109226     1 2 columns 1 columns ""
```

<sup>Created on 2021-10-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Here's a reprex with the bigger 32.4MB dataset that actually crashes R:
``` r
tmp <- tempfile()
download.file("https://people.math.ethz.ch/~wmario/Lecture/MTPL_data.csv", tmp)
nrow(base <- read.csv2(tmp))
#> [1] 500000
nrow(dt <- data.table::fread(tmp))
#> [1] 500000
nrow(readr <- readr::read_csv2(tmp))
#> i Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.
#> Rows: 499999 Columns: 12
#> -- Column specification --------------------------------------------------------
#> Delimiter: ";"
#> chr (10): id, claims, expo, power, gas, brand, area, dens, ct, truefreq
#> dbl  (2): age, ac
#> 
#> i Use `spec()` to retrieve the full column specification for this data.
#> i Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> [1] 499999

# Crashes R on Windows:
# readr::problems(readr)
```

<sup>Created on 2021-10-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sbearrows** [comment]
Since this situation seems rare, it's better to find the root cause of the issue which in this case seems to be using `mode = "w"` rather than `mode = "wb"`. You might find it helpful to review this related thread on using `download.files()` on a Windows machine https://github.com/HenrikBengtsson/Wishlist-for-R/issues/30
