### ISSUE TITLE
Tweak problems hint

### ISSUE THREAD

**Issue by hadley** [tidyverse/readr#1322]
From `problems()` to `problems({your_data_frame})` to make it more clear to run it on your data frame.

**Comment by twest820** [comment]
I think there might be more going on than just `problems({your_data_frame})`. I've hit this situation
```
tibbleFromCsv = read_csv(..., lazy = FALSE) # tibble seems fine but...
Warning message:                                                                                                
One or more parsing issues, see `problems()` for details 
problems() # displays nothing
problems(tibbleFromCsv) # still displays nothing

tibbleFromCsv = read_csv(..., lazy = TRUE) # no warning and the tibble still seems fine, though R is stuck holding the file handle open
```
Please let me know if there's details I can check into which might be helpful for diagnosing why there's apparently both some problems and also no problems in this situation. The .csv in question is 0.5 MB, so it's not immediately obvious how to turn it into a repex.

**Comment by jimhester** [comment]
@twest820 I think that might be a case of https://github.com/tidyverse/readr/issues/1313, if so it should be fixed by updating the the latest versions of readr and vroom.

**Comment by twest820** [comment]
Hi Jim, looks like it was 1313 indeed. Thanks!
