### ISSUE TITLE
Duration columns

### ISSUE THREAD

**Issue by tvatter** [tidyverse/readr#1327]
Hi,

I am aware of #549 and #1037, but it does not really address my problem. Additionally, I already filed a [similar bug report on the `lubridate` repo](https://github.com/tidyverse/lubridate/issues/1005) as I am unsure whether the responsibility to handle the following issue falls on `readr` or `lubridate`...

Here's a regex of my issue:

```r
df <- tibble(x = duration(1, "years"))     # x is a duration
tmp <- tempfile(); write_csv(df, tmp)    # write the df to file
df2 <- read_csv(tmp)                           # x is now a character which can't be easily coerced
```

The main issue is that `as.duration(as.character(duration(1, "years"))))` returns `NA` because the parser from the duration class is designed with a different purpose in mind.

Now, I get that one could just convert a duration as a numeric before writing, via `mutate(across(where(is.duration), as.numeric))`. 
But while I understand that `readr` can't handle every class out there, I was expecting the duration class, being provided by a `tidyverse` package, to be handled "properly" by `write_csv`.

Thoughts?

**Comment by vspinu** [comment]
Fixed in https://github.com/tidyverse/lubridate/issues/1005
