### ISSUE TITLE
read_tsv not reading string input

### ISSUE THREAD

**Issue by zeitlerd** [tidyverse/readr#1330]
In version 2.1.0 of readr, reading a .tsv file into a string with read_lines and then reading the input lines with read_tsv tries to open a file using the input string as the file name. This worked fine in version 1.4. Looks like recognition of the input string as data rather than a file name is broken. I tested read_delim and it fails the same.

`# read the tsv file into a string`
`tsv <- read_lines('myfile.tsv')`
`# extract needed lines from string`
`tsv <- tsv[str_detect(tsv, "^usethese")]`
`# convert the selected lines into an tbl for work`
`data <- read_tsv(tsv)`

My work around will be to write the intermediate out to a file first.

**Comment by jimhester** [comment]
This is a deliberate change, see https://github.com/tidyverse/readr/blob/main/NEWS.md#literal-data.

You need to put `I()` around the data, e.g.

```r
data <- read_tsv(I(tsv))
```

**Comment by zeitlerd** [comment]
Thanks. I’d missed that.

---
David Zeitler
