### ISSUE TITLE
Write columns with Period class to ISO8601 duration format

### ISSUE THREAD

**Issue by peterdesmet** [tidyverse/readr#1335]
`write_csv()` will write columns with class `Period` to CSV as `1y 2m 3d 4H 5M 6S`.

Would it be possible to support [ISO8601 duration format](https://en.wikipedia.org/wiki/ISO_8601#Durations) instead (i.e. `P1Y2M3DT4H5M6S`)? Cf. how datetimes are also written to ISO8601 format.

Note that a change in format will likely not affect `col_guess()` in `read_csv()`, since periods are guessed as character.

``` r
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union
library(readr)
interval <- interval(ymd_hms("2020-01-01 00:00:00"), ymd_hms("2021-03-04 04:05:06"))

# Create data.frame
df <- data.frame(period = as.period(interval))
# Print content of column period
df$period
#> [1] "1y 2m 3d 4H 5M 6S"
# Write to csv
write_csv(df, "df.csv")

# See how value was stored in file
read_file("df.csv")
#> [1] "period\n1y 2m 3d 5H 6M 7S\n"

# Read csv
df2 <- read_csv("df.csv")
#> Rows: 1 Columns: 1
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (1): period
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# Class of column "period"
class(df2$period)
#> [1] "character"
```

<sup>Created on 2021-11-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
At the current moment you can use `format_ISO8601()` to preemptively convert them to character in that format

``` r
library(lubridate)

period <- years(1) + months(2) + days(3) + hours(4)

format_ISO8601(period)
#> [1] "P1Y2M3DT4H"
```

I'm not sure if readr should be in the business of converting to this form automatically, since there isn't a corresponding parser directly into Period objects
