### ISSUE TITLE
Feature: Skip empty columns

### ISSUE THREAD

**Issue by CUBICinfinity** [tidyverse/readr#1339]
As an extension to this [question](https://stackoverflow.com/questions/38088329/remove-empty-columns-from-read-csv), is there not any feature of read_csv (read_delim, etc.) that skips blank columns? If not, we might consider adding it. Apologies if this has already been discussed.

Empty columns are the case where a file has a sequence of delimeters (`,,,,,,,`) without any data in those positions in the rows

**Comment by nstjhp** [comment]
You can use `cols_only()` to read in only certain columns (thereby skipping the rest).
Also see  `?col_skip`

**Comment by CUBICinfinity** [comment]
@nstjhp If I'm reading correctly, those require you to specify the columns. Be great if there was just an argument, like `skip_empty_cols = FALSE` that if changed to `TRUE` drops empty columns, according to `guess_max`.

**Comment by nstjhp** [comment]
Yes you are right. These days I am almost always specifying all my wanted columns as in the long run I have found it saves time. For a first read though I think you propose a reasonable idea.

**Comment by jennybc** [comment]
I view this as a violation of type stability. Meaning the structure of the output now varies according to the contents of the input. For example, for the same file, for different values of `guess_max` or `n_max`, you could get data frames with different numbers of columns back.

If you know you want to skip a column, we have ways to express that explicitly.

And, after you've seen the data, you know you want to drop a column, then that's when you should do that.

In general, we try to recognize when a "composite action" like this is OK/desirable to leave as separate parts (vs. really crying out for a special function or argument to get the combined behaviour). I feel like this is a case where it's best to leave these actions separate.

**Comment by CUBICinfinity** [comment]
For others reading, the dplyr::select also has some great tools that will assist with reducing columns after the data is loaded, if there are a lot of them: https://dplyr.tidyverse.org/reference/select.html
