### ISSUE TITLE
Feature: allow reading in columns as list-columns

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/readr#1340]
Allowing `col_types` to be passed something like `col_list_col_logical()`, `col_list_col_integer()`, `col_list_col_double()` or `col_list_col_character()` for the case when the values are not scalar but vectorish.

**Comment by sbearrows** [comment]
Thanks for opening this issue! This is an interesting idea, but not currently on the radar. You might look into `tidyr::separate_rows()`

``` r
df <- tibble::tibble(
  x = 1:3,
  y = c("a", "d,e,f", "g,h"),
  z = c("1", "2,3,4", "5,6")
)
tidyr::separate_rows(df, y, z, convert = TRUE)
#> # A tibble: 6 × 3
#>       x y         z
#>   <int> <chr> <int>
#> 1     1 a         1
#> 2     2 d         2
#> 3     2 e         3
#> 4     2 f         4
#> 5     3 g         5
#> 6     3 h         6
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
