### ISSUE TITLE
Memory usage when iterating calls to read_delim using a map function

### ISSUE THREAD

**Issue by JamesGillerITS** [tidyverse/readr#1342]
I have a folder of text files with data in comma-delimited format. Each file in the folder contains some data collected by a system on one day in a year, so 365 files in total. The files are about 174 MB each and 60.1 GB in total.

Below is an example of the code I try to run. Consider that the system consists of many sources of data, each with a unique `source_id`, and one row of a file contains data from a single source over a five-minute interval. My code is supposed to go through all the files, extract data from a subset of sources and store the subset of data in another data frame.

```
filenames <- Sys.glob("Data/*.txt")

subset_daily_data <- function(filename) {
  daily_data <- read_delim(filename, delim = ",")
  
  selected_ids <- 1:16
  subsample <- daily_data %>%
    filter(source_id %in% selected_ids)
  
  return(subsample)
}

selected_source_data <- map_dfr(filenames, subset_daily_data )
```

When I run the above code in RStudio version 1.2.5033 using readr version 2.0.2, the memory usage of RStudio grows as if I am keeping the entire contents of each file in memory (going into tens of gigabytes).

I changed my code to use a for loop with `bind_rows` instead of `map_dfr` and the memory does not grow. The final size of the subset of the data is only about 222 MB.

**Comment by DavisVaughan** [comment]
> readr version 2.0.2

If you update to CRAN readr does the problem persist? I have a feeling this is related to lazy reading, which was reverted back to eager in version 2.1.0.

My guess is that, during lazy reading, the `filter()` creates an ALTREP view of the original `daily_data`, so `subsample` probably does indeed refer to `daily_data`, preventing it from being garbage collected.
