### ISSUE TITLE
read_csv not respecting quotes (for strings that have commas in them) when space after field comma

### ISSUE THREAD

**Issue by michdn** [tidyverse/readr#1350]
I'm using readr 2.1.1 and I'm running into an issue that I do not experience using 1.4.0 when I'm reading in a file of my regression formulas. (I'm using multiple machines.) 

It's similar, but different to https://github.com/tidyverse/readr/issues/1237 where the issue was the quoted field needed to be next to the newline. Here, it's a space after the comma (that delimits fields, not within the quoted string). Which I thought from one of the comments (https://github.com/tidyverse/readr/issues/1237#issuecomment-884428729) on that issue was supposed to be supported if I'm reading it right? 

Here's a stripped down version of what I'm trying to read in: 
```r
read_csv('
         "my-formula", "cases + 0 + district + s(lag, by=var1)"
         "my-formula2", "cases + 0 + s(lag, by=var1)"
         ', col_names = FALSE, quote = "\"", 
         show_col_types = FALSE)
         
# A tibble: 2 x 3                                                                                                                               
#  X1          X2                           X3          
# <chr>       <chr>                        <chr>       
#1 my-formula  cases + 0 + district + s(lag "by=var1)\""
#2 my-formula2 cases + 0 + s(lag            "by=var1)\""
```

So it sounded like trimming white space might help, but does not seem to: 
```r
read_csv('
         "my-formula", "cases + 0 + district + s(lag, by=var1)"
         "my-formula2", "cases + 0 + s(lag, by=var1)"
         ', col_names = FALSE, quote = "\"", trim_ws = TRUE,
         show_col_types = FALSE)

# A tibble: 2 x 3                                                                                                                               
# X1          X2                           X3          
# <chr>       <chr>                        <chr>       
#1 my-formula  cases + 0 + district + s(lag "by=var1)\""
#2 my-formula2 cases + 0 + s(lag            "by=var1)\""
```

The only thing that I found works is editing the file itself to remove spaces between the comma after my formula name and the formula. While it is a solution, it's going to be a real pain to deal with, and it seems like it should have worked like before? 
```r
read_csv('
         "my-formula","cases + 0 + district + s(lag, by=var1)"
         "my-formula2","cases + 0 + s(lag, by=var1)"
         ', col_names = FALSE, quote = "\"",
         show_col_types = FALSE)

# A tibble: 2 x 2                                                                                                                               
#X1          X2                                    
#<chr>       <chr>                                 
#1 my-formula  cases + 0 + district + s(lag, by=var1)
#2 my-formula2 cases + 0 + s(lag, by=var1) 
```

Thanks!

**Comment by jennybc** [comment]
Are you actually using inlined data or is your input really found in a file?

**Comment by jennybc** [comment]
Aha! The whitespace that you really need to remove is the space after the commas that are serving as delimiters:

``` r
readr::read_csv('
         "my-formula","cases + 0 + district + s(lag, by=var1)"
         "my-formula2","cases + 0 + s(lag, by=var1)"
         ', col_names = FALSE, quote = "\"", 
         show_col_types = FALSE)
#> # A tibble: 2 × 2
#>   X1          X2                                    
#>   <chr>       <chr>                                 
#> 1 my-formula  cases + 0 + district + s(lag, by=var1)
#> 2 my-formula2 cases + 0 + s(lag, by=var1)
```

<sup>Created on 2022-01-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Perhaps this is what you were alluding to with this comment:

> So it sounded like trimming white space might help, but does not seem to

I can see where you're coming from, but yeah, that is not the fix.

I'll have to do more analysis, but it's not completely clear how quoted tokens and whitespace trimming should interact. I'll probably open an issue on vroom, but this is not going to see any swift action.

My main advice is for you to get rid of extraneous whitespace around your delimiters.

**Comment by michdn** [comment]
> Are you actually using inlined data or is your input really found in a file? I'm asking about your real application.

I am actually reading in file(s) with many more formulas that are more complicated. I tried trimmed it down to inline so that I had a reproducible example to show.  Here's a full example of my thin plate spline models: 

    models <- read_csv("data_formulas/models_tp.txt", col_names = FALSE, quote = "\"")
  
In the file are these four models (now with space after the field-delimiter-comma removed):

    "tp-fx-nonanom","anycases ~ 0 + district + MIRsummarystat + s(lag, by=var1, bs='tp') + s(lag, by=var2, bs='tp')"
    "tp-fx-anom","anycases ~ 0 + district + MIRsummarystat + s(lag, by=anom_var1, bs='tp') + s(lag, by=anom_var2, bs='tp') + s(doy, bs='tp')"
    "tp-sv-nonanom","anycases ~ 0 + district + MIRsummarystat + te(lag, doymat, by=var1, bs='tp') + te(lag, doymat, by=var2, bs='tp')"
    "tp-sv-anom","anycases ~ 0 + district + MIRsummarystat + te(lag, doymat, by=anom_var1, bs='tp') + te(lag, doymat, by=anom_var2, bs='tp') + s(doy, bs='tp')"

The single quotes around my spline types (e.g. bs='tp') really didn't play well with inline reading in, so I removed it in my example. 

I'm doing modeling for forecasting, and doing many trials of different mathematical model forms (my model file read in) with different predictor variables (var1, var2). I read in different files depending on which model(s) I want to run, and occasionally do filtering on model names to pull out specific ones. 

Does that answer your question how I'm using it? Let me know if you have any more questions for me.

**Comment by jennybc** [comment]
Got it.

If I put the file contents shown above into `formulas.csv`, I can successfully import that:

``` r
readr::read_csv("formulas.csv", col_names = FALSE)
#> Rows: 4 Columns: 2
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (2): X1, X2
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 4 × 2
#>   X1            X2                                                              
#>   <chr>         <chr>                                                           
#> 1 tp-fx-nonanom anycases ~ 0 + district + MIRsummarystat + s(lag, by=var1, bs='…
#> 2 tp-fx-anom    anycases ~ 0 + district + MIRsummarystat + s(lag, by=anom_var1,…
#> 3 tp-sv-nonanom anycases ~ 0 + district + MIRsummarystat + te(lag, doymat, by=v…
#> 4 tp-sv-anom    anycases ~ 0 + district + MIRsummarystat + te(lag, doymat, by=a…
```

<sup>Created on 2022-01-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

So I think the summary is that, if you need to lean heavily on quoting, you will have a much happier life if you eliminate any whitespace around the commas serving as delimiters. And this has been logged as a "maybe fix" in vroom.
