### ISSUE TITLE
Should `show_progress()` use `rlang::is_interactive()`?

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/readr#1356]
https://github.com/tidyverse/readr/blob/a14f189a344f60113540d75f13b49432df12bb70/R/utils.R#L23

I naively tried `rlang::with_interactive(value = FALSE, {expression-that-calls-read_tsv()})` and was surprised that I still saw the indexing output from vroom. I guess this is because this sets the rlang specific interactive option, which readr/vroom won't recognize. 

This should also be thought about in tandem with `vroom_progress()`
https://github.com/r-lib/vroom/blob/eaab3e161c2d82b922217e7b19a315f7c939af18/R/vroom.R#L237

I know about the `progress` argument that I could set directly, but this still feels relevant

**Comment by jennybc** [comment]
Yeah, I basically think we should always use `rlang::is_interactive()` for these purposes.
