### ISSUE TITLE
Support for frictionless data packages

### ISSUE THREAD

**Issue by vorpalvorpal** [tidyverse/readr#1363]
[Open Knowledge International](https://www.data4sdgs.org/partner/open-knowledge-international) has designed a format called [frictionless data](https://frictionlessdata.io/). This is basically a zip file containing csvs (or other data formats) plus a json file describing metadata. This json file specifies things like column types, labels and descriptions.

Given the emphasis placed on reproducible research in the tidyverse ecosystem, it would be great if frictionless data could be supported by readr. Metadata defined in the json file could be stored as attributes of either tibbles or individual columns which would allow print functions and the like to access them. A json file could then be reassembled from attribute data for writing to a new frictionless data zip.

Two existing packages are:
- [frictionless-r](https://github.com/frictionlessdata/frictionless-r)
- [datapackage-r](https://github.com/frictionlessdata/datapackage-r)

**Comment by sbearrows** [comment]
Thanks for opening this issue! It's great that there are existing packages for this. The idea definitely has merit but is not currently on our todo list.
