### ISSUE TITLE
Strange error while using write_tsv

### ISSUE THREAD

**Issue by ConYel** [tidyverse/readr#1366]
Hello and thank you much for this great package!

While using Rstudio on docker with flag --cpus="6.5" , eg `docker run --rm --cpus="6.5"  ...`
I got this error: `nrow(x)/100/num_threads`.
The 1st strange thing is that `write_tsv `was called sometimes before during the same session and run without an issue .
After checking if there was some issue with my code I tried to run also with an R data-set:
```r
starwars %>% write_tsv(file = "sstarwars.txt")
Error in nrow(x)/100/num_threads : 
  non-numeric argument to binary operator
```
When I run
```r
starwars %>% vroom::vroom_write(file = "sstarwars.txt")
```
I get the file written properly
```r
list.files()
 [1] "LICENSE"                      
...                                                                
[14] "README.md"                                
[15] "sstarwars.txt"                            

```
I checked that write_tsv runs:
```r
write_tsv
function (x, file, na = "NA", append = FALSE, col_names = !append, 
    quote = "none", escape = c("double", "backslash", "none"), 
    eol = "\n", num_threads = readr_threads(), progress = show_progress(), 
    path = deprecated(), quote_escape = deprecated()) 
{
    if (is_present(path)) {
        deprecate_warn("1.4.0", "write_tsv(path = )", "write_tsv(file = )")
        file <- path
    }
    if (is_present(quote_escape)) {
        deprecate_soft("2.0.0", "write_delim(quote_escape = )", 
            "write_delim(escape = )")
        escape <- quote_escape
    }
    write_delim(x, file, delim = "\t", na = na, append = append, 
        col_names = col_names, quote = quote, escape = escape, 
        eol = eol, num_threads = num_threads, progress = progress)
}
<bytecode: 0x55c9647639d0>
<environment: namespace:readr>
```
And when I run :`readr_threads()` I get:
```r
readr_threads()
[1] "name"
```
when I run 

```r
parallel::detectCores()
[1] 32
```
Although I have put on docker to be running only with 6.5 procs.

Any insight?

> EDIT
My docker image is based on : `bioconductor/bioconductor_docker:RELEASE_3_14`

**Comment by sbearrows** [comment]
It seems like there are some aspects of your set up that are not working right, specifically this part:

> readr_threads()
[1] "name"

This should not be returning a string. Until these parts are ironed out, it will be difficult to discern what's going on. You might try checking what `getOption("readr.num_threads")` or 
`Sys.getenv("VROOM_THREADS")` returns for more weirdness. 

It seems like we aren't getting the whole story here so I'm closing this until there is more evidence that this is a readr problem. If you've fixed some of these other aspects and are still having problems, open a new issue with some reproducible R code so we can experience the problem first hand.
