### ISSUE TITLE
bug when loading file with read_tsv()

### ISSUE THREAD

**Issue by AndreVidas** [tidyverse/readr#1371]
Hi!

I'm using readr 2.1.1

I'm not able to load a tab delimited file by using this command:
```r
read_tsv(<file.tsv>)
```

It gives me the following error:
```r
Error in app$vspace(new_style$`margin-top` %||% 0) :                                                               
  attempt to apply non-function
```
It worked a week ago or so. 

Best,
André

**Comment by Jason-Conner-NOAA** [comment]
@AndreVidas 
I have run into this error using readr 2.1.2, attempting to load a csv.  Would you explain why you closed this issue, please? 

Thanks,
Jason

**Comment by jennybc** [comment]
The error appears to come from cli. So one theory is that it's somehow triggered by a version incompatibility.

@Jason-Conner-NOAA what version of readr and cli do you have?

I would probably suggest getting current with the CRAN version of each.

**Comment by Jason-Conner-NOAA** [comment]
Thank you @jennybc 

I believe my packages are up to date:
MRAN 4.0.2
cli 3.2.0
readr 2.1.2

However, this error does not occur in a different environment with older versions of the packages:
MRAN 4.0.2
cli 3.0.1
readr 2.0.0

**Comment by philippbayer** [comment]
I just ran into the same issue with readr 2.1.1, updating `readr` to 2.1.2 did nothing but reinstalling `cli` to v3.2.0 fixed it

**Comment by vondoRishi** [comment]
I have also encountered the same problem, after upgrading R. To solve it, I have used 
`update.packages(checkBuilt=TRUE, ask=FALSE)`

**Comment by syzdekbr** [comment]
This same error came up for me in googlesheets4::read_sheet. I had the most current versions of:
cli 3.2.0
readr 2.1.2

Deleting and re-installing those packages then fixed.

**Comment by nFrechen** [comment]
For me installing glue 1.6.2 resolved the issue. It is used in cli 3.3.0 to output messages with inline markup. And I think that was the problem.

see also: https://github.com/tidyverse/dbplyr/issues/912 where the issue was narrowed down to `cli_warn()`

**Comment by camroberts** [comment]
`glue` version was also the problem for me. Version 1.4.2 produced the error. While installing 1.6.2 fixed it.
