### ISSUE TITLE
readr:read_excel refuses to load files with "°" or "ä" in filename on Windows

### ISSUE THREAD

**Issue by amaendle** [tidyverse/readr#1382]
When I try to load an Excel file with "°" or  "äöü?" in the filename, read_excel fails:

`read_excel("data/Fläche90°-SchlittenAlu.xlsx")
Error: Evaluation error: zip file 'C:\Users\mae.FINSTITUTE\data\Flï¿½che90ï¿½-SchlittenAlu.xlsx' cannot be opened.
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="data/Fläche90°-SchlittenAlu.xlsx": Das System kann die angegebene Datei nicht finden`

When I rename the file to "Flache90-SchlittenAlu.xlsx" read_excel suddenly reads the file without problems.

**Comment by sbearrows** [comment]
Looks like you are using `readxl::read_excel()`. Did you mean to open this in the readxl repo?
