### ISSUE TITLE
format_csv/write_csv quotes all strings starting with NA

### ISSUE THREAD

**Issue by hadley** [tidyverse/readr#1386]
``` r
df <- data.frame(x = c(NA, "NA", "NAM", "NAB", "NB"))
cat(readr::format_csv(df))
#> x
#> NA
#> "NA"
#> "NAM"
#> "NAB"
#> NB
```

<sup>Created on 2022-03-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I'm not convinced that even "NA" needs quotes, but either way it would be nice to document what `quote = "needed"` actually means.

**Comment by eBsowka** [comment]
Hello :)
I just spotted this error
Is there an option to stop this behaviour? I have data that starts with `NA` and double quotes are rly dangerous.
