### ISSUE TITLE
Warning about parsing problems won't always "work"

### ISSUE THREAD

**Issue by hpages** [tidyverse/readr#1401]
Hi,

When a package like Bioconductor package **gwascat** uses **readr** internally to import some file, we sometimes get the following warning:
```
library(BiocManager)
install("gwascat")

library(gwascat)
cur <- makeCurrentGwascat()
# trying URL 'http://www.ebi.ac.uk/gwas/api/search/downloads/alternative'
# downloaded 226.5 MB
#                                                                                                                                                                
# formatting gwaswloc instance...    
# NOTE: input data had non-ASCII characters replaced by '*'.
# done.
# Warning message:
# One or more parsing issues, see `problems()` for details 
```
Unfortunately, the suggested command doesn't work:
```
problems()
# Error in problems() : could not find function "problems"
```
This is because **gwascat** has **readr** in its `Imports` field and not in its `Depends` field, which is probably the right thing to do in this case.

Unfortunately, most users won't have a clue about where the warning is coming from and how to make it "work".

Could the warning say `readr::problems()` instead? That would make the command work no matter what.

Thanks,
H.

**Comment by jennybc** [comment]
I'm not entirely convinced this is practical, in that it could conceivably apply to any warning or error thrown by any package. In general, it feels like a "wrapper" should either make peace with the conditions emitted by a dependency or catch and rethrow them.

We have internal readr/vroom reasons for not wanting to explicitly namespace such things.

**Comment by hpages** [comment]
Given that providing a thin wrapper around a function like `readr::read_tsv()` to read in specific files where the columns and types are fixed and known in advance is a very common thing to do, it's unfortunate that each wrapper is expected to implement a complex and fragile-by-nature "catch and rethrow" mechanism just to prefix `problems` with `readr::`. Especially since it seems that this prefixing could have been easily taken care of by `readr::read_tsv()` in the first place.

sigh
