### ISSUE TITLE
Segfault when using read_delim for 2GB data file

### ISSUE THREAD

**Issue by stephpeng93** [tidyverse/readr#1409]
Hello,
I am simply trying up load a data file that is large, but not larger than my RAM. The file won’t load, causes R Studio to crash and gives a “segfault” message in R Console.

The exact code/data worked on my 2016 Mac, but won’t work on my 2020 Mac.

I have tried:
1) uninstalling/reinstalling R Studio and R Console
2) uninstalling/reinstalling base R packages 

Here is a screenshot of the segfault message below:

![DD7E133D-DA1C-482C-A389-D44A6B18A926](https://user-images.githubusercontent.com/54967259/176058835-c64c8692-8567-4437-96fb-25bdae4e4bdf.jpeg)

**Comment by jennybc** [comment]
Is this file available somewhere we can access it?
