### ISSUE TITLE
parse_number("1,2") returns 12

### ISSUE THREAD

**Issue by plogacev** [tidyverse/readr#1413]
read_csv() appears to parse the string "1,2" in an otherwise numerical column as 12. This appears to be due to the fact that parse_number("1,2") returns 12. I'm not entirely sure this is expected behavior. I can see why "1,200" would be parsed as "1200", but I doubt that is the case for "1,2".

Brief example:

```r
parse_number("1,2")
```

**Comment by sbearrows** [comment]
Duplicate of #1349
