### ISSUE TITLE
Set up a GHA job to check readr against dev vroom

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readr#1423]
Leading up to a near-simultaneous release of these, we need to be checking readr against dev vroom.

I am assigning this to myself.

**Comment by jennybc** [comment]
This appears to be working.

The job will run once every 24 hours and can also be run on demand:
https://github.com/tidyverse/readr/actions/workflows/R-CMD-check-against-dev-vctrs.yaml

**Comment by sbearrows** [comment]
@jennybc Shouldn't it be called `R-CMD-check-against-dev-vroom.yaml`?

**Comment by jennybc** [comment]
Ah yes, will you make that change?

**Comment by jennybc** [comment]
I changed it in 52f020ff7e0489750a20abb35ee1d62c825c8da0

**Comment by sbearrows** [comment]
Sorry, I didn't see your response until this morning!
