### ISSUE TITLE
Import variable labels from second row in csv file

### ISSUE THREAD

**Issue by torfason** [tidyverse/readr#1442]
It would be very useful to have a parameter in `read_csv()` to specify that the second row in a data set should be treated as variable labels, just as `col_names` lets the first row be treated as names. Such a parameter could be named `col_labels` with all legal values (`logical` or `character`) being treated in a parallel way, making a consistent interface.

Thus, after importing with such a parameter parameter set to `TRUE` the `speed` and `dist` variables in a data set imported from a data file that looked something like the following table would include variable labels (as set by e.g. `labelled::set_variable_labels()` and displayed by RStudio data viewer).

| speed  | dist |
| ------------- | ------------- |
| Speed (mph)  | Stopping distance (ft)  |
| 4  | 2  |
| 4  | 10  |
| ...  | ...  |

I realise that it is possible to achieve this by manually importing the data twice (using `skip=2` on one of the imports), or importing it, slicing it, and then converting types afterward. However, given that this is a pretty common format to encounter in the wild it would be very convenient to have a simple way of doing this while keeping all the `col_types` awesomeness that `read_csv()` offers.

I have seen issues #770, #901, and #1363. And I understand that it was decided not to implement them. However, I believe that this particular data format is much simpler, more common in CSV files out in the wild, and would be a relatively clean addition from an API standpoint (I have not gone deep enough into the internals to know if it would be simple or complex to implement).

**Comment by jennybc** [comment]
I'm afraid the stance from all the issues you linked is still our position on this. I see how it could be handy, but it actually is a substantial amount of work to implement this, at this point. Across all of our "rectangle reading" packages, there are too many things to do that have higher priority. The two-pass solution will remain the less-than-ideal workaround for the foreseeable future.
