### ISSUE TITLE
Parse numbers produces only NAs

### ISSUE THREAD

**Issue by Leprechault** [tidyverse/readr#1454]
Hi Everyone!

```
 library(dplyr)
 library(readr)
    
    # Read in the data
    ds <- read.csv("https://raw.githubusercontent.com/Leprechault/trash/main/parse_problem.csv")
    str(ds)
    # 'data.frame':	105 obs. of  5 variables:
    #  $ Especie      : chr  "C_externa" "C_externa" "C_externa" "C_externa" ...
    #  $ Rep          : chr  "R1" "R2" "R3" "R4" ...
    #  $ Instar_IN    : chr  "1Instar" "1Instar" "1Instar" "1Instar" ...
    #  $ Instar_PS    : chr  "ovo" "ovo" "ovo" "ovo" ...
    #  $ Tentou_predar: int  3 25 20 36 12 0 1 10 0 14 ...
```

I'd like to `parse_number` using `mutate` for `Especie` factor for plotting purposes. I've tried the following:

```
    ds.new <- ds %>% mutate(x_1=readr::parse_number(Especie),group = Especie)
    summary(ds.new$x_1)
    #    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
    #      NA      NA      NA     NaN      NA      NA     105 
```

I don't know why it's not working and I've just NA. Please, any ideas?

**Comment by joranE** [comment]
That function is for extracting numbers stored as characters, e.g. turning `"45"` into the integer 45. It looks like Especie doesn't have any numbers in it, and additionally isn't a factor, but a character vector. It sounds like you want the underlying integer codes from a factor. If so, you could explicitly coerce it to a factor (`as.factor()`) and then integer (`as.integer()`), i.e. `mutate(x_1 = as.integer(as.factor(Especie)))`.

**Comment by hadley** [comment]
Thanks @joranE!
