### ISSUE TITLE
Bug: " " read as NA

### ISSUE THREAD

**Issue by petyaracz** [tidyverse/readr#1457]
`read_delim` reads in a cell containing an empty space (`" "`) as NA by default.

`js` outputs `" "` as the input for pressing the space bar, so this is bad.

```r
> echo '"a","b"," "' > table.csv

readr::read_csv('table.csv', col_names = F)

# A tibble: 1 × 3
  X1    X2    X3   
  <chr> <chr> <lgl>
1 a     b     NA  
```

ed.
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.5.1
readr_2.1.3

**Comment by jennybc** [comment]
readr is working as designed and documented. You talk about `read_delim()`, but your example is with `read_csv()`, and they have different default re: whitespace trimming. The arguments relevant to this behaviour are `trim_ws` and `na`.

``` r
library(readr)

op <- options(readr.show_col_types = FALSE)

# trim_ws = TRUE is the default
read_csv(I('"a","b"," "'), col_names = FALSE)
#> # A tibble: 1 × 3
#>   X1    X2    X3   
#>   <chr> <chr> <lgl>
#> 1 a     b     NA

read_csv(I('"a","b"," "'), col_names = FALSE, trim_ws = FALSE)
#> # A tibble: 1 × 3
#>   X1    X2    X3   
#>   <chr> <chr> <chr>
#> 1 a     b     " "

# trim_ws = FALSE is the default
read_delim(I('"a","b"," "'), col_names = FALSE)
#> # A tibble: 1 × 3
#>   X1    X2    X3   
#>   <chr> <chr> <chr>
#> 1 a     b     " "

options(op)
```

<sup>Created on 2022-12-09 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by petyaracz** [comment]
My bad.
