### ISSUE TITLE
Problem with version 2.1.3

### ISSUE THREAD

**Issue by LaboratorioSMA** [tidyverse/readr#1466]
I am using a `read_csv` function from `readr` package, which worked fine for me with `readr` version 2.1.2; however, when upgrading to version 2.1.3, the following problem appears: `Warning: Error in enc2utf8: argument is not a character vector`.

```
encabezado_csv <- read_csv(input$csv$datapath,
                               col_names = FALSE, 
                               trim_ws = TRUE,
                               skip_empty_rows = TRUE) %>% 
slice(1:4)
```
How can I solve this problem?

(https://community.rstudio.com/t/problem-with-readr-version/159413)

**Comment by jennybc** [comment]
I can't run this code to see what you're experiencing. I.e. I don't have `input$csv$datapath`. Apparently `read_csv()` is expecting it to be character and I guess it's not?

Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks!

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
