### ISSUE TITLE
read_csv with zip file

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/readr#1471]
I have a zip file on Windows that contains a directory tree of csv files.  I tried and it just read the first csv file.
```
read_csv("myzip.zip", id = "id")
```

There are two problems:
- the help file has no information on how this is supposed to work.  
- it would be nice if it read all the csv files and not just the first.  It is unlikely that there are many actual applications where one wants to just read the first csv in a zip file containing a directory tree of many csv's.

If I separately unzip the zip file and then use `read_csv` giving it a character vector of all the csv file paths then it does work.

**Comment by hadley** [comment]
We're just mimicking the behaviour of `read.csv()` here. I'd definitely recommend unzipping and parsing yourself.
