### ISSUE TITLE
Suggestion: change default value of condense to FALSE in print.col_spec()

### ISSUE THREAD

**Issue by presnell** [tidyverse/readr#1478]
I find the default behavior pretty surprising/confusing for a print method.  See the example below to see what I mean.  Would it break anything else if this were changed?

```r
csv <- "
v,w,x,y,z
1,,,,2
"
df <- read_csv(csv)
col_spec <- spec(df)
col_spec$default <- col_double()
col_spec
print(col_spec, n = 3)                          # Not at all what I expected.
print(col_spec, n = 3, condense = FALSE)        # This is more like it.
```

**Comment by presnell** [comment]
On a related matter, I also think that `cols_condense()` would be much safer and more useful if there were an option to specify the default column type.  In this case, only columns of that type would be "condensed out", rather than the most common column type.

**Comment by hadley** [comment]
This might be surprising to you, but it's been this way for many years now, so changing it at this point is likely to increase new surprise, not decrease it.

**Comment by presnell** [comment]
How about the second suggesting?  The initial motivation for me was looking at data sets with many columns, many of which contain mostly missing data.  The readr/vroom guess for such columns is likely to be logical and those are exactly the ones I want to manually specify.  So if I could set the default in cols_condense to  the most common non-logical column type, then it leaves me with a more manageable list of the columns that I really need to deal with.

I'm not sure if I have explained that well, but in general it seems like a useful feature to me that shouldn't break anyone's pre-existing code.
