### ISSUE TITLE
Feature: Option for overriding default_locale()

### ISSUE THREAD

**Issue by panporter** [tidyverse/readr#1479]
readr uses default_locale() if no locale is passed as a parameter. There is no possibility to define one's own default other than hacking readr's default_locale() function using R.utils. (See reprex.)

Defining one's own defaults would come in handy for repetitive tasks without passing the locale each time. Especially inevitable for third party use of readr e.g. [readODS](https://github.com/ropensci/readODS) which utilises readr without giving the option to define a locale. See https://docs.ropensci.org/readODS/reference/read_ods.html

``` r
library(readr)
library(tibble)
# dataframe to convert
df <- tibble(date = "12.03.12")

# this works, but I have to append the locale parameter each time
type_convert(df, locale = locale(date_format = '%d.%m.%y') )
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   date = col_date(format = "")
#> )
#> # A tibble: 1 x 1
#>   date      
#>   <date>    
#> 1 2012-03-12

# all dates have this format:
my_default_locale <- function() { locale(date_format = '%d.%m.%y') }

library(R.utils)
# hacking readr's default_locale()
R.utils::reassignInPackage("default_locale", pkgName = "readr", my_default_locale)

# now magically works without appending locale parameter
type_convert(df)
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   date = col_date(format = "")
#> )
#> # A tibble: 1 x 1
#>   date      
#>   <date>    
#> 1 2012-03-12
```

<sup>Created on 2023-03-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
IMO that's a bug in readODS; if it passed on a `locale` argument you could use that to write your own wrapper.
