### ISSUE TITLE
Reading partitioned data files

### ISSUE THREAD

**Issue by scottporter** [tidyverse/readr#1487]
arrow and sparklyr both can read csv files with hive style partitioning.  It would be nice if readr could do the same.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
