### ISSUE TITLE
Request for argument synchronization with dplyr

### ISSUE THREAD

**Issue by jmgirard** [tidyverse/readr#1497]
I do a lot of teaching with tidyverse tools and one thing that is not ideal is that some arguments are different across tidyverse packages. For example, I teach about how to combine tibbles using `dplyr::bind_rows()` and the `.id` argument. Then I introduce the idea of giving a vector of file names to `readr::read_csv()` to do the same kind of thing from data files. This is great but then I have to tell the students that the argument here is `id` not `.id`. It would be very helpful if arguments like this could be synchronized across core tidyverse packages.

**Comment by jmgirard** [comment]
I guess you could argue that `dplyr::bind_rows(.id)` and `readr::read_csv(id)` do slightly different things (e.g., add a positional index or argument name for the former and add the file name for the latter). But in that case, then maybe the argument name should be even more different. So either way, it might be good to take a look at this.

**Comment by hadley** [comment]
Our justification for the different names can be found at https://design.tidyverse.org/dots-prefix.html.

**Comment by jmgirard** [comment]
> Our justification for the different names can be found at https://design.tidyverse.org/dots-prefix.html.

For posterity: Based on my reading of that link, they are different because `bind_rows()` uses `...` to create a data structure, whereas `read_csv()` does not. The tidy design guide says to add `.` before an argument name in the former case only.

**Comment by hadley** [comment]
Exactly!

We don't want to accidentally interfere if you are trying to do `bind_rows(id = id, ego = ego)` and it would be weird for `read_csv()` to have a single argument starting with a `.`.
