### ISSUE TITLE
Support for factor labels with integer coded factors.

### ISSUE THREAD

**Issue by ralmond** [tidyverse/readr#1498]
I have a situation where there saved data in the csv file has integer codes for the factors, but I know the labels I want to use from the codebook.  

I would think the way to specify this would be as follows

```r
col_factor(c(Male=0,Female=1))
```

However, that throws an error. 
```
Error: `levels` must be `NULL` or a character vector:
- `levels` is a 'numeric'
```

My intention is to feed the column into `factor(x, levels=arg, labels=names(arg))`, where `arg` is the argument to `col_factor`.

I think this would be a generally useful feature, as integer coding of factors (with external code book) is a common practice.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
