### ISSUE TITLE
set column types by regex?

### ISSUE THREAD

**Issue by kcandrews** [tidyverse/readr#250]
My data has hundreds of columns, many of them having the same form, such that a regular expression might be used to select all the columns whose header matches with a particular form and assign them the same column type. I couldn't find any examples of this case. Is this possible now, or would you be willing to add this feature?

**Comment by dewittpe** [comment]
I was wondering the same and I created a function `select_cols` for doing this.  A working example is in [this gist](https://gist.github.com/dewittpe/bcc78fd45b3d4887deb5).

I'd be happy to see this type of function as part of the `readr` package too.  Time to fork and work on the feature.

**Comment by dewittpe** [comment]
While developing this feature, have found two warning messages occurring.  A parsing warning that fewer columns have been read in than in the data source, and that the `col_euro_double()` has been deprecated.  The latter warning is of concern because, in the example below, no explicit call to `col_euro_double()` is made.  (I think it is coming from the call to `col_euro_double()` from within `col_types_standardise()`.

    library(devtools) 
    load_all("~/readr")  # the select-col-by-regex branch of dewittpe/reader

    # Example data 
    input_data <- 
    '"","sid","sex","age","group","proc1","proc2","proc3","proc4","proc5","proc6","proc7","proc8","proc9","proc10","proc11","proc12","procdos1","procdos2","procdos3","procdos4","procdos5","procdos6","procdos7","procdos8","procdos9","procdos10","procdos11","procdos12"
    "1",1,"F",8,"C",763.83,441.6,400.08,708.04,138.69,623.44,700.68,663.61,648.04,421.05,913.26,233.6,4,0,5,14,2,33,7,1,36,28,2,3
    "2",2,"F",13,"A",829.94,492.19,412.07,984.53,226.43,242.11,100.22,295.44,853.11,469.57,643.12,172.24,9,18,5,14,10,14,8,0,10,7,12,9
    "3",3,"M",17,"C",449.29,133.69,458.63,783.58,294.74,423.12,287.71,294.91,776.36,616.12,668.35,517.66,5,7,2,22,30,35,0,7,39,2,15,6
    "4",4,"F",5,"C",716.65,976.18,806.22,609.83,531.45,681.06,939.72,450.05,507.45,630.7,943.64,801.42,12,18,7,28,11,0,38,10,9,16,8,8
    "5",5,"F",8,"A",103.55,488.57,135.04,864.71,277.67,798.23,933.07,948.2,582.21,747.68,865.43,760.17,3,4,4,4,0,13,5,9,12,9,1,13
    "6",6,"F",17,"B",849.62,961.81,773.91,270.52,747.41,607.28,760.68,966.34,583.63,455.47,621.83,835.5,5,13,4,4,1,21,24,13,10,9,2,25
    "7",7,"F",18,"B",106.6,898.97,709.54,344.16,107.1,310.33,399.76,765.86,101.24,927.27,839.26,253.14,18,13,0,3,0,1,2,9,25,24,4,5
    "8",8,"M",2,"C",286.89,675.97,254.14,845.33,437.94,180.98,563.55,759.91,420.1,966.3,202.35,950.24,35,7,8,8,2,22,4,33,5,25,5,11
    "9",9,"F",9,"B",915.93,973.86,334.98,723.88,562.96,177.05,769.57,582.18,650.91,310.17,788.05,364.26,3,6,19,1,9,20,22,18,2,15,0,30
    "10",10,"F",10,"C",650.59,656.95,562.97,316.49,101.41,374.69,657.24,102.05,846.04,752.04,661.25,234.16,19,1,5,0,18,0,14,1,15,3,12,30
    ' 

    readr::read_csv(input_data, 
                    col_types = col_regex_type(regex = c("sid|procdos[1-5]$", "age|proc[1-5]$", "group"),
                                               type  = c("i", "d", "c")))


    Warning: 1 parsing failure.
    row col     expected       actual
     --  -- 13 col names 29 col names
       sid age group  proc1  proc2  proc3  proc4  proc5 procdos1 procdos2 procdos3 procdos4 procdos5
    1    1   8     C 763.83 441.60 400.08 708.04 138.69        4        0        5       14        2
    2    2  13     A 829.94 492.19 412.07 984.53 226.43        9       18        5       14       10
    3    3  17     C 449.29 133.69 458.63 783.58 294.74        5        7        2       22       30
    4    4   5     C 716.65 976.18 806.22 609.83 531.45       12       18        7       28       11
    5    5   8     A 103.55 488.57 135.04 864.71 277.67        3        4        4        4        0
    6    6  17     B 849.62 961.81 773.91 270.52 747.41        5       13        4        4        1
    7    7  18     B 106.60 898.97 709.54 344.16 107.10       18       13        0        3        0
    8    8   2     C 286.89 675.97 254.14 845.33 437.94       35        7        8        8        2
    9    9   9     B 915.93 973.86 334.98 723.88 562.96        3        6       19        1        9
    10  10  10     C 650.59 656.95 562.97 316.49 101.41       19        1        5        0       18 
    Warning messages:
    1: In col_euro_double() : Deprecated: please set locale
    2: In col_euro_double() : Deprecated: please set locale

**Comment by dewittpe** [comment]
This issue is similar to Issue #72

**Comment by kcandrews** [comment]
This looks promising. I just had `read_csv` read a column of double precision numbers as integers. The result was undesired truncation. I could use `select_cols` to force all columns to be doubles avoiding relying on whatever flawed heuristic `read_csv` is using.

**Comment by hadley** [comment]
@dewittpe do you have more compelling examples? I'm not sure why you even need the column specification in the example you provide - why don't the defaults work for you?

**Comment by hadley** [comment]
@kcandrews similarly, could you please provide a concrete example? Also I suspect the parsing problems you have experienced might be fixed in the dev version. Please try it out.

**Comment by dewittpe** [comment]
Hi @hadley,

One data set I'm working on right now has a little more than 60,000 rows and about 550 columns.  In some cases I need only six of the columns, in other cases I need about half of them.  Opting for the default column specifications results in more than 67,000 'problems.'  We all love messy data!

One issue I've run into is that the documentation for `col_type` within `read_` suggests that a named `list` where the names are a subset of the columns will return only those columns, however, that does not seem to be the behavior in `readr_0.1.1`.  The named list works well if it includes a `col_skip()` for each column that is not wanted.  

Two reasons for wanting to set types, illustrated in the following example, are:
1. default sets `proc1` to a double and `proc5` to a character.  It would be preferable for all the columns with similar information to have the same data type.  
2. I have many columns in my "real" data where the column is missing for the first several thousand rows and then becomes a character.  The need to set the column type is required to be set for 184 columns to resolve all the problems generated by taking the default col types.  

A feature allowing for returning a subset of columns while also setting the type would be a wonderful nice-to-have.

I've modified the example from my prior comment to show a couple issues:

 
```r
library(readr)  # version 0.1.1
library(dplyr)  # version 0.4.3
```

```r
# input_data2 is similar to the input_data from a prior comment.  However, in
# this version there are "E" codes in the proc5 and proc6
input_data2 <- 
'"sid","sex","age","group","proc1","proc2","proc3","proc4","proc5","proc6","proc7","proc8","proc9","proc10","proc11","proc12","procdos1","procdos2","procdos3","procdos4","procdos5","procdos6","procdos7","procdos8","procdos9","procdos10","procdos11","procdos12"
1,"F",8,"C",763.83,441.6,400.08,708.04,138.69,623.44,700.68,663.61,648.04,421.05,913.26,233.6,4,0,5,14,2,33,7,1,36,28,2,3
2,"F",13,"A",829.94,492.19,412.07,984.53,226.43,242.11,100.22,295.44,853.11,469.57,643.12,172.24,9,18,5,14,10,14,8,0,10,7,12,9
3,"M",17,"C",449.29,133.69,458.63,783.58,294.74,"E423.12",287.71,294.91,776.36,616.12,668.35,517.66,5,7,2,22,30,35,0,7,39,2,15,6
4,"F",5,"C",716.65,976.18,806.22,609.83,531.45,681.06,939.72,450.05,507.45,630.7,943.64,801.42,12,18,7,28,11,0,38,10,9,16,8,8
5,"F",8,"A",103.55,488.57,135.04,864.71,277.67,798.23,933.07,948.2,582.21,747.68,865.43,760.17,3,4,4,4,0,13,5,9,12,9,1,13
6,"F",17,"B",849.62,961.81,773.91,270.52,747.41,607.28,760.68,966.34,583.63,455.47,621.83,835.5,5,13,4,4,1,21,24,13,10,9,2,25
7,"F",18,"B",106.6,898.97,709.54,344.16,"E107.1",310.33,399.76,765.86,101.24,927.27,839.26,253.14,18,13,0,3,0,1,2,9,25,24,4,5
8,"M",2,"C",286.89,675.97,254.14,845.33,437.94,180.98,563.55,759.91,420.1,966.3,202.35,950.24,35,7,8,8,2,22,4,33,5,25,5,11
9,"F",9,"B",915.93,973.86,334.98,723.88,562.96,177.05,769.57,582.18,650.91,310.17,788.05,364.26,3,6,19,1,9,20,22,18,2,15,0,30
10,"F",10,"C",650.59,656.95,562.97,316.49,101.41,374.69,657.24,102.05,846.04,752.04,661.25,234.16,19,1,5,0,18,0,14,1,15,3,12,30
'

# The concise string errors if number of characters is not equal to number of
# columns
read_csv(input_data2, col_types = "i__i")
```

```
## Error in eval(expr, envir, enclos): You have 28 column names, but 2 columns
```

```r
# using a named list per documentation
# "must contain one '`collector`' for each column... read a subset of columns
# ... use a named list"
# expected output is a data frame with two columns for the subject id and
# procedure 1.  However, the output has *all* the columns.  The setting proc1 to
# a character works.  
named_list_read <- read_csv(input_data2, 
                            col_types = list(sid = col_integer(), proc1 = col_character()))
dim(named_list_read)
```

```
## [1] 10 28
```

```r
glimpse(named_list_read)
```

```
## Observations: 10
## Variables: 28
## $ sid       (int) 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
## $ sex       (chr) "F", "F", "M", "F", "F", "F", "F", "M", "F", "F"
## $ age       (int) 8, 13, 17, 5, 8, 17, 18, 2, 9, 10
## $ group     (chr) "C", "A", "C", "C", "A", "B", "B", "C", "B", "C"
## $ proc1     (chr) "763.83", "829.94", "449.29", "716.65", "103.55", "8...
## $ proc2     (dbl) 441.60, 492.19, 133.69, 976.18, 488.57, 961.81, 898....
## $ proc3     (dbl) 400.08, 412.07, 458.63, 806.22, 135.04, 773.91, 709....
## $ proc4     (dbl) 708.04, 984.53, 783.58, 609.83, 864.71, 270.52, 344....
## $ proc5     (chr) "138.69", "226.43", "294.74", "531.45", "277.67", "7...
## $ proc6     (chr) "623.44", "242.11", "E423.12", "681.06", "798.23", "...
## $ proc7     (dbl) 700.68, 100.22, 287.71, 939.72, 933.07, 760.68, 399....
## $ proc8     (dbl) 663.61, 295.44, 294.91, 450.05, 948.20, 966.34, 765....
## $ proc9     (dbl) 648.04, 853.11, 776.36, 507.45, 582.21, 583.63, 101....
## $ proc10    (dbl) 421.05, 469.57, 616.12, 630.70, 747.68, 455.47, 927....
## $ proc11    (dbl) 913.26, 643.12, 668.35, 943.64, 865.43, 621.83, 839....
## $ proc12    (dbl) 233.60, 172.24, 517.66, 801.42, 760.17, 835.50, 253....
## $ procdos1  (int) 4, 9, 5, 12, 3, 5, 18, 35, 3, 19
## $ procdos2  (int) 0, 18, 7, 18, 4, 13, 13, 7, 6, 1
## $ procdos3  (int) 5, 5, 2, 7, 4, 4, 0, 8, 19, 5
## $ procdos4  (int) 14, 14, 22, 28, 4, 4, 3, 8, 1, 0
## $ procdos5  (int) 2, 10, 30, 11, 0, 1, 0, 2, 9, 18
## $ procdos6  (int) 33, 14, 35, 0, 13, 21, 1, 22, 20, 0
## $ procdos7  (int) 7, 8, 0, 38, 5, 24, 2, 4, 22, 14
## $ procdos8  (int) 1, 0, 7, 10, 9, 13, 9, 33, 18, 1
## $ procdos9  (int) 36, 10, 39, 9, 12, 10, 25, 5, 2, 15
## $ procdos10 (int) 28, 7, 2, 16, 9, 9, 24, 25, 15, 3
## $ procdos11 (int) 2, 12, 15, 8, 1, 2, 4, 5, 0, 12
## $ procdos12 (int) 3, 9, 6, 8, 13, 25, 5, 11, 30, 30
```

```r
# get a subset of columns it appears that I need to construct a list with
# col_skip() for the unwanted columns.  Let's read in the sid and first five
# procedures as characters.  Construct a list of col_skip() for each column and
# then set the wanted types
ct        <- replicate(ncol(named_list_read), col_skip(), simplify = FALSE)
names(ct) <- names(named_list_read)

# sid is an integer and the first five procs are characters.  The common data
# type for all the procs will be helpful.
ct$sid <- col_integer()
for(i in which(grepl("^proc[1-5]$", names(ct)))) { 
  ct[[i]] <- col_character()
}

named_list_read2 <- read_csv(input_data2, col_types = ct)
dim(named_list_read2)
```

```
## [1] 10  6
```

```r
glimpse(named_list_read2)
```

```
## Observations: 10
## Variables: 6
## $ sid   (int) 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
## $ proc1 (chr) "763.83", "829.94", "449.29", "716.65", "103.55", "849.6...
## $ proc2 (chr) "441.6", "492.19", "133.69", "976.18", "488.57", "961.81...
## $ proc3 (chr) "400.08", "412.07", "458.63", "806.22", "135.04", "773.9...
## $ proc4 (chr) "708.04", "984.53", "783.58", "609.83", "864.71", "270.5...
## $ proc5 (chr) "138.69", "226.43", "294.74", "531.45", "277.67", "747.4...
```

**Comment by hadley** [comment]
@dewittpe that's helpful, thanks. I think I'd prefer a specification like:

```R
col_types(
  starts_with("proc") ~ col_character(),
  starts_with("procd") ~ col_integer(),
)
```

You'd be able to set the default column type with something like:

```R
col_types(
  ~ col_character(),
  starts_with("procd") ~ col_integer(),
)
```

you could of course default to `col_skip()` if you only wanted to load specific columns.

**Comment by eibanez** [comment]
Would it also be possible to allow the default column type to be guessed by `readr` (i.e., the default behavior)? This would allow you to focus on the problematic columns.

It would look like this:

```col_types(
  ~ col_guess(),
  starts_with("procd") ~ col_integer(),
)```

**Comment by antoine-lizee** [comment]
I totally +1 this, and especially the defaut spec. Related to https://github.com/hadley/readr/issues/382

**Comment by hadley** [comment]
We'll handle this eventually as part of the colspec package. The goal is to convert the colspec data structure to a tibble with one row per column. Then you'll be able to do arbitrary manipulations like this.

**Comment by randomgambit** [comment]
also wondering. I was actually trying to see how I can tell `dplyr` to

- treat all columns are numeric
- treat some specific columns as dates
- treat a subset of the columns (identified by a regex) as character

I can easily do the first two, for the last one I dont know
