### ISSUE TITLE
Binary data frame file format

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/readr#29]
Just ideas about how to store a data frame in a custom binary file. related to #28. 

We need:
- the number of columns (space for an 32 bits `int`) 
- the names of the columns (null terminated strings) 
- the R types of the columns (INTSXP, REALSXP, ...), perhaps distinguishing factors, perhaps handling attributes too (times and dates). 
- data for each column. Data should include space for header of the SEXP and space for allocator so that we can do #28. 

For STRSXP, I guess we'll have to rematerialize each CHARSXP so we'd have to come up with some smart way of serializing / deserializing the information

**Comment by joehl** [comment]
A binary data.frame file format where each column is represented as a contiguous file is already existing: ffdf in package ff does exactly this. The meta-data like column names, factor-levels etc. are not stored in the file(s) but in an R-object which points to the file(s). The meta-data can be saved in the usual way with save.image and loaded in a new session, provided automatic file removal has been switched-off appropriately. What ffdf doesnot support are strings (but factors). Furthermore factors with few levels and integers with few values can be represented with less bytes than 4 bytes (down to 2 bits), logicals with 2 bits, booleans with 1 bit. Current restriction: no long vectors, i.e. 2^31.
