### ISSUE TITLE
Support multibyte encodings (e.g. UTF-16LE)

### ISSUE THREAD

**Issue by bilydr** [tidyverse/readr#306]
Hi, I am trying to read in a file with UTF-16LE encoding 

which can be done with base package codes  

``` R
df <- read.delim(file1, stringsAsFactors = FALSE, fileEncoding = 'UTF-16LE')
```

but when I try to use readr to do the same 

``` R
df <- read_tsv(file1, locale = locale(encoding = 'UTF-16LE'))
```

I got the error **Error: Incomplete multibyte sequence**

Can you please help fix it? Thanks for your advice!

**Comment by hadley** [comment]
Can you please provide a reproducible example?

**Comment by bilydr** [comment]
Hi, please see the data file and codes in folder below

https://www.dropbox.com/sh/6vw6irfe0m3f5bm/AACmdssmln4iZjxkpzbE1MEaa?dl=0

thanks!

Longyi Bi

bilongyi@gmail.com
Mobile: +33-668655292

**Comment by bilydr** [comment]
and the screen shot
![screenshot](https://cloud.githubusercontent.com/assets/8634933/10937958/eef76f12-82f6-11e5-8eb6-db0c8986f547.PNG)

**Comment by bilydr** [comment]
Hi any follow-up on this issue? thanks!

**Comment by multiphrenic** [comment]
having a similar problem. even when I try loading the file using a file connection with explicit encoding, the read fails:
data.table(read_csv(file("data/Parking_Tags_data_2008.csv", encoding="UCS-2LE"))) for example, reads garbage, while read.csv works fine.

**Comment by zeehio** [comment]
I simplified the example so it only needs R to work (no external files required).


    tmp_file_name <- tempfile()
    # This is the Byte Order Mark:
    rawbom <- raw(2)
    rawbom[1] <- as.raw(255)
    rawbom[2] <- as.raw(254)
    # This is the text. 
    text <- "1\t2\n"
    # Converted to UTF-16LE
    text_utf16 <- iconv(text,from="UTF-8",to="UTF-16LE", toRaw = TRUE)
    # Write the BOM and the text to a file
    fd <- file(tmp_file_name, "wb")
    writeBin(rawbom, fd)
    writeBin(text_utf16[[1]], fd)
    close(fd)
    df_test <- data.frame(V1=1, V2=2)
    works <- read.delim(tmp_file_name, header=FALSE, fileEncoding = "UTF-16LE")
    assertthat::are_equal(works[1,], df)

    fails <- readr::read_table(tmp_file_name, col_names=FALSE, locale=locale(encoding="UTF-16LE"))
    assertthat::are_equal(fails, df_test)

**Comment by zeehio** [comment]
Narrowing down this issue. I suspect the tokenizer in readr does not account for multibyte line feeds.

```r
check_encodings <- function(text, encoding) {
  text_utf16 <- iconv(text,from="UTF-8",to=encoding, toRaw = TRUE)[[1]]
  ds <- readr:::datasource_string(text, skip=0)
  lines <- readr:::read_lines_(ds, locale_ = locale())
  ds_raw <- readr:::datasource_raw(text_utf16, skip=0, comment="")
  lines_raw <- readr:::read_lines_(ds_raw, locale_ = locale(encoding=encoding))
  assertthat::are_equal(lines, lines_raw)
}

check_encodings("3\t2", "UTF-16LE")  # works
check_encodings("3\t2\n", "UTF-16LE")  # fails:  Error: incomplete multibyte sequence

check_encodings("3\t2", "UTF-16BE") # works
check_encodings("3\t2\n", "UTF-16BE")   # fails:  Error: incomplete multibyte sequence

```


@hadley, This issue may require pushing the locale information into the tokenizer (at least the file encoding information to have the right encoding for '\n'). I don't know if that is fine for you or if you wanted the tokenizer to be locale-independent. This is assuming that my suspicions about not considering multibyte line feeds are correct.... I feel I can do a small C++ patch, but if I am right then several parts need fixing in the tokenizer. Could you please take a look into this issue and give some advice?

**Comment by hadley** [comment]
@zeehio Yeah, this is a big issue that will need some thought. In general, readr currently assumes that it can read byte-by-byte, and anything else will require quite of lot of work/thought.

**Comment by jvschoen** [comment]
Is this issue fixed? I'm still having issues pulling in tsv files.

**Comment by batpigandme** [comment]
@jvschoen, when it's fixed the issue will be closed.

**Comment by jvschoen** [comment]
Is there a good workaround you can suggest or do I need to open in excel and save as tsv?

**Comment by zeehio** [comment]
@jvschoen you always can use `read.table`, using 
`sep = "\t"` and the `fileEncoding` argument. There are several base R functions that are good enough for the task.

**Comment by jvschoen** [comment]
Thanks for the workaround. That worked!

**Comment by dhofstetter** [comment]
I'm currently faced with this issue as well.

Are there any plans to fix this issue? Really pitty not beeing able to use my beloved readr methods for the current project though :-(

BR Daniel

**Comment by espinielli** [comment]
If of help I could read UTF-16 encoded CSV with

```r
read.delim("data-raw/swiss_2020-06-01.csv",
           sep = ";",
           stringsAsFactors = FALSE,
           fileEncoding = 'UTF-16') %>% 
  as_tibble()
```

`readr::read_csv2` and `data.table::fread` did not work.

**Comment by anadiedrichs** [comment]
I had the same problem. I could read UTF-16LE encoded file with the `read.csv` function.

This dataset could be a great example, link: https://sisa.msal.gov.ar/datos/descargas/covid-19/files/Covid19Casos.csv

Source: http://datos.salud.gob.ar/dataset/covid-19-casos-registrados-en-la-republica-argentina

The dataset size is around 300 MB and contains information about COVID19 cases in Argentina.

Output of the file command in Linux.

<pre>
$ file Covid19Casos.csv 

Covid19Casos.csv: Little-endian UTF-16 Unicode text, with very long lines, with CRLF line terminators

</pre>

Output of `guess_encoding function`

<pre>
library(readr)

guess_encoding("Covid19Casos.csv")

# A tibble: 3 x 2
  encoding   confidence
  <chr>           <dbl>
1 UTF-16LE         1   
2 ISO-8859-1       0.68
3 ISO-8859-2       0.48
</pre>

The function `read.csv` worked in this case.

<pre>
dataset <- read.csv("Covid19Casos.csv", fileEncoding="UTF-16LE")

</pre>

**Comment by jimhester** [comment]
Closed by https://github.com/r-lib/vroom/commit/7d54cdab790188933e15248f41cd01ca9867b043
