### ISSUE TITLE
Writing compressed files

### ISSUE THREAD

**Issue by dhimmel** [tidyverse/readr#348]
Is there currently any way to write to a compressed text file?

Ideally, compression would be automatically detected from the `path` (ending in `.gz`, `.bz2`, or `.xz`) argument of `readr::write_tsv()`.

**Comment by holgerbrandl** [comment]
+1

**Comment by hadley** [comment]
The best way to do this is probably to use the C-level connection API (which I think will require a dependency on R 3.3.0), and then create the connection in R code.

**Comment by ivan-krukov** [comment]
What does `ready` label imply here? Next release?

**Comment by mbojan** [comment]
+1

IMHO, it would be ideal for `path` to accept R connection (like `write.csv` does), including `gzfile()` or `bzfile()`.

**Comment by wbzyl** [comment]
:+1:

It would be nice to have both functionalities:
```r
write_csv(df, bzfile("x.csv.bz2"))
```
and
```r
read_csv(bzfile("x.csv.bz2"))
```
instead of replacing the former with:
```r
write.csv(df, bzfile("x.csv.bz2"), row.names = F)
```
