### ISSUE TITLE
Full width spaces are not removed by read_csv() function with trim_ws = TRUE

### ISSUE THREAD

**Issue by kanaugust** [tidyverse/readr#397]
When we have full width spaces (e.g. with Japanese)  in the data these spaces are not getting removed with read_csv() function even when we set 'trim_ws' argument to TRUE, which I believe it's the default behavior but just in case I'm explicitly setting it to TRUE. 

```
library(readr)
df_with_space <- read_csv(
"ID, CURRENT_COUNT
1, 11816
2, 8001　　
3, 6129　
4, 7303　
5, 　7797
6, 　1899　
7, 　　6915　
8, 6064
9, 
10, 
11, 4986.54", trim_ws = TRUE)

> df_with_space
Source: local data frame [11 x 2]

      ID CURRENT_COUNT
   (int)         (chr)
1      1         11816
2      2      8001　　
3      3        6129　
4      4        7303　
5      5        　7797
6      6      　1899　
7      7    　　6915　
8      8          6064
9      9            NA
10    10            NA
11    11       4986.54
```

Therefore, type_conver() function still can't appropriately convert CURRENT_COUNT column to be numeric or double. 

```
df_with_space %>% type_convert()

Source: local data frame [11 x 2]

      ID CURRENT_COUNT
   (int)         (chr)
1      1         11816
2      2      8001　　
3      3        6129　
4      4        7303　
5      5        　7797
6      6      　1899　
7      7    　　6915　
8      8          6064
9      9            NA
10    10            NA
11    11       4986.54
```

Just as an example though, str_trim() function from 'stringr' package does remove those full width spaces like below, therefore type_convert() function appropriately convert CURRENT_COUNT column to be double type like below. 

```
library(dplyr)
library(stringr)

df_with_space %>% 
  mutate(CURRENT_COUNT2 = str_trim(CURRENT_COUNT)) %>%
  type_convert()

Source: local data frame [11 x 3]

      ID CURRENT_COUNT CURRENT_COUNT2
   (int)         (chr)          (dbl)
1      1         11816       11816.00
2      2      8001　　        8001.00
3      3        6129　        6129.00
4      4        7303　        7303.00
5      5        　7797        7797.00
6      6      　1899　        1899.00
7      7    　　6915　        6915.00
8      8          6064        6064.00
9      9            NA             NA
10    10            NA             NA
11    11       4986.54        4986.54
```

It would be nice if read_delim/csv function family supports trimming the spaces including full width ones.

**Comment by hadley** [comment]
This should be relatively straightforward to fix - we should be trimming any unicode whitespace not just spaces.

**Comment by hadley** [comment]
Special case of #306

**Comment by mirkhosro** [comment]
This also seems to be the case for trailing tab (\t) characters, even in plain ASCII files.
They don't get removed when `trim_ws=TRUE`, while the get removed by the built-in `read.csv` function when `strip.white=TRUE`.

**Comment by hadley** [comment]
@mirkhosro that's likely to be a different problem. Can you please file a new issue including a reprex demonstrating the basic problem?

**Comment by mirkhosro** [comment]
Sure, thank you @hadley . I just created a new issue here:
https://github.com/tidyverse/readr/issues/767

**Comment by jimhester** [comment]
Thank you for opening the issue.

While I agree this could be useful, dealing with non-ascii spaces would incur extra performance cost for all files and because it is fairly rare I think it best for us to omit this feature.

I have tried to better document the existing behavior.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:
