### ISSUE TITLE
Percent parser

### ISSUE THREAD

**Issue by hadley** [tidyverse/readr#449]
e.g

``` R
parse_percent("20%")
#> [1] 0.20
```

**Comment by huftis** [comment]
Quite a few European languages have a space between the number and the percent sign, e.g. "20 %". It would be nice if this was supported. (And localised versions of Excel outputs this space when saving percentage values in CSV format, so this format will be commonly found ‘in the wild’.)

**Comment by gvwilson** [comment]
:+1: for this feature

**Comment by jimhester** [comment]
A workaround is to parse percents by using the flexible number parser, but then you need to divide by 100.

``` r
readr::parse_number("20%") / 100
#> [1] 0.2
```

<sup>Created on 2019-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
