### ISSUE TITLE
It seems "readr" cannot parse "%d %b" (dates without year)

### ISSUE THREAD

**Issue by erwinia** [tidyverse/readr#508]
I think a previous version could handle this (?) Now, parse_datetime("1 Jan", "%d %b") results in "NA". Any possibility to have it parse the current year (or any year?). Thank you!

(Your packages are AWESOME)

**Comment by erwinia** [comment]
I modified my code to use lubridate  = parse_date_time("01-Jan", "dm") and got the "expected" result =  "2016-01-01 UTC"

But I'm pretty sure my previous code with parse_datetime worked in a previous version of readr (?)

**Comment by hadley** [comment]
I think filling in with the current year is dangerous because it means that running the same code on different times will return different results.  So fixing this is out of scope for readr - I'd recommend being explicit by pasting on the year yourself.
