### ISSUE TITLE
Support for True/False in col_logical

### ISSUE THREAD

**Issue by rgknight** [tidyverse/readr#514]
I can give this a try, following the example of https://github.com/hadley/readr/pull/406/commits/90041386e592575c083f909a890fd6f74f01ba32

Unless this is possible already?

**Comment by hadley** [comment]
Maybe we should just make `col_logical()` case insensitive?

**Comment by jimhester** [comment]
Now fixed (https://github.com/tidyverse/readr/commit/94b50da31104b65368a43d2cb632e9f027b4c651)
