### ISSUE TITLE
producing a column specification for type_convert()

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readr#517]
I'm learning the hard way that `readr::type_convert()` no longer takes column specifications as a character string, like `cccnnn`. Apparently I do this in googlesheets examples, tests, etc. Is there a specific reason to require the long form in `type_convert()`? If I have to workaround this myself, is there a better way than what I've got here? This looks a bit nutty.

``` r
x <- "cccnnn"
do.call(readr::cols, as.list(strsplit(x, "")[[1]]))
#> cols(
#>    = col_character(),
#>    = col_character(),
#>    = col_character(),
#>    = col_number(),
#>    = col_number(),
#>    = col_number()
#> )
```

**Comment by hadley** [comment]
Likely just a mistake

**Comment by jimhester** [comment]
This was changed in response to https://github.com/tidyverse/readr/issues/369, where we explicitly disabled support for character vectors in `type_convert()`. There is even a blurb in `?type_convert` (including a typo)

> Unlike other functions ‘type_convert()’ does not allow
  character specificatinos of ‘col_types’.

@jennybc Probably the easiest way to do what you want is to use `as.col_spec()`, but it is unexported :(.

``` r
readr::as.col_spec("cccnnn")
#> Error: 'as.col_spec' is not an exported object from 'namespace:readr'
readr:::as.col_spec("cccnnn")
#> cols(
#>    = col_character(),
#>    = col_character(),
#>    = col_character(),
#>    = col_number(),
#>    = col_number(),
#>    = col_number()
#> )
```

**Comment by hadley** [comment]
@jennybc what do you think we should do in this scenario?

```R
library(tidyverse)
df <- tibble(x = 1:2, y = 1:2)
type_convert(df, col_types = "dd")
```

**Comment by jennybc** [comment]
I would expect `x` and `y` to be double.

**Comment by hadley** [comment]
What about `type_convert(df, col_types = "cc")` ?

**Comment by jennybc** [comment]
Then character?

**Comment by hadley** [comment]
Hmmm, that's considerably expanding the scope — currently it only operates on character columns.
