### ISSUE TITLE
read_table() can wrongly read numbers (silently)

### ISSUE THREAD

**Issue by aphalo** [tidyverse/readr#518]
`read_table()` miss reads numbers in the first column when there is white space at the start of enough lines at the top of the file.

Of the attached files the shorter `readr-read-table.txt` is correctly read, but the second and longer file `readr-read-table-2.txt` is incorrectly read, with 1000 interpreted as 0, 1001 as 1, etc.

```
 readr::read_table("readr-read-table.txt", col_types = "dd")
 readr::read_table("readr-read-table-2.txt", col_types = "dd")
```

[readr-read-table.txt](https://github.com/hadley/readr/files/466869/readr-read-table.txt)
[readr-read-table-2.txt](https://github.com/hadley/readr/files/466870/readr-read-table-2.txt)

I noticed a problem with some of my files some months ago, but I did not find the cause of the problem until yesterday. `utils::read.table()` has no problems with either of these files.

readr installed from this repository minutes ago. 1.0.0.9000
R 3.3.1 Windows 10 x64.

**Comment by Yeedle** [comment]
Here's another similar [complain](http://stackoverflow.com/questions/40307042/reading-text-file-read-table-versus-read-table) citing the same issue. I'm not sure it's a bug though. By design, the tokenizer [reads only the first 100 lines](https://github.com/tidyverse/readr/blob/37d6eda5b2e52707bfa6ea2db8d52e0209796615/src/TokenizerFwf.cpp#L16) to determine the structure of the file. Probably because of efficiency, though it wouldn't hurt to mention it in the documentation.

**Comment by aphalo** [comment]
An option to remove white space at the start of lines before parsing could solve the problem, I think. In many data sets where the first column is an ordered index quantity like wavelength it is common that the numbers are right justified. This may happen even in files where the columns are not all aligned, which prevents the use of a fixed format.

**Comment by Yeedle** [comment]
The same issue occurs with both right-aligned and left-aligned columns. See the SO question I linked to above. There, the issue occurred to a left-justified column.

**Comment by hadley** [comment]
Yes, `read_table()` is potentially unreliable because it is magic. If you favour correctness over ease-of-use, you should use `read_fwf()`.

That said, `read_table()` should print out the spec that it uses (a la `col_types`) so you can tweak afterwards.
