### ISSUE TITLE
readr 1.0.0: read_csv2 silently drops decimals

### ISSUE THREAD

**Issue by jules32** [tidyverse/readr#521]
Hi there,

I have a data file that has mixed European-US conventions; it is semicolon separated (;) but the numeric values use periods (.) as decimals. When I use `read_csv2`, it silently drops the periods instead of treating them like decimals; it is probably expecting commas (,) as decimals instead.

It's probably not that common to have both formats within the same csv file, or maybe there is already a way to handle this?

Thanks!

Example:

let's say this is my `sample.csv`:

```
country;area_km2
Sweden;6739.5362
Denmark;15300.69996
Germany;140.98877
```

```r
readr::read_csv2('sample.csv')
# A tibble: 3 × 2
  country   area_km2
    <chr>      <dbl>
1  Sweden   67395362
2 Denmark 1530069996
3 Germany   14098877
```

**Comment by jplynch77** [comment]
I think you can just use the `read_delim` function with the delim option set to semi-colon. So for `sample.csv` you could do `read_delim('sample.csv', delim = ';')`. This seems to solve the problem of dropping the periods.

```R
read_delim('sample.csv', delim = ';')
Parsed with column specification:
cols(
  country = col_character(),
  area_km2 = col_double()
)
# A tibble: 3 × 2
  country   area_km2
    <chr>      <dbl>
1  Sweden  6739.5362
2 Denmark 15300.7000
3 Germany   140.9888
```
