### ISSUE TITLE
Print column specification whenever there is guessing?

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readr#522]
I really like the new printing of column specification. I notice that, if you provide an explicit specification for even a single column, the guessed specifications for the other p - 1 columns no longer get printed to screen. I wonder if it's a better idea to print the specification whenever there is guessing? Or to at least print the ones that were determined via guessing?

``` r
library(readr)
write_csv(head(mpg), "mpg.csv")

df <- read_csv("mpg.csv")
#> Parsed with column specification:
#> cols(
#>   manufacturer = col_character(),
#>   model = col_character(),
#>   displ = col_double(),
#>   year = col_integer(),
#>   cyl = col_integer(),
#>   trans = col_character(),
#>   drv = col_character(),
#>   cty = col_integer(),
#>   hwy = col_integer(),
#>   fl = col_character(),
#>   class = col_character()
#> )

df <- read_csv("mpg.csv", col_types = cols(cyl = col_number()))
```

Basically I wish this last `read_csv()` still printed output similar to the first.

**Comment by jennybc** [comment]
In the parsing section of [R for Data Science](http://r4ds.had.co.nz/data-import.html#parsing-a-file) @hadley writes:

> I highly recommend always supplying col_types, building up from the print-out provided by readr. This ensures that you have a consistent and reproducible data import script. If you rely on the default guesses and your data changes, readr will continue to read it in. 

If you think about a realistic workflow for achieving this worthy goal, I think it means it **would** be helpful to keep printing the col spec until there is no guessing.

**Comment by hadley** [comment]
If we do this, we'll also need some way to suppress output of guesses - currently I recommend doing `col_types = cols()`

**Comment by jimhester** [comment]
I don't know about this, you can always use `spec_csv()` to explicitly capture and print the specification if you want to do it iteratively.

**Comment by estroger34** [comment]
I'd like to support OPs suggestion. When reading files with few non-numeric and many numeric columns, I find it convenient to check the few printed non-default col specs for correct parsing (with .default = col_double()) without any additional step (like using spec_csv and condensing its output to suppress the many col_double lines).

Often, however, I need to specify one coltype (e.g. timestamp = col_datetime with non-standard date/time format) and it would be great to still be able to quickly check the guessing of all the other columns.

**Comment by jimhester** [comment]
After #1172 you can now force always printing of the spec with `show_col_types = TRUE`. While this is not exactly what was proposed I think it is close enough to close this issue.
