### ISSUE TITLE
write_excel_csv enhancements

### ISSUE THREAD

**Issue by dpprdan** [tidyverse/readr#523]
If I see correctly, it is not possible to specify `write_csv()` to use a semi-colon as separator between values and a comma as decimal separator. (Well, technically it is possible to add the semi-colong with `write_delim()`, but not the comma as decimal mark).

So, would it be possbible to add a `decimal_mark` option (and potentially a `grouping_mark` or even a full `locale` option) to `write_delim()` and add a `write_csv2()` wrapper function equivalent to `read_csv2()`?

**Comment by hadley** [comment]
Why do you need this? Is there some program that doesn't accept "regular" csvs?

**Comment by dapper2dan** [comment]
No, from a strict technical standpoint, I have not come across a program that does not _accept_ "regular" CSVs. You just might have to jump through some hoops. 

So why would I need this? 

Ideally I would like to export the CSVs in the same format that I imported them in (a.k.a. consistency). (This would include all `locale` options. `decimal_mark` was just the first I noticed.) That way my collaborators and I always know which format to expect. 

Said differently: This is how my Excel 2010 DE opens 
```
df <- read_csv(readr_example("mtcars.csv"))
write_csv(df, "output/df_.csv")
```
![df_write_csv](https://cloud.githubusercontent.com/assets/1423562/21452201/9ada4322-c905-11e6-81e1-2009248ef829.png)

vs.
```
write.csv2(df, "output/df.2.csv", row.names = FALSE)
```
![df_write csv2](https://cloud.githubusercontent.com/assets/1423562/21452211/b090b6ba-c905-11e6-9ffe-1c105a367476.png)


So IMHO this is equivalent to `write_excel_csv`. Excel accepts CSVs from `write_csv`, it's just handles UTF-8 encoded files better with a BOM.

**Comment by hadley** [comment]
It looks like we can do this without adding another writer by using `sep=,` as the first line of the csv: http://superuser.com/questions/407082/easiest-way-to-open-csv-with-commas-in-excel/730509#730509

And we should also throw an error if the first column name is called ID: https://support.microsoft.com/en-us/kb/323626

**Comment by dapper2dan** [comment]
Unfortunately, adding `sep=,` like this (if that's what you mean):

![sep](https://cloud.githubusercontent.com/assets/1423562/21646258/bbd33b26-d295-11e6-81b6-f2e67852ab26.png)

does not really cut it:

![sep_excel](https://cloud.githubusercontent.com/assets/1423562/21646270/c8aba09a-d295-11e6-852a-e5d24415c7c6.png)

Even though `sep=,` wouldn't hurt (well, in this case it does, actually), it is not the real problem, because one could always use `write_delim`. The real problem here is `decimal_mark`. 

BTW, I just mentioned Excel as an example, but the problem extents to programs beyond Excel (e.g. what I said above regarding consistency).
 
And did I mention that a `locale` would be nice? Or is that just not possble/too much work/out of the question for some other reason?

**Comment by diraol** [comment]
Regarding this discussion, here in Brazil the standard definition is to use comma as decimal separator. Because of that, we usually need to use the semi-colon as column separator. There are hundreds of public datasets (open data) that are delivered with this patterns.
So it would be really nice to consider giving the users the options to choose between these two standards, and I think that keep the analogy between read.csv/read.csv2 and write.csv/write.csv2 would be really nice and is a really good enhancement.

**Comment by hadley** [comment]
Ok, looks like the easiest way will just be to add `write_csv2` and `write_excel_csv2`

**Comment by mgagliol** [comment]
Same situation as @diraol describes in French speaking countries: we cannot just expect that everyone around us adapts to what is considered "regular" in other continents.. IMHO a way to solve this and all other possible future compatibility issues would be to let write_delim and other write_* functions to also take a locale argument, exactly as the read_* functions do. One of the things I still appreciate in read.table/write.table - regardless of the poor interface -  is that they can adapt to pretty much any format for reading, but also writing data, which makes collaborations possible with anyone using whatever software.. This said, thank you for making R tidyer ;)

**Comment by cderv** [comment]
FYI it is work in progress in #753 for a new `write_excel_csv2` function with semicolon separator and comma as decimal separator.

**Comment by jimhester** [comment]
Fixed by https://github.com/tidyverse/readr/pull/753

**Comment by cderv** [comment]
Thanks for the `write_excel_csv2` function. The above discussion mentionned also a `write_csv2` function. This issue was closed, so I am wondering : Is there any reason not to have an `write_csv2` function to complement `write_csv` function ? 

We have now `write_excel_csv` and `write_excel_csv2`, `read_csv` and `read_csv2`, but just a `write_csv`.

If it is just a miss, I can PR something if you want.

**Comment by dpprdan** [comment]
I think this is indeed an oversight. At least I don't see a way to write a csv with `delim = ";"`, `decimal.mark = ","` and `bom = FALSE`.

**Comment by cderv** [comment]
I am with @diraol formats that they have in brazil. In France,  we also use csv files with comma as decimal and semicolon as separator. In R, there is `write.csv2` function to write a csv like this (with no BOM) but not in readr.  I was just wondering why there are pairs of functions for other but not this one. 
Seems not difficult to offer the option.

``` r
library(readr)
tmp1 <- tempfile()
write.csv2(iris, file = tmp1)
# semi-colon separator and comma decimal
read_lines(tmp1, n_max = 3)
#> [1] "\"\";\"Sepal.Length\";\"Sepal.Width\";\"Petal.Length\";\"Petal.Width\";\"Species\""
#> [2] "\"1\";5,1;3,5;1,4;0,2;\"setosa\""                                                  
#> [3] "\"2\";4,9;3;1,4;0,2;\"setosa\""
# can be read with csv2
read_csv2(tmp1)
#> Using ',' as decimal and '.' as grouping mark. Use read_delim() for more control.
#> Warning: Missing column names filled in: 'X1' [1]
#> Parsed with column specification:
#> cols(
#>   X1 = col_double(),
#>   Sepal.Length = col_double(),
#>   Sepal.Width = col_double(),
#>   Petal.Length = col_double(),
#>   Petal.Width = col_double(),
#>   Species = col_character()
#> )
#> # A tibble: 150 x 6
#>       X1 Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>    <dbl>        <dbl>       <dbl>        <dbl>       <dbl> <chr>  
#>  1  1.00         5.10        3.50         1.40       0.200 setosa 
#>  2  2.00         4.90        3.00         1.40       0.200 setosa 
#>  3  3.00         4.70        3.20         1.30       0.200 setosa 
#>  4  4.00         4.60        3.10         1.50       0.200 setosa 
#>  5  5.00         5.00        3.60         1.40       0.200 setosa 
#>  6  6.00         5.40        3.90         1.70       0.400 setosa 
#>  7  7.00         4.60        3.40         1.40       0.300 setosa 
#>  8  8.00         5.00        3.40         1.50       0.200 setosa 
#>  9  9.00         4.40        2.90         1.40       0.200 setosa 
#> 10 10.0          4.90        3.10         1.50       0.100 setosa 
#> # ... with 140 more rows
```

A `write_csv2` could be simple to have for Western Europe Locales.

``` r
# same as write_csv but ; as separator and , as decimal
write_csv2 <- function(x, path, na = "NA", append = FALSE, col_names = !append) {
  stopifnot(is.data.frame(x))
  numeric_cols <- vapply(x, is.numeric, logical(1))
  x[numeric_cols] <- lapply(x[numeric_cols], format, decimal.mark = ",")
  write_delim(x, path, delim = ";", na = na, append = append, col_names = col_names)
}
tmp2 <- tempfile()
# equivalent in readr of write.csv2
write_csv2(iris, tmp2)
# semi-colon separator and comma decimal
read_lines(tmp2, n_max = 3)
#> [1] "Sepal.Length;Sepal.Width;Petal.Length;Petal.Width;Species"
#> [2] "5,1;3,5;1,4;0,2;setosa"                                   
#> [3] "4,9;3,0;1,4;0,2;setosa"
# can be read with read_csv2
read_csv2(tmp2)
#> Using ',' as decimal and '.' as grouping mark. Use read_delim() for more control.
#> Parsed with column specification:
#> cols(
#>   Sepal.Length = col_double(),
#>   Sepal.Width = col_double(),
#>   Petal.Length = col_double(),
#>   Petal.Width = col_double(),
#>   Species = col_character()
#> )
#> # A tibble: 150 x 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl> <chr>  
#>  1         5.10        3.50         1.40       0.200 setosa 
#>  2         4.90        3.00         1.40       0.200 setosa 
#>  3         4.70        3.20         1.30       0.200 setosa 
#>  4         4.60        3.10         1.50       0.200 setosa 
#>  5         5.00        3.60         1.40       0.200 setosa 
#>  6         5.40        3.90         1.70       0.400 setosa 
#>  7         4.60        3.40         1.40       0.300 setosa 
#>  8         5.00        3.40         1.50       0.200 setosa 
#>  9         4.40        2.90         1.40       0.200 setosa 
#> 10         4.90        3.10         1.50       0.100 setosa 
#> # ... with 140 more rows

# clean exit
unlink(c(tmp1, tmp2))
```
Created on 2018-02-08 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

A `write_csv2` function is more natural to write than `write_excel_csv2` when you don’t need particularly
excel behaviour. It is like `write_csv` and `write_excel_csv`.  
Does this seems off ? I always wonder why there is not this function when exporting files to csv. It would complete the sets of  `write_*` functions

**Comment by VincentGuyader** [comment]
For homogeneity reasons it might be useful to have a `write_csv2` function. (here in france  we usualy use `read.csv2` and `write_csv2`, when I present {readr} in class one of the questions is "where is write_csv2" :)

**Comment by dpprdan** [comment]
@cderv Looks fine to me so far. @jimhester What do think?
