### ISSUE TITLE
Second chunk has 0 observations when reading in data in chunks with connections

### ISSUE THREAD

**Issue by Ballings** [tidyverse/readr#524]
# The problem is that when I read in data through a connection in batches, the second
# batch will not have a header anymore, but I do want to have the column names that were
# obtained in the first batch (for processing). So in the first batch I set col_names=TRUE, I
# extract the column names of the result and store them in a character vector called colnames,
# and use col_names=colnames in the second batch. The second batch then comes out empty.
# A similar procedure does work with read.table.
# Am I missing anything?
# MAKE SOME TOY DATA AND SET read_delim PARAMETERS

n <- 1000
write.table(data.frame(a=1:n,b=1:n,c=runif(n),response=sample(c(0,1),n,TRUE)),
            file="test.csv",
            row.names=FALSE, sep=",")

colClasses <- cols(a = col_integer(),
                   b=col_integer(),
                   c=col_double(),
                   response=col_factor(levels=c(0,1)))
batchsize=100
sep= ","
quote="\""
# PROCESS DATA IN CHUNKS

closeAllConnections()
fileconnection <- file(paste0(getwd(),"/test.csv"))
open(fileconnection, "rb")
# READ IN FIRST BATCH:

data <- read_delim(file=fileconnection,
                   delim=sep,
                   col_names=TRUE,
                   col_types=colClasses,
                   n_max=batchsize)
data <- data.frame(data)
str(data)
# > str(data)
# 'data.frame':  10000 obs. of  4 variables:
# $ a       : int  1 2 3 4 5 6 7 8 9 10 ...
# $ b       : int  1 2 3 4 5 6 7 8 9 10 ...
# $ c       : num  0.288 0.833 0.509 0.107 0.865 ...
# $ response: Factor w/ 2 levels "0","1": 1 2 2 1 2 2 1 1 1 1 ...
# GET COLNAMES TO USE IN SECOND BATCH

colnames <- colnames(data)
# DO SOME PROCESSING
# REMOVE FROM MEMORY
# READ IN SECOND BATCH:

data <- read_delim(file=fileconnection,
                   delim=sep,
                   col_names=colnames,
                   col_types=colClasses,
                   n_max=batchsize)
data <- data.frame(data)
str(data)
# 'data.frame':  0 obs. of  4 variables:
# $ a       : int
# $ b       : int
# $ c       : num
# $ response: Factor w/ 2 levels "0","1":
# DO SOME PROCESSING
# REMOVE FROM MEMORY
# READ IN THIRD BATCH
# ....

closeAllConnections()

**Comment by hadley** [comment]
Please correct your markdown

**Comment by hadley** [comment]
I've closed this issue due to lack of requested cleanup. If you still care about this bug, please open a new issue with a reprex.
