### ISSUE TITLE
Reading less than the entire file still moves the file position to the end

### ISSUE THREAD

**Issue by jean997** [tidyverse/readr#525]
It seems like that in both read_lines and read_delim, setting n_max to something less than the entire length of the file will still move the current file position to the end.
Using the example file I've attached which has 1001 lines:
# Open the connection

con <- file("test_data.txt", "rb")
# Read a few lines

d <- read_lines(con, n_max=3)
# Report the current position

seek(con)
# [1] 181569 <-- end of the file

readLines() gives more expected behavior so that you can keep reading where you left off
con <- file("test_data.txt", "rb")
d <- readLines(con, n=3)
[test_data.txt](https://github.com/hadley/readr/files/484169/test_data.txt)

seek(con)
# [1] 423

I think this might be the same issue as whats going on in issue #524  - if so I'm sorry for the duplication but I hope this was clear.
Thanks!

**Comment by hadley** [comment]
Please combine this with #524
