### ISSUE TITLE
encoding parameter

### ISSUE THREAD

**Issue by neuwirthe** [tidyverse/readr#528]
I am using R on a Mac with en US-English locale, and I have to read csv file containing German umlauts, coming from a Windows machine.
After reading the data, I can get the UTF-encoding I need with iconv(.,"LATIN1",UTF-8).
It would be nice if I already could specify the encoding of the  file to read in the read_csv2
or read_delim function call.
Can this be added?

**Comment by SewerynGrodny** [comment]
I've encounter similar problem, while importing file with polish characters. I tried used local() with different encoding systems, but failed. iconv("windows-1250", "UTF-8") made the job.

Greetings
Seweryn

**Comment by jennybc** [comment]
You should be specify the encoding as part of the locale. Something along these lines:

``` r
characters <- read_csv("character_list5.csv", locale = locale(encoding = 'ISO-8859-1'))
```

**Comment by SewerynGrodny** [comment]
thanks, @jennybc 
I tried your solutions, it almost works. :) I used encoding = ISO-8859-2 . (https://en.wikipedia.org/wiki/ISO/IEC_8859-2)

But not all characters were correctly encoded: "ś", "ą" weren't.

**Comment by jennybc** [comment]
@SewerynGrodny Great! I wasn't suggesting that specific encoding for *your* data. It was a line of code I pulled from one of my own scripts as an example.

I assume this method of specifying encoding as part of the locale does exactly what you need, once you specific the correct encoding, yes?  Or are you saying those problems with "ś", "ą" still remain?

**Comment by SewerynGrodny** [comment]
@jennybc  after using ISO-8859-2, all but two polish characters were correctly encoding. So in total, there are 12 polish characters, 10 were correctly translated, 2 weren't. :)

**Comment by hadley** [comment]
See also `guess_encoding()`.
