### ISSUE TITLE
spec() working also on non-imported data frames? Would allow to save column specifications when exporting dataset

### ISSUE THREAD

**Issue by MatthieuStigler** [tidyverse/readr#529]
Hi

In my workflow, code is split into multiple small R scripts, so that a typical dataset gets exported and imported multiple times. 

I would like to be able to export/save the column specifications while exporting the dataset, instead of doing as now,  only later on when importing the dataset in a new script. 

It would be great hence if the spec() function would also work on non-imported data-frames/tbls. The current help file suggests this is possible (x: The data frame object to extract from), but this is unfortunately not the case:

    iris %>% as.tbl%>% spec

**Comment by hadley** [comment]
It's not possible because we don't know what the specs are.
