### ISSUE TITLE
Provide an option to suppress the column guessing printing

### ISSUE THREAD

**Issue by daattali** [tidyverse/readr#530]
When I read a very wide CSV for a preliminary look, I get flooded with a big red message about all the guessing that took place.  I can suppress it with `suppressMessages()`, but it'd be nice to have an option to suppress it from readr itself.

**Comment by jennybc** [comment]
Related to #527

**Comment by hadley** [comment]
You already can. Just supply `col_types = cols()`

**Comment by daattali** [comment]
Thanks, good to know. But not clear from documentation. Would you accept a PR to add that as an example in read_csv?

**Comment by hadley** [comment]
That'd be great!

**Comment by nutle** [comment]
To make it more intuitive and prevent unnecessary googling/skimming through documentation, wouldn't a better option be to include an option somewhere in the lines of ``verbose = FALSE``? I always find self explanatory function parameters very useful, requiring only a quick glimpse to the Help panel, even if that's an overhead functional-wise.
