### ISSUE TITLE
Optional `make.names` arg to preserve `as.formula` functionality

### ISSUE THREAD

**Issue by martinjhnhadley** [tidyverse/readr#531]
`readr` preserves colnames as per https://github.com/hadley/readr/issues/165 but this makes working with `as.formula` expressions complicated (/I didn't get this to work).

Here's a reproducible and fairly common problem:

```r
library(readr)
library(plotly)
desktop_itmes <- read_csv("https://ndownloader.figshare.com/files/6452595")
desktop_itmes %>% 
  select(`Desktop Items`, `Operating System`, University) %>%
  group_by(University, `Operating System`) %>%
  mutate(mean = mean(`Desktop Items`)) %>%
  plot_ly(x = ~mean,
          y = as.formula("~`Operating System`"),
          colors = ~University,
          type = "bar")
```

Of course this all fixed with 

```r
colnames(desktop_itmes) <- make.names(colnames(desktop_itmes))
desktop_itmes %>% 
  select(Desktop.Items, Operating.System, University) %>%
  group_by(University, Operating.System) %>%
  mutate(mean = mean(Desktop.Items)) %>%
  plot_ly(x = ~mean,
          y = ~Operating.System,
          type = "bar",
          orientation = "h")
```

However, I feel that many users will plug away for ages trying to shoehorn ``variable name`` into formula. It might be inappropriate to add an option for the function, but some comment on this somewhere in the `tidyverse` would be useful for many users - IMO.

**Comment by hadley** [comment]
Why don't you just use ``~`Operating System` ``?

Are you sure this isn't a bug in plotly?
