### ISSUE TITLE
parse_number doesn't parse scientific notation

### ISSUE THREAD

**Issue by aaronmcdaid** [tidyverse/readr#537]
`readr::parse_number('3e-5')`  returns `3` where I expected `0.00003`.

Perhaps this isn't quite a bug, I'm not sure what the designed behaviour is. I thought it would read any 'numeric'-type data.

At the least, the documentation could be improved to specify this more clearly, and to guide users towards `col_types="d"` instead of `"n"` when dealing with floating point in functions like `read_delim`.

I guess this is the relevant sentence from the vignette:

  "... it ignores non-numeric prefixes and suffixes"

Is scientific notation a "non-numeric suffix"?

**Comment by aaronmcdaid** [comment]
I've only just realized that this issue has been fixed here. It was an issue in the 1.0.0 on CRAN, but not in the latest code on github. Sorry for not checking earlier!

**Comment by aaronmcdaid** [comment]
Sorry to reopen. Turns out I did the wrong test. Anyway, the issue is still open. I'm looking at the code in `QiParsers.h` and hope to send a pull request soon. I think I can make a fix to include trailing `e` or `E` part of `parse_number`, if it is followed by an `+` or `=` (optional) and one or more digits.

**Comment by aaronmcdaid** [comment]
Pull request with proposed fix, just submitted: https://github.com/tidyverse/readr/pull/545

**Comment by holstius** [comment]
+1. I was bitten by this when handed a CSV file saved by someone else from Excel. A few hundred rows down, there was a value in scientific notation. Everything else in the column was just digits (and ".")! Took hours to figure out what was happening. :-/

**Comment by hadley** [comment]
Why can't you use `parse_double()`?

**Comment by holstius** [comment]
Thanks! didn't know about it. 

Several things seem to be steering folks looking for a quick way forward --- from legacy stuff like extract_numeric --- to parse_number instead of parse_double: autocomplete; deprecation warnings suggesting parse_number but (IIRC) not parse_double; and forum threads. 

The second seems like the most actionable. I'm off grid or would offer fix ideas. CC'ing myself for New Year's follow-up. 

David
