### ISSUE TITLE
problems() not pulling up the exact text of a parsing failure

### ISSUE THREAD

**Issue by kendonB** [tidyverse/readr#548]
The example:

```
library(tidyverse)
x <- tribble(
  ~unit, ~value,
  "a"  ,    "1",
  "b"  ,     "(NA)")
write_tsv(x, path = "test.tsv")
```
Now try and parse with the incorrect NA specification (in the real application it's not obvious exactly what represents NA).
```
new_x <- read_tsv("test.tsv",
                  na = "",
                  col_types = cols(
                      unit = col_character(),
                      value = col_number()
                    ))
file.remove("test.tsv")

problems(new_x)
# A tibble: 1 × 4
#     row   col expected actual
#   <int> <chr>    <chr>  <chr>
# 1     2 value a number       
```

I would have expected this to come up:
```
# A tibble: 1 × 4
#   row     col expected actual
# <int>   <chr>    <chr>  <chr>
# 1   2   value a number   (NA) 
```
Is this the expected behavior?

**Comment by hadley** [comment]
Simpler reprex:

```R
x <- read_tsv("unit	value
a	1
b	(NA)", na = "", col_types = "cn")
```

**Comment by kendonB** [comment]
Thanks for the fix!

I found another case which fails, even after the fix:

```
problems(read_tsv("(-)\n1\n(-)", na = "", col_types = "n"))
```

**Comment by jimhester** [comment]
Looks correct to me, what do you expect the output to be?

``` r
library(readr)
problems(read_tsv("(-)\n1\n(-)", na = "", col_types = "n"))
#> # A tibble: 1 × 4
#>     row   col expected actual
#>   <int> <chr>    <chr>  <chr>
#> 1     2   (-) a number      -
```

**Comment by kendonB** [comment]
The "-" should be "(-)".

On mobile.


On Feb 24, 2017 1:54 PM, "Jim Hester" <notifications@github.com> wrote:

Looks correct to me, what do you expect the output to be?

library(readr)
problems(read_tsv("(-)\n1\n(-)", na = "", col_types = "n"))#> # A
tibble: 1 × 4#>     row   col expected actual#>   <int> <chr>    <chr>
 <chr>#> 1     2   (-) a number      -

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tidyverse/readr/issues/548#issuecomment-282415918>, or mute
the thread
