### ISSUE TITLE
Implement col_duration()

### ISSUE THREAD

**Issue by sjackman** [tidyverse/readr#549]
I have a table of time durations in hms format. The number of hours can be greater than 24. Parsing this column with `col_time` fails with
```
Warning: 1 parsing failure.
row       col   expected      actual
  5 Wallclock valid date 24:56:18.90
```
My workaround is to use `col_string` and then parse the time format with `hms(roll=TRUE)`. My suggestion for possible solutions would be to either add a `col_duration` parser, or add a `roll=TRUE` parameter to `col_time`.

**Comment by jimhester** [comment]
Reprex is
``` r
library(readr)
parse_time("24:56:18.90", format = "%H:%M:%S")
#> Warning: 1 parsing failure.
#> row col   expected      actual
#>   1  -- valid date 24:56:18.90
#> NA
```

**Comment by jimhester** [comment]
This is unfortunately tricky to implement with the current implementation

**Comment by hadley** [comment]
This needs a completely new collector for durations.

**Comment by krlmlr** [comment]
Same for negative times:

``` r
readr::parse_time("-12:34:56")
#> Warning: 1 parsing failure.
#> row col   expected    actual
#>   1  -- time like  -12:34:56
#> NA
```

<sup>Created on 2019-10-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Can we solve it by new placeholders `%h%` and `%s` that collect unrestricted hours and an optional sign, and check valid values when we collect `%H`? A new collector seems like too much work for too little gain.
