### ISSUE TITLE
Please add documentation for `parse_guess`.

### ISSUE THREAD

**Issue by Make42** [tidyverse/readr#550]
Coming from https://github.com/tidyverse/readr/issues/392 I see that the result was changed for 1.0.0:

```
> str(parse_guess("1,234"))
 num 1234
> str(parse_guess("1,234 "))
 chr "1,234"
> str(parse_guess(" 1,234"))
 chr "1,234"
> str(parse_guess(" 1,234 "))
 chr "1,234"
> str(parse_guess("$1,234"))
 chr "$1,234"
> str(parse_guess("1,234$"))
 chr "1,234$"
> str(parse_guess("$1,234$"))
 chr "$1,234$"
```

Thank you. However, now there is no documentation for `parse_guess` anymore in https://cran.r-project.org/web/packages/readr/vignettes/column-types.html - why is that? Obviously it works differently then `parse_number`, so there is no replacement here. The same goes for `guess_parser`. Please add a documentation for `parse_guess`.

**Comment by hadley** [comment]
See ?readr::parse_guess
