### ISSUE TITLE
feature request: allow read_tsv to skip some specific rows.

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/readr#554]
Hello there,

I am not mistaken, the great `read_tsv` lacks of a very important features: namely skipping specific rows. Here is a real life example

I have a simple tsv file with the following structure

```
0 - headerline
1 - empty line
2 - PIG schema
3 - empty line
4 - 1-st line of DATA
5 - 2-nd line of DATA
```
I would like to read it, possibly using `reader::read_tsv` but here is the problem.

As you can see, the first row contains the headers. Then I have three rows that I do NOT want to read it (they contains some super weird data coming from Apache PIG), and at row 4 the data starts. In Pandas, I would do something like

`df = pd.read_csv('/localpath/data.tsv', sep='\t', skiprows=[1,2,3])`
which allows me to read the headers AND to skip row one, two, three.

I dont see a similar option in reader::read_tsv. That is :

`df = read_tsv('/localpath/data.tsv', col_names = TRUE, skip = 4)`

does not parse the headers...

Originally posted on http://stackoverflow.com/questions/40656827/dplyr-how-to-read-a-tsv-file-with-headers-while-skipping-some-lines?noredirect=1#comment68544949_40656827

Thanks!

**Comment by hadley** [comment]
This is not currently possible, and I don't see adding support in the near future.  You can work around it by parsing with `n_max = 1` to get the headers and then using your code to get the rest of the data.
