### ISSUE TITLE
slow with small datasets

### ISSUE THREAD

**Issue by lukas-rokka** [tidyverse/readr#555]
I made small package that guesses the formatting of flat/tabular files: https://github.com/lukas-rokka/readrGuess 

It tests different combinations of formatting, altogether `readr::read_delim()` is called 18 times. But the performance for small datasets is not good. 

Following code takes roughly 1.5 seconds, while it should take just a few milliseconds from a computation point of view. 
```
readrGuess::read_guess(readr::format_delim(data.frame(a=1:1, b="a", c=1.1), ";"))
```

Doing the same thing with a big dataset only takes about 2 seconds
```
readrGuess::read_guess(readr::format_delim(data.frame(a=1:10000, b="a", c=1.1), ";"))
```

When checking with profiling it appears that `read_delim()` has a quite big overhead. `gc` (memory clean up I believe) is running most of the time when using it with small datasets. 

Is it possible somehow use the functionalities of the `read_delim()` for small datasets without causing `gc()` calls, or is it an unavoidable trade off that comes with using rcpp?

**Comment by Ax3man** [comment]
`replicate(18, readr::read_delim(readr::format_delim(data.frame(a=1:1, b="a", c=1.1), ";"), ';'))` only takes a fraction of a second though. Are you sure this is due to `readr`?

`system.time(replicate(1500, readr::read_delim(readr::format_delim(data.frame(a=1:1, b="a", c=1.1), ";"), ';')))` takes about 1.5 seconds on my system.

**Comment by lukas-rokka** [comment]
Thanks @Ax3man, that was a much better way of testing it. Seems like the problem is in `reader::locale()`

I get something like 0.05 seconds when running your example. But as soon I use include `locale()` I'm back at 1.5 seconds:

```
system.time(
  replicate(
    18, 
    readr::read_delim(readr::format_delim(data.frame(a=1:1, b="a", c=11), ";"), ';', 
                      locale = locale(decimal_mark = "."))
))
```

**Comment by lukas-rokka** [comment]
Following code solves it by calling readr::locale() just once

```
locale <- readr::locale()

system.time(replicate(18, {
  locale$decimal_mark <- "."
  readr::read_delim(readr::format_delim(data.frame(
    a = 1:1, b = "a", c = 11
  ), ";"), ';',
  locale = locale)
}))
```
Thanks again
