### ISSUE TITLE
calling locale() is slow

### ISSUE THREAD

**Issue by lukas-rokka** [tidyverse/readr#558]
Based on issue #555 

Calling locale() is slow. Not a big issue if calling a large file once, but if calling small files many times it matters. This example takes 1.5 second to run
```
system.time(replicate(18, read_delim(
  "c1;c2\n1,0;2,0", ";", locale=locale(decimal_mark = ","))))
```

While if the locale is set just once, it only takes about 0.05 seconds.

It is the call to `OlsoNames()` from `check_tz()` at line 115 in locale.R that is the cause to the slowness. 
```
system.time(replicate(18, "UTC" %in% OlsonNames()))
```

**Comment by hadley** [comment]
My expectation is that you'll normally create it once and save the results:

```R
my_locale <- locale=locale(decimal_mark = ",")
```
