### ISSUE TITLE
read_file does not parse UTF-8 correctly

### ISSUE THREAD

**Issue by LaDilettante** [tidyverse/readr#564]
I try to parse the URL string from an URL, and `read_file` seems to fail while `readLines` works fine. See the example below of `read_file` failing:

```
library(readr) ; library(tidyjson)
cities <- read_file("http://www.numbeo.com/api/cities?api_key=jpr6dr6ifurrvr",
                            locale = locale(encoding = "UTF-8"))

cities %>%
  enter_object('cities')
```

> Error: lexical error: invalid bytes in UTF8 string.
>           ry":"Hungary","city":"Kaposv�r","latitude":46.3593606,"city_
>                      (right here) ------^

**Comment by hadley** [comment]
Because it's not actually in utf-8:

```R
cities <- read_file(
  "http://www.numbeo.com/api/cities?api_key=jpr6dr6ifurrvr",
  locale = locale(encoding = "ISO-8859-1")
)
```
