### ISSUE TITLE
Drop dependency on R6?

### ISSUE THREAD

**Issue by vspinu** [tidyverse/readr#565]
Is dependency on R6 necessary?  

I have a package that provides some side functionality that relies on chunked reader and I am hesitant to add an explicit import on readr and even less so on R6. But it looks like I have little to no choice now as inheritance from ChunkCallBack of the user callbacks is compulsory.

I think the current implementation is just a "fancy" way of doing closures. There is barely any inheritance over there. There is little point to have callback hanging around as objects anyways,  so why bother then with yet another OO?

**Comment by hadley** [comment]
I prefer R6 because it's a consistent way of wrapping up functions and state.  Rather than rolling out something simple (but subtly different), I'd rather standardise on one slightly more general way of doing things and use it everywhere.
