### ISSUE TITLE
function to guess encoding from character vector

### ISSUE THREAD

**Issue by cjyetman** [tidyverse/readr#566]
Would it make sense to have a function that can guess the encoding from a character vector?
for example...
```
guess_encoding_from_chr_vector <-
  function (chr_vector, ...) 
  {
    file <- charToRaw(paste(unique(chr_vector), collapse = ''))
    readr::guess_encoding(file, ...)
  }

df <- readr::read_csv('http://databank.worldbank.org/data/download/GDP.csv', skip = 3)
guess_encoding_from_chr_vector(df$Economy)
```

`readr::guess_encoding()` goes line by line through a file. Imagine a file with 500,000+ lines (well over the default n_max of 10,000) where the first non-ASCII character appears far below the 10,000th line, and there are **many** columns filled with numeric data and only one column with characters (i.e. country name). One could progressively increment `n_max` using `readr::guess_encoding()` and eventually find the first non-ASCII character to get an appropriate encoding guess, but wouldn't it be more efficient, especially if a `readr::read_csv()` had already been attempted and the data was in memory as a data.frame, to try to guess the encoding based only on the data/column/vector that contains the character strings (and only unique values of such)?

**Comment by hadley** [comment]
I don't think it's a good idea to guess from a character vector because the data has already been encoded (possibly incorrectly) once. Instead, you can pass `guess_encoding()` a raw vector.
