### ISSUE TITLE
col_datetime format - use just first n chars, ignore the rest

### ISSUE THREAD

**Issue by inkrement** [tidyverse/readr#569]
I want to load a csv file containing datetime values. The used format is quite ugly (only the first 12 chars are important for me) and the rest contains some additional time information (e.g. timezone) with varriing length. How can I parse this string properly? I was not able to find a proper solution and hardcoded the string pretty much the same like in the following example, because in most cases the datetime information is followed by 5 zeros:

```
bids <- read_csv('./data.csv', col_types = list(
    Time_Bid = col_datetime("%Y%m%d%H%M00000")
))
```

But I want to parse also datetimes, which do not end with five zeros, are there any wildcard symbols/fixes I can use?

**Comment by hadley** [comment]
`%*`
