### ISSUE TITLE
Skipping columns gives incorrect col names in problems

### ISSUE THREAD

**Issue by ajdamico** [tidyverse/readr#573]
hi, thanks for `readr`.  here's an example of a `problems(...)` warning that i am not sure should be triggered?

(reprex elided now we have a shorter one)

**Comment by hadley** [comment]
Do you think you could reduce this problem a little?

**Comment by ajdamico** [comment]
sure why not


	library(readr)

	tf <- tempfile()

	lines <- "  -1-1-1" 

	writeLines( lines , tf )

	readr_structure <- fwf_widths( c( 2 , 4 , 2 ) , col_names = c( "col1" , "col2" , "col3"  ) )

	x <-
		read_fwf(

			tf ,
			
			readr_structure ,
			
			col_types = "_dd"
			
		)

	# says the parsing failure is in column #3 but it's really in column #2
	problems(x)
	# looks like your column counter isn't excluding the "_" columns

	# change "_dd" to "ddd" and now `problems(x)` returns the correct column name

	x <-
		read_fwf(

			tf ,
			
			readr_structure ,
			
			col_types = "ddd"
			
		)

	problems(x)

**Comment by hadley** [comment]
Can you make it even by putting the data inline in the `read_fwf()` call?  (And reducing the amount of whitespace)

**Comment by ajdamico** [comment]
this work?

	library(readr)

	readr_structure <- fwf_widths( c( 2 , 4 , 2 ) , col_names = c( "col1" , "col2" , "col3"  ) )

	x <- read_fwf( "  -1-1-1\n" , readr_structure , col_types = "_dd" )

	# says the parsing failure is in column #3 but it's really in column #2
	problems(x)
	# looks like your column counter isn't excluding the "_" columns

	# change "_dd" to "ddd" and now `problems(x)` returns the correct column name

	x <- read_fwf( "  -1-1-1\n" , readr_structure , col_types = "ddd" )

	problems(x)

**Comment by hadley** [comment]
Thanks. That leads to something even simpler:

```R
library(readr)

st <- fwf_widths(c(2, 2, 2), col_names = c("x1", "x2", "x3"))
x <- read_fwf("aabbcc\n", st, col_types = "_dc")
problems(x)
```
