### ISSUE TITLE
C Stack usage is too close to the limit?

### ISSUE THREAD

**Issue by pgensler** [tidyverse/readr#578]
I have been trying to experiment with readr for a relatively small file (1GB), and I keep getting a warning once I read in the file that states:
Error: C stack usage  112472876 is too close to the limit

This is what I have used to read the file in, and I think it may have something to do with the backend of readr, and using connections to read in text files. I know this csv file was structurally incorrect, so I bet that reading in the file like this does not make it any less easier.

```
fileurl <- "http://daniels-pull.universityofdenv.netdna-cdn.com/assets/GeneralOccurrencesAll.csv"
stringr::str_view_all(string = string, pattern = ",(?!\\s)")

system.time(genocc <- readr::read_file(datafile))

system.time(test <- str_replace_all(genocc, ",(?!\\s)", ";"))
#Bash command to get count of lines from the csv file
system('wc ‐l  Desktop/GeneralOccurrencesAll.csv')

file <- readr::read_delim(file = test, delim = ";")
```

One thing that is interesting to note (not sure if this is a bug), is that when I specify a delimiter with read_csv, such as ; it does not recognize it as a delim, yet with base r this works fine with
read.csv2. It would be nice to have more documentation on how to use text connections to read in bad csv files to work with in R. I will try to get my base-r code up, but seems like I may I have lost some of it.

**Comment by pgensler** [comment]
Something to note here is that while it is relatively to do this with baser using this:
u <- "http://daniels-pull.universityofdenv.netdna-cdn.com/assets/GeneralOccurrencesAll.csv"
Lines <- readLines(u, 3)

read.csv2(text = gsub(",(\\S)", ";\\1", Lines))

It tends to get a bit more complicated with using the tidyverse approach, causing RStudio to crash:
lines2 <- readr::read_lines(datafile)
system.time(final <- read_delim(file = stringr::str_replace_all(lines2,",(?!\\s)", ";"), delim = ";"))

**Comment by jimhester** [comment]
Please provide a runnable example, your example contains a number of errors due to undefined variable names, cleaning it up this runs without error on my machine.

``` r
library(readr); library(stringr); library(magrittr)
data <- "http://daniels-pull.universityofdenv.netdna-cdn.com/assets/GeneralOccurrencesAll.csv" %>%
  read_file() %>%
  str_replace_all(",(?!\\s)", ";") %>%
  read_delim(delim = ";")

data
#> # A tibble: 591,911 × 15
#>       RIN               UCR_Group                                UCR_Cat
#>     <int>                   <chr>                                  <chr>
#> 1  416667 Crimes Against Property     Criminal Mischief/Damaged Property
#> 2  416673  Crimes Against Persons                  Forcible Sex Offenses
#> 3  416674  Crimes Against Persons                  Forcible Sex Offenses
#> 4  416680  Public Disorder Crimes Violation of a Restraining/Court Order
#> 5  416684  Crimes Against Persons                  Forcible Sex Offenses
#> 6  416686   Public Disorder Crime                     All Other Offenses
#> 7  416689 Crimes Against Property                                Larceny
#> 8  416687  Public Disorder Crimes                     All Other Offenses
#> 9  416694 Crimes Against Property     Criminal Mischief/Damaged Property
#> 10 416698  Public Disorder Crimes                     All Other Offenses
#> # ... with 591,901 more rows, and 12 more variables:
#> #   EXP_TRANSLATION <chr>, OCC_DATE <chr>, OCC_TIME <int>, LOC <chr>,
#> #   TRANSLATION <chr>, PIN <int>, DOB <chr>, SEX <chr>, X <dbl>, Y <dbl>,
#> #   LON <dbl>, LAT <dbl>
```

I am guessing you had a typo in your regular expression (probably missing the first `,`, which causes every character to be separated by a `;`, resulting in the C stack issue.

**Comment by Treeepti** [comment]
I am having the same problem while using sum function on a column. How to stop getting this error?
