### ISSUE TITLE
Include filename in warning message when parsing of values fails

### ISSUE THREAD

**Issue by estroger34** [tidyverse/readr#581]
I read a large number of files using lapply and read_csv with fixed coltypes:

    datalist <- lapply(filelist, function (x) read_csv(x,col_types='ccdddic')

Occasionally there is a non-numeric entry in a column that should parse as double and I get a warning message like this:

    Warning: 1 parsing failure.
    row    col expected actual
      1 Wert01 a double      b 

However, from this warning I do not know in which of the dozens, sometimes hundreds of files the parsing failed.

Would it be possible to include the filename for the failed parsing in the warning message?

**Comment by hadley** [comment]
I agree that this is good practice

**Comment by hadley** [comment]
Ideally we should also include the filename if there are any errors

**Comment by jimhester** [comment]
I started working on this, it is going to require quite extensive changes to implement as none of the collectors or parsers store the filename information. We need to think about what internal objects should store the filename information and which should not. In particular I am pretty sure we need to  avoid including the filename in the Token object, as that would likely slow parsing considerably.

**Comment by hadley** [comment]
What if we did this at the R level by wrapping the condition raised in C++?

**Comment by jimhester** [comment]
That would work, I can give it a try.

**Comment by jimhester** [comment]
Turns out it was even easier than using exceptions, we can just add the filename to the problems attribute directly, should have thought of that first!
