### ISSUE TITLE
Explore support for R 3.0.0

### ISSUE THREAD

**Issue by hadley** [tidyverse/readr#583]
If it's not too much work, it might be worth it.

**Comment by jimhester** [comment]
tibble is only R (3.1.0), so that would need to change, the other dependencies are R > 3.0

**Comment by jimhester** [comment]
In terms of new functions as far as I can tell the only thing is readr uses  is `file.info(extra_cols=FALSE)` which was added in 3.2.

We could use the backports definition for it https://github.com/mllg/backports/blob/master/R/file.info.R

**Comment by hadley** [comment]
Or we could just drop the `extra_cols` argument? I guess maybe that would give a minor performance regression?

**Comment by hadley** [comment]
I'm rolling back on this R 3.1 is adequate
