### ISSUE TITLE
Write using Chunked API

### ISSUE THREAD

**Issue by kylelundstedt** [tidyverse/readr#589]
The [Chunked API](http://readr.tidyverse.org/reference/read_delim_chunked.html) looks really interesting.  It would be really useful to add 'write_*_chunked' function equivalents.  The specific use case that I have in mind is processing files too large to fit into memory and writing them out chunk-wise.  

For example, I'd like to use 'readr' to "pre-process" (I.e., clean up bad values, format dates, etc) large raw 100 GB CSV files, then write the processed files back to CSV to enable loading them into a DBMS, using them in other code, etc.  See https://github.com/edwindj/chunked for some nice examples.

**Comment by jimhester** [comment]
Not sure why you need a new function, to do what you describe you simply write a callback that does the processing then calls one of the regular write functions with `append = TRUE`.

**Comment by hadley** [comment]
This will be more obvious in the future once there are more tutorials/vignettes on using the chunked classes effectively.
