### ISSUE TITLE
"Not enough storage is available to process this command."

### ISSUE THREAD

**Issue by jonspring** [tidyverse/readr#593]
Apologies upfront: I don't know how to make a reprex for this and I'm not positive the issue is with readr -- that's just where it's showing up. I'm attempting to read a 150 MB csv on a machine with 4GB RAM and I'm getting this error:
```
bar <- as.tbl(readr::read_csv(file = "S:/foo.csv"))

Error in eval(substitute(expr), envir, enclos) : 
  Cannot read file S:/foo.csv: Not enough storage is available to process this command.
```
The error did not occur when the file was smaller (say, 100 MB). Clearing all objects from the RStudio workplace does not fix it, but restarting R does. Please let me know what other info might help.

Using readr 1.0.0 
RStudio 1.0.136
R 3.3.2 on Windows 7

**Comment by jimhester** [comment]
I don't believe this error message has anything to do with readr, or R at all. A [google search](https://www.google.com/search?q="Not+enough+storage+is+available+to+process+this+command") for the messeage looks like there are a handful of likely causes, most dealing with accessing files on network shares.
