### ISSUE TITLE
read_csv() behaves oddly with paste()

### ISSUE THREAD

**Issue by dkyleward** [tidyverse/readr#600]
I'm reading a large CSV file in an RMD file in Rstudio, and the following two code blocks lead to very different behavior. The first works as expected, but the second does not. The difference is whether I concatenate the filename (using `paste()`) outside or inside the function call.

``` r
dir <- "../data"
csv_file <- "test.csv"
full_path <- paste(dir, csv_file)
df <- read_csv(full_path)
```

This second block of code takes 100(?) times longer to read the file with a progress bar appearing. What's even stranger to me is that if I stop the read process, a second progress bar will show up. This one is much faster, and the file is read. The same thing happens with `paste0()`.

``` r
dir <- "../data"
csv_file <- "test.csv"
df <- read_csv(paste(dir, csv_file))
```

Lastly, when I knit the page, the CSV is read quickly regardless of which code block is used.

**Comment by jimhester** [comment]
Can you provide a minimal [reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) with a real dataset?

Your example above is almost definitely incorrect unless you have a file at `../data test.csv`, as `paste()` uses a single space as the default separator. Also I would suggest using `file.path()` to generate file paths rather than `paste()`.

**Comment by dkyleward** [comment]
Will do. Sorry - I actually wrote the paste with paste0(), then tested paste() and found the same behavior. I then changed my code block incorrectly.

**Comment by dkyleward** [comment]
OK. I think the problem may be completely unrelated. I may just need a fresh R/Rstudio install. I'm getting the behavior without paste/file.path. Also, if I create a large data frame, write it out, then read it back in, I don't get this issue. When I read one of my CSVs created by my CAD program, I get the behavior (but not when I knit!).

I call `read_csv()`. I let it run slowly for a minute until it reached 16 MB. I then stopped the process. It then read the file quickly showing the second progress bar.
![image](https://cloud.githubusercontent.com/assets/10221750/22697216/d190368c-ed1e-11e6-949f-462c99cfb8b6.png)

I'm going to close this issue, but if you have any idea about what might be wrong with my CSV file structure, that would be awesome.

Thanks!

**Comment by dkyleward** [comment]
Just wanted to follow up after I figured out what was going on. It was actually a notebook setting causing the issue. When I turned off inline-output in favor of output in the console (gear icon next to knit icon), everything went back to normal speed. I think having to render progress bar inline was slowing everything down.
