### ISSUE TITLE
Add Inf= option to parse_double?

### ISSUE THREAD

**Issue by shabbybanks** [tidyverse/readr#604]
At times I have to parse a csv file which encodes infinities as `I` (I'm looking at you, SAS), instead of `Inf`. I have also see `infty` for infinity. Could `parse_double` gain an option similar to the `na` option for those strings which should be interpreted as infinity? I guess there would be some complication with respect to minus infinities and optional plus signs, but otherwise not terribly complicated.

**Comment by hadley** [comment]
For now, I'd say this is out of scope for readr because we only read IEEE 754 doubles (and this code is fairly deep inside readr so it would be hard to fix).

**Comment by shabbybanks** [comment]
Looking through the code for a quick fix, I agree with the latter comment! However, not to belabor the point, IEEE 754 _does_ include + and - infinities, so I'm not sure of the relevance of the standard here.

**Comment by jimhester** [comment]
readr uses the [Boost QI Parser to parse doubles](http://www.boost.org/doc/libs/1_56_0/libs/spirit/doc/html/spirit/qi/reference/numeric/real.html#spirit.qi.reference.numeric.real._code__phrase_role__identifier__realpolicies__phrase___code_), which accepts positive and negative infinity specified as case insinsitive `[+-]Inf` or `[+-]Infinity` 

```r
readr::parse_double(c("Inf", "Infinity", "-Inf", "-Infinity"))
```
Supporting other formats for infinity would require deriving a new type from the `real_policies` type with the required logic.
