### ISSUE TITLE
Skipping columns without specifying the type

### ISSUE THREAD

**Issue by LaDilettante** [tidyverse/readr#614]
Currently, to skip a column I have to specify the type

`read_csv("X1,X2\nhi,there\n", col_types = cols_only(X1="c"))`

It should be able to do without like so

`read_csv("X1,X2\nhi,there\n", col_types = cols_only(X1))`
`read_csv("X1,X2\nhi,there\n", col_types = cols_only("X1"))`

because skipping columns and specifying types are two distinct tasks. One needs not require the other.

**Comment by hadley** [comment]
Just specify that you want the type to be guessed `cols_only(X1 = "?")`
