### ISSUE TITLE
parse_datetime() don't support %a as format

### ISSUE THREAD

**Issue by jaksch** [tidyverse/readr#622]
`parse_datetime()` don't support the abbreviated weekday format `%a`, is that intentional?

```
> readr::parse_datetime("Thu 23 Feb 2017 19:23:27 +0100", 
+                         format = "%a %d %b %Y %H:%M:%S %Z", 
+                         locale = readr::locale("en"))
Error in parse_vector_(x, collector, na = na, locale_ = locale) : 
  Unsupported format %a
```

**Comment by jimhester** [comment]
This is a documented missing feature, it is unlikely to be added in the near term.

>      Currently, readr does not support all of ISO8601. Missing features:
> 
>        • Week & weekday specifications, e.g. "2013-W05", "2013-W05-10"
