### ISSUE TITLE
Feature suggestion: add a ``zero`` argument to ``read_delim``

### ISSUE THREAD

**Issue by kendonB** [tidyverse/readr#625]
My motivating example is a dataset that contains ``(-)``, which likely indicates zero, rather than NA.

I'd like to be able to get the parser to recognize this as a zero.

Is this already possible somehow?

**Comment by hadley** [comment]
No, and it's sufficiently rare that I'd say it's outside the scope of readr. You can always read as character and do your own parsing in R.
