### ISSUE TITLE
File generated by write_sas cannot be opened by SAS.

### ISSUE THREAD

**Issue by DavisBrian** [tidyverse/readr#626]
MWE

```
library(tidyverse)
data_frame(x = LETTERS, y = letters) %>% write_sas(path = "test.sas7bdat")

x <- read_sas("test.sas7bdat") # This Works
```

However, when I go to SAS (9.3) and try to read it in

> 26   data test_letters;
> 27       set cin.Test;
> ERROR: File CIN.TEST.DATA is not a SAS data set.
> 28   run;
>

**Comment by jimhester** [comment]
Please open this issue at the [haven repository](https://github.com/tidyverse/haven/issues), which is the package that reads SAS files.
