### ISSUE TITLE
Is readr::problems supposed to catch a missing column declared in cols_only?

### ISSUE THREAD

**Issue by alessandro-gentilini** [tidyverse/readr#629]
The following snippet

```
cat(sprintf("readr version is %s\n",packageVersion("readr")))
write.table(data.frame(a=c(1,2,3)),file = "test.csv",row.names = FALSE,quote = FALSE)
df<-readr::read_csv("test.csv",col_types = readr::cols_only(a="i",b="i"))
print(readr::problems(df))
```

gives this output

```
readr version is 1.0.0
# A tibble: 0 × 4
# ... with 4 variables: row <int>, col <int>, expected <chr>, actual <chr>
Warning message:
The following named parsers don't match the column names: b  
```

I was expecting that the data frame returned by `readr::problems` had at least one row.

What am I missing?

**Comment by jimhester** [comment]
I think this is just due to an implementation detail with the readr works internally. If a column is missing entirely this may happen.

**Comment by jimhester** [comment]
In particular the warning here comes from `col_spec_standardise` and the only issues which are in the problem output are those which occur when parsing.
