### ISSUE TITLE
Read_table reads long files incorrectly due to wrong columns width guessing

### ISSUE THREAD

**Issue by adrfantini** [tidyverse/readr#638]
See the example code below, which makes use of the attached file, specifically the first column.
The last members of the first column, which should be `c(1005:1010)`, are instead `c(5:10)` when read by `read_table()` without skipping anything.

It seems that `read_table()` looks for the first 100 rows when reading, and finds that the first column only has a three digits number. However, later in the file the number becomes 4-digits.

```
testfile <- "https://github.com/tidyverse/readr/files/847495/testfile.txt"
com <- read_table(testfile, col_names=FALSE); tail(com$X1)
# [1]  5  6  7  8  9 10
com <- read_table(testfile, col_names=FALSE, skip=20); tail(com$X1)
# [1] 1005 1006 1007 1008 1009 1010
```

How can I avoid this, without using `read_fwf()` (which is not doable for me because this script must be able to read a large number of differently formatted files)?
Would it be possible to add a tuning parameter that specifies how many rows are checked to choose the column width?

Thanks in advance.

[testfile.txt](https://github.com/tidyverse/readr/files/847495/testfile.txt)

**Comment by jimhester** [comment]
I think this has been changed in the devel version of readr (which should be released to CRAN in the next couple of weeks). There is a`guess_max` value (default of 1000) that can be used to control the number of rows read to find the whitespace.

**Comment by adrfantini** [comment]
Oh. I love when this happens: I report a problem and find it solved already in the next version :)

Thanks!

**Comment by adrfantini** [comment]
Sorry, but am I mistaken or the guess_max option already exists, but does nothing?

    com <- read_table(testfile, col_names=FALSE, guess_max=100000); tail(com$X1)

Does not return an error, but the result is still wrong.

**Comment by jimhester** [comment]
As I said this it is in devel readr, i.e. readr 1.0.1 which was just released yesterday, not readr 1.0.0.

**Comment by adrfantini** [comment]
Ok, I thought that this option was not even present in the previous version of `readr`. But it was. Since I updated all the system yesterday, I was not really sure which `readr` version I had when I opened this issue and could not easily check this. Thanks.

**Comment by jimhester** [comment]
For future reference you can always check versions of all currently loaded packages with `sessionInfo()`, or for a particular package with `packageVersion("readr")`

**Comment by adrfantini** [comment]
Yes, I know. But since I upgraded all packages since last week, and I did not know whether I also updated `readr`, it may have been that I had a 0.x version of `readr` before. I did not check when opening this issue (my bad). Anyhow, thanks! Will update ASA CRAN is synced.
