### ISSUE TITLE
Differences in output between local and internet file

### ISSUE THREAD

**Issue by ldecicco-USGS** [tidyverse/readr#640]
If I pull some data off the web:

[https://waterdata.usgs.gov/nwis/measurements/?site_no=01381900&range_selection=date_range&format=rdb](https://waterdata.usgs.gov/nwis/measurements/?site_no=01381900&range_selection=date_range&format=rdb)

```
library(readr)

readr.data <- read_delim("https://waterdata.usgs.gov/nwis/measurements/?site_no=01381900&range_selection=date_range&format=rdb", 
                         skip = 15,
                         delim="\t",col_names = FALSE)
```

It loses all the data that gets flagged as "No" in column `X6`:
```
# "No" data:
no_data <- readr.data[readr.data$X6 == "No",]
```
![image](https://cloud.githubusercontent.com/assets/1105215/24062006/c3482bc6-0b27-11e7-89e2-1e399d81ec00.png)

However.....if I copy all the contents on that page and save it as a text file...

```
local.data <- read_delim("C:/Users/ldecicco/Desktop/rdbTest.txt",
                         skip = 15,
                         delim="\t",col_names = FALSE)
no_local_data <- local.data[local.data$X6 == "No",]
```

![image](https://cloud.githubusercontent.com/assets/1105215/24061983/af7398c4-0b27-11e7-91ec-4d502d94026a.png)

**Comment by ldecicco-USGS** [comment]
readr         * 1.0.0   2016-08-03 CRAN (R 3.3.2)

**Comment by jimhester** [comment]
There is no more data after the 'No' columns, it is being read properly directly from the web and became corrupted when you copied by hand.

``` r
lines <- readr::read_lines("https://waterdata.usgs.gov/nwis/measurements/?site_no=01381900&range_selection=date_range&format=rdb")
grep("\\bNo\\b", lines, value = TRUE)
#> [1] "USGS\t01381900\t318\t2013-07-29 13:20:00\tEDT\tNo\t\t\t\t\t\t\t\t\t\t\t\t"
#> [2] "USGS\t01381900\t323\t2014-07-11 14:57:28\tEDT\tNo\t\t\t\t\t\t\t\t\t\t\t\t"
#> [3] "USGS\t01381900\t333\t2015-09-21 13:39:00\tEDT\tNo\t\t\t\t\t\t\t\t\t\t\t\t"
#> [4] "USGS\t01381900\t335\t2015-12-09 16:05:38\tEST\tNo\t\t\t\t\t\t\t\t\t\t\t\t"
#> [5] "USGS\t01381900\t336\t2016-02-02 10:56:53\tEST\tNo\t\t\t\t\t\t\t\t\t\t\t\t"
#> [6] "USGS\t01381900\t337\t2016-02-16 15:27:53\tEST\tNo\t\t\t\t\t\t\t\t\t\t\t\t"
#> [7] "USGS\t01381900\t341\t2016-07-06 11:19:32\tEDT\tNo\t\t\t\t\t\t\t\t\t\t\t\t"
#> [8] "USGS\t01381900\t342\t2016-08-17 12:09:00\tEDT\tNo\t\t\t\t\t\t\t\t\t\t\t\t"
#> [9] "USGS\t01381900\t343\t2016-10-05 11:03:00\tEDT\tNo\t\t\t\t\t\t\t\t\t\t\t\t"
```

**Comment by ldecicco-USGS** [comment]
But if you go to the website, there *is* data in those rows (most of the "No" data is at the bottom), and it looks just like the "local.data" result shows.

**Comment by jimhester** [comment]
That doesn't seem to be the case to me?
<img width="947" alt="screenshot 2017-03-17 17 05 52" src="https://cloud.githubusercontent.com/assets/205275/24062979/0cf8870a-0b34-11e7-93df-19d16c268ed4.png">

**Comment by ldecicco-USGS** [comment]
That's super-helpful....I see it and I must be behind a firewall that gives me extra access. Thanks!!!
