### ISSUE TITLE
Not possible to specify datetime format in locale() (makes it impossible to import non-standard datetimes)

### ISSUE THREAD

**Issue by huftis** [tidyverse/readr#642]
It's not possible to specify the datetime format in `locale()`. So if one uses the compact string representation of `col_types`, it is **impossible** to import data that doesn't use the ISO 8601 data format. Example:

```r
  x = "dtime;d;time\n24.12.2016 03:04:05;24.12.2016;03:04:05"
  read_delim(x,
    delim = ";",
    col_types = "TDt",
    locale = locale(date_format = "%d.%m.%Y", time_format = "%H:%M:%S"))
```

This results in the following warning and data output:

```r
Warning: 1 parsing failure.
row   col   expected              actual
  1 dtime date like  24.12.2016 03:04:05

# A tibble: 1 × 3
   dtime          d       time
  <dttm>     <date>     <time>
1   <NA> 2016-12-24 11045 secs
```

If I try to add a `datetime_format` to `locale()`, I get a `unused argument (datetime_format = "tsd")` error message.

If the datetime has normal ISO 8601-like syntax, everything works fine, i.e.

```r
  x2 = "dtime;d;time\n2016-12-24 03:04:05;24.12.2016;03:04:05"
  read_delim(x2,
             delim = ";",
             col_types = "TDt",
             locale = locale(date_format = "%d.%m.%Y", time_format = "%H:%M:%S"))
```
results in
```r
# A tibble: 1 × 3
                dtime          d       time
               <dttm>     <date>     <time>
1 2016-12-24 03:04:05 2016-12-24 11045 secs
```
Note that the (non-ISO 8601) date-specificiation was *not* used when parsing the datetime. This is correct behaviour; if one wants to parse datetimes, one should specify the datetime format. The problem is that it currently isn’t *possible* to specify the datetime format (when using the compact string representation for column types).

Note that `parse_datetime()` handles non-standard datetimes fine; it’s just `locale()` that is missing datetime support:

```r
> parse_datetime("24.12.2016 03:04:05", format="%d.%m.%Y %H:%M:%S")
[1] "2016-12-24 03:04:05 UTC"
```

So to fix the problem, support for specifying a `datetime_format` argument should be added to `locale()` and `read_*()` should use this format when parsing datetimes (i.e. column type `T`).

**Comment by jimhester** [comment]
It is not impossible, you need to specify the format in your column specification, not in the locale.

e.g.

``` r
library(readr)
x <- "dtime;date;time\n24.12.2016 03:04:05;24.12.2016;03:04:05"
read_delim(x,
  delim = ";",
  col_types = list(
    dtime = col_datetime(format = "%d.%m.%Y %H:%M:%S"),
    date = col_date(format = "%d.%m.%Y"),
    time = col_time(format = "%H:%M:%S")
  )
)
#> # A tibble: 1 x 3
#>   dtime               date       time    
#>   <dttm>              <date>     <time>  
#> 1 2016-12-24 03:04:05 2016-12-24 03:04:05
```

<sup>Created on 2021-05-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jimhester** [comment]
We are not planning to implement this feature, as there is a straightforward workaround that I showed you above. The shorthands are only supposed to handle the most common types of data, more complicated types require the functional interface.

If you would still like this feature you are welcome to work on a pull request to implement it, or fund someone to do so on your behalf and we will gladly re-open this issue and review it.
