### ISSUE TITLE
quoted_na doesn't seem to work

### ISSUE THREAD

**Issue by LaDilettante** [tidyverse/readr#643]
I may be missing something obvious here, but the argument doesn't work:

```r
readr::read_csv('a,b,"NA"\nd,e,f', col_names = F, quoted_na = F)
#> # A tibble: 2 × 3
#>      X1    X2    X3
#>   <chr> <chr> <chr>
#> 1     a     b  <NA>
#> 2     d     e     f
```

I'm using version 1.0.0

> packageDescription("readr")
> Package: readr
> Version: 1.0.0

**Comment by jimhester** [comment]
This seems like a regression, thank you for the report.

**Comment by LaDilettante** [comment]
I thought I was going crazy since there was an issue explicitly dealing with this. Your prompt reply saved me $TONS of therapy

**Comment by tom-christie** [comment]
+1

**Comment by jimhester** [comment]
I cannot now reproduce this in the devel version, so it seems fixed.
