### ISSUE TITLE
Documented return type doesn't match actual

### ISSUE THREAD

**Issue by alexkahn** [tidyverse/readr#644]
This is my first time jumping into this new-fangled "make my life easier" R packages and found myself looking at the man page for [`read_csv`](https://github.com/tidyverse/readr/blob/master/man/read_delim.Rd#L120) where it states the return value is a data.frame type.

In reality it is a tibble:

```R
library(readr)
class(read_csv("x,y\n1,2\n3,4"))
# [1] "tbl_df"     "tbl"        "data.frame"
```

The documentation should probably note that - it's my fault I didn't use `str` and found myself here.

Happy to put in a PR.

R Version 3.3.3
Readr version 1.1.0 (I think, no idea how to do this with R from console)

**Comment by jimhester** [comment]
`packageVersion("pkgName")`  to get the package version in the console and happy to accept a PR to fix this if you would like!
