### ISSUE TITLE
Need peek function

### ISSUE THREAD

**Issue by hadley** [tidyverse/readr#649]
Like

```R
peek <- function(path, n_max = 10) {
   lines <- read_lines(path, n_max = n_max)
   writeLines(lines)
   invisible(lines)
}
```

To make it easier to see what's in a file on disk

**Comment by jimhester** [comment]
Developing good software requires relentless focus, which means that we have to say no to many good ideas.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future 😛
