### ISSUE TITLE
Consider promotion of integer -> double tokenizers

### ISSUE THREAD

**Issue by kevinushey** [tidyverse/readr#652]
For certain numeric columns, it's possible that the first entries are representable as integer, with only the later entries being representable as double. In such a case, calls to `read_csv()` can fail as the inferred integer tokenizer will fail to tokenize those later entries.

Would it be possible for `readr` to instead just promote the tokenizer from integer to double on the fly in such a case?

**Comment by jimhester** [comment]
We no longer guess integer columns by default, so I am closing this.
