### ISSUE TITLE
write_csv should have option to quote character variables

### ISSUE THREAD

**Issue by rmcd1024** [tidyverse/readr#653]
Perhaps I've missed an option, but I don't see how to have `write_csv` quote strings. This creates problems when strings look like integers.

```
library(readr)
write_csv(data.frame(a=c(rep("10", 1000), "01")), 'test1.csv')
x1 = read_csv('test1.csv')  ## a imported as integer, breaking last observation
write_csv(data.frame(a=c("01", rep("10", 1000))), 'test2.csv')
x2 = read_csv('test2.csv')  ## a imported correctly as character
```

Obviously in the read statements one could set `guess_max=Inf`, but it would be helpful to write quoted strings in the first place.

**Comment by jimhester** [comment]
Ok, I agree it should be possible to force quoting if desired.

**Comment by jxu** [comment]
Agreed. See `quote` argument of `write.table`. 
I think there should be three options: Always quote character vectors, quote when needed (the current default), and never quote (dangerous, but here to mimic the functionality of `write.table`).

**Comment by bbolker** [comment]
+1000.  Protecting text fields with commas in them is super-important! Falling back to `write.csv()` now ...

**Comment by jimhester** [comment]
@bbolker `readr` already quotes text fields with commas automatically, this issue is about forcing quoting even if it isn't strictly needed.

**Comment by bbolker** [comment]
sorry, I  ran into some issues last night that made me think otherwise, but it was late. (Actually I think the problem was OpenOffice deciding it should split fields on semicolons as well as commas ...)

**Comment by mmuurr** [comment]
I'm curious if this open issue is truly open, or if there's a workaround that's commonly used (apart from `write.csv` and family). I, too, would like to strictly enforce quote-wrapping of certain character columns while writing those columns...

**Comment by jimhester** [comment]
One straightforward way to do this is to call `base::dQuote()` or `glue::double_quote()` on the columns you want to quote before passing to `readr`.

**Comment by philpav** [comment]
Is there still no built-in way to for forcing quotes on all columns?

**Comment by sjackman** [comment]
> Is there still no built-in way for forcing quotes on all columns?

```r
write_csv(x, file, quote = "all")
```

**Comment by dagibson-alaska** [comment]
> > Is there still no built-in way for forcing quotes on all columns?
> 
> write_csv(x, file, quote = "all")

Quote parameter should be passed as list
write_csv(x, file, quote = c("all"))
