### ISSUE TITLE
parse_number() fails to parse numbers written in scientific notation

### ISSUE THREAD

**Issue by GegznaV** [tidyverse/readr#654]
I use `parse_number` from `readr` version 1.1.0.  When I try to parse number written in scientific notation  (e.g., 2e-6) where absolute value of exponent is high number, e.g. 10 or -6, the result is incorrect:

```
parse_number(5e-6)
## [1] 5

parse_number(2e5)
## [1] 2
```
When exponent is not far from zero, the resul is correct:
```
parse_number(5e-3)
## [1] 0.005

parse_number(2e4)
## [1] 20000
```

The problem persists if I try to parse big numbers:
```
readr::parse_number(20000000)
##  [1] 2
```

**Is this behavior expected for non-string input?**

**Comment by jimhester** [comment]
I don't think this is expected, looks like a bug to me.

**Comment by jiho** [comment]
This is also true for integers stored in scientific notation

```
> parse_double("56067e3")
[1] 56067000
> parse_integer("56067e3")
Warning: 1 parsing failure.
row col               expected actual
  1  -- no trailing characters     e3

[1] NA
attr(,"problems")
# A tibble: 1 x 4
    row   col               expected actual
  <int> <int>                  <chr>  <chr>
1     1    NA no trailing characters     e3
```

This problem is made particularly acute because `write_***` insists on writing integers in scientific notation.

**Comment by del** [comment]
As jiho points out, this is a really frustrating bug when using integers, because `write_delim` will create output that `read_delim` will then refuse to consume:

```
tmp = data.frame(a = 10*(1999:2001))
write_delim(tmp, "h:/workspace/daniel/tmp_test.txt", delim = "|")
tmp2 = read_delim("h:/workspace/daniel/tmp_test.txt", delim = "|", col_types = cols(a = col_integer()))
```

this generates the output:
```
Warning: 1 parsing failure.
row col               expected actual                               file
  2   a no trailing characters     e4 'h:/workspace/daniel/tmp_test.txt'
```

**Comment by jimhester** [comment]
This is now fixed by https://github.com/tidyverse/readr/pull/684 for character vector input, which is what `parsed_number()` is documented to accept. It doesn't really make sense to give `parse_number()` non-character input as in the first example, as the numbers are then parsed by R's built in parser. Regardless the examples you gave do work as expected even in that case.
