### ISSUE TITLE
Read from clipboard

### ISSUE THREAD

**Issue by danielsjf** [tidyverse/readr#656]
I was wondering if reading from a clipboard will be supported in the future? There was an [earlier issue](https://github.com/tidyverse/readr/issues/112) which provided a work-around, but it doesn't seem to work anymore.

```
> x <- readr::read_csv(file("clipboard"))
Error in read_connection_(con) : can only read from a binary connection
> x <- readr::read_csv(file("clipboard", open = 'rb'))
Error in file("clipboard", open = "rb") : 
  'mode' for the clipboard must be 'r' or 'w'
```

read_csv can only read from a binary connection while the connection itself only allows for non-binary connections.

Using the base functions, this is quite straightforward.

```
> x <- read.csv("clipboard", sep = '\t')
> x
  a b c
1 1 2 3
2 4 5 6
```

**Comment by jennybc** [comment]
Here's another workaround that uses [clipr](https://github.com/mdlincoln/clipr#readme) and works today:

``` r
library(tidyverse)
library(clipr)

txt <- "v1,v2\n1.1,1.2\n2.1,2.2"
read_csv(txt)
#> # A tibble: 2 × 2
#>      v1    v2
#>   <dbl> <dbl>
#> 1   1.1   1.2
#> 2   2.1   2.2
write_clip(txt)
read_csv(paste(read_clip(), collapse = "\n"))
#> # A tibble: 2 × 2
#>      v1    v2
#>   <dbl> <dbl>
#> 1   1.1   1.2
#> 2   2.1   2.2
```

**Comment by msberends** [comment]
May I ask why this will not be supported? 
`read_delim` is so much better than the base alternatives! Except for this fact...

**Comment by jimhester** [comment]
It is supported. Either use @jennybc's example of clipr (which works the same across platforms), or do it with readLines and `file("clipboard")`.

```r
read_csv(paste(readLines(file("clipboard"))), collapse = "\n"))
```

**Comment by msberends** [comment]
@jimhester That's a great suggestion. But why not comply with base R, so
```r
read_csv("clipboard")
```
would internally be treated as
```r
read_csv(paste(readLines(file("clipboard"))), collapse = "\n"))
```
?

It think it is far more convenient for users, and should not be too much work for the `readr` developers. I would even create a pull request myself if you would allow this translation 😉

**Comment by jimhester** [comment]
https://github.com/tidyverse/readr/pull/732 implements `read_csv("clipboard")` to read from the system clipboard.

```r
clipr::write_clip("a,b,c\n1,2,3")
readr::read_csv("clipboard")
#> # A tibble: 1 x 3
#>       a     b     c
#>   <dbl> <dbl> <dbl>
#> 1  1.00  2.00  3.00
```

**Comment by msberends** [comment]
You sir, are fantastic :+1:

**Comment by dataRangler** [comment]
@jimhester  "clipboard" or clipboard() no longer work on my windows 7 setup.    @jennybc 's workaround is still good.  

```
> readr::read_csv(clipboard())
Error in clipboard() : could not find function "clipboard"

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2    yaml_2.1.18   
```
