### ISSUE TITLE
col_skip() and subsequent incorrect column names

### ISSUE THREAD

**Issue by enbrown** [tidyverse/readr#658]
There is a strange interaction between the col_skip() function, subsequent column specifications, and column names in the warning output (and the problems() function output).

Here's a short test csv file (saved as 'test.csv')
```
A,B,C,D
1,,2,3
4,,'b',5
6,,8,9
```

The following function call
`read_csv('test.csv', col_types = cols('B'=col_skip(),'C'=col_integer()))`
results in the warning
```
Warning: 1 parsing failure.
row col   expected actual
  2   D an integer    'b'
```

Here, the warning references column *D* whereas it was column *C* that had the parsing failure. The resulting tibble appears correct. If column *B* was not skipped, then the warning is assigned the correct column name.

**Comment by enbrown** [comment]
Looks like this is a bug in the name_problems() function in `R/problems.R` at this line:

`problems$col <- all_colnames[problems$col]`

The `problems$col` index number refers to the column number in the final data frame however the column names (`all_colnames`) still include the names of those columns that are skipped.

**Comment by jimhester** [comment]
This seems to be fixed in the devel version.

``` r
library(readr)
read_csv("A,B,C,D
1,,2,3
4,,'b',5
6,,8,9", col_types = cols('B'=col_skip(),'C'=col_integer()))
#> Warning: 1 parsing failure.
#> row col   expected actual         file
#>   2   C an integer    'b' literal data
#> # A tibble: 3 x 3
#>       A     C     D
#>   <dbl> <int> <dbl>
#> 1     1     2     3
#> 2     4    NA     5
#> 3     6     8     9
```
