### ISSUE TITLE
Reading triangular matrix

### ISSUE THREAD

**Issue by carlganz** [tidyverse/readr#659]
Hello,

Sometimes symmetric matrices are presented in text files with just the lower or upper triangle of the matrix filled in with values. For example, here is a DAT file provided with [*Multivariate Analysis*](https://www.amazon.com/Applied-Multivariate-Statistical-Analysis-6th/dp/0131877151) by Johnson and Wichern:

```
  1.00  
  0.49  1.00  
  0.53  0.57  1.00  
  0.49  0.46  0.48  1.00  
  0.51  0.53  0.57  0.57  1.00  
  0.33  0.30  0.31  0.24  0.38  1.00  
  0.32  0.21  0.23  0.22  0.32  0.43  1.00  
  0.20  0.16  0.14  0.12  0.17  0.27  0.33  1.00  
  0.19  0.08  0.07  0.19  0.23  0.24  0.26  0.25  1.00  
  0.30  0.27  0.24  0.21  0.32  0.34  0.54  0.46  0.28  1.00  
  0.37  0.35  0.37  0.29  0.36  0.37  0.32  0.29  0.30  0.35  1.00  
  0.21  0.20  0.18  0.16  0.27  0.40  0.58  0.45  0.27  0.59  0.31  1.00
```

Based on this [SO answer](http://stackoverflow.com/questions/13863569/reading-a-symmetric-matrix-from-file-that-omits-upper-triangular-part) I can read this in with base R's `read.table` if I specify `fill=TRUE`, and my matrix has fewer than 5 columns since, from the docs, "The number of data columns is determined by looking at the first five lines of input..."

So if my matrix is greater than 5 columns, and I don't know this in advance (and therefore can't correctly set the length of `col.names`) then I am SOL.

I was hoping that `readr::read_table` might be robust enough to handle this sort of issue especially since I can choose `guess_max` arbitrarily, but I have not had any luck. 

Docs say that `read_table2` can handle rows of different lengths, but I am having trouble doing so.

```{R}
# file is the same as the above data
readr::read_table2(paste0("data-raw/", file), col_names = FALSE, guess_max = 100)
```
This gives me the first two columns plus warnings about additional columns in certain rows. 

Since the documentation says that `readr::read_table2` can handle rows of different lengths, I am guessing there is something equivalent to `read.table`'s `fill` parameter, but perhaps I am misunderstanding something.

Kind Regards,
Carl

**Comment by jimhester** [comment]
You don't need **readr** or `read.table()` for this, just use `scan()` and construct the matrix directly.

``` r
f <- tempfile()
cat(file = f,
"1.00
0.49  1.00
0.53  0.57  1.00
0.49  0.46  0.48  1.00
0.51  0.53  0.57  0.57  1.00
0.33  0.30  0.31  0.24  0.38  1.00
0.32  0.21  0.23  0.22  0.32  0.43  1.00
0.20  0.16  0.14  0.12  0.17  0.27  0.33  1.00
0.19  0.08  0.07  0.19  0.23  0.24  0.26  0.25  1.00
0.30  0.27  0.24  0.21  0.32  0.34  0.54  0.46  0.28  1.00
0.37  0.35  0.37  0.29  0.36  0.37  0.32  0.29  0.30  0.35  1.00
0.21  0.20  0.18  0.16  0.27  0.40  0.58  0.45  0.27  0.59  0.31  1.00")

x <- scan(f)
dims <- floor(sqrt(length(x) * 2))

m <- matrix(NA, dims, dims)
m[upper.tri(m, diag = TRUE)] <- x
m <- t(m)
m
#>       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
#>  [1,] 1.00   NA   NA   NA   NA   NA   NA   NA   NA    NA    NA    NA
#>  [2,] 0.49 1.00   NA   NA   NA   NA   NA   NA   NA    NA    NA    NA
#>  [3,] 0.53 0.57 1.00   NA   NA   NA   NA   NA   NA    NA    NA    NA
#>  [4,] 0.49 0.46 0.48 1.00   NA   NA   NA   NA   NA    NA    NA    NA
#>  [5,] 0.51 0.53 0.57 0.57 1.00   NA   NA   NA   NA    NA    NA    NA
#>  [6,] 0.33 0.30 0.31 0.24 0.38 1.00   NA   NA   NA    NA    NA    NA
#>  [7,] 0.32 0.21 0.23 0.22 0.32 0.43 1.00   NA   NA    NA    NA    NA
#>  [8,] 0.20 0.16 0.14 0.12 0.17 0.27 0.33 1.00   NA    NA    NA    NA
#>  [9,] 0.19 0.08 0.07 0.19 0.23 0.24 0.26 0.25 1.00    NA    NA    NA
#> [10,] 0.30 0.27 0.24 0.21 0.32 0.34 0.54 0.46 0.28  1.00    NA    NA
#> [11,] 0.37 0.35 0.37 0.29 0.36 0.37 0.32 0.29 0.30  0.35  1.00    NA
#> [12,] 0.21 0.20 0.18 0.16 0.27 0.40 0.58 0.45 0.27  0.59  0.31     1
```

**Comment by carlganz** [comment]
Neat, you learn something new every day.

For my use case, I have 100 .DAT files some of which are lower triangle, and some of which are not (and I don't know which are which ahead of time). 

Ideally I could load them with a function that is robust enough to handle either case (regular .DAT file or lower triangle .DAT file), but the `scan` solution for triangular .DAT files won't work for regular .DAT files, and the `read.table` solution for regular .DAT files won't work for the triangular .DAT files.

**Comment by jimhester** [comment]
In that case read the first two lines to determine if it is triangular or square and use the appropriate function. Both `readr::read_lines()` and `readLines()` take a parameter to restrict the number of lines returned.
