### ISSUE TITLE
Missing column-types vignette

### ISSUE THREAD

**Issue by meow9th** [tidyverse/readr#660]
Column types vignette appears to be missing, even though it is mentioned multiple times in existing documentation (e.g. `read_delim()`).

Checked in my local R:
```
> vignette("column-types")
Warning message:
vignette ‘column-types’ not found 
```
Checked on [CRAN](https://cran.r-project.org/package=readr):
![screen shot 2017-04-27 at 9 59 50 am](https://cloud.githubusercontent.com/assets/1068987/25494953/4c1c22fe-2b30-11e7-9d2f-748995df4027.png)

Checked on [GitHub](https://github.com/tidyverse/readr/tree/master/vignettes):
![screen shot 2017-04-27 at 10 00 54 am](https://cloud.githubusercontent.com/assets/1068987/25494994/71241e26-2b30-11e7-867a-7cb4165205ac.png)

Checked commit log, didn't see a message about removing the vignette, but did find an [old version](https://github.com/tidyverse/readr/blob/f1e6708ff42a77e98faba5386119060dba5ce931/vignettes/column-types.Rmd).

Hope I'm not going crazy, thanks!

**Comment by jimhester** [comment]
Yes seems to have been removed with 0d0a0981b, not sure it was intentional though.

**Comment by jimhester** [comment]
This information was rolled into the introduction documentation and references to the column-types vignette have been removed.
