### ISSUE TITLE
Make an all-NA variable logical

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readr#662]
It seems like a variable that is filled with `NA` should be logical not character.

``` r
readr::read_csv("v1,v2\nNA,NA")
#> # A tibble: 1 × 2
#>      v1    v2
#>   <chr> <chr>
#> 1  <NA>  <NA>
read.csv(text = "v1,v2\nNA,NA")
#>   v1 v2
#> 1 NA NA
sapply(read.csv(text = "v1,v2\nNA,NA"), class)
#>        v1        v2 
#> "logical" "logical"
```

I feel like I've raised this issue before and learned that the choice of character was somewhat deliberate? But now I can't remember why. Recent [tidyverse ingest discussion](https://github.com/tidyverse/tidyverse/issues/34#issuecomment-278463951) supports a default to logical.

Was thinking of this because googlesheets runs data through `readr::read_csv()` in some cases. Working to get consistent result from googlesheets, readxl, and readr for the same data.

**Comment by jimhester** [comment]
This behavior was defined in https://github.com/tidyverse/readr/commit/1f352e55df1df29481810b67e7cc8bcbfc385ee9, the rational seems to be that if the first X values are missing readr will guess a charcter vector, so if there are non-missing values later they won't be lost.

**Comment by jennybc** [comment]
Yes, this sounds familiar now. Is it prohibitive to do a check after the data has been read to detect all-`NA` columns and make them logical?

**Comment by jennybc** [comment]
I have a new example of why logical `NA` would really be better than character. At least in the "all `NA`" case.

I want to do this: `map_dfr(files, read_csv, .id = "card")` but cannot because there's a variable that is empty in some csv files (ergo, character `NA`s) and present in others (data is integer). So the row bind fails.

You can see the problem with `read_csv()` and `dplyr::bind_rows()` alone. It's also related to dplyr becoming very strict about coercions, which seems to be an intentional decision (see https://github.com/tidyverse/dplyr/pull/2209#issuecomment-260198877). readr's default to character and dplyr's refusal to coerce is an unfortunate combination. In this case, `read.csv()` (+ `rbind()` or `bind_rows()`) gives a more natural result.

``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-10-28

library(tidyverse)

df1 <- read_csv("x,y\n1,\n")
df2 <- read_csv("x,y\n3,4\n")
bind_rows(df1, df2)
#> Error in bind_rows_(x, .id): Column `y` can't be converted from character to integer
rbind(df1, df2) ## "works" but is wrong because now y is character
#> # A tibble: 2 x 2
#>       x     y
#>   <int> <chr>
#> 1     1  <NA>
#> 2     3     4

df1 <- read.csv(text = "x,y\n1,\n")
df2 <- read.csv(text = "x,y\n3,4\n")
rbind(df1, df2) %>% as_tibble()
#> # A tibble: 2 x 2
#>       x     y
#>   <int> <int>
#> 1     1    NA
#> 2     3     4
bind_rows(df1, df2) %>% as_tibble()
#> # A tibble: 2 x 2
#>       x     y
#>   <int> <int>
#> 1     1    NA
#> 2     3     4
```
