### ISSUE TITLE
Get write_lines() to write Windows new lines (CRLF)

### ISSUE THREAD

**Issue by Pablo-Leon** [tidyverse/readr#665]
I'm aware of Issue #87 on read_csv(), and it's correct that write functions use the same terminator, but sometimes you need to write a file for another program, that only understands CRLF lines.

So I would like to be able to specify a CRLF line terminator as an option on write functions.

Meanwhile, the hackish way :
     > write_lines(paste0(vData, "\r"), filePath)) 

Thanks for the great package.
- Pablo

**Comment by jimhester** [comment]
I think just using `base::writeLines()` would be the way to go if you really want `CRLF` terminated lines.

**Comment by Pablo-Leon** [comment]
Haha , forgot about base::* !

But base::writeLines() lack an EOL parameter so it will work while running on windows, not in linux.
Keeping my hack 'cause it works and is still faster (33%).

thanks
- Pablo

**Comment by jimhester** [comment]
? `writeLines(

**Comment by Pablo-Leon** [comment]
thanks!

**Comment by mr-majkel** [comment]
Hi, @jimhester  if I may suggest something - I would not use "sep" name for argument about end of line mark. "sep" is traditionally used in base R functions to state what is a separator between columns. Maybe we could "eol" instead?
