### ISSUE TITLE
Implement read_nonmem

### ISSUE THREAD

**Issue by dpastoor** [tidyverse/readr#67]
Hi Hadley,

Low priority question but might give you some user feedback.

I wanted to check with you to see if this was a reasonable implementation strategy based on your documentation:

Software I use has simulation output like the following (truncated) data below. Note no spaces before TABLE line, 1 space before column ID line, and 2 spaces before lines with data. This wrecks havoc on normal parsers

```
TABLE NO.  2
 ID          REP         TIME        DV          EVID        AMT         DOSE        FORM        SEX         WT          AGE         RNUM        IPRED
  1.0000E+00  1.0000E+00  0.0000E+00  0.0000E+00  1.0000E+00  1.0000E+02  1.0000E+02  0.0000E+00  1.0000E+00  5.6800E+01  2.8000E+01  2.0000E+00  1.3283E+03
  1.0000E+00  1.0000E+00  2.5000E-01  1.3273E+03  0.0000E+00  0.0000E+00  1.0000E+02  0.0000E+00  1.0000E+00  5.6800E+01  2.8000E+01  2.0000E+00  1.2945E+03
  1.0000E+00  1.0000E+00  5.0000E-01  1.2327E+03  0.0000E+00  0.0000E+00  1.0000E+02  0.0000E+00  1.0000E+00  5.6800E+01  2.8000E+01  2.0000E+00  1.2615E+03 
TABLE NO.  2
 ID          REP         TIME        DV          EVID        AMT         DOSE        FORM        SEX         WT          AGE         RNUM        IPRED
  1.0000E+00  1.0000E+00  0.0000E+00  0.0000E+00  1.0000E+00  1.0000E+02  1.0000E+02  0.0000E+00  1.0000E+00  5.6800E+01  2.8000E+01  2.0000E+00  1.3283E+03
  1.0000E+00  1.0000E+00  2.5000E-01  1.3273E+03  0.0000E+00  0.0000E+00  1.0000E+02  0.0000E+00  1.0000E+00  5.6800E+01  2.8000E+01  2.0000E+00  1.2945E+03
  1.0000E+00  1.0000E+00  5.0000E-01  1.2327E+03  0.0000E+00  0.0000E+00  1.0000E+02  0.0000E+00  1.0000E+00  5.6800E+01  2.8000E+01  2.0000E+00  1.2615E+03 
TABLE NO.  2
 ID          REP         TIME        DV          EVID        AMT         DOSE        FORM        SEX         WT          AGE         RNUM        IPRED
  1.0000E+00  1.0000E+00  0.0000E+00  0.0000E+00  1.0000E+00  1.0000E+02  1.0000E+02  0.0000E+00  1.0000E+00  5.6800E+01  2.8000E+01  2.0000E+00  1.3283E+03
  1.0000E+00  1.0000E+00  2.5000E-01  1.3273E+03  0.0000E+00  0.0000E+00  1.0000E+02  0.0000E+00  1.0000E+00  5.6800E+01  2.8000E+01  2.0000E+00  1.2945E+03
  1.0000E+00  1.0000E+00  5.0000E-01  1.2327E+03  0.0000E+00  0.0000E+00  1.0000E+02  0.0000E+00  1.0000E+00  5.6800E+01  2.8000E+01  2.0000E+00  1.2615E+03 
```

raw version of data [here](https://raw.githubusercontent.com/dpastoor/misc-datasets/master/nonmem_sim_small.vpc)

To attempt to handle this, I have tried the following implementation:
- read_lines()
- parse each line to remove leading whitespace and replace double spaces with commas 
- append line + '\n\' to a growing string (only if data so skip table and name lines)
- pass string to read_csv to get into data frame

Do you have any thoughts on a better implementation barring major c++ constructs

line parser

```
#include <Rcpp.h>
#include <boost/algorithm/string.hpp>
#include <string>
// [[Rcpp::depends(BH)]]
using namespace Rcpp;
// [[Rcpp::export]]
std::string clean_nonmem(std::vector<std::string> x) {
  int n = x.size();
  std::string str;
  std::string line_break = "\n";
  std::string table = "TABLE";
  std::string colname = "ID";
  for(int i = 0; i < n; ++i) {
  if(!boost::contains(x[i], table) && !boost::contains(x[i], colname)) {
    boost::trim(x[i]);
    boost::replace_all(x[i], "  ", ",");
    str.append(x[i]);
    str.append(line_break);
  }
  }
  return str;
}
```

in context of full reader function:

```
capture_colnames <- function(x, strip_flags = c("TABLE", "ID", "DV", "MDV", "EVID")) {
  no_table <- strip_flags[!(strip_flags %in% "TABLE")]
  flags <- paste0(no_table, collapse = "|")

  for (i in seq_along(x)) {
    if(isTRUE(as.logical(grep(flags, x[i])))) return(x[i])
  }
  warning("could not find column names")
  return(NULL)
}

#' read nonmem files easily
#' @param path path to file
#' @export
read_nonmem <- function(path) {
  lines <- readr::read_lines(path)
  col_name <- stringr::str_trim(capture_colnames(lines))
    col_name <- stringr::str_replace_all(col_name, "\\s+", ",")
    lines <- clean_nonmem(lines)
  readr::read_csv(text = paste0(col_name,"\n", lines))
}
```

These functions in package are [here](https://github.com/dpastoor/PKPDmisc/blob/master/R/readers.R)

and cpp implementation code mentioned above [here](https://github.com/dpastoor/PKPDmisc/blob/master/src/clean_nonmem.cpp)

**Comment by dpastoor** [comment]
BTW, if there is a better implementation strat (like using your parse_vector()) if you point me in the right direction I can give it a shot then add to the documentation for others to reference.

**Comment by hadley** [comment]
To me, this looks more like a fixed width file where you want to skip some lines. Let me think about it.

**Comment by dpastoor** [comment]
awesome thanks,

One thing I did realize, that implementation was buggy in that if there are negative values, one of the white spaces is removed (eg "1  2 -3").

I resorted to:

```
boost::trim(x[i]);
boost::trim_all(x[i]);
boost::replace_all(x[i], " ", ",");
```

to trim leading spaces, then multiple spaces,then replace with commas. Of course I could just trim to one space then pass in as a fwf with space separation at that point rather than also replacing to csv.

**Comment by hadley** [comment]
Given #121, maybe it's worth investing some time in a `read_nonmem()` function that works for a wide variety of nonmem output.  Can you provide more examples of the structure? Is it common to see the column headers repeated many times?  Why do you get the repeated lines starting with "TABLE"?

**Comment by dpastoor** [comment]
Absolutely -

First, here is the link to my solution that 'works':

* [cleaning](https://github.com/dpastoor/PKPDmisc/blob/master/src/clean_nonmem.cpp)
* [reading the file](https://github.com/dpastoor/PKPDmisc/blob/master/R/readers.R#L142)

That said, the tricky part with nonmem is there isn't a single type of output:

## Two primary 'file type' cases

# Typical output:

using @ronkeizer 's [hands on nonmem examples](https://github.com/ronkeizer/nonmem_examples)

either example will show that for a given run (controlled by the `<run.mod>`) will output a number of files, notably: `*.coi*`, `*.cov`, `*.ext`, `*.grd`, `*.lst`, `*.mod`, `*.phi`

You can note that the `*.coi *.cor *.cov` files all have the same format of 

```
TABLE NO.     1: First Order Conditional Estimation with Interaction: Problem=1 Subproblem=0 Superproblem1=0 Iteration1=0 Superproblem2=0 Iteration2=0
 NAME         THETA1       THETA2       THETA3       THETA4       THETA5       SIGMA(1,1)   OMEGA(1,1)   OMEGA(2,1)   OMEGA(2,2)
 THETA1        8.52824E-02 -7.41289E-02 -1.11339E-01 -5.79811E-01  5.59844E-01  0.00000E+00  6.08600E-02  0.00000E+00  7.55561E-02
 THETA2       -7.41289E-02  2.90189E+00 -2.10314E-01  2.42365E-01 -2.47892E-01  0.00000E+00 -2.28196E-01  0.00000E+00  3.29016E-01
 THETA3       -1.11339E-01 -2.10314E-01  2.95712E+01  5.31406E-02 -1.00804E-01  0.00000E+00 -2.30036E-01  0.00000E+00 -4.04863E-02
 THETA4       -5.79811E-01  2.42365E-01  5.31406E-02  5.55125E-02 -9.93211E-01  0.00000E+00  1.41371E-01  0.00000E+00  2.26601E-01
```

[example .cor file](https://github.com/ronkeizer/nonmem_examples/edit/master/Hands_onA/run100.cor) 

The `*.ext` file [shown here](https://github.com/UMCTM/phmx601_datasets/blob/master/NM-PP1/run002.ext) has a different indentation pattern to represent iterations, then the - 1xxx... files represent things like standard errors for the final iteration, this is simpler (model) version of the file mentioned in #121 

```
TABLE NO.     1: First Order Conditional Estimation with Interaction: Goal Function=MINIMUM VALUE OF OBJECTIVE FUNCTION: Problem=1 Subproblem=0 Superproblem1=0 Iteration1=0 Superproblem2=0 Iteration2=0
 ITERATION    THETA1       THETA2       THETA3       THETA4       THETA5       SIGMA(1,1)   OMEGA(1,1)   OBJ
            0  1.00000E+00  9.00000E+00  2.50000E+01  5.00000E+00  5.00000E+01  1.00000E-02  0.00000E+00    446.52963866013522
            5  1.09680E+00  9.47305E+00  2.61353E+01  4.14103E+00  4.15335E+01  1.12233E-02  0.00000E+00    284.70051607529342
           10  1.01174E+00  8.89413E+00  2.30515E+01  3.87800E+00  3.93404E+01  1.03710E-02  0.00000E+00    283.49793131385951
           15  1.03045E+00  8.99244E+00  2.36606E+01  3.90367E+00  3.99263E+01  1.03536E-02  0.00000E+00    283.48646037865342
           17  1.03039E+00  8.99200E+00  2.36583E+01  3.90340E+00  3.99240E+01  1.03479E-02  0.00000E+00    283.48645051959869
  -1000000000  1.03039E+00  8.99200E+00  2.36583E+01  3.90340E+00  3.99240E+01  1.03479E-02  0.00000E+00    283.48645051959869
  -1000000001  1.74028E-01  1.43640E+00  6.26800E+00  5.13291E-01  5.53128E+00  2.57397E-03  1.00000E+10    0.0000000000000000
  -1000000004  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  1.01724E-01  0.00000E+00    0.0000000000000000
```

Lastly, from the default output, there is also `*.phi` files which again change up the indentation scheme, shown [here](https://github.com/UMCTM/phmx601_datasets/blob/master/NM-PP1/run002.phi)

```
TABLE NO.     1: First Order Conditional Estimation with Interaction: Problem=1 Subproblem=0 Superproblem1=0 Iteration1=0 Superproblem2=0 Iteration2=0
 SUBJECT_NO   ID           ETA(1)       ETC(1,1)     OBJ
            1            1  0.00000E+00  0.00000E+00    80.651838509827471
            2            2  0.00000E+00  0.00000E+00    98.238106076793599
            3            3  0.00000E+00  0.00000E+00    104.59650593297761
```


## user defined table:

In a given run, a user will also define tables to output parameter values, get residuals, etc, these are shown in the `*tab*` files such as [catab100](https://github.com/ronkeizer/nonmem_examples/blob/master/Hands_onA/catab100)

these can be user defined for the separator, however very few to no people use the additional options and stick to the default

```
TABLE NO.  3
 ID          SEX         ETN         DV          PRED        RES         WRES
  1.0000E+00  1.0000E+00  1.0000E+00  1.2161E+00  0.0000E+00  1.2161E+00  2.9410E-01
  1.0000E+00  1.0000E+00  1.0000E+00  1.2565E+01  0.0000E+00  1.2565E+01  3.0387E+00
  1.0000E+00  1.0000E+00  1.0000E+00  1.1218E+01  0.0000E+00  1.1218E+01  2.7129E+00
  1.0000E+00  1.0000E+00  1.0000E+00  1.7709E+01  0.0000E+00  1.7709E+01  4.2827E+00
```

notably, the 'frustrating' leading indentation pattern of no indent for Table, 1 space for the col headers, and 2 spaces for the rest of the rows.

**Comment by dpastoor** [comment]
## second type of output

The second type of output, as I noted in initial comment, is when doing repeated simulation replicates, nonmem handles results by appending the output to the existing file, resulting in table files as mentioned in my first comment, so to your question about the lines

for each rep you get:

`TABLE NO. 2` - row indicates that this was the 2nd user defined table requested for output
`<header row>`
`<results for that simulation rep.`
....

rinse, repeat.

I can give you larger simulation output tables via dropbox? or some other method. 



One last thing to note, is that I have not run into anyone dealing with outputs larger than 1 gb, even 100-200 MB is an 'edge' case for output size. The killer often is that when doing factorial clinical trial simulations there may be many such files for different scenarios so the read time adds up when parsing them to aggregate results.

**Comment by dpastoor** [comment]
@dmenne you tried my `PKPDmisc::read_nonmem()` function to see if that is sufficient? My benchmarks have shown it is somewhere between 13-20x faster than read.table, and is pretty 'robust' to all the different nonmem table idiosyncracies as it just blows them all away and converts to csv before parsing.

**Comment by hadley** [comment]
Hmmm, I think once `read_wsd()` exists, this is just a matter of using `comment = "TABLE"`

**Comment by dpastoor** [comment]
Agreed - would it also be possible to set 'comment' = '[A-Z]' or something along those lines to mark anything with a character column to start as a "comment", which would also handle the multiple sim tables appended issue.

The edge case I can forsee with the `read_wsd` is would it either have an arg or automatically trim leading whitespace?

**Comment by hadley** [comment]
Now I'm thinking it's better to write a custom tokenizer for nonmem files. Can you confirm that:

* The first line always starts with "TABLE"
* The "TABLE" line is always followed by a row of names
* "TABLE" is never indented

**Comment by dpastoor** [comment]
confirmed! 

however for full disclosure it is possible to do things like NOHEADER in the control file to not print out headers names, however these are usually only used in the context of suppressing because that users parser of choice cannot handle headers.

**Comment by hadley** [comment]
Does nonmen use missing values?

**Comment by dpastoor** [comment]
`.` is used for missing values

It can also only have have numeric output (including scientific notation) 


here is the snippet from the user guide regarding table formatting options:

![image](https://cloud.githubusercontent.com/assets/3196313/10049739/d4ff0fd8-61e6-11e5-923f-03cf6e193077.png)

however to my knowledge the only times these are used are when the parser available is insufficient, and regardless, given such a change (such as changing to format=,) would then allow the normal read_csv to be used regardless.

**Comment by hadley** [comment]
Ugh, my brain isn't in DFA writing mode at the moment, so it's taking me too long. I'm going to skip for now (work to date is in the nonmem branch) and I'll come back to it for the next release.

**Comment by dpastoor** [comment]
No problem! Still appreciate you even starting some work!

**Comment by hadley** [comment]
Realistically, it looks like this isn't going to get far up priority list to actually implement. Sorry 😕

**Comment by dpastoor** [comment]
Thats ok! On the usefulness spectrum compared to your other tools, this is extremely low anyway.

For others that stumble on this issue, please see

`read_nonmem()` from the PKPDmisc - https://github.com/dpastoor/PKPDmisc

in addition, the fread() function from the data.table package now handles non-normal whitespace, so the fortran and ext files output, that were unparseable when this request was started, can now be handled with fread as well.
