### ISSUE TITLE
Use dev version number

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readr#670]
I'm fiddling with tidyverse versions a lot right now and noticed that readr has not reset to a dev version since the v1.1.0 release. It's making it harder to quickly tell if I'm using the CRAN version or not.

**Comment by jimhester** [comment]
devtools::session_info can help with this as well, maybe we could have the sha in the tidyverse onload as well...

**Comment by jimhester** [comment]
Fixed by https://github.com/tidyverse/readr/commit/c4c5a88ea2b3b00f02ce78e97753caa61772bcce
