### ISSUE TITLE
col_logical does not recognize True and False as logicals

### ISSUE THREAD

**Issue by johndoe28** [tidyverse/readr#672]
If I specify a column type as col_logical(), the strings "True" and "False" are not recognized as logicals. Instead, readr complains that it expects 1/0/T/F/TRUE/FALSE. So, I am forced to read the columns as character and convert the columns using the as.logical function after the data has been read. This readr behavior is inconsistent with what as.logical expects because the documentation of as.logical states that character strings c("T", "TRUE", "True", "true") are regarded as true, c("F", "FALSE", "False", "false") as false, and all others as NA.

**Comment by jimhester** [comment]
I believe you are using an older version of readr, this is not the case in the latest CRAN release (1.1.0)

``` r
readr::parse_logical(c("T", "True", "true", "TRUE", "F", "False", "false", "FALSE"))
#> [1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE
packageVersion("readr")
#> [1] ‘1.1.0’
```

**Comment by johndoe28** [comment]
That is good to know. I am using version 1.0.0 which comes from Microsoft's R repository snapshot of 2017-03-15.  This is their default snapshot date for V 3.3.3 of R.
