### ISSUE TITLE
Standard evaluation `readr::cols`

### ISSUE THREAD

**Issue by robertamezquita** [tidyverse/readr#675]
Would it be possible to add an SE version of `cols` for use in making R packages? The obvious workaround is to simply use a `colnames` afterwards.

**Comment by jimhester** [comment]
`cols` doesn't use non-standard evaluation? Likely `do.call(cols, args)` where args is a named list will do what you are after. What are you trying to do?

**Comment by robertamezquita** [comment]
My bad, you're absolutely right, do.call is what I needed! Thanks ~
