### ISSUE TITLE
read_csv blank lines

### ISSUE THREAD

**Issue by hbeale** [tidyverse/readr#680]
If there are blank lines before a header, the header is recognized as such but also included as a row. I came across this in read_tsv, but the min example was easier in read_csv.

e.g. 

`read_csv("\n\nfileName,variableName,fileDescription\nmy.tsv,awesomeStuff,that awesome stuff i made")`
`# A tibble: 2 × 3`
`  fileName variableName           fileDescription`
`    <chr>        <chr>                     <chr>`
`1 fileName variableName           fileDescription`
`2   my.tsv awesomeStuff that awesome stuff i made`

It may not be an additional problem, but in my case I'm also using comments:
`read_csv("# this is a comment\n\nfileName,variableName,fileDescription\nmy.tsv,awesomeStuff,that awesome stuff i made", comment="#")`

**Comment by slonik-az** [comment]
I ran into this problem today. Very annoying behavior. read.csv has blank.lines.skip parameter. read_csv should have something similar.

**Comment by jimhester** [comment]
If you know the number of blank / comment lines use the `skip` parameter.

**Comment by jimhester** [comment]
Closed by https://github.com/tidyverse/readr/commit/6517708c7863887d13c09b8265fcff75213fa15e

**Comment by slonik-az** [comment]
* It is very dangerous and bug-prone to rely on knowing number of blank lines. I would not let such code through a code review.
* Empty lines can happen in the middle of the cvs file. In this case `skip` lines parameter is useless.

I still cannot get it -- why is it so difficult to skip over blank lines. What am I missing?

--Leo
