### ISSUE TITLE
vignette column-types

### ISSUE THREAD

**Issue by evelynmitchell** [tidyverse/readr#681]
#122 Need better help for col_types was closed with "I think a vignette is probably the best place".

Sometime after this, "See vignette("column-types") for more details." was added to the docs, but there is no such vignette, nor is there any explanation of column-types.

**Comment by Breza** [comment]
This is by no means an official answer, but I highly recommend R For Data Science, especially this chapter:
http://r4ds.had.co.nz/data-import.html
It offers an excellent introduction to readr's handling of different data types.

**Comment by jennybc** [comment]
There was indeed a column types vignette for a while, but its content has been incorporated into readr's main overview vignette:

http://readr.tidyverse.org/articles/readr.html
https://cran.r-project.org/web/packages/readr/vignettes/readr.html

**Comment by dewittpe** [comment]
The documentation was updated to reflect the absence of a `vignette("column-type")` in favor of the `vignette("readr")` between `v1.1.1` and 61a537e.

**Comment by jimhester** [comment]
Should now be fixed.

**Comment by bbrewington** [comment]
Correct me if I didn't look hard enough, but I wasn't able to find the part in the vignette where it explains the col_types shorthand version, where you could do something like this:
```r
read_csv("file.csv", col_types = "ccciid")
```

**Comment by boshek** [comment]
@bbrewington Here it is:

https://github.com/tidyverse/readr/blob/23eb46d1f9d487ad6d5cdc5b9375e72dcfdfd1a7/R/read_delim.R#L39-L43

**Comment by bbrewington** [comment]
@boshek it's like when I can't find my glasses and they're on my face haha.  Thanks!
