### ISSUE TITLE
feature request : select subset of variables when loading huge csv with read_csv

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/readr#687]
I am a bit surprised that `readr` does not allow me to select a subset of the variables I want to load.

The idea is that I have a huge `csv`, and loading everything would max out my ram. Instead, I want to load in `dplyr` only the variables I care about. 

Is this something you plan on working on?

**Comment by jimhester** [comment]
Use can use the short form `_` or `col_skip()` to skip a given column.

``` r
library(readr)
x <- "a\tb\tc\n1\t2\t3\n"
read_tsv(x, col_types = "n_n")
#> # A tibble: 1 x 2
#>       a     c
#>   <dbl> <dbl>
#> 1     1     3
read_tsv(x, col_types = cols(b = "_"))
#> # A tibble: 1 x 2
#>       a     c
#>   <dbl> <dbl>
#> 1     1     3
read_tsv(x, col_types = cols(b = col_skip()))
#> # A tibble: 1 x 2
#>       a     c
#>   <dbl> <dbl>
#> 1     1     3
```

**Comment by randomgambit** [comment]
OK thanks. But this is somewhat not optimal dont you think? More of the time one is in the situation where the number N of total variables is large, and the number m of wanted variables is small. Here it appears I need to type `a = col_skip(), b = col_skip()`, etc forever. Or am I missing something?

**Comment by jimhester** [comment]
```r
read_tsv(x, col_types = cols(b = "n", .default = col_skip()))
#> # A tibble: 1 x 1
#>       b
#>   <dbl>
#> 1     2
```

**Comment by jimhester** [comment]
And actually just remembered this is what `cols_only()` is for.
```r
read_tsv(x, col_types = cols_only(b = "n"))
#> # A tibble: 1 x 1
#>       b
#>   <dbl>
#> 1     2

**Comment by randomgambit** [comment]
thats great, you should really say that on the vignettes somewhere..

Thanks!
