### ISSUE TITLE
problems attribute not preserved by mutating?

### ISSUE THREAD

**Issue by MatthieuStigler** [tidyverse/readr#691]
Hi

It seems the `problems` attribute is not preserved by use of mutate. Is this is desired feature? The issue is that if a user does not call `problems` immediately, she might erroneously conclude the dataset was imported correctly? Maybe the `problems` attribute could be preserved, or have a warning if `problems` is called on a transformed `tibble` that lost its `problems` attribute?

    x <- read_csv("x\n1\n2\nb", col_types = list(col_double()))

    x %>% attr("problems")
    x %>% mutate(a=1) %>% attr("problems")

    problems(x)
    problems(mutate(x, a=1))

**Comment by jimhester** [comment]
This is not really a readr issue, problems attribute is dropped when sub-setting because of how the tibble subset function works. I don't think it is likely to change in the future. You should assume the problems will only exist right after reading a dataset.

**Comment by MatthieuStigler** [comment]
I guess the issue at the readr level is that the "problems" test relies on the absence of attribute, which can come from different situation a (having no problem, or having a problem but having used mutate afterwards). 

Would always returning a problem attribute, positive or negative, be a more stable approach? That would also allow to throw a warning when the attribute is away, that the problems function won't produce a reliable output?
