### ISSUE TITLE
Add `quiet` option to read_* functions.

### ISSUE THREAD

**Issue by gwarnes-mdsol** [tidyverse/readr#695]
I would like to be able to suppress the column type determination messages, particularly when executing code in batch mode.

**Comment by jimhester** [comment]
You can suppress it by specifying the column types explicitly, which is what you should do to ensure the data conforms to the types you except when running a script.

**Comment by gwarnes-mdsol** [comment]
Hi @jimhester,  it is best to specify this information to `read_*` when the the number and type of the columns are known.  However, this script reads some data files for which this information is not available, hence it is necessary to use the auto-type detection of `read_delim `.

Fortunately, I've discovered that the code uses R's `message` system, so the type determination messages can be silenced using `suppressMessages` and/or `suppressWarnings`.

**Comment by jimhester** [comment]
You can use `readr::read_csv("file", col_types = cols())` to turn off the printing in that case.
