### ISSUE TITLE
stdin, stdout (standard in, out, err) doesnt work in readr

### ISSUE THREAD

**Issue by xhudik** [tidyverse/readr#703]
```
write_delim(tibble(a=c(1,2)),path = stdout())

Error in stream_delim_(df, path, ...) : 
  'write' not enabled for this connection
```

read:
```
read_csv(stdin())

Error in read_connection_(con) : 
  Evaluation error: can only read from a binary connection.
```

similar question: https://stackoverflow.com/questions/35722765/is-it-possible-to-write-stdout-using-write-csv-from-readr - there is a workaround, but it looks strange.

Is there an easy way how to work with streams (stdin, stdout, stderr) in `readr`? Or, is this a bug?

**Comment by jimhester** [comment]
readr uses the connections API to read from connections, however that API only works with binary connections and `stdin()` and `stdout()` are text mode connections. We could potentially detect textmode connections and work around this, but for now you need to do it manually.

```r
writeLines(format_delim(tibble(a=c(1,2)), delim = ","), stdout())

read_csv(paste(collapse = "\n", readLines(stdin())))
```

**Comment by xhudik** [comment]
thank you for the fast reply - appreciated! I'm closing the issue
