### ISSUE TITLE
read_package

### ISSUE THREAD

**Issue by hadley** [tidyverse/readr#709]
Wrapper around `data()` that forces the promise. This is also a stronger parallel to loading data from a file, which is useful in intro courses.

cc @mine-cetinkaya-rundel

**Comment by hadley** [comment]
Maybe package should be the second argument and it should search attached packages by default (like `data()`)

**Comment by hadley** [comment]
And cc @garrettgman

**Comment by jimhester** [comment]
How is this related to https://github.com/tidyverse/readr/issues/664, are they the same thing?

**Comment by hadley** [comment]
Yes it's the same thing 😭
