### ISSUE TITLE
readr - parse_date - date_names

### ISSUE THREAD

**Issue by DevGri** [tidyverse/readr#711]
There are different month names for January is in Austria and Germany ("Jänner"/"Januar").
The solution is to build my own data_name object for Austria.

> mon <- c("Jänner", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember")
> monab <- c("Jän", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez")
> day <- c("Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag")
> dayab <- c("So", "Mo", "Di", "Mi", "Do", "Fr", "Sa")
> deAT <- date_names(mon, monab, day, dayab)
> deAT
<date_names>
Days:   Sonntag (So), Montag (Mo), Dienstag (Di), Mittwoch (Mi), Donnerstag
        (Do), Freitag (Fr), Samstag (Sa)
Months: Jänner (Jän), Februar (Feb), März (Mrz), April (Apr), Mai (Mai), Juni
        (Jun), Juli (Jul), August (Aug), September (Sep), Oktober
        (Okt), November (Nov), Dezember (Dez)
AM/PM:  AM/PM

It seems to be a correct data_name object. 
But a simple test failed!

> dt <- parse_date("24. Jänner 2014", format = "%d. %B %Y", locale = locale(date_names = deAT))
Warning: 1 parsing failure.
row # A tibble: 1 x 4 col     row   col            expected          actual expected   <int> <int>               <chr>           <chr> actual 1     1    NA date like %d. %B %Y 24. Jänner 2014

> problems(dt)
# A tibble: 1 x 4
    row   col            expected          actual
  <int> <int>               <chr>           <chr>
1     1    NA date like %d. %B %Y 24. Jänner 2014

What goes wrong?
A test with the language Germany succeeded.

> parse_date("24. Januar 2014", format = "%d. %B %Y", locale = locale(date_names = "de"))
[1] "2014-01-24"

The format argument seem to be correct.

**Comment by cderv** [comment]
Hi @DevGri, 

I don't know what is going wrong as the parsing happen in C function. 
However, I just wanted to help clarify the question on a formatting point of view as it will help people to see code and results. It will allow to reproduce easily the issue

### Markdown formatting for code
You could use backticks \` to format code like `this` or block of code like
```r
this
```
with 

    ```r
    this
    ```

You use `>` in your text which is for citation and not suitable for code
> this

### About reproductible example
Know that for R, you could use the excellent `reprex`  package to create easily some **Repr**oductible **Ex**amples
1. write your code in a script as independant code (with library call and all)
2. Copy your code
3. Call `reprex::reprex()` in the console or use the add-in in RStudio. A viewer will open with rendered code as it will be shown on github and put the right formatting to get this result in your clipboard.
4. Paste directly in a GH issue (it will paste ```r and all you need.)

See the [documentation](http://reprex.tidyverse.org/) for more insight and examples

**In your case you need the current dev version because you have special character. You need to install it 
with `devtools::install_github(tidyverse/reprex)`**

## Good formatting to clarify your issue
``` r
library(readr)
mon <- c("Jänner", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember")
monab <- c("Jän", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez")
day <- c("Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag")
dayab <- c("So", "Mo", "Di", "Mi", "Do", "Fr", "Sa")
deAT <- date_names(mon, monab, day, dayab)
deAT
#> <date_names>
#> Days:   Sonntag (So), Montag (Mo), Dienstag (Di), Mittwoch (Mi),
#>         Donnerstag (Do), Freitag (Fr), Samstag (Sa)
#> Months: Jänner (Jän), Februar (Feb), März (Mrz), April (Apr), Mai (Mai),
#>         Juni (Jun), Juli (Jul), August (Aug), September (Sep),
#>         Oktober (Okt), November (Nov), Dezember (Dez)
#> AM/PM:  AM/PM

# Do not work
dt <- parse_date("24. Jänner 2014", format = "%d. %B %Y", locale = locale(date_names = deAT))
#> Warning: 1 parsing failure.
#> row # A tibble: 1 x 4 col     row   col            expected          actual expected   <int> <int>               <chr>           <chr> actual 1     1    NA date like %d. %B %Y 24. Jänner 2014
problems(dt)
#> # A tibble: 1 x 4
#>     row   col            expected          actual
#>   <int> <int>               <chr>           <chr>
#> 1     1    NA date like %d. %B %Y 24. Jänner 2014

# Test with Germany
parse_date("24. Januar 2014", format = "%d. %B %Y", locale = locale(date_names = "de"))
#> [1] "2014-01-24"
```

With this formatting, you can copy the code and directly execute it in your environment or even better 
1. copy the block of code including results and comment
2. use `reprex::reprex_clean()` that will clean for you in your clipboard the code from the commented lines and write again in your clipboard
3. paste in a script : you have only the line of code from the reproductible example. 

Clever, isn't it ? And so much easier to help debugging.

Hope it helps.

**Comment by DevGri** [comment]
Thanks for your hints about formatting. I'm new in GitHub and have at this time no experience with markdown. But I will start reading about it. I am sure that this formatting rules will help other r developers to answer my issue. Thanks @cderv .

**Comment by jimhester** [comment]
So the issue is you were defining the new locale while you were using a non-UTF8 locale, and not specifying a `locale=` argument to `readr::locale()`. You can fix this by explicitly specifying the correct encoding in the call to `locale()`. In the following example I first run the code with a UTF-8 locale and it parses successfully. Then I run in a non-UTF-8 locale and the parsing fails. Then run by setting the encoding to match the session encoding and it again parses successfully.

``` r
library(readr)
Sys.setlocale(, "en_US.UTF-8")
#> [1] "en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8"
mon <- c("Jänner", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember")
monab <- c("Jän", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez")
day <- c("Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag")
dayab <- c("So", "Mo", "Di", "Mi", "Do", "Fr", "Sa")
deAT <- date_names(mon, monab, day, dayab)
parse_date("24. Jänner 2014", format = "%d. %B %Y", locale = locale(date_names = deAT))
#> [1] "2014-01-24"
Sys.setlocale(, "zh_TW.Big5")
#> [1] "zh_TW.Big5/zh_TW.Big5/zh_TW.Big5/C/zh_TW.Big5/en_US.UTF-8"
mon <- c("Jänner", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember")
monab <- c("Jän", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez")
day <- c("Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag")
dayab <- c("So", "Mo", "Di", "Mi", "Do", "Fr", "Sa")
deAT <- date_names(mon, monab, day, dayab)
parse_date("24. Jänner 2014", format = "%d. %B %Y", locale = locale(date_names = deAT))
#> Warning: 1 parsing failure.
#> row col            expected           actual
#>   1  -- date like %d. %B %Y 24. Jänner 2014
#> [1] NA
parse_date("24. Jänner 2014", format = "%d. %B %Y", locale = locale(date_names = deAT, encoding = "Big5"))
#> [1] "2014-01-24"
```

Created on 2017-12-11 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by DevGri** [comment]
Thanks for your answer! This answer give me the right hint to solve my problem.
It wasn't possible to set the locale of my **WINDWOS-PC** to **en_US.UTF-8**!

```r
Sys.setlocale("LC_ALL", "en_US.UTF-8")
Sys.setlocale("LC_ALL", "English_United States.UTF-8")
```
Both commands *didn't work on my operating system* ( ... request to set locale ... not honored).

But now I have an idea. I tried following statement:
``` r
library(readr)

(deDE <- date_names_lang("de"))
#> <date_names>
#> Days:   Sonntag (So.), Montag (Mo.), Dienstag (Di.), Mittwoch (Mi.),
#>         Donnerstag (Do.), Freitag (Fr.), Samstag (Sa.)
#> Months: Januar (Jan.), Februar (Feb.), MÃ¤rz (MÃ¤rz), April (Apr.), Mai
#>         (Mai), Juni (Juni), Juli (Juli), August (Aug.), September
#>         (Sep.), Oktober (Okt.), November (Nov.), Dezember (Dez.)
#> AM/PM:  vorm./nachm.
parse_date(c("24. Januar 2014", "12. MÃ¤rz 2016"), 
           format = "%d. %B %Y", 
           locale = locale(date_names = deDE, encoding = "Windows-1252"))
#> [1] "2014-01-24" "2016-03-12"
```
The encoding argument **Windows-1252** is mandatory. I got this hint from the solution before.
I define my own date_names (because the country Austria isn't available) to show "Jänner" instead of "Januar". Here is the code:

``` r
library(readr)

mon <- enc2utf8(c("JÃ¤nner", "Februar", "MÃ¤rz", "April", "Mai", "Juni", 
                  "Juli", "August", "September", "Oktober", "November", "Dezember"))
monab <- enc2utf8(c("JÃ¤n.", "Feb.", "Mrz.", "Apr.", "Mai.", "Jun.", 
                    "Jul.", "Aug.", "Sep.", "Okt.", "Nov.", "Dez."))
day <- enc2utf8(c("Sonntag", "Montag", "Dienstag", "Mittwoch", 
                  "Donnerstag", "Freitag", "Samstag"))
dayab <- enc2utf8(c("So.", "Mo.", "Di.", "Mi.", "Do.", "Fr.", "Sa."))

(deAT <- date_names(mon, monab, day, dayab))
#> <date_names>
#> Days:   Sonntag (So.), Montag (Mo.), Dienstag (Di.), Mittwoch (Mi.),
#>         Donnerstag (Do.), Freitag (Fr.), Samstag (Sa.)
#> Months: JÃ¤nner (JÃ¤n.), Februar (Feb.), MÃ¤rz (Mrz.), April (Apr.), Mai
#>         (Mai.), Juni (Jun.), Juli (Jul.), August (Aug.), September
#>         (Sep.), Oktober (Okt.), November (Nov.), Dezember (Dez.)
#> AM/PM:  AM/PM

parse_date(c("24. JÃ¤nner 2014", "12. MÃ¤rz 2016"), 
           format = "%d. %B %Y", 
           locale = locale(date_names = deAT, encoding = "Windows-1252"))
#> [1] "2014-01-24" "2016-03-12"
```
The solution to my problem on a **WINDOWS-PC** was to encoding all strings for the date_names function to **UTF-8**. This could be simple done with **enc2utf8**-Function.

I hope to help other with the same encoding problem.
remark: I used also the first time to format my code on GitHub with Markdown. Works nice!
