### ISSUE TITLE
read_csv2 implicitly uses ',' as decimal separator but this fact is not written in the Help.

### ISSUE THREAD

**Issue by alessandro-gentilini** [tidyverse/readr#714]
It seems to me that `read_csv2` implicitly uses `,` as decimal separator but this fact is not written in the Help.

I had a text file where the field delimiter is `;`, a field is a real number and the decimal separator in my text file is `.`.

I read the help and chose to use `read_csv2` because my delim is `;` but then the parsing of the field with the real number was wrong.

I got the warning message [Using ',' as decimal and '.' as grouping mark. Use read_delim() for more control.](https://github.com/tidyverse/readr/blob/v1.1.1/R/read_delim.R#L134) but I found it confusing.

I would like that the Help clearly states: 

> read_csv2 uses `,` as decimal separator.

I recognize that maybe this can be too subjective to be a bug.

**Comment by lgaborini** [comment]
So that's why `read_csv2` was not applying locale settings!

This is definitely confusing.

**Comment by jimhester** [comment]
Thanks, I tweaked the wording to explicitly state what values are used for what separators.
