### ISSUE TITLE
col_guess doesn't handle zero-inflated data well

### ISSUE THREAD

**Issue by eric-pedersen** [tidyverse/readr#716]
I work with several large data sets with data on species abundances (with one column for each species), that frequently have large numbers of zeros. This means that `read_csv` will frequently parse the column as an integer, as the bulk of the rows at the start of the entry are zero, even when the non-zero entries are doubles. These data sets often have too many columns for it to be efficient to specify the type of each one when coding, and can have enough data in them that increasing guess_max can slow things down.

Would it be possible to give parse_guess an option to be more conservative? For instance, specifying that it treats all numeric values as double, or all strings as character (to avoid automatically parsing things into dates)?

**Comment by jimhester** [comment]
The devel version of readr never guesses types of integer, so if that is the main issue you can use that. If you want to use a different form of guessing, the best option is to create a new function that constructs the list of column types yourself. Here is a version that converts all numeric values as double and strings as character.

``` r
library(readr)
write_tsv(iris, "iris.tsv")

is_numeric <- function(x) suppressWarnings(all(!is.na(as.numeric(na.omit(x)))))

simple_cols <- function(file, ..., guess_max = 1000) {
  data <- read_tsv(file, ..., col_types = cols(.default = col_character()), n_max = guess_max)
  lapply(data, function(x)
    if (is_numeric(x)) {
      col_double()
    } else {
      col_character()
    })
}
read_tsv("iris.tsv", col_types = simple_cols("iris.tsv", guess_max = 10))
#> # A tibble: 150 x 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl> <chr>  
#>  1         5.10        3.50         1.40       0.200 setosa 
#>  2         4.90        3.00         1.40       0.200 setosa 
#>  3         4.70        3.20         1.30       0.200 setosa 
#>  4         4.60        3.10         1.50       0.200 setosa 
#>  5         5.00        3.60         1.40       0.200 setosa 
#>  6         5.40        3.90         1.70       0.400 setosa 
#>  7         4.60        3.40         1.40       0.300 setosa 
#>  8         5.00        3.40         1.50       0.200 setosa 
#>  9         4.40        2.90         1.40       0.200 setosa 
#> 10         4.90        3.10         1.50       0.100 setosa 
#> # ... with 140 more rows
```

**Comment by eric-pedersen** [comment]
This is great, thanks! I'll try the devel version for this. I also didn't realize it would be that straightforward to write my own conversion function; glad to see it's pretty simple to do.

Cheers,

Eric
