### ISSUE TITLE
read_delim() : unable to retrieve a zipped CSV over HTTP

### ISSUE THREAD

**Issue by neveldo** [tidyverse/readr#720]
Hello,

First of all, thanks a lot for readr !

I think I have found a weird behaviour when trying to retrieve a zipped CSV over HTTP (from data.gouv.fr).

`read_delim('http://files.data.gouv.fr/sirene/sirene_2017002_E_Q.zip', ';')`

Returns : 

```
Parsed with column specification:
cols(
  `PK` = col_character()
)
Warning: 1891 parsing failures.
row # A tibble: 5 x 5 col     row          col  expected        actual                                                      file expected   <int>        <chr>     <chr>         <chr>                                                     <chr> actual 1     1 "PK\003\004"           embedded null 'http://files.data.gouv.fr/sirene/sirene_2017002_E_Q.zip' file 2     1         <NA> 1 columns     2 columns 'http://files.data.gouv.fr/sirene/sirene_2017002_E_Q.zip' row 3     2 "PK\003\004"           embedded null 'http://files.data.gouv.fr/sirene/sirene_2017002_E_Q.zip' col 4     3 "PK\003\004"           embedded null 'http://files.data.gouv.fr/sirene/sirene_2017002_E_Q.zip' expected 5     4 "PK\003\004"           embedded null 'http://files.data.gouv.fr/sirene/sirene_2017002_E_Q.zip'
... ................. ... ...................................................................................................... ........ ...................................................... [... truncated]
Error in rep(space, max_width) : argument 'times' incorrect
De plus : Warning message:
In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)
```

And `read_file('http://files.data.gouv.fr/sirene/sirene_2017002_E_Q.zip')`
 returns me a strange file content : 

```
[1] "PK\003\004\n"
```
If I download the file and then open it from my hard drive (`read_delim('~/sirene_2017002_E_Q.zip', ';')`), it works fine.

Moreover, I have already open sucessfuly some CSV (non zipped) from data.gouv.fr with read_delim() function.

thanks in advance !

**Comment by jimhester** [comment]
Only gz compressed files are supported over connections (using `base::gzcon()`), not zip archives. So this behavior is expected, you need to download zip files before opening them.

**Comment by neveldo** [comment]
Hello @jimhester ,

Thank you for your explanation. However, I think that the documentation should be updated to mention that point, for now, it's seems to be a little bit misleading : 

> Files ending in .gz, .bz2, .xz, or .zip will be automatically uncompressed.
