### ISSUE TITLE
Multicharacter separator/deliminator in Read_delim of Tidyverse?

### ISSUE THREAD

**Issue by Henri-Lo** [tidyverse/readr#721]
Older approaches such as [here](https://stackoverflow.com/questions/18186357/importing-csv-file-with-multiple-character-separator-to-r) without Tidyverse use custom solutions for reading in files with multichar separators or multichar deliminators. I assume the terms multicharacter separator and multicharacter deliminator to mean the same thing.

**What is the choice to read in files with multicharacter separators or multicharacter deliminators in Tidyverse such as read_delimn?**

**Comment by jimhester** [comment]
There is no support for multi-character delimiters in readr. Adding support would complicate the implementation considerably and there are not that many files using this format, so it is unlikely to be added in the future.

However in most cases it is quite simple for you to handle by transforming the multi character delimiters in a preprocessing step. Here two `;;` are used as the delimiter and it is transformed into the [ascii record separator](http://ascii-table.com/info.php?c=30), then read by `readr::read_delim()`.

``` r

lines <- "a;;b;;c\n1;;2;;3\n"
lines <- gsub(";;", "\036", lines)
readr::read_delim(lines, delim = "\036")
#> # A tibble: 1 x 3
#>       a     b     c
#>   <int> <int> <int>
#> 1     1     2     3
```
