### ISSUE TITLE
write_csv() and friends should be able to write a matrix

### ISSUE THREAD

**Issue by jstaf** [tidyverse/readr#723]
A lot of Bioconductor packages require working with matrices instead of dataframes. It would be a nice "quality of life" feature if `write_csv()` and similar functions were able to write matrices to csv/other formats. 

As it currently stands, you have to turn the matrix to a data.frame, and then convert the matrix rownames to a column before you can use `readr` functions (to prevent `readr` from stripping your identifying rownames), which makes base R functions like `write.csv()` much more convenient to use. It would be nice if `readr` functions could write matrices just as easily as they write dataframes.

**Comment by felasa** [comment]
I the meantime, `as_data_frame()` from tibble has a `rownames` argument that lets you preserve matrix rownames in a column.

**Comment by mjsteinbaugh** [comment]
@felasa Although I think it's recommend to simply use `mat %>% as_tibble(rownames = "XXX") %>% write_csv("mat.csv")`, especially for large datasets because the S3 method for tibble coercion is faster

**Comment by felasa** [comment]
TIL

**Comment by julian-urbano** [comment]
A little nudge to this one :+1:
Not just for Bioconductor; many times our own processes simply generate a matrix.

**Comment by mjsteinbaugh** [comment]
@julian-urbano Take a look at `rio::export()` or simply use `write.csv()` instead to write a matrix to disk in CSV format. The readr package is designed to work with tidy data classes, particularly `tbl_df`.

**Comment by julian-urbano** [comment]
Didn't know package `rio`. Looking great.
Thanks! :+1:

**Comment by KasperThystrup** [comment]
:+1:  for the idea, especially for the heavy use of rownames in Bioconductor. Why not just add an argument that allows for use of rownames? It seems extremely unintuitive that this function family, provide data tables that differs from the object in R!

**Comment by KasperThystrup** [comment]
+1 for the idea, especially for the heavy use of rownames in Bioconductor. Why not just add an argument that allows for use of rownames?

It seems very unintuitive that this function family exports data tables that differs from the object in R!

**Comment by mjsteinbaugh** [comment]
For reference, my [pipette](https://pipette.acidgenomics.com) package supports this in its `export()` function. Not yet up on CRAN or Bioconductor, but I'm working on it.

**Comment by jimhester** [comment]
While I can see how this might be useful, none of the other functions (reading or writing) in readr support matrices, so it seems out of scope to add for this particular use case.

In addition generally in Bioconductor import and export functions are specially written for the particular dataset for performance, so it seems likely support already exists for the most common data types.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:
