### ISSUE TITLE
Read into a 'melted' structure

### ISSUE THREAD

**Issue by nacnudus** [tidyverse/readr#724]
Thank you for this fantastic package.

Would you consider a PR for reading into a 'melted' structure?

``` r
readr::tokenize_melt("1,as\n3.3,2017-01-03,5\n\n6")
#> # A tibble: 6 x 4
#>     row   col      value data_type
#>   <int> <int>      <chr>     <chr>
#> 1     0     0          1   integer
#> 2     0     1         as character
#> 3     1     0        3.3    double
#> 4     1     1 2017-01-03      date
#> 5     1     2          5   integer
#> 6     2     0          6   integer
```

This form is useful when the source is ragged and/or has mixed data types within columns.  Once it has been read into R in this form, it can be traversed and transformed into something tidier.

I realise the readr purpose is 'Read Rectangular Text Data', but since the implementation would be a thin wrapper around existing C++ code, it would seem to belong here.  Otherwise would it be possible to use the readr headers from another package?

**Comment by jimhester** [comment]
Possibly, although this seems like a separate package to me. If you have the implementation mostly complete we could discuss it in a PR.

**Comment by jimhester** [comment]
Now merged
