### ISSUE TITLE
Suppress warnings if a column is missing

### ISSUE THREAD

**Issue by md0u80c9** [tidyverse/readr#725]
Hi,

I am importing in an R package a wide CSV file where the exporter can configure sets of columns on or off.

The problematic column is a team code which is an integer with sometimes a letter in (so guessing columns may result in this being wrongly interpreted as an integer column when it is a character column).

So I have specified the col type. The problem is of course that if the column is missing you get a warning.

I can’t see a way to get around this except using suppressWarnings - but doing that will remove a useful validation for malformed files.

Is there a way to mark a column definition as ‘optional’? And if it could I propose it as a development idea (so if that col type is missing no warning is generated, but any other missing ones would still generate errors).

**Comment by arendsee** [comment]
Perhaps in addition the the 'optional' flag, we could add 'required', as well. I often want an error, rather than just a warning, to be raised if certain columns are missing.

**Comment by bart1** [comment]
These would be great features. I encountered this issue while looking for this functionality for developing packages as well.

**Comment by bart1** [comment]
I just noticed that with the new `readr` being based on `vroom` this issue can be resolved in the same way it is in `vroom`: https://github.com/r-lib/vroom/issues/317

**Comment by jennybc** [comment]
Thanks for pointing out this new development @bart1!

``` r
library(readr)

read_csv(
  I("x,y\n1,2\n3,4\n"),
  col_types = list(
    x = col_double(),
    y = col_double(),
    z = col_double()
  )
)
#> Warning: The following named parsers don't match the column names: z
#> # A tibble: 2 × 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
#> 2     3     4

suppressWarnings(
  classes = "vroom_mismatched_column_name",
  read_csv(
    I("x,y\n1,2\n3,4\n"),
    col_types = list(
      x = col_double(),
      y = col_double(),
      z = col_double()
    )
  )
)
#> # A tibble: 2 × 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
#> 2     3     4
```

<sup>Created on 2021-12-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
