### ISSUE TITLE
Read .csv.zip from AWS S3

### ISSUE THREAD

**Issue by josiekre** [tidyverse/readr#727]
Appreciate this package so much!

I've got it working so that I can read directly from an S3 bucket using the aws.signature and aws.s3 packages. 

```
read_csv_s3 <- function(path){

  tryCatch({
    aws.signature::use_credentials()
  }, error = print)

  aws.s3::get_object(path) %>%
    rawToChar() %>%
    readr::read_csv(obj)
}
```

I'd like to do the same thing if the S3 object is a compressed file, but I cannot make sense of what needs to be used instead of, or in addition to, `rawToChar()`.  Suggestions?

**Comment by jimhester** [comment]
If `get_object(path)` is returning a raw vector you should do the following instead which avoids converting to character and reads the raw vector directly.

```r
readr::read_csv(readr::datasource(aws.s3::get_object(path)))
```

Probably the easiest thing to do is for compressed files is to write them to a file (with the extension) with `writeBin()`, then pass the filename to readr, which will handle creating the connections to read the compressed file. `readr:::standardize_path()` has the logic used and what connections are opened.

https://github.com/tidyverse/readr/blob/a16dfc791092eab4ba3dfd359b49ae11d93989c8/R/source.R#L105-L141
