### ISSUE TITLE
readr::read_csv issue: Chinese Character becomes messy codes

### ISSUE THREAD

**Issue by kk22boy** [tidyverse/readr#729]
I'm trying to import a dataset to RStudio, however I am stuck with Chinese characters, as they become messy codes. Here is the code:

```
library(tidyverse)
df <- read_csv("中文,英文\n英文,德文")
df
# A tibble: 1 x 2
  `\xd6\xd0\xce\xc4`            `Ӣ\xce\xc4`
               <chr>                  <chr>
1 "<U+04E2>\xce\xc4" "<U+00B5>\xc2\xce\xc4"
```

When I use the base function read.csv, it works well. I guess I must do something wrong with encoding. But there are no encoding option in read_csv, how can I do this?

**Comment by yutannihilation** [comment]
I answered on SO: https://stackoverflow.com/a/46999569/5397672

BTW, I wonder why we have to explicitly specify the encoding here. `file` argument should be translated into UTF-8 before passing it to C++.

**Comment by Sciurus365** [comment]
Chinese characters seem to be encoded using "GB2312" \:
`> df <- parse_character("中文,英文\n英文,德文")
> df
[1] "\xd6\xd0\xce\xc4,Ӣ\xce\xc4\nӢ\xce\xc4,�\xc2\xce\xc4"
> df <- parse_character("中文,英文\n英文,德文",locale=locale(encoding="GB2312"))
> df
[1] "中文,英文\n英文,德文"`
And it seems that the functions of readr::read_csv can not identify characters encoded by GB2312 automatically, while base::read,csv can.

**Comment by jimhester** [comment]
readr assumes character input is UTF-8 unless you specify a different encoding explicitly. This is done on purpose to ensure code is reproducible across systems.

@Sciurus365 Thank you for tracking down what the encoding of the characters actually was, I think this can be closed.

**Comment by yutannihilation** [comment]
@Sciurus365 Thanks for the information! But, I'm afraid this is not correct:

> while base::read.csv can.

Both `read.csv()` and `read_csv()` don't **identify** the encoding from the characters at all. Instead, they just **assume** the encoding (`read.csv()` bets on the system's default encoding and `read_csv()` bets on UTF-8) and, in this case, `read.csv()` won the bet.

However, while assuming and praying can be a good strategy for external resources, for character vectors that already on R's memory, I think we can **identify** their encoding by using the `Encoding()` attribute. This is the basic idea of my PR #730.

**Comment by yutannihilation** [comment]
@jimhester 

> This is done on purpose to ensure code is reproducible across systems.

I agree with this strategy, but I think such code as `read_csv("中文,英文\n英文,德文")` should be reproducible without specifying the encoding, I mean, should succeed not only on Linux and macOS but also on non-UTF-8 Windows. Please consider encoding the characters as UTF-8 before converting it to a `datasource()` (#730).
