### ISSUE TITLE
negative length vectors are not allowed

### ISSUE THREAD

**Issue by ilyasustun** [tidyverse/readr#731]
Using read_lines_raw gives me the following error:

```
Error in read_lines_raw_(ds, n_max = n_max, progress = progress) : 
  negative length vectors are not allowed
```

This happens only on a particular file, on other files it is OK. Can anyone help me? The question is asked on StackOverflow with more detail. 
https://stackoverflow.com/questions/46977977/read-lines-raw-negative-length-vectors-are-not-allowed

Thanks.

**Comment by jimhester** [comment]
Can you give the results of `traceback()`, after you see this error? That would help pinpoint exactly where the error is occurring. Ideally supplying the data you are trying to read would go furthest to fixing the problem.
