### ISSUE TITLE
Default col_double is overridden with col_integer

### ISSUE THREAD

**Issue by brisk022** [tidyverse/readr#736]
When default column type is explicitly set to `col_double`, `read_tsv` overrides it with `col_integer` if it determines that first 1000 values are integers. (Note: write_tsv saves 1000 as '1e3', which triggers an error when column type is set to `col_integer`.)

    dsOut <- data_frame(A = c(rep.int(1, 1000), 1000))
    write_tsv(dsOut, "a.txt")
    dsIn <- read_tsv("a.txt", col_types=c(.default = col_double()))

That results in a warning ("number of columns of result is not a multiple of vector length") and the column type is integer.

    spec(dsIn)
    # cols(
    #   A = col_integer()
    # )

If there is a double ('1e3' in this case) within the first 1000 values, everything works properly without warnings and the column is double.

    dsOut <- data_frame(A = c(rep.int(1, 999), 1000, 1000))
    write_tsv(dsOut, "b.txt")
    dsIn <- read_tsv("b.txt", col_types=c(.default = col_double()))
    spec(dsIn)
    # cols(
    #   A = col_double()
    # )

**Comment by jimhester** [comment]
You are not specifying the columns properly. You need to use `cols()` or `list()`, not `c()` to specify the columns.

``` r
library(readr)
c(.default = col_double())
#> list()
cols(.default = col_double())
#> cols(
#>   .default = col_double()
#> )

dsOut <- data.frame(A = c(rep.int(1, 1000), 1000L))
write_tsv(dsOut, "a.txt")
dsIn <- read_tsv("a.txt", col_types=c(.default = col_double()))
#> Warning in rbind(names(probs), probs_f): number of columns of result is not
#> a multiple of vector length (arg 2)
#> Warning: 1 parsing failure.
#> row # A tibble: 1 x 5 col     row col   expected               actual file    expected   <int> <chr> <chr>                  <chr>  <chr>   actual 1  1001 A     no trailing characters e3     'a.txt' file # A tibble: 1 x 5
spec(dsIn)
#> cols(
#>   A = col_integer()
#> )
dsIn <- read_tsv("a.txt", col_types=cols(.default = col_double()))
spec(dsIn)
#> cols(
#>   .default = col_double(),
#>   A = col_double()
#> )
```

In addition the devel version of readr no longer guesses columns to be type integer, which also resolves the issue.

**Comment by brisk022** [comment]
Indeed, thanks! That was a silly mistake on my part. One of those cases where type checking would have saved a lot of grief. :)
