### ISSUE TITLE
Parsing multiple date types

### ISSUE THREAD

**Issue by md0u80c9** [tidyverse/readr#737]
Hi,

Busy writing a piece of analysis which takes in CSVs produced from SQL Server. The date format is usually yyyy-mm-dd hh:mm .

However if the CSV file gets loaded into Excel by the users and resaved the date format becomes dd/mm/yyyy hh:mm.

There are about 50 date columns in the dataset - all will be in one for,at or the other.

Clearly the two formats are mutually exclusive.

is there a neat way to accept more than one date format?

**Comment by jimhester** [comment]
Not really, I would suggest reading the columns as characters and using the functions in lubridate to parse them into dates.

I don't think we want to support multiple possible date formats in readr.
