### ISSUE TITLE
read_log chokes on proxied web logs

### ISSUE THREAD

**Issue by jaearick** [tidyverse/readr#739]
Apache logs with no proxy gives one IP address, but proxied connections give two IP addresses in the log.  This causes read_log() to complain about extra columns during the read operation.  Example:

```r
library(readr)
logfile <- read_log("logfile",col_types=cols(.default="c"),col_names=FALSE,progress=FALSE)
```

with data:

```
Nov  3 00:02:26 vrpweb1 httpd: 131.253.25.174 - - [03/Nov/2017:00:02:25 -0400] "GET /geology/GE254/Dunes_2017.pptx HTTP/1.1" 200 38620803 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534+ (KHTML, like Gecko) BingPreview/1.0b"
Nov  3 00:02:26 vrpweb1 httpd: 47.29.65.34, 8.37.233.32 - - [03/Nov/2017:00:02:26 -0400] "GET /chemistry/PChem/notes/GibbsPhaseRule.pdf HTTP/1.1" 200 14470 "-" "Mozilla/5.0 (Linux; U; Android 7.0; en-US; Moto G (5) Plus Build/NPN25.137-67-5) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/11.4.8.1012 (SpeedMode) U4/1.0 UCWEB/2.0 Mobile Safari/534.30"
```
gives the following problem():

```r
> problems(logfile)
# A tibble: 1 x 5
    row   col   expected     actual            file
  <int> <chr>      <chr>      <chr>           <chr>
1     2  <NA> 15 columns 16 columns '~/Desktop/xxx'
```

The second line of the example data shows a proxied connection with two IP addresses.  These types of entries are somewhat rare in my Apache access logs, making them a problem for read_log().  It would be nice if coding magic in read_log could account for proxies.

My current workaround is to remove proxies from the data before using R, in Linux doing

grep -v "., [0-9]" < raw-log-file > file-for-R-program

**Comment by jimhester** [comment]
Unfortunately I don't think it will be possible to support this directly in readr. The way the log parser is written it expect all non-quoted spaces to delimit fields. You will have to preprocess the files in some way.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:
