### ISSUE TITLE
fatal error with read_table()

### ISSUE THREAD

**Issue by DDWetzel** [tidyverse/readr#740]
Hi,

i have the Problem, that i get a fatal error and Rstudio (an also R for Windows GUI front-end) crashes.

The only thing i did was to load "readr" and read my data (see appendix) in with read_table().

I was not sure how to report this Problem, especially with my data which causes this error.

I hope it is all right how i did this...
I have a minimal example:

----R-Code----
library(readr)
read_table("data.ALL")

----system-info----
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

-----Data----
[data.zip](https://github.com/tidyverse/readr/files/1456638/data.zip)
-----Picture-of-error-----
![fatal_error](https://user-images.githubusercontent.com/33509805/32593328-cd930136-c527-11e7-964d-7155e17b75bd.jpg)

**Comment by jimhester** [comment]
I can confirm the crash, however the data you are trying to read seems to be truncated, perhaps a download was not complete.

**Comment by DDWetzel** [comment]
thanks for the verification. The download was complete, but the data is indeed truncated and not how it should be. I obtain the date from a specific measurement tool and i get a few hundred datafiles and can not check them all. I just want to inform about the crash/bug.

**Comment by jimhester** [comment]
Ok should now be fixed!
