### ISSUE TITLE
Feature request: more powerful `col_*()` functions

### ISSUE THREAD

**Issue by nbenn** [tidyverse/readr#741]
This might be beyond the scope of readr, but is it being considered to introduce more powerful column specification?

Things I have in mind include:

- per column `na` parameter: we might want, for example to have `0` be a `NA` for one but not for other columns
  ```r
  col_spec(
    colA = col_integer(na = c("", "NA", "0")),
    colB = col_double()
  )
  ```
- guarantees: e.g. that a column contains no `NA` or no negative values
  ```r
  col_spec(
    colA = col_character(allow_na = FALSE),
    colB = col_integer(gte(0L))
  )
  ```
  the column parser would then thrown an error if any assertion fails.
- renaming a column: i.e.
  ```r
  col_spec(
    OrigColA = col_character(name = "new_col_a"),
    OrigColB = col_integer(name = "new_col_b")
  )
  ```

Of course all of this can be achieved after reading in the data with readr (or by reading everything as `.default = col_character()` and then using `parse_*()`), but then again, readr is all about simple and robust data import, so I feel like this could be useful to some.

**Comment by batpigandme** [comment]
> ```r
> col_spec(
>    colA = col_character(allow_na = FALSE),
>     colB = col_integer(gte(0L))
> ) 
> ```

I think the `allow_na = FALSE` could be tricky because it's unclear if you're removing the entire row (_i.e._ the record, in a tidy dataset), or just those values from a column.

**Comment by nbenn** [comment]
I wasn't talking about removing any data.

My idea was to be able to specify expectations (i.e. `colA` should not contain any `NA`) and have an error thrown if a violation is encountered.

This would in turn give me guarantees for any successful import.

**Comment by jimhester** [comment]
I agree this could be useful in principle. However in practice there are very few datasets which do not have a consistent value for missing data throughout. 

Unfortunately supporting this would require restructuring a good deal of the parsing logic, so is unlikely to happen.
