### ISSUE TITLE
Consider adding support for reading multiple header lines

### ISSUE THREAD

**Issue by javierluraschi** [tidyverse/readr#742]
From the [RStudio Importing Data Article](https://www.google.com/url?hl=en&q=https://support.rstudio.com/hc/en-us/articles/218611977-Importing-Data-with-RStudio&source=gmail&ust=1510705662773000&usg=AFQjCNH90i8ImOF11HMW7_hhbYJlYRuR5A):

<img width="654" alt="screen shot 2017-11-13 at 5 00 43 pm" src="https://user-images.githubusercontent.com/3478847/32757419-382cdbce-c894-11e7-9011-26b687a579a8.png">

**Comment by jimhester** [comment]
It is not really clear to me from the question what he would like done with the multiple header lines.

**Comment by jennybc** [comment]
I assume this is very much related to the multi-row header phenomenon in spreadsheets. That doesn't provide any immediate solutions here in readr. But it's a good reminder that the best solutions would lie outside packages like readr and readxl and, ideally, be usable from or with them.

**Comment by jimhester** [comment]
It seems like complicated headers like this are really a separate dataset that describes the columns and should be read separately.

We seem unlikely to ever support this directly in readr, so I am going to close this issue.
