### ISSUE TITLE
[Feature request] Date/hours format option for write_csv 

### ISSUE THREAD

**Issue by sibojan** [tidyverse/readr#745]
Right now, it writes the UTC date/hours. Hope to add the feature to write like write.csv to ensure back-compatibility.

**Comment by mgirlich** [comment]
You might want to have a look at `readr::output_column()`. This function already offers the possibility to manipulate the output as desired, e.g.

``` r
output_column.POSIXt <- function(x) {
  format(x, "My Time: %Y-%m-%d%H:%M:%OS", tz = "UTC")
}

csv <- format_csv(data.frame(time = Sys.time()))
cat(csv)
#> time
#> My Time: 2017-11-2405:21:59
```

**Comment by sibojan** [comment]
Thank you for the help. However, I found that that approach changes the behavior of output columns globally, affecting both **base::write.csv** and **readr::write_csv.**    It also becomes default unless you set it back. That seems to be cumbersome.  **readr::write_csv (data, path,  timeformat='xx')** is still desired.

**Comment by jimhester** [comment]
Our intention is for readr to produce standard format of files reproducible regardless of locale. If you want to write columns in a different format you will need to use a `output_column` method as suggested or use `format()` on your columns before writing with readr.
