### ISSUE TITLE
Update pkgdown site for correct link to vignette

### ISSUE THREAD

**Issue by cderv** [tidyverse/readr#751]
Hi, 

_jabowery_ reported on [rstudio.community](https://community.rstudio.com/t/readr-docs-link-to-vignette-404s/3081) a broken link to a non existing vignette in tidyverse `readr` website.

#661 has replaced all the reference, from  `vignette("column-types")` to `vignette("readr")`. However, website was not rebuild with pkgdown, so links are still wrong as there are no more _column types_ article on readr.tidyverse.org.

`pkgdown` needs to be rebuilt.

**Comment by batpigandme** [comment]
Thanks, @cderv. I just saw that on the community site, and it's super helpful to have this over here.

**Comment by hadley** [comment]
@jimhester can you please do?

**Comment by jimhester** [comment]
It has now been https://github.com/tidyverse/readr/commit/4d5e81c77fff7e5a56c6795c0e7377b7fbae685b, thanks for opening the issue and responding to the original question!
