### ISSUE TITLE
Explicitly state readr is UTF-8 by default, unless using locale()

### ISSUE THREAD

**Issue by pgensler** [tidyverse/readr#752]
cc @jimhester if you would like me to refactor the roxygen for this, please let me know and I'd be more than willing to help.

It would be extremely help if readr stated somewhere in the documentation that the read_csv and read_delim use UTF-8 as the default encoding, unless otherwise specified with the locale argument. And, if you are unsure about your file encoding:

```
#for mac os x
file -I <my_file>
#linux
file -i <my_file>
```
even use https://linux.die.net/man/1/enconv or https://www.gnu.org/savannah-checkouts/gnu/libiconv/documentation/libiconv-1.15/iconv.1.html
to go about fixing prior to uploading in R

readr assumes UTF-8 by default([here](https://github.com/tidyverse/readr/commit/9e1e2e29702fd162cab8651a8357bba5f111c824))

unless otherwise specified, in which case it goes haywire without the proper encoding
https://github.com/tidyverse/readr/issues/564

**Comment by batpigandme** [comment]
FTR, this is in the readr [Locales](http://readr.tidyverse.org/articles/locales.html#character) vignette.

> By default, readr assumes that your input is also in UTF-8.

This is also in the [`locale`](http://readr.tidyverse.org/reference/locale.html) object documentation, which is linked to both in the primary [function reference](http://readr.tidyverse.org/reference/read_delim.html), and the [arguments](http://readr.tidyverse.org/reference/read_delim.html#arguments) for the `read_delim` functions.

**Comment by pgensler** [comment]
@batpigandme Correct, but it does not show up in ```read_csv``` or ```read_lines_chunked``` in the locale arguments where I would expect it to say it defaults to UTF-8:

https://www.rdocumentation.org/packages/readr/versions/1.1.1/topics/read_delim

Yes, you can see it on the locales documentation for encoding, but I think it would save some time and much headache if it was explicit upfront.

**Comment by batpigandme** [comment]
Yeah, I'm not clear on how rdocumentation.org works. It _is_ in there, if you click on locales. in the documentation. I'm sure Jim can provide clarification, but, since it's a package-wide behaviour, you'd want to make sure it's cross-referenced in such a way as to avoid having to make changes in multiple places in the future.

**Comment by pgensler** [comment]
True. I can understand why you would not want it in two places, but it's also pretty complicated with using functions as arguments for other functions. I get that it makes the package more powerful, but  it also sends people down rabbit holes IMO, leading to issues like #564.

Personally, I think pandas does a good job of stating what the default values are for each function so you know instantly what the default behavior does, so maybe the line for the tidyverse needs to be a bit more refined as to how that looks because it has a different architecture? https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html

**Comment by jimhester** [comment]
The default argument to `locale` is `default_locale()`, and as mentioned `?default_locale` states the default is UTF-8.

Also you can simply run the function to see what the defaults are.

```r
readr::default_locale()
#> <locale>
#> Numbers:  123,456.78
#> Formats:  %AD / %AT
#> Timezone: UTC
#> Encoding: UTF-8
#> <date_names>
#> Days:   Sunday (Sun), Monday (Mon), Tuesday (Tue), Wednesday (Wed),
#>         Thursday (Thu), Friday (Fri), Saturday (Sat)
#> Months: January (Jan), February (Feb), March (Mar), April (Apr), May
#>         (May), June (Jun), July (Jul), August (Aug), September
#>         (Sep), October (Oct), November (Nov), December (Dec)
#> AM/PM:  AM/PM
```

I can't really justify the encoding as any more significant information than the other locale settings and we cannot add all of them to the `read_delim` documentation.

In general R functions typically don't list the defaults in the argument level documentation as the defaults are shown in the usage line. Here the default value has at least 7 settings which would have to be listed, it is not really practical to do so.

**Comment by yutannihilation** [comment]
I think what people get confused with is not readr's documentation, but the encoding itself. #564 is the typical example; what they don't understand was not the readr's default, but the actual encoding of the CSV. For example, how about improving the error message by including the suggestion of other possible encodings?

(That said, it's great if we can distinguish the case where the user intentionally set UTF-8 or not. c.f. #730)

**Comment by pgensler** [comment]
@yutannihilation I agree, I'm not entirely sure how to protect against these things other than being explicit with stating upfront UTF-8 is optimal encoding if possible. You could always use `rvest::guess_encoding` as a suggestion or simply say to use iconv. I think this is still a general pain-point with R, and definitely could use some sort of mechanism to handle encoding better within the tidyverse.
 
For example, I ran into a similar issue with tidyr's separate due to my file having an "No-Break-Space char" inside my string, which just made everything go absolute haywire for me. I know dplyr has had some issues with headers and encoding issues, but it would be nice to have a strategy around how to handle these issues.  
https://github.com/tidyverse/tidyr/issues/382
