### ISSUE TITLE
readr does not read columns with missing headers

### ISSUE THREAD

**Issue by brainfood** [tidyverse/readr#762]
Based on previous experience, I thought when readr was given a file where the header line had fewer columns than the rest of the file, it reads in all of the columns and assigns names (e.g. X3, X4) to the columns missing their headers. However, it seems reader is now dropping the columns with missing headers. Here's an example I pulled from the original issue that initiated the desired behavior (https://github.com/tidyverse/readr/issues/189):
```
read_csv("a,b\n1,2,3,4")
#> Warning: 1 parsing failure.
#> row # A tibble: 1 x 5 col     row   col  expected    actual         file expected
#> <int> <chr>     <chr>     <chr>        <chr> actual 1     1  <NA> 2 columns 4 columns literal data file
#> 
#> # A tibble: 1 x 2
#>       a     b
#>   <int> <int>
#> 1     1     2
#> Warning message:
#> In rbind(names(probs), probs_f) :
#>   number of columns of result is not a multiple of vector length (arg 2)
```
While read_csv does throw a warning identifying the problem, it still fails to read the columns with missing headers. In the original postings about issue 189, read_csv behaved correctly and read in all four columns, naming the last two columns X3 and X4, respectively. Did something change with readr recently, or is there an error in my code? Maybe a weird interaction with tibble?

Note, I'm using R v3.4.2 and readr v1.1.1.

edit: Cleaned up some weird formatting with the code example.

**Comment by jimhester** [comment]
From `git bisect` it looks like the behavior was inadvertently changed in https://github.com/tidyverse/readr/commit/ac24e9ed43b110b0666982af613971f361731c43 not long after it was initially introduced.

**Comment by brainfood** [comment]
Odd. I must have been getting this confused with cases where I had columns with the empty string in the header line, but the delimiters were still present.
```
read_csv("a,b,,\n1,2,3,4")
#> # A tibble: 1 x 4
#>       a     b    X3    X4
#>   <int> <int> <int> <int>
#> 1     1     2     3     4
#> Warning message:
#> Missing column names filled in: 'X3' [3], 'X4' [4]
```

**Comment by estroger34** [comment]
This might be related:

`read_* `functions also fail to read some colums if `col_names = FALSE` in messy text files (that I frequently have to deal with), where the typical number of colums and  `col_types` are known, but the initial rows contain a different number of columns than actually specified

``` r
library(readr)
#> Warning: package 'readr' was built under R version 3.6.2
read_csv("1\n1,2", 
         col_names = FALSE, 
         col_types = "ii")
#> Warning: Unnamed `col_types` should have the same length as `col_names`. Using
#> smaller of the two.
#> Warning: 1 parsing failure.
#> row col  expected    actual         file
#>   2  -- 1 columns 2 columns literal data
#> # A tibble: 2 x 1
#>      X1
#>   <int>
#> 1     1
#> 2     1

read_table2("1\n1 2", 
            col_names = FALSE, 
            col_types = cols(
              X1 = col_integer(),
              X2 = col_integer()
              ))
#> Warning: The following named parsers don't match the column names: X2

#> Warning: 1 parsing failure.
#> row col  expected    actual         file
#>   2  -- 1 columns 2 columns literal data
#> # A tibble: 2 x 1
#>      X1
#>   <int>
#> 1     1
#> 2     1
```

<sup>Created on 2020-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

What I would wish to obtain is the results I get from `read.table` with `fill = TRUE`, where missing columns in initial rows are filled with `NA`

``` r
library(readr)
#> Warning: package 'readr' was built under R version 3.6.2
write_file("1\n1,2\n", "test.int")

read.table("test.int", sep = ",", header = FALSE, fill = TRUE)
#>   V1 V2
#> 1  1 NA
#> 2  1  2
```

<sup>Created on 2020-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
You can work around this by explicitly specifying the column names

``` r
readr::read_csv("1\n1,2\n", col_names = c("V1", "V2"), col_types = "ii")
#> Warning: 1 parsing failure.
#> row col  expected    actual         file
#>   1  -- 2 columns 1 columns literal data
#> # A tibble: 2 x 2
#>      V1    V2
#>   <int> <int>
#> 1     1    NA
#> 2     1     2
```

<sup>Created on 2020-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Pomelo64** [comment]
I have encountered the same problem. The data.table::fread() can handle the situation very well, it adds "extra default column names at the end", while dplyr::read_tsv() just drop the extra columns.

**Comment by burgerga** [comment]
Same issue here, but a different use case: I'm trying to read txt files exported with `write.table(row.names = T)`, example:

``` r
library(tidyverse)
test = data.frame(letter = letters[1:2], digit = 1:2)
rownames(test) <- c("test1", "test2")
test
#>       letter digit
#> test1      a     1
#> test2      b     2

write.table(test, row.names = T) %>% 
  capture.output %>% 
  read_delim(delim = " ")
#> Warning: 2 parsing failures.
#> row col  expected    actual         file
#>   1  -- 2 columns 3 columns literal data
#>   2  -- 2 columns 3 columns literal data
#> # A tibble: 2 x 2
#>   letter digit
#>   <chr>  <chr>
#> 1 test1  a    
#> 2 test2  b
```

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

So it assigns the first colname to the rownames, and it skips the last column...

It would be very convenient if the output would be

``` r
#> # A tibble: 2 x 3
#>   X1    letter digit
#>   <chr> <chr>  <int>
#> 1 test1 a          1
#> 2 test2 b          2
```

**Comment by MattAFiedler** [comment]
The workaround offered by @jimhester no longer appears to work in readr 2.0.

``` r
library(readr)

with_edition(1, readr::read_csv("1\n1,2\n", col_names = c("V1", "V2"), col_types = "ii"))
#> Warning: 1 parsing failure.
#> row col  expected    actual         file
#>   1  -- 2 columns 1 columns literal data
#> # A tibble: 2 x 2
#>      V1    V2
#>   <int> <int>
#> 1     1    NA
#> 2     1     2

with_edition(2, readr::read_csv("1\n1,2\n", col_names = c("V1", "V2"), col_types = "ii"))
#> Warning: One or more parsing issues, see `problems()` for details
#> # A tibble: 2 x 1
#>      V1
#>   <int>
#> 1     1
#> 2    NA
```

<sup>Created on 2021-09-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jennybc** [comment]
I am still getting to know readr and vroom, the maintenance of which I inherited rather recently.

But my current impression is that many/most of the wishes in this thread are not easily granted within the current design.

In particular, I fear it's not practical to, e.g., parse the whole file and then set the number of columns as the max of what has been observed across all rows. The header row, the first data row, and the provided `col_names` / `col_types` are all used early on to set up structures into which tokens are parsed.

@jimhester gives a good snippet here that addresses one type of dysfunctional file: namely the case brought up by OP where the header row doesn't have enough fields / delimiters.

https://github.com/tidyverse/readr/issues/1328#issuecomment-973007918

``` r
text <- "Aldur;Fjöldi
0-5 ára;1.287;
6-12 ára;1.438;
13-16 ára;730;
17-24 ára;1.409;
25-34 ára;3.891;
35-66 ára;6.561;
67 ára og eldri;1.683;
Samtals;16.999;"

read_delim(text, delim = ";", skip = 1, col_names = strsplit(readr::read_lines(text, n_max = 1), ";")[[1]], locale = is_locale)
#> Rows: 8 Columns: 3
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ";"
#> chr (1): Aldur
#> lgl (1): X3
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 8 × 3
#>   Aldur           Fjöldi X3   
#>   <chr>            <dbl> <lgl>
#> 1 0-5 ára           1287 NA   
#> 2 6-12 ára          1438 NA   
#> 3 13-16 ára          730 NA   
#> 4 17-24 ára         1409 NA   
#> 5 25-34 ára         3891 NA   
#> 6 35-66 ára         6561 NA   
#> 7 67 ára og eldri   1683 NA   
#> 8 Samtals          16999 NA
```

The key idea is to use `skip = 1` to skip the usual reading of the header row. Then to take charge of reading the header row and process that into something suitable for `col_names`. I think maneuvers like this solve some of the scenarios in this thread.

As for the others, I'm going to classify them as out of scope for readr/broom.

For the poor souls with ragged files that aspire, yet fail, to be rectangular, I'm going to recommend the meltr package:

https://github.com/r-lib/meltr
