### ISSUE TITLE
Read bz2 anx xz compressed URLs

### ISSUE THREAD

**Issue by dhimmel** [tidyverse/readr#764]
Currently only remote gz files are supported (added in https://github.com/tidyverse/readr/commit/22d60358ad22379f81de06a7b5af400fc6de0270 / https://github.com/tidyverse/readr/issues/163).

From a user standpoint, it'd be nice to also be able to read xz and bz2 compressed files from URLs. Pandas (python) now supports reading tables from compressed URLs. Not sure if R base is equally capable?

**Comment by jimhester** [comment]
There is no xz or bz2 equivalent to `gzcon()` so right now no, this is not possible.
