### ISSUE TITLE
Tabs are not trimmed when trim_ws = TRUE

### ISSUE THREAD

**Issue by mirkhosro** [tidyverse/readr#767]
When using `read_csv` to read a CSV file that contains tabs on its rows, the `trim_ws` argument does not seem to have any effect. The tab characters do not get stripped anyway.
Take this CSV file for example
```
X,Y
x1,y1
x2	,y2
x3,y3	
x4,y4
```
There is a tab after `x2` and after `y3` (not visible). And the code below demonstrates the issue
```
> data <- read_csv("test.csv", trim_ws = TRUE, col_types = "cc")
> data[, 1]
# A tibble: 4 x 1
       X
   <chr>
1     x1
2 "x2\t"
3     x3
4     x4
> data[, 2]
# A tibble: 4 x 1
       Y
   <chr>
1     y1
2     y2
3 "y3\t"
4     y4
```
As you can see the tab characters are there and not trimmed.
I'm running the code using R 3.3.3 and readr 1.1.1. on macOS High Sierra.

**Comment by batpigandme** [comment]
Could you please turn this into a [reprex](http://reprex.tidyverse.org/) so we can be sure we're troubleshooting the exact same thing. Thanks

**Comment by mirkhosro** [comment]
Here  it is. I hope I've done it correctly.
``` r
library(readr)
csv_file <- "X,Y\nx1\t,y1\nx2,y2\t\nx3 ,y3 \n"
data <- read_csv(csv_file, trim_ws = TRUE, col_types = "cc")
data[, 1]
#> # A tibble: 3 x 1
#>        X
#>    <chr>
#> 1 "x1\t"
#> 2     x2
#> 3     x3
data[, 2]
#> # A tibble: 3 x 1
#>        Y
#>    <chr>
#> 1     y1
#> 2 "y2\t"
#> 3     y3
```

**Comment by mirkhosro** [comment]
(bump) this bug seems to be still there and left open, are you able to reproduce it using the reprex above?

**Comment by mirkhosro** [comment]
Thanks for the fix @jimhester . But it seems to only handle the space and tab characters and not "whitespace" in general. Wouldn't it better to capture white space using `\s` regex?

**Comment by jimhester** [comment]
No.

**Comment by mirkhosro** [comment]
Thanks for your extensive explanation :)
