### ISSUE TITLE
Better csvy support

### ISSUE THREAD

**Issue by hadley** [tidyverse/readr#770]
* provide high performance yaml header parser (https://github.com/leeper/csvy/issues/9) - probably in separate package

* review additional metadata (ie column descriptions) and think about how to specify in col specs

* round trip col specs to and from [table spec](https://specs.frictionlessdata.io/table-schema/)

(`read_csvy` would continue to live in csvy package, I think, but we could do more to support it)

**Comment by jimhester** [comment]
csvy doesn't really seem to have caught on, I think we can close this.
