### ISSUE TITLE
Values changes when read from equally spaced tab-file

### ISSUE THREAD

**Issue by TPreijers** [tidyverse/readr#771]
Somehow the read_table function in **readr** does not return the correct values when a tab-file with equally spaced numbers (!ONLY numerics) is read in. I've tried to debunk where this is going wrong, However, I couldn't follow it this far, since the read_tokens_ is imported from using c++-compiled files. The mentioned tab-file contains multiple columns with several values -99. These -99 values are turned into 99 (a change of sign). 

I hope this can be debugged!

```r
> tab1 <- read.table('cotab214', skip=1, header=T)
> tab1[4108:4117,"CREAT"]
 [1] -99 -99 -99 -99 -99 -99 -99 -99 -99 -99
> 
> tab2 <- read_table("cotab214", col_names = colnames(tab1), paste0(rep('d', length(colnames(tab1))), collapse = ''), skip=2)
> tab2[4108:4117,"CREAT"]
# A tibble: 10 x 1
   CREAT
   <dbl>
 1    99
 2    99
 3    99
 4    99
 5    99
 6    99
 7    99
 8    99
 9    99
10    99
```

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).
