### ISSUE TITLE
TSV with NULL values

### ISSUE THREAD

**Issue by danielsjf** [tidyverse/readr#773]
I have an obscure TSV that I'm trying to read and apparently it has some NULL values embedded. These are the first 100 bytes of the file (shortened with a hex editor): [test_file.txt](https://github.com/tidyverse/readr/files/1615081/test_file.txt) (I had to rename it to txt in order for github to accept it).

```r
file <- 'test_file.txt'

# read_tsv doesn't like the file. After a close inspection, it seems to block on the NUL as only the first character is rendered (y) (see below).
readr::read_tsv(file, n_max = 2)
#> Warning: Duplicated column names deduplicated: '' => '_1' [3], '' =>
#> '_2' [4], '' => '_3' [5], '' => '_4' [6], '' => '_5' [7], '' => '_6' [8],
#> '' => '_7' [9], '' => '_8' [10], '' => '_9' [11], '' => '_10' [12], '' =>
#> '_11' [13]
#> Parsed with column specification:
#> cols(
#>   y = col_character(),
#>   col_character(),
#>   `_1` = col_character(),
#>   `_2` = col_character(),
#>   `_3` = col_character(),
#>   `_4` = col_character(),
#>   `_5` = col_character(),
#>   `_6` = col_character(),
#>   `_7` = col_character(),
#>   `_8` = col_character(),
#>   `_9` = col_character(),
#>   `_10` = col_character(),
#>   `_11` = col_character()
#> )
#> Error in read_tokens_(data, tokenizer, col_specs, col_names, locale_, : Column 2 must be named

# read lines reads the first actual character 'y' and the file identifier characters that seem to parse as 'Ã¿Ã¾' in UTF-8
readLines(file, n = 1)
#> Warning in readLines(file, n = 1): line 1 appears to contain an embedded
#> nul
#> [1] "Ã¿Ã¾y"

# the problem is in the hidden NULL characters as the following command shows
readLines(file, n = 1, skipNul = T)
#> [1] "Ã¿Ã¾year\tmonth\tday\tDateTime\tAreaTypeCode\tAreaName\tMapCode\tPowerSystemResourceName\tProductionTypeName\tActualGenerationOutput\tActualConsumption\tInstalledGenCapacity\tSubmissionTS"

# readr's read_lines function ends the line at a NULL character, in contrary to what issue #338 seems to indicate
readr::read_lines(file, n_max = 1)
#> [1] "y"
```

read_lines is supposed to be fixed related to the NULs as #338 indicates. I am using the latest (non-developer) version of readr.

However, the higher level functions (read_tsv) also don't handle the NULs well.

Is there a work-around and is this issue supposed to be fixed in a future release?

**Comment by batpigandme** [comment]
What's the encoding on the file supposed to be?

**Comment by danielsjf** [comment]
UTF-8. Sublime text 3 correctly displays all the special characters (such as ó and Ñ) when I use UTF-8.

**Comment by danielsjf** [comment]
The encoding seems to only affect the first two bytes. After that it is UTF-8. The second problem is in the NULs that occur after each additional character. You can see it in the print screen of the hex editor.

![image](https://user-images.githubusercontent.com/6696142/34723079-8c835270-f549-11e7-904e-3366b31af30e.png)

**Comment by danielsjf** [comment]
Potentially related to #306 as notepad++ reports the encoding as UCS-2 LE BOM which seems to be a predecessor of UTF-16.

It is difficult to follow the progress of that issue since it was solved in the form of a PR that was then split into multiple pull requests.

**Comment by danielsjf** [comment]
When I try it with that encoding, I get a different error:

    file <- 'test_file.txt'
    tmp <- readr::read_tsv(file, n_max = 2, locale = readr::locale(encoding = "UCS-2"))
    #> Error in guess_header_(datasource, tokenizer, locale): Incomplete multibyte sequence

**Comment by jimhester** [comment]
Reader currently expects single byte line feeds and it will be a fair amount of work to add support for them, so for the meantime you will need to convert this file to UTF-8 before reading it.

**Comment by D3SL** [comment]
In the meantime would it be possible to amend the error message for null characters to just point users at ```base::read*``` functions which will gracefully take ```skipNul=TRUE```? There's shockingly little documentation about this issue, and the way the base function spells it ```nul``` rather than ```null``` means anyone searching for "null characters" will come up empty handed.

**Comment by jimhester** [comment]
This now works as you would hope, as long as you set the encoding to `UTF-16` appropriately. e.g.

``` r
library("readr")

file <- "~/p/readr/test_file.txt"

readr::read_tsv(file, n_max = 2, locale = locale(encoding = "UTF-16"))
#> Rows: 2 Columns: 13
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: "\t"
#> chr  (5): AreaTypeCode, AreaName, MapCode, PowerSystemResourceName, Producti...
#> dbl  (6): year, month, day, ActualGenerationOutput, ActualConsumption, Insta...
#> dttm (2): DateTime, SubmissionTS
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 2 x 13
#>    year month   day DateTime            AreaTypeCode AreaName MapCode
#>   <dbl> <dbl> <dbl> <dttm>              <chr>        <chr>    <chr>  
#> 1  2014    12    24 2014-12-24 13:00:00 CTA          REE CA   ES     
#> 2  2014    12    24 2014-12-24 12:00:00 CTA          REE CA   ES     
#> # … with 6 more variables: PowerSystemResourceName <chr>,
#> #   ProductionTypeName <chr>, ActualGenerationOutput <dbl>,
#> #   ActualConsumption <dbl>, InstalledGenCapacity <dbl>, SubmissionTS <dttm>
```

<sup>Created on 2021-05-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
