### ISSUE TITLE
Provide lists / vectors of col_types to cols function to support versioned CSVs

### ISSUE THREAD

**Issue by md0u80c9** [tidyverse/readr#774]
Hi,

Apologies if this is already implemented differently and I just can't find it...

Many thanks for the rlang package - it's extremely useful!

I've got a CSV file with multiple different versions in use where I'm writing a package to load the file in painlessly, tidy and aggregate it ready for analysis. Full files can be 300MB in size with 300 columns - I don't have control over the changes made to the CSV format.

I can establish which version is in use by doing a quick test read and checking the position and naming of certain columns.

With ~300 fields in the file, and probably 10 (and potentially more in future with a factorial combination of columns added or removed) different CSV versions in existence what I would prefer to do is to break up my cols specification into groups of cols definitions.

Let's say that version 1 just has MyColumn; and version2 has MyColumn and MyNewColumn in.

To load version 1 files, we would just load the columnTypes definitions. But for version 2 files we want to also include the column definitions in columnTypes2.

I was hoping that the cols syntax would be behaving list-like or vector-like, so I've tried the following examples:

```
columnTypes <- readr::cols(
MyColumn = readr::col_integer())
columnTypes2 <- readr::cols(
MyNewColumn = readr::col_character())

 importedData <- readr::read_csv(filename, col_names = TRUE, col_types = c(columnTypes, columnTypes2))
```

I've also tried:

```
columnTypes2 <- readr::cols(
MyNewColumn = readr::col_character())

columnTypes <- readr::cols(
MyColumn = readr::col_integer(),
columnTypes2)
 importedData <- readr::read_csv(filename, col_names = TRUE, col_types = columnTypes)

```

The other nice syntax way (which I appreciate doesn't work as it's not NSE) would be to use rlang features:
```

columnTypes <- readr::cols(
MyColumn = readr::col_integer(),
!!! columnTypes2)

```

Am I missing a neat way to achieve this? If it's not possible, do you think any of the methods above could be considered in future? Or any suggestions on suitable workarounds for the problem?

**Comment by jimhester** [comment]
`col_spec()` objects are just a 2 element named list

1. `cols`, a list of column specifications
2. `default`, a default column specification.

In your case you need to append the two `cols` lists together.
``` r
library(readr)
t1 <- cols(
  column_one = col_integer(),
  column_two = col_number())
t1
#> cols(
#>   column_one = col_integer(),
#>   column_two = col_number()
#> )

t2 <- cols(
  column_three = col_character())
t2
#> cols(
#>   column_three = col_character()
#> )

str(unclass(t1))
#> List of 2
#>  $ cols   :List of 2
#>   ..$ column_one: list()
#>   .. ..- attr(*, "class")= chr [1:2] "collector_integer" "collector"
#>   ..$ column_two: list()
#>   .. ..- attr(*, "class")= chr [1:2] "collector_number" "collector"
#>  $ default: list()
#>   ..- attr(*, "class")= chr [1:2] "collector_guess" "collector"
str(unclass(t2))
#> List of 2
#>  $ cols   :List of 1
#>   ..$ column_three: list()
#>   .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
#>  $ default: list()
#>   ..- attr(*, "class")= chr [1:2] "collector_guess" "collector"

t3 <- t1
t3$cols <- c(t1$cols, t2$cols)
t3
#> cols(
#>   column_one = col_integer(),
#>   column_two = col_number(),
#>   column_three = col_character()
#> )
str(unclass(t3))
#> List of 2
#>  $ cols   :List of 3
#>   ..$ column_one  : list()
#>   .. ..- attr(*, "class")= chr [1:2] "collector_integer" "collector"
#>   ..$ column_two  : list()
#>   .. ..- attr(*, "class")= chr [1:2] "collector_number" "collector"
#>   ..$ column_three: list()
#>   .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
#>  $ default: list()
#>   ..- attr(*, "class")= chr [1:2] "collector_guess" "collector"
```

Created on 2018-01-11 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by md0u80c9** [comment]
Ah - that's worked! Awesome, thank you for that!

**Comment by md0u80c9** [comment]
Would it be worth popping that in a vignette do you think?

**Comment by jimhester** [comment]
Maybe just as an additional example in `?cols`

**Comment by md0u80c9** [comment]
Agreed. I have submitted it as a PR (done live on GitHub but as it's trivial hopefully should be right first time :-).)
