### ISSUE TITLE
read_csv incorrectly parses the header row when importing compressed files?

### ISSUE THREAD

**Issue by hstojic** [tidyverse/readr#780]
Hello!

if I export `mtcars` as a csv: 
`write_csv(mtcars, "mtcars.csv")` 

and then create a compressed file with default Ubuntu archiver (on Ubuntu 16.04), when I try to import the file with:
`read_csv("mtcars.tar.gz")`

first column name is read in incorrectly and parsing failures are reported:
```R
Parsed with column specification:
cols(
  mtcars.csv = col_double(),
  cyl = col_integer(),
  disp = col_double(),
  hp = col_integer(),
  drat = col_double(),
  wt = col_double(),
  qsec = col_double(),
  vs = col_integer(),
  am = col_integer(),
  gear = col_integer(),
  carb = col_integer()
)
Warning: 2 parsing failures.
# A tibble: 2 x 5
    row        col   expected    actual                        file
  <int>      <chr>      <chr>     <chr>                       <chr>
1    33 mtcars.csv   a double                        'mtcars.tar.gz'
2    33       <NA> 11 columns 1 columns              'mtcars.tar.gz'
```

For `zip` or `gz` compression missing column name is reported instead.
Strangely, if I compress the file directly from R: `write_csv(mtcars, gzfile("mtcars.gz"))` then all seems in order. Anyone else encountered strange behavior with compressed files?

**Comment by jimhester** [comment]
`.tar.gz` is not the same thing as `.gz`, readr only reads compressed files, not archived and compressed files. You need to extract the file you want to read from the `tar` archive first.

**Comment by hstojic** [comment]
Hm, when I did some tests with `.gz` or `zip` I was getting similar behavior, but cannot replicate it now, it appears only with `tar`. 

Thanks, problem solved!
