### ISSUE TITLE
read_delim raises rbind warning

### ISSUE THREAD

**Issue by tres-pitt** [tidyverse/readr#782]
I noticed the issue while porting my code from 3.3.2 (x86_64-w64-mingw32) to 3.4.3 ( x86_64-redhat-linux-gnu). While there are many parsing errors/failures, these are expected (appearing in both versions) due to some very messy data, and `read_delim('pipe='|')` returns the correct number of rows, which is all I care about. The new warning is: 

`[In rbind(names(probs), probs_f) :`
`  number of columns of result is not a multiple of vector length (arg 1))`

**Comment by batpigandme** [comment]
Could you create a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample) for this? It will help us help you if we can be sure we're all working with/looking at the same thing.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/). The [reprex dos and don'ts](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) are also useful.

Thanks.

**Comment by tres-pitt** [comment]
That package looks awesome. Unfortunately, it's going to be a bit of a project to get a reproducible example, but I can probably find time in the next couple weeks

**Comment by batpigandme** [comment]
@tres-pitt sounds good. rstudio::conf is next week, so there might be a little slow down on our end as well!

**Comment by jimhester** [comment]
This warning message seems similar to other open issues https://github.com/tidyverse/readr/issues/754, so may already be fixed in the devel version of readr. You may want to try it to see if things are fixed.

```r
devtools::install_packages("tidyverse/readr")
```

**Comment by jimhester** [comment]
Sorry, that was a typo, I have edited my post to be accurate now :)
