### ISSUE TITLE
Removes leading spaces when writing/reading .csv

### ISSUE THREAD

**Issue by cameron-faerber** [tidyverse/readr#786]
If a character vector being read in has a value of say " a", the space is removed while reading in. The same goes for writing a .csv; the space is removed.

**Comment by jimhester** [comment]
Set `trim_ws = FALSE` when reading in the file.

When writing spaces are retained if they exist in the data.

``` r
 readr::format_csv(data.frame(a = " 1 "))
#> [1] "a\n 1 \n"
```

Created on 2018-01-29 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).
