### ISSUE TITLE
compile crashes

### ISSUE THREAD

**Issue by conchoecia** [tidyverse/readr#787]
Ran into this unpleasant bug on kite eating tree on rstudio server:

``` 
> install.packages("readr")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/readr_1.1.1.tar.gz'
Content type 'application/x-gzip' length 233793 bytes (228 KB)
==================================================
downloaded 228 KB

* installing *source* package ‘readr’ ...
** package ‘readr’ successfully unpacked and MD5 sums checked
** libs
g++  -I/usr/share/R/include -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Collector.cpp -o Collector.o
In file included from /usr/local/include/assert.h:5:0,
                 from /usr/local/lib/R/site-library/BH/include/boost/assert.hpp:58,
                 from /usr/local/lib/R/site-library/BH/include/boost/smart_ptr/shared_ptr.hpp:25,
                 from /usr/local/lib/R/site-library/BH/include/boost/shared_ptr.hpp:17,
                 from Collector.h:5,
                 from Collector.cpp:4:
/usr/local/include/except.h:15:32: error: conflicting declaration ‘typedef struct Except_Frame_T* Except_Frame_T’
 typedef struct Except_Frame_T *Except_Frame_T;
                                ^
/usr/local/include/except.h:15:16: note: previous declaration as ‘struct Except_Frame_T’
 typedef struct Except_Frame_T *Except_Frame_T;
                ^
/usr/local/include/except.h:17:18: error: field ‘prev’ has incomplete type ‘Except_Frame_T’
   Except_Frame_T prev;
                  ^
/usr/local/include/except.h:16:8: note: definition of ‘struct Except_Frame_T’ is not complete until the closing brace
 struct Except_Frame_T {
        ^
/usr/lib/R/etc/Makeconf:168: recipe for target 'Collector.o' failed
make: *** [Collector.o] Error 1
ERROR: compilation failed for package ‘readr’
* removing ‘/usr/local/lib/R/site-library/readr’
Warning in install.packages :
  installation of package ‘readr’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpfpHqtV/downloaded_packages’
```

**Comment by zeehio** [comment]
This issue does not look related to readr. It looks like there are broken headers installed in your server system.

After some googling, in this threads they are blaming GMAP/GSNAP software:

- https://github.com/hms-dbmi/dropEst/issues/2
- https://groups.google.com/forum/#!topic/bedtools-discuss/CURWF19qBuA

With a quick look at GMAP/GSNAP sources I see some headers that I believe should be provided by the compiler but they are bundled with GMAP/GSNAP instead. Those headers get installed when you install the software, overriding the system headers and messing with anything else you compile on the system. This is a bug in GMAP/GSNAP. For instance, in my computer I have `/usr/include/assert.h` provided by the GNU C Library, while in your computer the header file is found in `/usr/local/include/assert.h`. Usually apps compiled from source use `/usr/local` as installation directory.

Uninstall GMAP/GSNAP and try installing readr again. If you want to install GMAP/GSNAP again, please install it in a different directory out of the search path (using `./configure --prefix="/opt/gmap"`, see the GMAP README for details).

This is just a wild guess, I don't know anything about GMAP/GSNAP. If this fixes your issue you may want to report this to GMAP/GSNAP authors so they stop bundling system headers with their application.

**Comment by jimhester** [comment]
As noted this is an issue with the system libraries installed on your machine, not an issue with the readr package itself.
