### ISSUE TITLE
read_csv with ulimit on linux fails

### ISSUE THREAD

**Issue by rdisalv2** [tidyverse/readr#790]
Hi all,

if I have ulimit set at (say at 20gb using e.g. https://github.com/krlmlr/ulimit, though I have replicated the error by setting ulimit before starting R on the terminal) on my rsession and try to read in a large csv file with read_csv (say 20gb), I get this error:

```
> # devtools::install_github('tidyverse/readr')
> library(readr)
> ulimit::memory_limit(20000)
 soft  hard 
20000   Inf 
> read_csv('Appalachia_LT_Leases_Prj_Docs_5km.csv',n_max = 1000) -> temp
Error in guess_header_(datasource, tokenizer, locale) : 
  Cannot read file /media/zillow/commonshare/Appalachia_LT_Leases_Prj_Docs_5km.csv: Cannot allocate memory
```

The first 1000 rows of this file should be easily readable and read.csv(nrows=1000) works fine. I was wondering whether this is a known issue with the readr team. If it is not I'd be willing to follow-up with some more details. (this also affects read_csv_chunked, which has been somewhat more frustrating since I can't just drop back to read.csv so easily in that case).

Thanks!

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readr_1.2.0

loaded via a namespace (and not attached):
 [1] compiler_3.4.3  R6_2.2.2        hms_0.4.1       tools_3.4.3     pillar_1.1.0   
 [6] tibble_1.4.2    yaml_2.1.14     ulimit_0.0-3    Rcpp_0.12.15    pkgconfig_2.0.1
[11] rlang_0.1.6
```

**Comment by jimhester** [comment]
readr uses mmap, which basically means the whole file is allocated in virtual memory, regardless of what is actually used. See https://stackoverflow.com/q/2909955/2055486 for an example, there isn't anything we can really do about this situation except to increase your ulimit.

**Comment by rdisalv2** [comment]
Thanks. The
