### ISSUE TITLE
Potential bug with space (" ") in parse_factor levels

### ISSUE THREAD

**Issue by jasonserviss** [tidyverse/readr#792]
Not sure if this is expected but, this fails to parse the factor due to the space in the character vector specifying the levels:

<pre>
library(readr)
library(dplyr)
library(ggplot2)
library(tibble)
tibble(a = c("a", " b")) %>% 
mutate(a = parse_factor(a, levels = c("a", " b")))
</pre>

My use case:
Sometimes I have long names that I need to wrap and align in, for example, a plot legend:
<pre>
tibble(x = 1:2, y = 1:2, a = c("AAA\nAAAAAAAAAAAAA", "          AAA\nBBBBBBBBBBBBB")) %>%
ggplot() +
geom_point(aes(x = x, y = y, colour = a))
</pre>

If I want to change the order of the legend I would typically:
<pre>
tibble(x = 1:2, y = 1:2, a = c("AAA\nAAAAAAAAAAAAA", "          AAA\nBBBBBBBBBBBBB")) %>%
mutate(a = parse_factor(a, levels = c("AAA\nAAAAAAAAAAAAA", "          AAA\nBBBBBBBBBBBBB"))) %>%
ggplot() +
geom_point(aes(x = x, y = y, colour = a))
</pre>

but this fails to parse the factor as in the initial example. I tried with both the release (sessionInfo below) and devel (readr_1.2.0) versions of readr with similar results.

<pre>
sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.2.1 bindrcpp_0.2  dplyr_0.7.4   readr_1.1.1  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15      bindr_0.1         magrittr_1.5      hms_0.4.0         munsell_0.4.3     colorspace_1.3-2  R6_2.2.2          rlang_0.1.6       plyr_1.8.4        httr_1.3.1       
[11] tools_3.4.3       grid_3.4.3        rgeolocate_1.0.1  gtable_0.2.0      utf8_1.1.3        cli_1.0.0         digest_0.6.15     lazyeval_0.2.1    assertthat_0.2.0  tibble_1.4.2     
[21] crayon_1.3.4      curl_3.1          glue_1.2.0        labeling_0.3      compiler_3.4.3    pillar_1.1.0.9000 scales_0.5.0      jsonlite_1.5      pkgconfig_2.0.1 
</pre>

**Comment by jimhester** [comment]
This is fixed in the devel version by setting `trim_ws = FALSE`.

``` r

library(readr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
library(tibble)
tibble(a = c("a", " b")) %>% 
mutate(a = parse_factor(a, levels = c("a", " b"), trim_ws = FALSE))
#> # A tibble: 2 x 1
#>   a    
#>   <fct>
#> 1 a    
#> 2 " b"
```

Created on 2018-02-12 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).
