### ISSUE TITLE
Disable progress bar when in R-notebooks

### ISSUE THREAD

**Issue by jimhester** [tidyverse/readr#793]
https://community.rstudio.com/t/inline-notebook-display-is-slow-when-loading-data/5231

Hopefully the RStudio IDE sets an option we can use when code is running in a notebook, that we can add to `show_progress()` (I am pretty sure it does).

**Comment by huyunwei** [comment]
I spent hours to figure out why `readr::read_csv` is order of magnitude slower than `base::read.csv` , let alone `data.table::fread `
I reinstalled readr and tried all kinds of things, until I found the post mentioned above. It is clear in hindsight that interaction between the progress bar and the notebook kills the efficiency. 
The default should be disabling progress bar in Notebook environment.
