### ISSUE TITLE
strnlen on older macs

### ISSUE THREAD

**Issue by abelew** [tidyverse/readr#795]
Greetings,
  If one attempts to install readr on an older mac (I don't think it is ancient though -- it is 10.6.8), Iconv.cpp fails due to it missing strnlen().  I stole the strnlen from openbsd:
https://github.com/robertbachmann/openbsd-libc/blob/master/string/strnlen.c
and everything seems to work.
  I am not sure if this is worth spending time on, but I figured it is worth giving a heads-up.

**Comment by jimhester** [comment]
10.6.8 (Snow Leopard) was officially unsupported by Apple on February 25, 2014, so yes it is quite old.

I am glad you were able to find a workaround, but I don't think we are going to add the code to support this to readr.
