### ISSUE TITLE
Option for thousands separator in read_csv()

### ISSUE THREAD

**Issue by EricHe98** [tidyverse/readr#799]
Several times while working with datasets using readr's read_csv() function, I've had parse errors thrown because of unexpected commas being used as thousands separators. After guessing the column types to be doubles from the first 1000 rows, the function comes across a large numeric value which doesn't fit as a double because it has commas! To get around this, I have to specify the column type using the col_types argument. But sometimes it is not convenient to manually type out the column types for each feature.

In my case, the solution was to go upstream to my database manager and change the settings so that it does not write in thousands separators. But this isn't always possible for datasets someone might find in the wild.

The [pandas read_csv](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) command has an option to specify a thousands separator. I've found this extremely convenient for many datasets now, and frequently eliminates all parse errors. Is it possible to include a similar feature?

**Comment by batpigandme** [comment]
You can specify this using locale. In this case: `locale = locale(decimal_mark = ",")`, I believe. 

See in the docs (below) for detail:
http://readr.tidyverse.org/articles/locales.html#numbers

**Comment by cderv** [comment]
@batpigandme, for thousands separator, readr calls this _grouping_mark_ that can be also precise with `locale`
``` r
library(readr)
read_delim("X;Y\n2.5;3,456.3", delim = ";", locale = locale(grouping_mark = ","))
#> # A tibble: 1 x 2
#>       X     Y
#>   <dbl> <dbl>
#> 1  2.50  3456
# Which is , by default
read_delim("X;Y\n2.5;3,456.3", delim = ";")
#> # A tibble: 1 x 2
#>       X     Y
#>   <dbl> <dbl>
#> 1  2.50  3456

# behing the scene it is parse_number
parse_number("3,456")
#> [1] 3456
parse_number("3.456", locale = locale(grouping_mark = "."))
#> [1] 3456
```

However, as you can see,  `grouping_mark` should be comma by default. So it should work without using an argument in the case of @EricHe98.   
I think it is more something about guessing mechanism.  With readr, you precise column types and parser args with `col_type` argument, or you can increase the number of rows used for guessing column type using`guess_max` argument (`read_csv2("file.csv", guess_max = 1500)`). This way your values containing commas will be guess to use the parser `parse_number`

``` r
# a number with comma is guessed to be parsed with parse_number
readr::guess_parser("3,123")
#> [1] "number"
```

Hope it helps.
