### ISSUE TITLE
White space definition differs between read.csv() & read_csv()

### ISSUE THREAD

**Issue by saghirb** [tidyverse/readr#801]
There appears to be a difference in the way Base R `read.csv()` and `readr::read_csv()` define "white spaces". `help(read.csv)` and `help(scan)` provide a Base R white space definition but I could not find anything similar for `readr::read_csv()` (perhaps I missed it).

In the reprex example below there is space after each `,` (comma) in the csv file. `read.csv()` counts this towards what it reads in whereas `readr::read_csv()` does not. Both approaches have their logic but are they different by design?

Note: Below I am using `readr` version ‘1.2.0’ installed using `devtools::install_github("tidyverse/readr")`

```
library(tidyverse)
csvFile <- tempfile(fileext = ".csv")
csvSpace <- c('Date, City, Temp
"18/06/2017", "Lisbon", 23
"18/06/2017", "  Rome", 25
"18/06/2017", "Oslo", 12\n')
write_file(csvSpace, csvFile)

# `readr::read_csv()`
# Without trimming white spaces variable `Temp` is character.
space_csv_F <- readr::read_csv(csvFile, trim_ws = FALSE)
glimpse(space_csv_F)

space_csv_T <- readr::read_csv(csvFile, trim_ws = TRUE)
glimpse(space_csv_T)

# Base R `read.csv()`
# Temp is integer with or without stripping white spaces.
space.CSV.F <- read.csv(csvFile, stringsAsFactors = FALSE, strip.white = FALSE)
glimpse(space.CSV.F)

space.CSV.T <- read.csv(csvFile, stringsAsFactors = FALSE, strip.white = TRUE)
glimpse(space.CSV.T)
```

**Comment by batpigandme** [comment]
I think this is related to/possibly a duplicate of: https://github.com/tidyverse/readr/issues/397.

**Comment by saghirb** [comment]
@batpigandme I agree. Sorry I missed it in my review of issues. It seems the intention is to use the same definition of white spaces as for base R so I can close this issue.
