### ISSUE TITLE
Readr can't recognise some scientific notation properly

### ISSUE THREAD

**Issue by Carenser** [tidyverse/readr#803]
Hi!
I try to import numeric values from a database written in scientific notation with a blank when the exposant is positive :
> readr::parse_number(2.21140453307162E 003)
Error: unexpected input in "readr::parse_number(2.21140453307162E "

Is-it possible to expand the format catalog to recognize this format ?

**Comment by jimhester** [comment]
You need to wrap the number in quotes, e.g.
``` r
readr::parse_number("2.21140453307162E003")
#> [1] 2211.405
```

Created on 2018-02-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
