### ISSUE TITLE
Add readr_example() to the pkgdown site

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readr#809]
Seems like `readr_example()` should appear here?

http://readr.tidyverse.org/reference/index.html

**Comment by jimhester** [comment]
Yeah, not sure why it does not, perhaps the pkgdown site has not been rebuilt since the interal keyword was removed in https://github.com/tidyverse/readr/commit/cc020664e919afeab6b9e50c76c45d36a5f29c23

**Comment by jimhester** [comment]
Now done
