### ISSUE TITLE
Dealing with decimals in read_fwf()

### ISSUE THREAD

**Issue by hiltonmbr** [tidyverse/readr#811]
Could you add an option such as "decimal_places" in fwf_positions(start, end = NULL, col_names = NULL) and make sure that read_fwf() receive a vector of decimal places for each column and do the division: column/10^decimal ?
Thanks in advance!

**Comment by jimhester** [comment]
Thanks for filing this issue! Unfortunately, we are unlikely to ever have the time to implement this feature.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:
