### ISSUE TITLE
write_delim with delim= " " leads to a quotes issue

### ISSUE THREAD

**Issue by saghirb** [tidyverse/readr#812]
When using the `write_delim()` function with `delim= " "` [`space`] the output file, within a column, has quotes around the character variables where there is a space in the data but not otherwise. When the delimiter is set to a comma, semi-colon or colon,... then it does not "write" any quotes. 

```
library(tidyverse)
mydat <- tribble(
  ~colA, ~colB,
  "aaa",   1,
  "b b",   2,
  "ccc",   3
)

withColon <- tempfile(fileext = ".txt")
withSpace <- tempfile(fileext = ".txt")

write_delim(mydat, path = withSpace, delim =" ", col_names = FALSE)
write_delim(mydat, path = withColon, delim =":", col_names = FALSE)

file.show(withSpace)
file.show(withColon)
```

Would it be possible to force quotes or remove them with the risk that it leads to problems with the columns. When writing only one column and setting `delim = ":"` or some other character, the quotes are not "written".

**Comment by jimhester** [comment]
Fixed by a6c2080130cb6c3e29a4e89c636ab449ae958cfc, you can now force quoting for all character fields by using `quote = "all"`
