### ISSUE TITLE
read_csv: when the first section of a cell is quoted, the row is not parsed correctly

### ISSUE THREAD

**Issue by gregrs-uk** [tidyverse/readr#814]
In the examples below, cell 1 is always entirely unquoted, cell 3 is always entirely quoted and cell 2 has a particular section quoted.

If cell 2 has a quoted section at the end or in the middle, the row is parsed correctly.

``` r
library(readr)

read_csv('1,2,3\ncell 1,cell "2","cell 3"\n')

#> # A tibble: 1 x 3
#>   `1`    `2`          `3`
#>   <chr>  <chr>        <chr>
#> 1 cell 1 "cell \"2\"" cell 3
```

If cell 2 has a quoted section at the start, the row is not parsed correctly.

``` r
read_csv('1,2,3\ncell 1,"cell" 2,"cell 3"\n')

#> Warning in rbind(names(probs), probs_f): number of columns of result is not
#> a multiple of vector length (arg 1)
#> Warning: 3 parsing failures.
#> row # A tibble: 3 x 5 col     row col   expected           actual    file         expected   <int> <chr> <chr>              <chr>     <chr>        actual 1     1 2     delimiter or quote " "       literal data file 2     1 2     delimiter or quote c         literal data row 3     1 <NA>  3 columns          2 columns literal data
#> # A tibble: 1 x 3
#>   `1`    `2`                 `3`
#>   <chr>  <chr>               <chr>
#> 1 cell 1 "cell\" 2,\"cell 3" <NA>
```

Cell 2 should be `"cell" 2` and cell 3 should be `cell 3`.

**Comment by jimhester** [comment]
readr assumes the entire field is quoted if quotes appear. In this case you need to disable quoting by setting `quote = ""`.

``` r
readr::read_csv('1,2,3\ncell 1,"cell" 2,"cell 3"\n', quote="")
#> # A tibble: 1 x 3
#>   `1`    `2`          `3`         
#>   <chr>  <chr>        <chr>       
#> 1 cell 1 "\"cell\" 2" "\"cell 3\""
```

Created on 2018-03-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by gregrs-uk** [comment]
Thanks @jimhester. It only seems to assume the field is quoted if a quote appears at the beginning of the cell i.e. `"here" is the cell value` rather than anywhere else e.g. `here is the "cell" value` or `here is the cell "value"`. The latter two parse correctly and the cell value includes the quotation marks.

I'm trying to read a CSV file with less than ideal quoting i.e. unquoted cell values which themselves contain quotation marks, but I guess the best way will be to `read_csv` with `quote = ""` then sort out the mess afterwards!

**Comment by jimhester** [comment]
Then you are going to have to preprocess your data in some fashion, we do not support the format you describe.
