### ISSUE TITLE
At windows7, read_csv() keeps encoding of multibites colnames and select() can't treat it with unquoted expressions.

### ISSUE THREAD

**Issue by cuttlefish44** [tidyverse/readr#815]
Thank you for your works.

At my office PC, windows 7, when colnames (1st row of csv file) are Japanese, read_csv() keeps the encoding and select(), pull(), ..., can't treat them with unquoted expressions.
At my private PC, mac sierra, this problem doesn't happen.
I wonder this problem is made by read_csv(') or select(), but in any case I feel this is a bug.

Below is an example code (I can't show the output of reprex because of Garbled, sorry): 

``` r
library(tidyverse)
data_frame(てすと = 1:5, test = 1:5) %>% write_csv("test.csv")

d1 <- read_csv("test.csv", locale = locale(encoding = "utf-8"))
d2 <- read.csv("test.csv", fileEncoding = "utf-8")

list(d1, d2) %>% map(~ Encoding(names(.)))
# [[1]]
# [1] "UTF-8"   "unknown"
# [[2]]
# [1] "unknown" "unknown"

d1 %>% select(てすと)    # not work
# Error in FUN(X[[i]], ...) : object 'てすと' not found

d1 %>% select(test)      # work
d2 %>% select(てすと)    # work
```

**Comment by cuttlefish44** [comment]
Because no one have interests, I closed this issue and reprinted it into dplyr git.

**Comment by batpigandme** [comment]
Just adding the reprex here as well. Hopefully updating to dev versions solves this for you!
``` r
library(tidyverse)
data_frame(てすと = 1:5, test = 1:5) %>% write_csv("test.csv")
d1 <- read_csv("test.csv", locale = locale(encoding = "utf-8"))
#> Parsed with column specification:
#> cols(
#>   てすと = col_double(),
#>   test = col_double()
#> )
d2 <- read.csv("test.csv", fileEncoding = "utf-8")

list(d1, d2) %>% map(~ Encoding(names(.)))
#> [[1]]
#> [1] "UTF-8"   "unknown"
#> 
#> [[2]]
#> [1] "unknown" "unknown"

d1 %>% select(てすと)
#> # A tibble: 5 x 1
#>   てすと
#>    <dbl>
#> 1     1.
#> 2     2.
#> 3     3.
#> 4     4.
#> 5     5.
d1 %>% select("てすと")  # work
#> # A tibble: 5 x 1
#>   てすと
#>    <dbl>
#> 1     1.
#> 2     2.
#> 3     3.
#> 4     4.
#> 5     5.
d1 %>% select(test)      # work
#> # A tibble: 5 x 1
#>    test
#>   <dbl>
#> 1    1.
#> 2    2.
#> 3    3.
#> 4    4.
#> 5    5.
d2 %>% select(てすと)    # work
#>   てすと
#> 1      1
#> 2      2
#> 3      3
#> 4      4
#> 5      5
```
Created on 2018-03-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by cuttlefish44** [comment]
@batpigandme
Thank you for your response.
It isn't easy to install dev versions into the company PC but I'll try it to run my old code.

Thank you very much !!

**Comment by cuttlefish44** [comment]
I tried dplyr ver. 0.7.4.900 and I found it solves this problem about select(),
But unfortunately pull() and rename() still have the problem.

Below is an example code:

```
library(tidyverse)

data_frame(てすと = 1:5, test = 1:5) %>% write_csv("test.csv")
d1 <- read_csv("test.csv", locale = locale(encoding = "utf-8"))

d1 %>% select(てすと)        # run

d1 %>% pull(てすと)          # Error in eval_tidy(enquo(var), var_env) : object 'てすと' not found
d1 %>% rename(aaa = てすと)  # Error in .f(.x[[i]], ...) : object 'てすと' not found
```

**Comment by jimhester** [comment]
So this seems to be an issue with dplyr verbs rather than readr, so I am closing here. I think we are doing this correctly.
