### ISSUE TITLE
Feature Request: Give the Option of Reading Only Specific Columns in read_* Function Family

### ISSUE THREAD

**Issue by jtelleriar** [tidyverse/readr#816]
Imagine I have a 22 GB CSV, with 20 Columns, but I am only interested in 3 of them.

It would be useful to give the option in _readr_ package functions that:
* Although all columns are read at time of processing the data.
* Only "some" of them are saved into RAM memory, in order to save memory space.
* And the remaining columns are considered "dummy" variables, and are not imported into RAM (Although yes processed).

This could be easily achieved with an optional clause in read_* functions. e.g:
read_csv2("file.csv", restrict_columns = c("MyColumn_Name1", ..., "MyColumnNameN"))

In MySQL, for example, you can easily do this by assigning some of the CSV columns to dummy variables, which are overwriten with each register read, and not saved. 

It is fairly easy to implement, anyone interested in collaboration?

Thank you.
Juan

**Comment by batpigandme** [comment]
Just to clarify, is the difference here that you _wouldn't_ have to specify the columns that you want to skip (as below).

``` r
library(readr)
mtcars <- mtcars
head(mtcars)
#>                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
#> Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
#> Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
#> Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
#> Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
dim(mtcars)
#> [1] 32 11
write_csv(mtcars, "mtcars.csv")
mtcars_skipped <- read_csv("mtcars.csv", col_types = cols(
  cyl = col_integer(),
  disp = col_double(), drat = col_skip(),
  hp = col_integer(), mpg = col_double(),
  qsec = col_skip()
))

mtcars_skipped
#> # A tibble: 32 x 9
#>      mpg   cyl  disp    hp    wt    vs    am  gear  carb
#>    <dbl> <int> <dbl> <int> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21.0     6  160.   110  2.62    0.    1.    4.    4.
#>  2  21.0     6  160.   110  2.88    0.    1.    4.    4.
#>  3  22.8     4  108.    93  2.32    1.    1.    4.    1.
#>  4  21.4     6  258.   110  3.22    1.    0.    3.    1.
#>  5  18.7     8  360.   175  3.44    0.    0.    3.    2.
#>  6  18.1     6  225.   105  3.46    1.    0.    3.    1.
#>  7  14.3     8  360.   245  3.57    0.    0.    3.    4.
#>  8  24.4     4  147.    62  3.19    1.    0.    4.    2.
#>  9  22.8     4  141.    95  3.15    1.    0.    4.    2.
#> 10  19.2     6  168.   123  3.44    1.    0.    4.    4.
#> # ... with 22 more rows
```

Created on 2018-03-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jtelleriar** [comment]
Yes, did not notice you could use col_skip().

In such case, it could be interesting to add such feature in read_*
function documentation. Will check it out latter.

Thank you.

**Comment by batpigandme** [comment]
Yeah, it's in the Column Parsers section:
http://readr.tidyverse.org/reference/index.html#section-column-parsers

The function reference is [here](http://readr.tidyverse.org/reference/col_skip.html), but maybe we could make it easier to find.

**Comment by jimhester** [comment]
This is actually what `cols_only()` is for, it has a default column specification of skipping, so only columns you specify will be returned.

``` r
library(readr)
write_csv(mtcars, "mtcars.csv")
read_csv("mtcars.csv", col_types = cols_only(cyl = "i", disp = "d"))
#> # A tibble: 32 x 2
#>      cyl  disp
#>    <int> <dbl>
#>  1     6  160.
#>  2     6  160.
#>  3     4  108.
#>  4     6  258.
#>  5     8  360.
#>  6     6  225.
#>  7     8  360.
#>  8     4  147.
#>  9     4  141.
#> 10     6  168.
#> # ... with 22 more rows
```

Created on 2018-03-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jimhester** [comment]
`cols_only()` seems to be woefully under-documented however, I added some documentation at https://github.com/tidyverse/readr/commit/31dfea0f8cc3fde0449ef2a54be54cee5c3ce435, which should make this at least a little more discoverable.

**Comment by batpigandme** [comment]
Yeah, Jim I realised that once I started reading through the docs more closely. (>ლ)

**Comment by jtelleriar** [comment]
Great improvement in documentation. Thank you.
