### ISSUE TITLE
Have read_* functions parse non-traditional logicals

### ISSUE THREAD

**Issue by StevenMMortimer** [tidyverse/readr#818]
Functions like `read_delim()` and `read_csv()` do not recognize columns with logical data coded as "0/1" or "true/false", but it does recognize "T/F". This behavior is different than `parse_logical()` which accepts all of the examples listed above. Is it possible to have these functions parse similar to `parse_logical()`?

**read_delim() Behavior**
```
lines <- "a,b
A,true
B,true
C,false
"
read_delim(lines, ",")
# A tibble: 3 x 2
  a     b    
  <chr> <chr>
1 A     true 
2 B     true 
3 C     false
```

**Desired Behavior**
```
lines <- "a,b
A,true
B,true
C,false
"
read_delim(lines, ",")
# A tibble: 3 x 2
  a     b    
  <chr> <lgl>
1 A     TRUE 
2 B     TRUE 
3 C     FALSE
```

**parse_logical() Behavior**
```
readr::parse_logical(c("T", "F", "true", "false", 0, 1))
[1]  TRUE FALSE  TRUE FALSE FALSE  TRUE
```

**Comment by jimhester** [comment]
You need to specify the columns are logical types when you read the data.

``` r
library(readr)
lines <- "a,b
A,true
B,true
C,false
"
read_delim(lines, ",", col_type = "cl")
#> # A tibble: 3 x 2
#>   a     b    
#>   <chr> <lgl>
#> 1 A     TRUE 
#> 2 B     TRUE 
#> 3 C     FALSE
```

Created on 2018-03-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by StevenMMortimer** [comment]
Thanks, @jimhester, but I think you mistook my feature request for a question. I know about `read_delim(lines, ",", col_type = "cl")` (that's how I created the desired behavior block of code). I want to know why functions like `read_delim` are not smart enough to recognize non-traditional logicals on their own; however `parse_logical()` can. My feature request/enhancement is to replicate the `parse_logical()` behavior inside of `read_delim()` so it is more robust to different types of logicals.

**Comment by jimhester** [comment]
The guesser currently does this https://github.com/tidyverse/readr/blob/31dfea0f8cc3fde0449ef2a54be54cee5c3ce435/src/CollectorGuess.cpp#L35

But the parser does an insensitive compare
https://github.com/tidyverse/readr/blob/31dfea0f8cc3fde0449ef2a54be54cee5c3ce435/src/Collector.cpp#L294

So yes we could change the guesser to do the same. If you would like to open a PR to do this it would be great, if not we will get to it eventually, but it may take some time.

**Comment by StevenMMortimer** [comment]
Thanks for taking a second look, @jimhester. No rush on implementing.

**Comment by jennybc** [comment]
Here's how this is done in readxl, in case there is interest in doing same. It delegates the comparison back to R:

https://github.com/tidyverse/readxl/blob/ed499fb299934b2c3355e239644d118498edbdab/src/utils.h#L116-L126

**Comment by jimhester** [comment]
Thanks @jennybc, using `Rf_StringTrue` seems like a good idea

**Comment by jennybc** [comment]
@jimhester It was probably your idea 😁

**Comment by jimhester** [comment]
Oh yeah (https://github.com/tidyverse/readxl/pull/277#discussion_r104053499), still thank you for reminding me about it and using it for this!
