### ISSUE TITLE
Missing factor causes an rbind warning

### ISSUE THREAD

**Issue by md0u80c9** [tidyverse/readr#821]
Hi,

Using ReadR 1.1.1.

Create a minimal CSV file with one column and three factor values:
`
missingFactor
one
two
three
`

Then try to load it but forget to declare one of the factors:

`
 badCSV <- readr::read_csv(
     '../missingFactor.csv',
     col_names = TRUE,
     readr::cols(
         missingFactor = readr::col_factor(
             levels = c('one',
                        'two'))
     ))
`

Whilst you get the expected parsing failure warning that there is also an rbind warning that probably should be suppressed or handled differently.

`
Warning: 1 parsing failure.
row # A tibble: 1 x 5 col     row col           expected           actual file                   expected   <int> <chr>         <chr>              <chr>  <chr>                  actual 1     3 missingFactor value in level set three  '../missingFactor.csv' file # A tibble: 1 x 5

Warning message:
In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 2)
`

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

**Comment by jimhester** [comment]
I am pretty sure this is already fixed in the development version of readr. Please try installing it with `devtools::install_github("tidyverse/readr")`

**Comment by md0u80c9** [comment]
Hi jimhester,

You're quite correct - this is fixed in the development version. I'll close this.
