### ISSUE TITLE
read_csv not reading all columns

### ISSUE THREAD

**Issue by mohkar123** [tidyverse/readr#824]
I have a dataset which has the first row for some column empty and some columns filled. Due to this, while using read_csv,  it is not reading those columns and throwing a warning. This is very dangerous for larger datasets. For examples, I have 158 columns but its reading only 86. 
What is the solution for this? I tried setting default column types to character and it didn't solve it. Nor did any of the other datatypes. Is there a way to skip some rows for **guessing alone** (not skip the rows entirely)?

**Comment by jimhester** [comment]
Could you provide a reproducible example of the problem with a handful (< 10) of columns from your dataset.
