### ISSUE TITLE
[Feature] Standardize column names

### ISSUE THREAD

**Issue by pachevalier** [tidyverse/readr#826]
Very often, column names are not standardized. Some of them include blank spaces (eg "height of father"), some include accents (eg "Départements", "Région" in French datasets), etc. Those column names are not easy to manipulate in R and have to be standardized. 

I've developped  `set_standard_names()`, a function which I find very useful to remove all non ascii characters and blank spaces in column names.

The code behind the function is [here](https://github.com/pachevalier/tricky/blob/master/R/tibbles.R#L89) and it relies on  [`str_standardize`](https://github.com/pachevalier/tricky/blob/master/R/strings.R#L17). The documentation is [here](http://pachevalier.github.io/tricky/reference/set_standard_names.html).

For now, the function is in my personal package and therefore hardly discoverable. Do you think it would be relevant to include those functions in the `readr` package or in any other package of the `tidyverse` ?

**Comment by jimhester** [comment]
http://tibble.tidyverse.org/reference/tidy_names.html

**Comment by pachevalier** [comment]
Thanks for pointing me to this function. 

I've tested the differences between `set_standard_names()` and `set_tidy_names()` (http://pachevalier.github.io/tricky/articles/standard_names.html) and there are some differences  : 

* `set_standard_names()` removes accents. `set_tidy_names` doesn't.
* `set_standard_names()` replaces blank spaces with `_` where `set_tidy_names()` uses `.`

It's quiet surprising for me to since I've read in the [tidyverse's styleguide](http://style.tidyverse.org/syntax.html#object-names) that "variable and function names should use only lowercase letters, numbers, and _.". 

Do you think it would make sense to suggest improvement of the `set_tidy_names()` function ?

**Comment by pachevalier** [comment]
@batpigandme I'm not sure to understand your answer. I think that accents in column names are bad and that they should be removed. Don't you ?

**Comment by pachevalier** [comment]
I've seen in the `locale()` function that there is the option `asciify = TRUE`. Would it be possible to add this as an option to `set_tidy_names()` in order to remove diacritics characters ?

**Comment by jimhester** [comment]
I do not  think accents in column names are necessarily bad and there are definitely times when I would want to preserve them.

However I think an `asciify` option to `set_tidy_names()` might make sense, I would suggest you open an issue in the tibble package proposing it.
