### ISSUE TITLE
Failure to parse French numbers with parse_double() and parse_integer()

### ISSUE THREAD

**Issue by pachevalier** [tidyverse/readr#827]
In French, formatted numbers use a blank space as a grouping mark. I've tried to parse French numbers using `parse_double()` and `parse_integer()` functions but I've got an error. 

``` r
readr::parse_double(x = "1 123", locale = readr::locale(grouping_mark = " "))
#> Warning: 1 parsing failure.
#> row # A tibble: 1 x 4 col     row   col expected               actual expected   <int> <int> <chr>                  <chr>  actual 1     1    NA no trailing characters " 123"
#> [1] NA
#> attr(,"problems")
#> # A tibble: 1 x 4
#>     row   col expected               actual
#>   <int> <int> <chr>                  <chr> 
#> 1     1    NA no trailing characters " 123"
```

Created on 2018-04-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

It's weird since it works perfectly with function `parse_number()`  (https://github.com/tidyverse/readr/issues/796)

``` r
readr::parse_number(x = "1 123", locale = readr::locale(grouping_mark = " "))
#> [1] 1123
```

Created on 2018-04-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Why is the behavior of parse_double() different from the behavior of parse_number() ?

**Comment by batpigandme** [comment]
[`parse_number()`](http://readr.tidyverse.org/articles/locales.html#numbers) is the more flexible counterpart to `parse_double()` and `parse_integer()`

``` r
library(readr)
parse_number(x = "1 123", locale = locale("fr", grouping_mark = " "))             
#> [1] 1123
```
Created on 2018-04-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by pachevalier** [comment]
Ok
