### ISSUE TITLE
Can `cols()` take the full column type as an abbreviation

### ISSUE THREAD

**Issue by gergness** [tidyverse/readr#829]
I was hoping to write code that would do some tweaking to guess_parser's logic and then feed that into a column spec. However, the column spec only accepts the shortcuts for types (eg "i" for integer) but guess_parser returns the full name.

Can cols add the longer names as a shortcut too?

``` r
library(readr)
library(dplyr)

df <- data_frame(x = "1", y = "a")
type_convert(df, cols(x = "integer", y = "character"))
#> Error: Unknown shortcut: integer
```

Created on 2018-04-11 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

Example why this would be useful:
``` r
library(dplyr)
library(purrr)
library(readr)

df <- data_frame(x = "1", y = "a")

types <- map(df, guess_parser) %>%
  # Manual munging of types omitted to make example more minimal
  set_names(names(df))

readr::type_convert(df, do.call(cols, types))
#> Error: Unknown shortcut: integer



# Instead I have to do this:
df <- data_frame(x = "1", y = "a")

types <- map(df, ~recode(guess_parser(.), integer = "i", character = "c")) %>%
  # Manual munging of types omitted to make example more minimal
  set_names(names(df))

readr::type_convert(df, do.call(cols, types))
#> # A tibble: 1 x 2
#>       x y    
#>   <int> <chr>
#> 1     1 a
```

Created on 2018-04-11 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by batpigandme** [comment]
At the very least, you shouldn't have to make those abbreviations by hand:

From the readr [spec delim docs](http://readr.tidyverse.org/reference/spec_delim.html):
> Alternatively, you can use a compact string representation where each character represents one 
> column: c = character, i = integer, n = number, d = double, l = logical, D = date, T = date time, t = 
> time, ? = guess, or _/- to skip the column.

And in [create column specification](http://readr.tidyverse.org/reference/cols.html):
```r
# You can also use the standard abreviations
cols(a = "i")
#> cols(
#>   a = col_integer()
#> )
cols(a = "i", b = "d", c = "_")
#> cols(
#>   a = col_integer(),
#>   b = col_double(),
#>   c = col_skip()
#> )
```

**Comment by gergness** [comment]
I think we're on the same page now, but this is hopefully a better illustration of what I want:

``` r
library(readr)
library(dplyr)

df <- data_frame(x = "1", y = "a")

guess_parser(df$x)
#> [1] "integer"

# I'd like to be able to do this
type_convert(df, cols(x = guess_parser(df$x)))
#> Error: Unknown shortcut: integer
```

Created on 2018-04-11 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by jimhester** [comment]
Thanks for filing this issue! Unfortunately I don't think this issue is urgent enough for us to ever work on it.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:
