### ISSUE TITLE
Password Protected Excel Sheets

### ISSUE THREAD

**Issue by msmall318** [tidyverse/readr#830]
Hi,

Is there a way to read-in a password protected excel sheet (.xls or .xlsx) to R using the readr package (or another R package)? 

Regards,

Matt

**Comment by cderv** [comment]
Hi, 

In the tidyverse, reading excel files is not part of `readr` but `readxl`. `readr` is for flat file only. 

An advice: for this kind of question, do no hesitate to ask on Q&A site like https://community.rstudio.com. You'll have an awesome community who will share experience.

To get you some info regarding readxl 📦 , this is related to tidyverse/readxl#84. It seems it is not supported by readxl currently, and it is not planned by the tidyverse team. 
Know that there is other 📦 in R to read excel files. You could find one that deals with password protected one. It seems [excel.link](https://github.com/gdemin/excel.link) is one of them. I never tried it.

**Comment by msmall318** [comment]
Thank you for the help! I got my readr and readxl packages mixed up🤦🏻‍♂️.  I’ll look into excel.link.
