### ISSUE TITLE
How to: missing values on a column by column basis?

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/readr#831]
When calling `read_*` functions how to specify missing values column-wise?

I understand you can specify missing values with the `na` parameter with `parse_*` functions but not with `col_*`  functions, right? Is this by design?

What I am suggesting is to have something along these lines:

```r
col_date("%d/%m/%y", na = c("", "na", "null"))
```

Thanks in advance.

**Comment by jimhester** [comment]
Yes, there is no ability to select missing values on a column by column basis, and no current plans to add this functionality. I would suggest you either add all missing types to the global missing values, or if that is not possible disable auto detection of missing types and substitute them after reading per column as needed.

**Comment by ramiromagno** [comment]
OK. Thanks.
