### ISSUE TITLE
readr::write_csv

### ISSUE THREAD

**Issue by lsusatyo-gcmlp** [tidyverse/readr#832]
Setting both the append=TRUE and col_names=TRUE, achieves intended behavior by appending new rows to a file, however, the column names row is also duplicated for each append. This behavior is observed in the version 1.1.0

**Comment by cderv** [comment]
I think this why by default `col_names = !append`. If you want to append to an exisiting csv file you do not want to write column names. If you force `col_names = TRUE`, you are forcing the writing of column names. Hence the duplicated row. I do not think it is a bug but rather a question of behavior that may or may not be changed.

Maybe something can be done about that to put a warning or something else but I find the behavior rather consistent. Out of curiosity, can you provide the example of code of your use case for that ? 

A least, if it stays that way, documentation of `write_csv` could be improve to add precision on this behavior.

**Comment by lsusatyo-gcmlp** [comment]
I agreed, that the behavior is as expected, but in my special situation, I am setting the append=TRUE, and prefer to let the function to check itself whether the file is new or not, and if it's a new file, a column name should be written out, and it doesn't that's why i set the col_names = TRUE which then cause this secondary effect that started this conversation.

**Comment by lsusatyo-gcmlp** [comment]
Yeah, that's what I ended up doing, I thought the community might be interested to include the check within the function. Thanks again for all of the responses all.

**Comment by jimhester** [comment]
For now we are going to close this, if others express similar interest we can re-open.
