### ISSUE TITLE
read_fwf, substitute character as EOF

### ISSUE THREAD

**Issue by blablablerg** [tidyverse/readr#836]
Hello,

When reading a fixed width file with a substitute character as EOF (pretty old school I know), read_fwf throws a warning.

I get: 

> Warning message:
> In rbind(names(probs), probs_f) :
>   number of columns of result is not a multiple of vector length (arg 1)

when I do problems(), get:

>     row col    expected   actual    file                                               
>   <int> <chr>  <chr>      <chr>     <chr>                                              
> 1  1073 col_1 4 chars    1         'C:/path/to/file'
> 2  1073 col_1 an integer "\u001a"  'C:/path/to/file'
> 3  1073 NA     13 columns 1 columns 'C:/path/to/file'

The number of lines in the file is 1072 (EOF excluded). Also when when I put n_max = 1072, I still get a warning:

>     row col    expected actual file                                               
>   <int> <chr>  <chr>    <chr>  <chr>                                              
> 1  1073 col_1 4 chars  1      'C:/path/to/file'

vim handles the substitute character just fine, while notepad shows a small box.

**Comment by jimhester** [comment]
Could you include an example file? This seems like such a special case I doubt we would support it, I think you will just have to pre-process the file before parsing with readr.
