### ISSUE TITLE
"read_table()" cannot read long strings?

### ISSUE THREAD

**Issue by jpiggod** [tidyverse/readr#842]
I have been using readr package for fast import for some time but after writing some analytic codes of my data, some unpredicted errors occur, and after debugging I found it is due to the incapability of read_table() to read long strings:

For my input file, I have long character strings in each line (and I need to separate them using functions such as str_split() ). Here is an example line: "gene_id_1 ABC-5%, DEFIOIAFDJO-18%, OISHDFU-77%". However, after processing all my genetic information, there were 28 errors, and I found that all these lines concluded long strings. In one of these imported lines, the import was not complete, and the line was truncated to something like "gene_id_1 ABC-5%, DEFIOIAFDJO-18%," which ended abruptly. 

This is my original code:
```{r}
  data[[species]] <- read_table(file = data.txt.names[index],
                                col_names = FALSE)
```

And the parsing did not yield any errors:
`Parsed with column specification:
cols(
  X1 = col_character()
)`

However, since my strings were not completely imported, I tried to switch back to the base R function "read.delim()"
```{r}
  data[[species]] <- read.delim(file = data.txt.names[index],
                                header = FALSE,
                                stringsAsFactors = FALSE)`
```

This import is successful and the full line could be imported. nchar() shows there are 199 characters in one of these aforementioned lines. Hence, in view of this, are there some type of upper limit of the number of characters in each line that readr could import? 

Thanks,
Jason.

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

Right now the best way to install reprex is:
```r
# install.packages("devtools")
devtools::install_github("tidyverse/reprex")
```
If you run into problems with access to your clipboard, you can specify an outfile for the reprex, and then copy and paste (or drag and drop) the contents here.

```r
reprex::reprex(input = "fruits_stringdist.R", outfile = "fruits_stringdist.md")
```

Thanks

**Comment by jonovik** [comment]
I suspect I have the samme issue. The problem seems to be that read_table will not recognize lines (much?) longer than the first one. Consider these (full output below):

```r
library(readr)
read_table("a b\nc d")
read_table("a b\ncc d")
read_table("a b\nccc d")
```
In all cases I would expect two columns `a` and `b`, where `b` contains `d` in all cases, and `a` contains `c`, `cc` and `ccc`, respectively.
Only the first works as expected.  
The second makes one column called `a b` containing `cc d`.
The third makes one column called `a b` containing `ccc`.

Full example:

```r
library(readr)
read_table("a b\nc d")
## # A tibble: 1 x 2
##   a     b    
##   <chr> <chr>
## 1 c     d
read_table("a b\ncc d")
## # A tibble: 1 x 1
##   `a b`
##   <chr>
## 1 cc d
read_table("a b\nccc d")
## # A tibble: 1 x 1
##   `a b`
##   <chr>
## 1 ccc
devtools::session_info()
## Session info -------------------------------------------------------------
##  setting  value                       
##  version  R version 3.5.1 (2018-07-02)
##  system   x86_64, mingw32             
##  ui       RTerm                       
##  language (EN)                        
##  collate  English_United States.1252  
##  tz       Europe/Berlin               
##  date     2018-10-18
## Packages -----------------------------------------------------------------
##  package    * version date       source                      
##  assertthat   0.2.0   2017-04-11 CRAN (R 3.5.1)              
##  backports    1.1.2   2017-12-13 CRAN (R 3.5.0)              
##  base       * 3.5.1   2018-07-02 local                       
##  cli          1.0.1   2018-09-25 CRAN (R 3.5.1)              
##  compiler     3.5.1   2018-07-02 local                       
##  crayon       1.3.4   2017-09-16 CRAN (R 3.5.1)              
##  datasets   * 3.5.1   2018-07-02 local                       
##  devtools     1.13.6  2018-06-27 CRAN (R 3.5.1)              
##  digest       0.6.17  2018-09-12 CRAN (R 3.5.1)              
##  evaluate     0.11    2018-07-17 CRAN (R 3.5.1)              
##  fansi        0.3.0   2018-08-13 CRAN (R 3.5.1)              
##  graphics   * 3.5.1   2018-07-02 local                       
##  grDevices  * 3.5.1   2018-07-02 local                       
##  hms          0.4.2   2018-03-10 CRAN (R 3.5.1)              
##  htmltools    0.3.6   2017-04-28 CRAN (R 3.5.1)              
##  knitr        1.20.15 2018-08-22 Github (yihui/knitr@4864ac9)
##  magrittr     1.5     2014-11-22 CRAN (R 3.5.1)              
##  memoise      1.1.0   2017-04-21 CRAN (R 3.5.1)              
##  methods    * 3.5.1   2018-07-02 local                       
##  pillar       1.3.0   2018-07-14 CRAN (R 3.5.1)              
##  pkgconfig    2.0.2   2018-08-16 CRAN (R 3.5.1)              
##  R6           2.2.2   2017-06-17 CRAN (R 3.5.1)              
##  Rcpp         0.12.19 2018-10-01 CRAN (R 3.5.1)              
##  readr      * 1.1.1   2017-05-16 CRAN (R 3.5.1)              
##  rlang        0.2.2   2018-08-16 CRAN (R 3.5.1)              
##  rmarkdown    1.10    2018-06-11 CRAN (R 3.5.1)              
##  rprojroot    1.3-2   2018-01-03 CRAN (R 3.5.1)              
##  stats      * 3.5.1   2018-07-02 local                       
##  stringi      1.2.4   2018-07-20 CRAN (R 3.5.1)              
##  stringr      1.3.1   2018-05-10 CRAN (R 3.5.1)              
##  tibble       1.4.2   2018-01-22 CRAN (R 3.5.1)              
##  tools        3.5.1   2018-07-02 local                       
##  utf8         1.1.4   2018-05-24 CRAN (R 3.5.1)              
##  utils      * 3.5.1   2018-07-02 local                       
##  withr        2.1.2   2018-03-15 CRAN (R 3.5.1)              
##  xfun         0.3     2018-07-06 CRAN (R 3.5.1)              
##  yaml         2.2.0   2018-07-25 CRAN (R 3.5.1)
```

**Comment by yutannihilation** [comment]
It seems a documented behaviour. According to `?read_table`:

> `read_table2()` is like `read.table()`, it allows any number of whitespace characters between columns, and the lines can be of different lengths.
> `read_table()` is more strict, each line must be the same length, and each field is in the same position in every line. It first finds empty columns and then parses like a fixed width file.

So `read_table2()` seems what you want in this case.

``` r
library(readr)

read_table("a b\nccc d")
#> # A tibble: 1 x 1
#>   `a b`
#>   <chr>
#> 1 ccc
read_table2("a b\nccc d")
#> Warning: 1 parsing failure.
#> row col expected        actual         file
#>   1   b          embedded null literal data
#> # A tibble: 1 x 2
#>   a     b    
#>   <chr> <chr>
#> 1 ccc   d
```

<sup>Created on 2018-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jonovik** [comment]
Ah I see. Thanks a lot!

**Comment by jonovik** [comment]
But why the parsing failure and warning message?
On my system it's even more noisy than yours:

```r
library(readr)
read.table(textConnection("a b\nccc d"), header = TRUE)
##     a b
## 1 ccc d
read_table2("a b\nccc d")
## Warning: 1 parsing failure.
## row # A tibble: 1 x 5 col     row col   expected actual        file         expected   <int> <chr> <chr>    <chr>         <chr>        actual 1     1 b     ""       embedded null literal data file # A tibble: 1 x 5
## 
## # A tibble: 1 x 2
##   a     b    
##   <chr> <chr>
## 1 ccc   d    
## Warning message:
## In rbind(names(probs), probs_f) :
##   number of columns of result is not a multiple of vector length (arg 2)
```

**Comment by yutannihilation** [comment]
It seems readr assumes the CSV ends with a line break. I don't know how valid the assumption is, but the warning should not be this cryptic... Anyway, this seems a different issue to me.

``` r
readr::read_table2("a b\nccc d")
#> Warning: 1 parsing failure.
#> row col expected        actual         file
#>   1   b          embedded null literal data
#> # A tibble: 1 x 2
#>   a     b    
#>   <chr> <chr>
#> 1 ccc   d

readr::read_table2("a b\nccc d\n")
#> # A tibble: 1 x 2
#>   a     b    
#>   <chr> <chr>
#> 1 ccc   d
```

<sup>Created on 2018-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jonovik** [comment]
Thanks for your patience and clarifications 8-)
