### ISSUE TITLE
suggest to change default quote parameter for tsv

### ISSUE THREAD

**Issue by jhpoelen** [tidyverse/readr#844]
In IANA's definition of TSV at https://www.iana.org/assignments/media-types/text/tab-separated-values , no mention is made of string quoting. In fact, the reason for the use of TSV was to avoid having to deal with confusing string quoting at all by simply stating the tab character may not be used in the values of fields. 

Currently, the default value of "quote" parameter in readr::read_tsv is ```\"```. 

To follow the spirit of TSV, suggest to change the default value of the "quote" parameter in readr:read_tsv (and accompanying methods) to an empty value.

**Comment by jimhester** [comment]
This seems reasonable to me, do you have an opinion @hadley?

**Comment by hadley** [comment]
Hmmm, I'd be slightly concerned about breaking existing code, but it seems like it should be ok.

**Comment by cboettig** [comment]
@jimhester I think this issue also impacts `write_tsv()`?  Looks like `readr` cannot write a IANA valid tsv file with quoted text, since there's not even an option(?) to not double-quote quotations?

**Comment by jimhester** [comment]
@cboettig there is now a escape_na option for the `write_*()` functions, so at least that concern is removed.
