### ISSUE TITLE
read_delim_chunked feature request - get specified chunk

### ISSUE THREAD

**Issue by bheavner** [tidyverse/readr#848]
It would be really nice to be able to have the ability to get a specified chunk from readr functions like `read_tsv_chunked()` - perhaps something like a `chunk_number` or `skip_to_chunk` argument in the function to return just the chunk specified.

As a motivating example, I've got a `get_problem_chunk()` function in a package I wrote - https://github.com/UW-GAC/wgsaparsr/blob/5a4786dba5793d046d1a77f8a64e691a644b07c5/R/troubleshooting-utils.R#L24 

I made the function to assist with troubleshooting when parsing a larger-than-memory file - when I get a parsing error in chunk 2,500 out of 3 million, I'd like to be able to just get that chunk to look at and step through my code. It would be nice to get rid of my while loop to do this more cleanly.

(and now I'll go try to see if I can use the `pos` argument in my callback function to come up with a solution with the current `read_tsv_chunked()`

Thanks for your work in general, and `readr` in particular!

**Comment by jimhester** [comment]
You can do this by using a counter in your callback and then call `browse()` when you get to whatever chunk you want. No changes to the API are necessary, e.g.

```r
get_problem_chunk <- function(num) {
  i <- 1
  function(x, pos) {
    if (i == num) browser()
    i <<- i + 1
 }
}

write_tsv(mtcars, "mtcars.tsv")
read_tsv_chunked("mtcars.tsv", get_problem_chunk(3), chuck_size = 2)
```

**Comment by bheavner** [comment]
Oh, that's very handy, and I think I can use for interactive debugging or figure out a way to return the chunk of interest from a function call. Thank you.

Is it possible to short-circuit the reading after I return the chunk of interest? If I'm looking at chunk 20 out of 20 million, it would be nice to be able to stop the read and close the file handle.
