### ISSUE TITLE
read_delim_chunked feature request - add skip and n_max arguments

### ISSUE THREAD

**Issue by bheavner** [tidyverse/readr#851]
When working with a larger than memory file (e.g. using `readr::read_delim_chunked()`), It would be nice to be able to get a certain number of chunks then stop reading the file.

see also #848 and https://stackoverflow.com/questions/50300981/is-there-a-way-to-stop-readrread-tsv-chunked-after-a-certain-number-of-chunk

**Comment by jimhester** [comment]
You can do this by using the SideEffectCallback (which is the default when passed a normal function) and returning the results using the `<<-` operator, e.g.

``` r
library(readr)

get_problem_chunk <- function(num) {
  i <- 1
  function(x, pos) {
    if (i == num) {
      res <<- x
      return(FALSE)
    }
    i <<- i + 1
 }
}

write_tsv(mtcars, "mtcars.tsv")
read_tsv_chunked("mtcars.tsv", get_problem_chunk(3), chunk_size = 2, col_types = cols())
#> NULL
res
#> # A tibble: 2 x 11
#>     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1  18.7     8   360   175  3.15  3.44  17.0     0     0     3     2
#> 2  18.1     6   225   105  2.76  3.46  20.2     1     0     3     1
```

Created on 2018-05-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by bheavner** [comment]
I _really_ appreciate your handholding. Thanks @jimhester !

**Comment by jimhester** [comment]
No worries, the callback API is unfortunately not a terribly well documented part of readr.
