### ISSUE TITLE
read_fwf does not interpret fwf widths correctly on latin1 encoded input strings with special characters

### ISSUE THREAD

**Issue by s-fleck** [tidyverse/readr#852]
Under certain circumstances the widths of fwf columns are not interpreted correctly when `file` is a character vector, rather than a file path. 

This bug was a bit hard pinpoint. I did not seem to occur on utf8 encoded input (e.g. when I construct the text string directly in the R-script). I tried this with the latest readr version from cran as well as github (1.1.1 and 1.2.0)

## Reprex
(the outputs are wrapped in `as.data.frame()` to avoid truncating the first column)

[test.txt](https://github.com/tidyverse/readr/files/2003627/test.txt)

``` r

library(readr)

col_positions <- readr::fwf_widths(
  c(5, 30, 4, 7, 6, 1, 5, 5, 5, 5, 5, 14, 12, 6, 4)
)

col_types <- "icicccddiiccccc"



# This works:

r1 <- readr::read_fwf(
  "test.txt",
  locale = readr::locale(encoding = "latin1"),
  col_types = col_types,
  col_positions = col_positions
)

as.data.frame(r1)
#>     X1           X2  X3     X4   X5   X6   X7 X8 X9 X10   X11         X12
#> 1 1111 Fadd-Tombori 111 111111 1111 <NA> 1111 NA NA  NA xxxxx       xxxxx
#> 2 1111  Dunaföldvar 111 111111 1111 <NA> 1111 NA NA  NA xxxxx xxxxxxxxxxx
#> 3 1111  Dunaujvaros 111 111111 1111 <NA> 1111 NA NA  NA xxxxx  xxxxxxxxxx
#>       X13   X14 X15
#> 1 xxxxxxx xxxxx  11
#> 2    <NA> xxxxx  11
#> 3    <NA> xxxxx  11


# This doesn't:

x <- readr::read_lines(
  "test.txt",
  locale = readr::locale(encoding = "latin1")
)


r2 <- readr::read_fwf(
  x,
  col_types = col_types,
  col_positions = col_positions
)

as.data.frame(r2)  # errors in line 2 because of the "ö" character
#>     X1           X2  X3     X4   X5   X6   X7 X8 X9 X10   X11
#> 1 1111 Fadd-Tombori 111 111111 1111 <NA> 1111 NA NA  NA xxxxx
#> 2 1111  Dunaföldvar 111 111111  111    1 1111 NA NA  NA  xxxx
#> 3 1111  Dunaujvaros 111 111111 1111 <NA> 1111 NA NA  NA xxxxx
#>              X12     X13   X14  X15
#> 1          xxxxx xxxxxxx xxxxx   11
#> 2 x   xxxxxxxxxx       x  xxxx x  1
#> 3     xxxxxxxxxx    <NA> xxxxx   11
```

Created on 2018-05-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by gergness** [comment]
I believe readr's current behavior is correct (even if it's a bit confusing) - column positions in fixed width files refer to bytes, not characters. Your error comes form the fact that readr converts all data to UTF-8 which can have a different number of bytes than the data when it was stored in latin1. Therefore after reading the data in with `read_lines()`, your original column positions no longer apply.

You can get around this by converting back to latin1 encoding with iconv:

``` r
col_positions <- readr::fwf_widths(
  c(5, 30, 4, 7, 6, 1, 5, 5, 5, 5, 5, 14, 12, 6, 4)
)

col_types <- "icicccddiiccccc"

x <- readr::read_lines(
  "C:/users/gfellis/desktop/test.txt",
  locale = readr::locale(encoding = "latin1")
)

y <- iconv(x, from = "UTF-8", to = "latin1")

r3 <- readr::read_fwf(
  paste(y, collapse = "\n"),
  col_types = col_types,
  col_positions = col_positions
)

as.data.frame(r3)
#>     X1             X2  X3     X4   X5   X6   X7 X8 X9 X10   X11
#> 1 1111   Fadd-Tombori 111 111111 1111 <NA> 1111 NA NA  NA xxxxx
#> 2 1111 Dunaf<f6>ldvar 111 111111 1111 <NA> 1111 NA NA  NA xxxxx
#> 3 1111    Dunaujvaros 111 111111 1111 <NA> 1111 NA NA  NA xxxxx
#>           X12     X13   X14 X15
#> 1       xxxxx xxxxxxx xxxxx  11
#> 2 xxxxxxxxxxx    <NA> xxxxx  11
#> 3  xxxxxxxxxx    <NA> xxxxx  11
```

**Comment by s-fleck** [comment]
Hmm this sounds like good reasoning, but I still find it a bit counter-intuitive.

**Comment by jimhester** [comment]
I sympathize with this being counter-intuitive, however we really don't have much other choice than using bytes without re-writing a large portion of readr code.

Thank you @gergness for tracking down the cause!

**Comment by s-fleck** [comment]
But this basically means `read_fwf()` is broken for utf8 files with special characters. Maybe there should at least be a warning? I am pretty sure this problem will pop up again once/if UTF8 gets adapted more widely.

I totally get the usecases for reading bytes though --- I sometimes have to deal with weird fwf files that have binary encoded numbers in them. Maybe it would be nice to have both options (though i totally get that this is not a priority)?

**Comment by gergness** [comment]
In my experience, this will not be a problem because data that is provided with fixed width format and multi-byte UTF-8 characters will use column offsets that are byte-based. The unfortunate side effect (which caused your original issue) is that the column positions only apply in the original encoding.

For what it's worth, Stata's `infix` command explicitly says that the column positions are byte-based (and it can *only* read UTF-8/ascii data) and I believe that SPSS and SAS behave the same way.

> infix reads into memory from a disk dataset that is not in Stata format. infix requires that the
data be in fixed-column format. Note that the column is byte based.
> 
> https://www.stata.com/manuals14/dinfixfixedformat.pdf

(Would like to reiterate that I agree all of this is a pain - my knowledge on this comes from several long debugging sessions. I just think readr is doing the best job it can given how complicated text encoding is.)
