### ISSUE TITLE
feature suggestion - send lines that fail to parse to a new tibble or vector

### ISSUE THREAD

**Issue by seanpor** [tidyverse/readr#855]
In a large csv file (more than a million rows) a handful (45) did not parse properly.  I manually ran read_csv(), looked at the error message, edited the file to remove the offending line (and put it in another file).

Some tools like Informatica / Talend allow you to send parse failures to a parse_error file without falling over, ie. the rest of the parsing continues.

It would be nice to be able to have the option in read_csv() (and friends) to send these lines which fail parsing to some sort of parse.reject character vector or tbl with the row numbers.

**Comment by jimhester** [comment]
Yes, agreed, this is what `readr::problems()` is for, note there shouldn't have been an error message for the problems, it should have been a Warning.

``` r
library(readr)
x <- parse_integer(c("1X", "blah", "3"))
#> Warning: 2 parsing failures.
#> row col               expected actual
#>   1  -- no trailing characters   X   
#>   2  -- an integer               blah
problems(x)
#> # A tibble: 2 x 4
#>     row   col expected               actual
#>   <int> <int> <chr>                  <chr> 
#> 1     1    NA no trailing characters X     
#> 2     2    NA an integer             blah
```

Created on 2018-05-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by seanpor** [comment]
Thanks Jim - I had completely misunderstood problems()!
