### ISSUE TITLE
Next CRAN release?

### ISSUE THREAD

**Issue by nevrome** [tidyverse/readr#856]
Dear readr development team,

first of all thanks for your great work! I use readr whenever I need reliable and reproducible data reading.... for example in our new package [c14bazAAR](https://github.com/ISAAKiel/c14bazAAR). It's pretty much release ready, but unfortunately we ran into #750 / #833. 

Would you mind preparing a readr CRAN release with the already implemented fixes? 
(@stianlagstad: Thanks for the [reminder](https://github.com/ISAAKiel/c14bazAAR/issues/41#issuecomment-391426074)!)

**Comment by nevrome** [comment]
Thanks for your fast reply!

So the new release was rejected although the current version already has this NOTE? And `R_GetConnection()` was explicitly added in 3.3.0 and later silently dropped? Hm...

As this problem concerns the C++ code, I don't see an option for me to implement the fix in my package by overwriting the readr function. I guess I have to wait or change to another file reading implementation.

**Comment by stianlagstad** [comment]
For someone who doesn't follow the R-package-devel list (and don't know how to properly search and navigate the email logs), are there any updates on this?

**Comment by JoFAM** [comment]
The mail I linked to was the last one in that conversation. I haven't heard anything since then, so I hope the maintainer of the package have contact with R core over this.

**Comment by hadley** [comment]
See #915
