### ISSUE TITLE
read_tsv with subset of columns gives token warnings

### ISSUE THREAD

**Issue by gksmyth** [tidyverse/readr#859]
When I use readr to skip some columns of a file, I always get warnings from `read_tokens_`. The read operation seems to work correctly, but I don't know what the warnings mean or how to get rid of them. I get one warning for each column of the file. The upshot is that I always enclose `read_tsv` within `suppressWarnings()` if I make use of it in public software.

Am I missing something in my code call? Or is there something subtle going on my environment or locale? Or is this a readr feature/bug?

Here is a typical (non-reproducible) example from my practice:

     > x <- read_tsv("P6_1.bismark.cov.gz",col_names=FALSE,col_types="ci__ii",progress=FALSE)
     Warning messages:
    1: In read_tokens_(data, tokenizer, col_specs, col_names, locale_,  :
      length of NULL cannot be changed
    2: In read_tokens_(data, tokenizer, col_specs, col_names, locale_,  :
      length of NULL cannot be changed
    3: In read_tokens_(data, tokenizer, col_specs, col_names, locale_,  :
      length of NULL cannot be changed
    4: In read_tokens_(data, tokenizer, col_specs, col_names, locale_,  :
      length of NULL cannot be changed
    5: In read_tokens_(data, tokenizer, col_specs, col_names, locale_,  :
      length of NULL cannot be changed
    6: In read_tokens_(data, tokenizer, col_specs, col_names, locale_,  :
      length of NULL cannot be changed
    > head(x)
    # A tibble: 6 x 4
      X1         X2    X5    X6
      <chr>   <int> <int> <int>
    1 chr15 3051454    14     2
    2 chr15 3051455     1     0
    3 chr15 3051486    16     0
    4 chr15 3051555    13     3
    5 chr15 3051556     1     0
    6 chr15 3051559    14     2

    > sessionInfo()
    R version 3.5.0 (2018-04-23)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 15063)
    
    Matrix products: default
    
    locale:
    [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
    [3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
    [5] LC_TIME=English_Australia.1252    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] readr_1.1.1
    
    loaded via a namespace (and not attached):
    [1] compiler_3.5.0  R6_2.2.2        hms_0.4.2       tools_3.5.0    
    [5] pillar_1.2.2    tibble_1.4.2    Rcpp_0.12.17    pkgconfig_2.0.1
    [9] rlang_0.2.0

**Comment by jennybc** [comment]
Sounds like #833 and #750 which have been resolved. Have you tried the dev version of readr?

**Comment by gksmyth** [comment]
@jennybc If I rebuild readr from the github version (last edited 12 May) then I get an error:

    >  x <- read_tsv("P6_1.bismark.cov.gz",col_names=FALSE,col_types="ci__ii",progress=FALSE)
    Error in read_connection_(con) : 
      object '_readr_read_connection_' not found

**Comment by jimhester** [comment]
likely your readr installation failed and is using an outdated dll, try re-installing readr in a fresh R session with no packages loaded.
