### ISSUE TITLE
consider exporting standarize_path?

### ISSUE THREAD

**Issue by cboettig** [tidyverse/readr#863]
Maybe I'm missing something, but `readr`'s internal method, `standardize_path` seems like a super useful abstraction when writing packages to parse a particular file format.   

 Is there any chance you would consider exporting this function?

**Comment by jennybc** [comment]
This is definitely a handy function. But I doubt @jimhester would want readr revdeps *because* of this function. I am starting to generally use [fs](https://fs.r-lib.org) for path manipulation and file system operations. If this were to be exported, fs might be a more natural home for it.

**Comment by cboettig** [comment]
Thanks! yeah, I had the same thought; almost feels more like an fs-like utility, though I guess it would be expanding the scope of `fs` a bit?.  Is the `standardize_path` impacted by the R-API the issue #856 or independent of that?

**Comment by jimhester** [comment]
I am not really sure it makes sense to export this, the behavior is pretty readr specific and it is also fairly limited.

I think if you wanted to use it in another package you should just copy it (with attribution to the readr authors) and adapt it to your needs.
