### ISSUE TITLE
suggestion: implement a write_csv2 to write what read_csv2 reads

### ISSUE THREAD

**Issue by sellisd** [tidyverse/readr#866]
For reading csv files the functions read_csv and read_csv2 exist, while for writing we have only write_csv. It would be handy to implement a write_csv2 which directly writes in the format that read_csv2 can read even though it can easily be done I find it a helpful shortcut

**Comment by cderv** [comment]
I agree with that. 
This has been also mentioned and discussed with a proposed implementation in https://github.com/tidyverse/readr/issues/523#issuecomment-364257424

**Comment by Zack-83** [comment]
The best would be to have a function named `write_excel_csv2`, which would have both advantages: leading byte for UTF-8 (like `write_excel_csv`) and Europe-compatible delimiter and decimal separator.

**Comment by romainfrancois** [comment]
I understand the legacy from `.csv2` functions from base, but wasn't some way to name this something perhaps more meaningful than using the `csv2` suffix ?
