### ISSUE TITLE
read_csv_chunked() delim parameter not recognized

### ISSUE THREAD

**Issue by Naboum** [tidyverse/readr#869]
Hello, I want to run this code : 
```
  separator <- ";"
  sirenPart <- read_csv2_chunked(file("sirene-part\\sirene1.csv"), 
                                 callback = callbackMerge, 
                                 chunk_size = 20000, 
                                 col_names =  TRUE, 
                                 delim = separator)
```

However it seems that the delim parameter is not recognized, it shows me this error :
`unused argument (delim = separator)`

Can you please tell me how to use the function read_csv_chunked() and the parameter delim ?

**Comment by batpigandme** [comment]
For the delim argument use [`read_delim_chunked()`](https://readr.tidyverse.org/reference/read_delim_chunked.html). `read_csv2()` (and its chunked counterpart) is a special case of [`read_delim()`](https://readr.tidyverse.org/reference/read_delim.html) with the separator, `;`, already specified.
