### ISSUE TITLE
write_csv gives an error for list-columns yet still creates a file

### ISSUE THREAD

**Issue by martj42** [tidyverse/readr#871]
Say I were to run the following code:

```r
library(tidyverse)
library(repurrrsive)

x <- tibble(
  name = got_chars %>% map_chr("name"),
  aliases = got_chars %>% map("aliases"),
  allegiances = got_chars %>% map("allegiances")
)

x %>% write_csv("got_chars.csv")
```

With the columns `aliases` and `allegiances` being character list-columns.

I get this message in console:
`Error in stream_delim_(df, path, ...) : 
  Don't know how to handle vector of type list.`

But! The file got_chars.csv gets created up to the point of the first list.

**Comment by cderv** [comment]
This is related to a discussion in #303 . 
Maybe since it is not yet possible to write list-column, a check can be done way before when trying to use a `write_*` function and stop with message indicating that a tibble with list column can't be written

**Comment by jimhester** [comment]
Yeah #303 is tracking this issue and the current behavior seems fine until it is addressed.
