### ISSUE TITLE
add skip_footer 

### ISSUE THREAD

**Issue by mtelesha** [tidyverse/readr#88]
It would be nice to have a skip_footer like Pandas read.csv [search of skip_footer in Pandas github](https://github.com/pydata/pandas/search?utf8=✓&q=skip_footer)

One of our mandated data base providers reports always has a few extra lines on the bottom of every csv file. So typically I have to read the document and than remove the footers.

```
# remove the bottom 4 lines of a data frame
dataList <- lapply(dataList, function(i){
nrDF <- nrow(i) - 4
  i <- i[1:nrDF]
})
```

it would be great if instead we can add a skip_footer

```
# Read a csv file into a data frame
read_csv(mtcars_path, skip_footer = 4)
```

**Comment by hadley** [comment]
Can you share what the csv looks like? (at least the last few lines and the first few cols)

**Comment by mtelesha** [comment]
Here is a example. I typed over our Person_ID column with fictitious numbers. This is the first four columns.

    Report_B,3/13/2015,,
    FM: Person ID,FM: Race,FM: Race Detail,FM: Secondary Language
    6543,Other,,English
    4535,White,,Arabic
    54534,Black or African American,,
    35453,Other,,English
    54567,Asian,,English
    34534,Other,,Arabic
    "Grand Total: 6,634",,,
    Page -1 of 1,,,

**Comment by hadley** [comment]
Currently you could do `col_type = list(`FM: Person ID` = col_numeric()`)` and you'd just get an NA and a warning.

**Comment by jimhester** [comment]
A easy workaround is to first read the file in as lines, filter out the extra lines, then pass that to the read function
``` r
library(readr)
library(magrittr)
read_lines("test.csv") %>%
  head(n = -2) %>%
  paste(collapse = "\n") %>%
  read_csv(skip = 1)
#> # A tibble: 6 × 4
#>   `FM: Person ID`                `FM: Race` `FM: Race Detail`
#>             <int>                     <chr>             <chr>
#> 1            6543                     Other              <NA>
#> 2            4535                     White              <NA>
#> 3           54534 Black or African American              <NA>
#> 4           35453                     Other              <NA>
#> 5           54567                     Asian              <NA>
#> 6           34534                     Other              <NA>
#> # ... with 1 more variables: `FM: Secondary Language` <chr>
```

**Comment by hadley** [comment]
This seems like a reasonable work around to me.  If we reconsider in the part it'll be as part of a more sweeping specification of row specification (which would include reservoir sampling etc)

**Comment by etiennebr** [comment]
I'm hitting a limit at 4095 MB with this work around. I couldn't reproduce exactly my dataset, but this is pretty close:
``` r
library(tidyverse)
m <- 100
n <- 1e7

o <- map(1:n, ~paste0(rnorm(m), collapse = ";")) %>%
  head(n = -1) %>%
  paste(collapse = "\n") %>%
  read_delim(";", col_names = paste0("V", 1:m))
#> Error in paste(., collapse = "\n") : result would exceed 2^31-1 bytes
```
My real output is 
```r
#> |============================================================================================| 100% 4095 MB
#> Error in paste(., collapse = "\n") : result would exceed 2^31-1 bytes
#> In addition: Warning message:
#>   In (function (con, what, n = 1L, size = NA_integer_, signed = TRUE,  :
#>                   possible truncation of >= 4GB file             possible truncation of >= 4GB file
```
I read from a zip file, so writing the file to disk seems slightly inefficient only to skip the last line, but it's the only solution I've found. @jimhester, I see the feature was IN PROGRESS at a certain point, is there anything I could try?

**Comment by jimhester** [comment]
No there isn't a good way to get around the limit other than writing to a file.
