### ISSUE TITLE
col_number() precision issues

### ISSUE THREAD

**Issue by pakuipers** [tidyverse/readr#881]
I apologize if this doesn't reproduce on all systems:

I created a file (temp.txt) containing a single number: 108.62

```
library(readr)

packageVersion("readr")
## [1] ‘1.1.1’

a <- read_fwf('temp.txt', 
                       col_positions = fwf_positions(start = 1, end = 6, col_name = "test"),
                       col_types = 'n')
b <- read_fwf('temp.txt', 
                       col_positions = fwf_positions(start = 1, end = 6, col_name = "test"),
                       col_types = 'd')

a$test == b$test
## [1] FALSE
a$test == 108.62
## [1] FALSE
b$test == 108.62
## [1] TRUE
```

**Comment by cderv** [comment]
When comparing floating point numeric values in R, you should take care of what you use. `==` is for exact equality, but with floating number on a computer is very difficult to represent exactly. See this [SO answer](https://stackoverflow.com/a/9508558/3436535). For comparison, you should use `all.equal`, that compare with a tolerance base [on your machine](http://stat.ethz.ch/R-manual/R-patched/library/base/html/zMachine.html). 
Here the impact in your example comparing `parse_number` and `parse_decimal`, used respectively by `col_types = 'n'` and `col_types = 'd'`
``` r
library(readr)
x <- "108.62"
# parse with parse_number and default locale understanding decimal as .
(n <- parse_number(x))
#> [1] 108.62
# parse with parse_double and default locale understanding decimal as .
(d <- parse_double(x))
#> [1] 108.62
# is is equal ? 
d == n
#> [1] FALSE
# should be 0 ? 
d - n
#> [1] 1.421085e-14
# ok it is not exactly equal, 
# but is it what it is call near equality, with a tolerance for double precision ? 
all.equal(n , d)
#> [1] TRUE
```

Created on 2018-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by pakuipers** [comment]
This is a major problem:

```
library(readr)
library(dplyr)

x <- "108.62"

tibble_number <- tibble(test = parse_number(x))
tibble_double <- tibble(test = parse_double(x))

tibble_number %>%
  dplyr::filter(test < 108.62) %>%
  nrow()
#> [1] 1

tibble_double %>%
  dplyr::filter(test < 108.62) %>%
  nrow()
#> [1] 0
```

**Comment by jimhester** [comment]
This is just due to rounding errors in the floating point implementation, I don't think there is anything to do, as @cderv mentioned this is something you have to take into account when doing comparisons with floating point numbers. This is also explained in [Section 7.31](https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-doesn_0027t-R-think-these-numbers-are-equal_003f) of the R FAQ.

``` r
library(readr)
x <- parse_double("108.62")
y <- parse_number("108.62")
x - y
#> [1] 1.421085e-14
pryr::bytes(x)
#> [1] "40 5B 27 AE 14 7A E1 48"
pryr::bytes(y)
#> [1] "40 5B 27 AE 14 7A E1 47"
```

<sup>Created on 2018-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by pakuipers** [comment]
Okay, great point.

I think the misunderstanding lies in user expectations. Most users expect that "parse_number" will choose either double or integer based on the data. However, when supplied with a double the result is another double with different properties. I assume it's not straight-forward on your end for the precision to by tied to the precision given in the data. User's should beware then and round doubles after reading in with "parse_number."
