### ISSUE TITLE
parse_datetime() does not return real seconds

### ISSUE THREAD

**Issue by thanosgatos** [tidyverse/readr#883]
Trying to read in a csv with `read_csv()`, I realized my datetimes were only read to the full second, when they have microsecond accuracy--the format is as in "2018-07-04 10:33:15.064859".

Trying to understand why this is happening, I realized that `parse_datetime()` does exactly the same thing--it gives back the datetime to the full seconds, even though %OS is specified in the format for real seconds.

```
parse_datetime("2018-07-04 10:33:15.064859", format = "%Y-%m-%d %H:%M:%OS")
[1] "2018-07-04 10:33:15 UTC"
```

`parse_time()` does work as @jimhester describes in his last comment in #379, but `parse_datetime()` does not work as expected.

**Comment by jimhester** [comment]
Actually this is working correctly and parsing the partial seconds as the input format suggests, but POSIXct does not display the partial seconds by default.

``` r
library(readr)
x <- parse_datetime("2018-07-04 10:33:15.064859", format = "%Y-%m-%d %H:%M:%OS")
as.POSIXlt(x)$sec
#> [1] 15.06486
```

<sup>Created on 2018-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
