### ISSUE TITLE
Manually setting multiple col_types in read_csv

### ISSUE THREAD

**Issue by dioh** [tidyverse/readr#887]
Dear all, I hope this has not been answered in the past.

I'm reading a csv file with 600 variables.
Most of them are numeric encoding values of categorical data.
In order to run some rpart models I need them to be parsed as character instead of integer as cols_guess is returning.

I have a dataframe with two fields, a column name and if it should be parsed as character or not.

I want to create a cols object using this spec. Please consider for simplicity that I have the variables in a list named variables:

> t1 = cols()
> t1$cols = variables
> t1$default = rep(col_character(), length(t1$cols)))

Doesn't work, t1 is not valid.

> cols(variables, .default = col_character())
returns: ror in switch(x, `_` = , `-` = col_skip(), `?` = col_guess(), c = col_character(),  : 
  EXPR must be a length 1 vector

I don't really know what should I use in default attribute to create the spec that I need.

Thanks!

**Comment by jimhester** [comment]
Hard to be sure I understand the problem correctly without a full reprex, but you can do something like this.

``` r
library(readr)
columns <- data.frame(name = c("a", "b", "c"), use_char = c(TRUE, FALSE, TRUE))
columns
#>   name use_char
#> 1    a     TRUE
#> 2    b    FALSE
#> 3    c     TRUE

variables <- setNames(
  ifelse(columns$use_char,
    rep(list(col_character()), nrow(columns)),
    rep(list(col_guess()), nrow(columns))),
  columns$name)

column_types <- do.call(cols, variables)
column_types
#> cols(
#>   a = col_character(),
#>   b = col_guess(),
#>   c = col_character()
#> )

read_csv(
"a,b,c\n
1,2,3",
  col_types = column_types)
#> # A tibble: 1 x 3
#>   a         b c    
#>   <chr> <int> <chr>
#> 1 1         2 3
```

Created on 2018-09-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
