### ISSUE TITLE
Documentation Request: cols Abbreviations

### ISSUE THREAD

**Issue by billdenney** [tidyverse/readr#888]
The documentation for `cols()` indicates "You can also use the standard abreviations"

Minor note:  There is a typo there, "abreviations" should have two "b"s: "abbreviations"

Larger note:  Where are the abbreviations documented?  I found them by looking into `readr:::col_concise()`, but I didn't see them anywhere else (most notably on the `cols()` help page).

I'd be happy to put together a PR to fix the typo and create or link the documentation, but I want to make sure I'm not missing something first.

**Comment by jimhester** [comment]
I don't think you are missing anything. IIRC they were originally in a `col-types` vignette, but that was removed and rolled into the introduction. However the abbreviation section was omitted.

**Comment by Zedseayou** [comment]
@billdenney Unless I'm mistaken they are documented under the `col_types` argument of `read_delim`, which is usually where people first look to check the function usage.

From my installation (run `?read_csv` or similar):

> Alternatively, you can use a compact string representation where each character represents one column: c = character, i = integer, n = number, d = double, l = logical, D = date, T = date time, t = time, ? = guess, or _/- to skip the column.

**Comment by billdenney** [comment]
@Zedseayou, Thank you, that simplifies the patch requirement.
