### ISSUE TITLE
read_csv doesn't read some values written by write_csv correctly when col_types = "n"

### ISSUE THREAD

**Issue by aaronschiff** [tidyverse/readr#894]
`write_csv` writes some integers in scientific notation. If `col_types = "n"` is specified for the relevant column, `read_csv` doesn't read these values correctly. 

Simple example:

```
library(readr)
data_out <- data.frame(x = c(1234, 5678, 1000))
write_csv(data_out, "data.csv")
read_csv("data.csv", col_types = "n")
# A tibble: 3 x 1
      x
  <dbl>
1  1234
2  5678
3     1
```

**Comment by jimhester** [comment]
This issue is fixed in the development version of readr

``` r
# devtools::install_github("tidyverse/readr")
library(readr)
data_out <- data.frame(x = c(1234, 5678, 1000))
write_csv(data_out, "data.csv")
read_csv("data.csv", col_types = "n")
#> # A tibble: 3 x 1
#>       x
#>   <dbl>
#> 1  1234
#> 2  5678
#> 3  1000
```

<sup>Created on 2018-10-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by aaronschiff** [comment]
Hi Jim, that's good, thanks for letting me know!
