### ISSUE TITLE
Add possibility to read non-English data directly from text on Windows

### ISSUE THREAD

**Issue by GegznaV** [tidyverse/readr#898]
Add possibility to read non-English data directly from text (`R` string) and avoid encoding issues using `readr` functions on Windows. On Mac this problem does not seem to exist (see [this](https://stackoverflow.com/questions/52806647/read-non-english-text-as-data-frame-using-readr-package-encoding-issue/52807741) GitHub issue).

```r
Sys.setlocale(locale = "Lithuanian")
library(readr)

# Data
df_in_text <-
("Ežeras\tPlotas, ha\tGylis, m
Drūkšiai\t4479,0\t33,3
Dysnai\t2439,4\t6,0")
    
df <- read_tsv(df_in_text, locale = locale(decimal_mark = ","))
df
## # A tibble: 2 x 3
##   `E\xfeeras`      `Plotas, ha` `Gylis, m`
##   <chr>                   <dbl>      <dbl>
## 1 "Dr\xfbk\xf0iai"        4479        33.3
## 2 Dysnai                  2439.        6  
```

```r
Encoding(c(names(df), df[[1]]))
## [1] "UTF-8"   "unknown" "unknown" "UTF-8"   "unknown"
```

**Comment by yutannihilation** [comment]
I believe this is already fixed in the dev version by this PR: https://github.com/tidyverse/readr/pull/730

**Comment by GegznaV** [comment]
I tried the development version of `readr`. The problem is really fixed in it.
