### ISSUE TITLE
Feature request: Silence warning about no newline at end of input

### ISSUE THREAD

**Issue by jonovik** [tidyverse/readr#900]
As mentioned in #842, read_table gives a warning if the input does not end in a newline.
I think input not ending in newline should be accepted for consistency with `read.table`.

```r
read.table(textConnection("a b\nccc d"), header = TRUE)
#>     a b
#> 1 ccc d

readr::read_table2("a b\nccc d")
#> Warning: 1 parsing failure.
#> row col expected        actual         file
#>   1   b          embedded null literal data
#> # A tibble: 1 x 2
#>   a     b    
#>   <chr> <chr>
#> 1 ccc   d

readr::read_table2("a b\nccc d\n")
#> # A tibble: 1 x 2
#>   a     b    
#>   <chr> <chr>
#> 1 ccc   d
```

**Comment by jimhester** [comment]
Lines according to the [POSIX standard](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) are defined as always ending with a newline, so this is the intended behavior.
