### ISSUE TITLE
Implement vnames and lables into READR like Hmisc Package

### ISSUE THREAD

**Issue by gandalf-randolph** [tidyverse/readr#901]
Hmisc allows you to add labels to your variables via the labels keyword specification and also indicate which row contains the variable names to use for that column.

Consider also adding another keyword that would direct READR to the line the CSV data, that contains the format of the data, that is expected.   That would save some programming lines with your column specifications, if we are already embedding this information in the CSV.

Regards Gandalf

**Comment by jimhester** [comment]
https://github.com/tidyverse/readr/issues/770 is a similar issue, if we were to add support for csv metadata I believe that is the route we would take.
