### ISSUE TITLE
readr_csv not reading all columns - shows parsing failure

### ISSUE THREAD

**Issue by sindile** [tidyverse/readr#904]
I have a dataset (TXT file) that looks like this and using readr_csv :
"1","18","ABC","00000","","","L7-2/1907","2479 SQM","JDHD","","*"
"2","18","ABC","00000","","ABC RD","NYY","","","","*"
"4","18","ABC","00000","MGA","838129081","T1/2015","20150303","","20140801","R40000","201632","","","","*"
"5","18","ABC","00000","T203/1974","1017","2015502023","","GRANT","T4/2015","2010332","MALE","328","*"
"6","18","ABC","00000","09","090076","E","C0950001","000000180","*"
"1","29","ABC","00000","","","L-18/1907","2479 SQM","JDHD","","*"
"2","29","ABC","00000","","ABC RD","NY","","","","*"
"3","29","ABC","00000","I-6/2010C","","","  000000","","*"
"4","29","ABC","00000","B MILY TRUST","IT4/2008","T370/2014","20140804","","20110314","R20000","20615","","","","*"
"5","29","ABC","00000","T7/3","0331","","","GRANT","T3/2006","","KR","280816","*"
"5","29","ABC","00000","T3/4","0505","","","R80000.00","T370/2014","20135615","DF","625053086","*"
"5","29","ABC","00000","T3/4","0505","","","R80000.00","T370/2014","20135615","FHJ","660967089","*"
"6","29","ABC","00000","09","090000017026","E","C0","0000002900300","*"

There are no headings.

Not all columns are read as shown below
# A tibble: 1,368 x 5
     row col   expected   actual     file                                                                                
   <int> <chr> <chr>      <chr>      <chr>                                                                               
 1     3 NA    11 columns 16 columns 'data.TXT'
 2     4 NA    11 columns 14 columns 'data.TXT'
 3     5 NA    11 columns 10 columns 'data.TXT'
 4     8 NA    11 columns 10 columns 'data.TXT'
 5     9 NA    11 columns 16 columns 'data.TXT'
 6    10 NA    11 columns 14 columns 'data.TXT'
 7    11 NA    11 columns 14 columns 'data.TXT'
 
Is the a way I could split the data into separate tables based on the first column number (that is all rows with where first column is 1
"1","18","ABC","00000","","","L7-2/1907","2479 SQM","JDHD","","*"
"1","29","ABC","00000","","","L-18/1907","2479 SQM","JDHD","","*"

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by sindile** [comment]
library(tidyverse)
testdata <- read_csv("/home/sxj/rdir/testdata.txt", col_names = FALSE)
#> Parsed with column specification:
#> cols(
#>   X1 = col_integer(),
#>   X2 = col_integer(),
#>   X3 = col_character(),
#>   X4 = col_character(),
#>   X5 = col_character(),
#>   X6 = col_character(),
#>   X7 = col_character(),
#>   X8 = col_character(),
#>   X9 = col_character(),
#>   X10 = col_character(),
#>   X11 = col_character()
#> )
#> Warning in rbind(names(probs), probs_f): number of columns of result is not
#> a multiple of vector length (arg 1)
#> Warning: 9 parsing failures.
#> row # A tibble: 5 x 5 col     row col   expected   actual     file                              expected   <int> <chr> <chr>      <chr>      <chr>                             actual 1     3 <NA>  11 columns 16 columns '/home/sxj/rdir/testdata.txt' file 2     4 <NA>  11 columns 14 columns '/home/sxj/rdir/testdata.txt' row 3     5 <NA>  11 columns 10 columns '/home/sxj/rdir/testdata.txt' col 4     8 <NA>  11 columns 10 columns '/home/sxj/rdir/testdata.txt' expected 5     9 <NA>  11 columns 16 columns '/home/sxj/rdir/testdata.txt'
#> ... ................. ... ..................................................................... ........ ..................................................................... ...... ..................................................................... .... ..................................................................... ... ..................................................................... ... ..................................................................... ........ .....................................................................
#> See problems(...) for more details.
[testdata.txt](https://github.com/tidyverse/readr/files/2505984/testdata.txt)


problems(testdata)
#> # A tibble: 9 x 5
#>     row col   expected   actual     file                             
#>   <int> <chr> <chr>      <chr>      <chr>                            
#> 1     3 <NA>  11 columns 16 columns '/home/sxj/rdir/testdata.txt'
#> 2     4 <NA>  11 columns 14 columns '/home/sxj/rdir/testdata.txt'
#> 3     5 <NA>  11 columns 10 columns '/home/sxj/rdir/testdata.txt'
#> 4     8 <NA>  11 columns 10 columns '/home/sxj/rdir/testdata.txt'
#> 5     9 <NA>  11 columns 16 columns '/home/sxj/rdir/testdata.txt'
#> 6    10 <NA>  11 columns 14 columns '/home/sxj/rdir/testdata.txt'
#> 7    11 <NA>  11 columns 14 columns '/home/sxj/rdir/testdata.txt'
#> 8    12 <NA>  11 columns 14 columns '/home/sxj/rdir/testdata.txt'
#> 9    13 <NA>  11 columns 10 columns '/home/sxj/rdir/testdata.txt'

**Comment by sindile** [comment]
Here is the sample data 
[testdata.txt](https://github.com/tidyverse/readr/files/2505991/testdata.txt)

**Comment by batpigandme** [comment]
Yeah, so this question might actually be a better fit for community.rstudio.com, as I don't think this is about a bug in readr. The issue is that you _do_ have a different number of columns in various rows, and because readr is trying to parse them using the first row, the wider rows (e.g. the third one) are getting cut off. The same principle described in this StackOverflow thread applies:

https://stackoverflow.com/a/18922914/785190

I put the test data and two modifications thereof in a gist here so it's easier to see what's going on: https://gist.github.com/batpigandme/e63317d1ff0a9d792d36d6693db6cff8

**Comment by sindile** [comment]
Thanks and closing this issue to follow https://stackoverflow.com/a/18922914/785190
