### ISSUE TITLE
add n_max parameter into read_csv_chunked function

### ISSUE THREAD

**Issue by EvgenyPetrovsky** [tidyverse/readr#905]
Working with huge files I want to process them in chunks. Sometimes files have header rows to be ignored and footer rows to be ignored. There is an option in `read_csv` function to specify `skip` and `n_max` however there is no `n_max` in chunked functions. 

So I can't process huge file with standard `read_csv_chunked` function if I need to ignore footer lines.

**Comment by jimhester** [comment]
`n_max` in a chunk doesn't really make a lot of sense unless every chunk has lines you want to ignore. If there are lines at the end of the file you will have to detect them manually.

In either case I don't think a `n_max` function is appropriate.

**Comment by EvgenyPetrovsky** [comment]
Thank you for considering my request and taking decision. Can you please recommend me how I can detect and ignore first 2 and last 5 lines in X line file if I process it with Y-line chunks? When data that I read from file is 3 numeric columns and footer has free text. 

Below I am adding example content of file where ... means skipped block of data lines. 

```
Version:1.0
Date:2018-11-14
Measure1,Measure2,Measure3
1,2,3
0,2,1
...
2,2,0
Footer
Record count:Y
Column1 sum:12345
Column2 sum:23456
Column3 sum:34567
```
