### ISSUE TITLE
Parsing Failures warning is unreadable

### ISSUE THREAD

**Issue by jzadra** [tidyverse/readr#906]
The parsing failures output from readr is unreadable.  It looks like it is meant to be in a table, but depending on the width of the console, the output is not aligned.  Putting it into a text editor with word wrap and adjusting the width you can sometimes get it to line up, but overall it's undecipherable as is.

![image](https://user-images.githubusercontent.com/25590353/47824799-2a266f80-dd34-11e8-9d02-f4d1341ff560.png)

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by jennybc** [comment]
I believe these problems are fixed in the dev version, btw. So the reprex should either be run with the dev version or should be such that someone else can check it with the dev version.

**Comment by jzadra** [comment]
Thanks Jenny, confirmed that the dev version has already solved this problem.
