### ISSUE TITLE
Help file for `read_delim` mentions non existing vignette

### ISSUE THREAD

**Issue by prosoitos** [tidyverse/readr#907]
The help file for `read_delim`, under "Arguments/col_types" mentions:

> See ‘vignette("column-types")’ for more details.

But, unless I am mistaken, there is no such vignette. If the vignette hasn't been written yet, but is planned for, I guess you could just close this issue.

Otherwise, maybe it could say

> See "Column specification" in `vignette("readr")`

instead? (this seemed to me to be the most relevant info). In this case, I would be happy to submit a PR with the change.

**Comment by batpigandme** [comment]
I believe this was fixed for https://github.com/tidyverse/readr/issues/660.

https://github.com/tidyverse/readr/blob/69c9fd326dd2428a109e435bd014b19273ba505c/R/read_delim.R#L28-L29

It seems to have been corrected in the [online docs](https://readr.tidyverse.org/reference/read_delim.html), as well, though, obviously, the results of `?read_delim` depend on the version you have installed.


Are you looking at a different instance than the one I'm linking to in [`read_delim.R`](https://github.com/tidyverse/readr/blob/69c9fd326dd2428a109e435bd014b19273ba505c/R/read_delim.R#L28-L29)?

**Comment by prosoitos** [comment]
Mmm... this is weird because I am using the latest release (1.1.1) and the help file I have is different than the online one.

**Comment by prosoitos** [comment]
Oh yes. I hadn't paid attention to the fact that the last release dates back from May. Thank you Mara.
