### ISSUE TITLE
parse_character() behavior is inconsistent with parse_number()

### ISSUE THREAD

**Issue by jzadra** [tidyverse/readr#920]
```
> parse_number("asdf3")
[1] 3
> parse_character("asdf3")
[1] "asdf3"
```

Expected output: "asdf"

There are no examples of `parse_character()` use in the help, so it's hard to tell what it's intended behavior is.

**Comment by jimhester** [comment]
The intended behavior is to parse the input as a character, not to parse only character text, so it is working as intended.

There is little reason you would need ever need to call `parse_character()` explicitly, except maybe to trim whitespace or to set NA values. It generally exists for consistency and for use internally when parsing a file directly.
