### ISSUE TITLE
Bug with parse_number

### ISSUE THREAD

**Issue by PMassicotte** [tidyverse/readr#921]
Any reason why this is no longer working?

Thank you,
Phil

``` r

readr::parse_number(1)
#> Error in parse_vector(x, col_number(), na = na, locale = locale, trim_ws = trim_ws): is.character(x) is not TRUE
```

<sup>Created on 2018-11-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       Linux Mint 19               
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_CA:en                    
#>  collate  en_CA.UTF-8                 
#>  ctype    en_CA.UTF-8                 
#>  tz       America/Toronto             
#>  date     2018-11-22                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.1)
#>  backports     1.1.2   2017-12-13 [1] CRAN (R 3.5.1)
#>  base64enc     0.1-3   2015-07-28 [1] CRAN (R 3.5.1)
#>  callr         3.0.0   2018-08-24 [1] CRAN (R 3.5.1)
#>  cli           1.0.1   2018-09-25 [1] CRAN (R 3.5.1)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.1)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.1)
#>  devtools      2.0.1   2018-10-26 [1] CRAN (R 3.5.1)
#>  digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.1)
#>  evaluate      0.12    2018-10-09 [1] CRAN (R 3.5.1)
#>  fs            1.2.6   2018-08-23 [1] CRAN (R 3.5.1)
#>  glue          1.3.0   2018-07-17 [1] CRAN (R 3.5.1)
#>  hms           0.4.2   2018-03-10 [1] CRAN (R 3.5.1)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.1)
#>  knitr         1.20    2018-02-20 [1] CRAN (R 3.5.1)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.1)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.1)
#>  pillar        1.3.0   2018-07-14 [1] CRAN (R 3.5.1)
#>  pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.5.1)
#>  pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.1)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.1)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.1)
#>  processx      3.2.0   2018-08-16 [1] CRAN (R 3.5.1)
#>  ps            1.2.1   2018-11-06 [1] CRAN (R 3.5.1)
#>  R6            2.2.2   2017-06-17 [2] CRAN (R 3.4.3)
#>  Rcpp          1.0.0   2018-11-07 [1] CRAN (R 3.5.1)
#>  readr         1.2.1   2018-11-22 [1] CRAN (R 3.5.1)
#>  remotes       2.0.2   2018-10-30 [1] CRAN (R 3.5.1)
#>  rlang         0.3.0.1 2018-10-25 [1] CRAN (R 3.5.1)
#>  rmarkdown     1.10    2018-06-11 [1] CRAN (R 3.5.1)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.1)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.1)
#>  stringi       1.2.4   2018-07-20 [1] CRAN (R 3.5.1)
#>  stringr       1.3.1   2018-05-10 [1] CRAN (R 3.5.1)
#>  testthat      2.0.1   2018-10-13 [1] CRAN (R 3.5.1)
#>  tibble        1.4.2   2018-01-22 [1] CRAN (R 3.5.1)
#>  usethis       1.4.0   2018-08-14 [1] CRAN (R 3.5.1)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.1)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.1)
#> 
#> [1] /home/pmassicotte/R/x86_64-pc-linux-gnu-library/3.5
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

**Comment by jennybc** [comment]
The input of `parse_*()` functions is generally anticipated to be *character*. So maybe the question is: why did this ever work?

What sort of workflow has you sending numeric input into `parse_number()`?

**Comment by PMassicotte** [comment]
When I have a dataframe where I have only numeric columns, I would use `df %>% mutate_all(parse_number)`. Just beeing lazy I guess :)

**Comment by PMassicotte** [comment]
Another handy feature that is not working anymore is `readr::parse_number(factor(c(1:5)))`.

**Comment by jimhester** [comment]
Using non-character input to any parse functions is nonsensical, at best it would essentially wasting time (because the input is coerced to a character then back to a number) and at worst it gives you incorrect results because the coercion can be lossy.

There are probably 10+ issues of people using non-character inputs to `parse_()` functions and being confused by the results, which is why this was changed to an error.

**Comment by jaanos** [comment]
But surely parsing factors does make sense (and can actually be done more efficiently than converting the entire vector to characters)? A common use case is when using `reshape2::melt` to convert columns corresponding to, say, years, into a single factor column, on which `parse_number` is then used to extract numbers.

**Comment by cdchapman** [comment]
Another useful feature is converting from a float to an integer (in `parse_integer`), as a quick way to truncate float or mixed character data.

I understand the need for defensive programming and I could believe that people have issues with this, but either way you are going to have issues. My impression in using the `parse_*` functions is that they would conform to the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle). The prefix "parse" implies that there may be some danger or loss; that we are going from something less structured to more controlled. The argument against loss is not very strong, because even character input can be lossy (e.g. `parse_number("$12.34")`).

**Comment by brianstamper** [comment]
I had a use case that brought this up and got me to here. I totally agree with @cdchapman about the robustness principle, and I just wanted to share an example of why someone might be trying to do this.

I understand that parsing a numeric doesn't make sense, but if you are doing things over a loop or mutate_all or similar this might come up, unless you explicitly code in the right checks, which it might be nice to not have to do if you are aware of what you are doing.

I'm taking many heterogenous CSV files doing a read_csv/reduce+inner join/bind_rows thing, and there is a column that contains a ranking where sometimes there are ties, so it will have a few rows with "T4", "T4" for two people tied for fourth, for example, and the read_csv guesser reads that as character. But sometimes there aren't ties, so the read_csv guesser takes them to be numeric. I wanted the parser to make them all numeric and my intuition was that it would not have a problem with receiving numerics and just passing them through. There are also a lot of different file layouts so I had hoped to avoid explicitly coding col_classes (and indeed I am parsing to numeric so first converting all to character to avoid this error just doesn't seem right).

This is what I am using now (not fully universal, but works for my situation):

```
my_parse_number <- function(x) {
  if (is_character(x)) {
    parse_number(x)  
  } else {
    x
  }
}
```
