### ISSUE TITLE
Build system cannot accomodate relative build locations: rpath setting wrong

### ISSUE THREAD

**Issue by eddelbuettel** [tidyverse/readr#924]
Debian builds have always relative to a current (possibly) temporary build directory.  The builds then happen in a set of subdirectories relative to the current directory: first `debian/`, then the package name and that location is taken to be `/` below which `/usr` etc are created -- and are at the end bundled up in a tarfile relative to the subdirectory which makes the lower-level directories believe it is actually  `/` and the root.

That works for as long as paths are in fact relative.  If an absolute path is constructed from the current directory, things fail.  That just happened here.   The log from my Debian upload of readr 1.2.1 shows

```
g++ -shared -L/usr/lib/R/lib -Wl,-z,relro -o readr.so Collector.o CollectorGuess.o Iconv.o LocaleInfo.o RcppExports.o Reader.o Source.o Tokenizer.o TokenizerDelim.o TokenizerFwf.o TokenizerWs.o connection.o datetime.o grisu3.o init.o localtime.o parse.o read.o type_convert.o write.o write_connection.o write_delim.o -L. -lrcon -L../inst/rcon -Wl,-rpath,/build/r-cran-readr-1.2.1/debian/r-cran-readr/usr/lib/R/site-library/readr/rcon -L/usr/lib/R/lib -lR
````

The key here is the `/build/r-cran-readr-1.2.1/debian/r-cran-readr/usr/lib/R/site-library/readr/rcon`. We see the build operating in a chroot cleanroom `/build` with the package, its `debian/` and package directory below it ... and then the supposed abolute path.  We get that for free from expanding

```
PKG_LIBS = -L. -lrcon -L../inst/rcon -Wl,-rpath,$(R_PACKAGE_DIR)/rcon
```

I just tried to fix it by overriding the fixed (known) path that would be used for the installed package.  That however failed for loading the package at the end of the build process -- so it is a bit of an issue.  If you could look into a scheme in which normal builds proceed as usual but we get to override this at build or install time I'd appreciate it.  This can't be a new issue for the build systems, but it has been a while since I last had to use `rpath` on a packaged library.

More context in [this Debian bug report](http://bugs.debian.org/914633) which was just filed again my r-cran-readr package for this issue.  I will follow up there with the respective Debian folks.

**Comment by jimhester** [comment]
I believe https://github.com/tidyverse/readr/tree/924 should fix this but it would nice to test it to be sure, clearly my test platforms did not surface this issue.

**Comment by eddelbuettel** [comment]
I can give you pointers to set up such an environment if you are interested in pursuing this.  I think we have demonstrated that the coverage of your current test platforms is narrower than what users do.

Can you explain (briefly) why you went down this route of an external shared library?  I can't say I am aware of another CRAN package doing this.

**Comment by jimhester** [comment]
Now fixed as part of https://github.com/tidyverse/readr/commit/160427575826348bfcafde435e92b63d9235ed74

**Comment by eddelbuettel** [comment]
Would you mind explaining why you went this route (as I asked here two days ago) ?  I am genuinely curious.

**Comment by jimhester** [comment]
https://github.com/tidyverse/readr/issues/856#issuecomment-391787058 may give you a hint, I will decline to answer more explicitly as CRAN frowns upon public discourse of it's policies.

**Comment by eddelbuettel** [comment]
I was coming from a similar angle as I am thinking that this had not been tried before.  Will poke you on DM.
