### ISSUE TITLE
readr 1.2.1 incompatible with Bioconductor package GEOquery 2.50.0

### ISSUE THREAD

**Issue by biostu24** [tidyverse/readr#925]
Apologies in advance if it would be more relevant to raise this issue with Bioconductor but I thought it was worth highlighting the different behavior of packages that rely readr.

I had been working on some scripts that used the GEOquery Bioconductor package to read in microarray data from GEO using GEOquery::getGEO. GEOquery requires readr. Everything was working fine until I installed some new packages (which I suspect upgraded readr). I think this was from version 1.1.1 to 1.2.1. It took a while to work out the issue was with readr. Rolling back from 1.2.1 to 1.1.1 resolved the issue.

Essentially getGEO loads in a large matrix with unique row and column names as well additional metadata. When readr 1.2.1 is installed, column names are not parsed correctly, resulting in duplicate column names and metadata is no longer correctly referenced to the columns. 

**Example of the issue**
I am using 64 bit R version 3.5.1 on Windows 10 Pro. This issue is also present with 64 bit R 3.4.4 on Unbuntu 16.04.5. I am using GEOquery 2.50.0.
The examples below use my Windows version, the only difference is the readr version:

_readr version 1.2.1:_
```R
> test <- GEOquery::getGEO('GSE76885', GSEMatrix = T, AnnotGPL=TRUE)
Found 1 file(s)
GSE76885_series_matrix.txt.gz
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE76nnn/GSE76885/matrix/GSE76885_series_matrix.txt.gz'
Content type 'application/x-gzip' length 10006900 bytes (9.5 MB)
==================================================
downloaded 9.5 MB
_
Parsed with column specification:
cols(
  .default = col_double(),
  A_23_P100001 = col_character()
)
See spec(...) for full column specifications.
File stored at: 
C:\Users\****\AppData\Local\Temp\RtmpuOk8mu/GPL6480.annot.gz
Warning message:
Duplicated column names deduplicated: '-0.615' => '-0.615_1' [65], '-0.267' => '-0.267_1' [95], '-0.303' => '-0.303_1' [96], '-0.105' => '-0.105_1' [101], '0.089' => '0.089_1' [107], '0.146' => '0.146_1' [110], '-0.184' => '-0.184_1' [124], '-0.45' => '-0.45_1' [149], '-0.16' => '-0.16_1' [154], '-0.047' => '-0.047_1' [155], '0.019' => '0.019_1' [157], '-0.074' => '-0.074_1' [158], '-0.113' => '-0.113_1' [159], '0.009' => '0.009_1' [168], '-0.149' => '-0.149_1' [170], '-0.085' => '-0.085_1' [175], '0.096' => '0.096_1' [176], '-0.281' => '-0.281_1' [177], '-0.096' => '-0.096_1' [178], '0.248' => '0.248_1' [179], '-0.308' => '-0.308_1' [181], '-0.22' => '-0.22_1' [190], '-0.306' => '-0.306_1' [195] 
```

See error on last line `Duplicated column names deduplicated`. The column names are supposed to start with "GSM" but are number strings instead. The column names are not parsed correctly which leads to failures on downstream data processing.

_readr version 1.1.1:_
```R
> test <- GEOquery::getGEO('GSE76885', GSEMatrix = T, AnnotGPL=TRUE)
Found 1 file(s)
GSE76885_series_matrix.txt.gz
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE76nnn/GSE76885/matrix/GSE76885_series_matrix.txt.gz'
Content type 'application/x-gzip' length 10006900 bytes (9.5 MB)
downloaded 9.5 MB
_
Parsed with column specification:
cols(
  .default = col_double(),
  ID_REF = col_character()
)
See spec(...) for full column specifications.
|==============================================================================================| 100%   27 MB
File stored at: 
C:\Users\****\AppData\Local\Temp\RtmpuOk8mu/GPL6480.annot.gz
Warning message:
closing unused connection 3 (https://ftp.ncbi.nlm.nih.gov/geo/series/GSE76nnn/GSE76885/matrix/)
```

This time the data is read in correctly. 

I have not had a chance to look into exactly where the parsing issue is arising.

**Comment by wloof** [comment]
Same problem!

**Comment by wloof** [comment]
datamat <- read_tsv(fname,quote='"',
                        na=c('NA','null','NULL','Null'), 
                        # somewhere in the past month or so, read_tsv changed
                        # the way it dealt with skip!!! Had to add the -1 to
                        # avoid the problem.
                        skip = series_table_begin_line-1,
comment = '!series_matrix_table_end')

**Comment by wloof** [comment]
datamat <- read_tsv(fname,quote='"',
                        na=c('NA','null','NULL','Null'), 
                        # somewhere in the past month or so, read_tsv changed
                        # the way it dealt with skip!!! Had to add the -1 to
                        # avoid the problem.
                        skip = series_table_begin_line-1, comment = '!series_matrix_table_end')

**Comment by jimhester** [comment]
This should be fixed by https://github.com/tidyverse/readr/pull/933
