### ISSUE TITLE
type_convert cannot convert characters "t"/"f" to logical type

### ISSUE THREAD

**Issue by stelsemeyer** [tidyverse/readr#947]
postgres' copy command (i.e. `COPY ... TO STDOUT WITH ...`) converts boolean columns to the characters "t" and "f" by default. There seems to be no flag to avoid this behaviour in postgres, unless manually casting to text first.

Would it be possible to add an option for `readr::type_convert` to guess columns solely consisting of the values `t` and `f`. Currently those are kept characters:

```
readr::type_convert(dplyr::data_frame(bool = c("t", "f")))

#> Parsed with column specification:
#> cols(
#>   bool = col_character()
#> )
#> # A tibble: 2 x 1
#>   bool 
#>   <chr>
#> 1 t    
#> 2 f
```

**Comment by jennybc** [comment]
readr can use R's conventions re: converting character to logical. But you need to request it by specifying col type in the `type_convert()` call.

``` r
readr::parse_logical(c("t", "f"))
#> [1]  TRUE FALSE

readr::type_convert(
  dplyr::data_frame(bool = c("t", "f")),
  col_types = "l"
)
#> # A tibble: 2 x 1
#>   bool 
#>   <lgl>
#> 1 TRUE 
#> 2 FALSE
```

<sup>Created on 2018-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by stelsemeyer** [comment]
Thank you, @jennybc! That is very helpful and seems to also work for multipe types (when working under the questionable assumption of having unknown column names and types):

``` r
readr::type_convert(
  dplyr::data_frame(bool = c("t", "f"), num = 1:2, char = c("a", "b")),
  col_types = readr::cols("l", "c")
  )
#> # A tibble: 2 x 3
#>   bool    num char 
#>   <lgl> <int> <chr>
#> 1 TRUE      1 a    
#> 2 FALSE     2 b
```

<sup>Created on 2018-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
