### ISSUE TITLE
Changed date format in `write_excel_csv`

### ISSUE THREAD

**Issue by jschelbert** [tidyverse/readr#948]
With newer version of `readr` something has changed when writing data frames to CSV via the `write_excel_csv` function.
Old version (1.1.0) yields `2018-01-01T00:00:00Z` in the newer versions (since 1.2.0) I get `2018/01/01 00:00:00`.

See example code below:
```r
library(readr)
library(dplyr)
library(lubridate)

df <- data_frame(a=ymd_h(2018010100, 2018120112), b = 1:2)
write_excel_csv(df, "temp.csv")
devtools::session_info()


#--------------------------------------------------------------------------------------------
devtools::dev_mode()
devtools::install_version("readr", version = "1.1.0", repos = "http://cran.us.r-project.org")
library(readr)
library(dplyr)
library(lubridate)

df <- data_frame(a=ymd_h(2018010100, 2018120112), b = 1:2)
write_excel_csv(df, "temp2.csv")
devtools::session_info()
```

**Comment by cderv** [comment]
This change happened in #761 to fix #553 . 

`write_excel_csv` is intended to be used to create output that can be imported into excel, so this is on purpose. You still have the unchange date format in `write_csv`.

**Comment by jschelbert** [comment]
Hi Christophe,
thank you for the clarification. I was a bit puzzled as this change wasn't mentioned in the change log (or have I missed it?).

**Comment by cderv** [comment]
you are right, it seems to be missing from the NEWS file... 🤔 Do not know if it can be added with such a delay.
