### ISSUE TITLE
Unable to use select() on a "spec_tbl_df"

### ISSUE THREAD

**Issue by MZellou** [tidyverse/readr#951]
Hello,

Does the spec_tdb_df not inherit the select() method? 

i have the following error :  unable to find an inherited method for function ‘select’ for signature ‘"spec_tbl_df"’

Thanks,
Marouane

**Comment by cderv** [comment]
hello, 

can you follow advice from https://www.tidyverse.org/help/ by providing a reprex ? 

what is the context where this error happen ? what did you try exactly ? 

Do not hesitate also to look for help in community.rstudio.com. There is a broad community happy to help there.

**Comment by MZellou** [comment]
Hello,
Thank you for your quick answer ! 

I'm reading the first line of a csv file, which one is uploaded from a shiny app. 
Then each observation of this first line is used in valueBoxes or tableOutputs. However, this error appeared whereas everything worked until now.

Here is an example : 

server : 
data_header <- reactive({
  read_delim(
    input$file$datapath,                            # The file i'm uploading
    ";",
    escape_double = FALSE,
    col_names = as.character(header_bailleur) ,
    col_types = cols(.default = "c"),
    quote = "",
    trim_ws = TRUE,
    n_max = 1,
    locale = locale(decimal_mark = ",")
  )
})

SIRETPRO <- reactive({ select(data_header(), SIRETPRO) })

output$SIRETPRO_check <- renderUI({
  
  req(input$file)
  if (str_detect(SIRETPRO(),"E+")){
  
  valueBox(
    value=h2("SIRET au format scientifique"),
    subtitle="",
    icon=icon("exclamation-triangle"),width=4,
    color="red"
  )}
  
  else{
    valueBox(
      value=h2(paste("SIRET :",SIRETPRO())),
      subtitle="",
      icon=icon("check-circle"),width=4,
      color="green"
    )}
  })

ui : 
fluidRow(uiOutput("SIRETPRO_check"))



I'm pretty sure I have this error because the variable header_bailleur is a spec_tbl_df. Every output using the data_header() gives an error and I don't understand how to make it simple tbl_df.

Hoping you could help,
Marouane

**Comment by MZellou** [comment]
I think it is not coming from the spec_tbl_df ^^'
