### ISSUE TITLE
Why does readr::read_csv need timezone data and Olson database?

### ISSUE THREAD

**Issue by ttimbers** [tidyverse/readr#952]
This issue is closed, but I see no resolution: https://github.com/tidyverse/readr/issues/320

I just ran into a similar situation today when teaching on a server. We were trying to use `readr::read_csv` to load this file: https://raw.githubusercontent.com/UBC-DSCI/dsci-100/master/materials/worksheet_01/marathon_small.csv

On one server which has tzdata installed, it works fine, on another that does not have this installed the following error message is given:

```
library(tidyverse)
marathon_small <- read_csv("marathon_small.csv")
```

```
Warning message in OlsonNames():
“no Olson database found”
Error: Unknown TZ UTC
Traceback:

1. read_csv("marathon_small.csv")
2. read_delimited(file, tokenizer, col_names = col_names, col_types = col_types, 
 .     locale = locale, skip = skip, comment = comment, n_max = n_max, 
 .     guess_max = guess_max, progress = progress)
3. col_spec_standardise(data, skip = skip, comment = comment, guess_max = guess_max, 
 .     col_names = col_names, col_types = col_types, tokenizer = tokenizer, 
 .     locale = locale)
4. guess_header(ds_header, tokenizer, locale)
5. guess_header_(datasource, tokenizer, locale)
6. default_locale()
7. locale()
8. check_tz(tz)
9. stop("Unknown TZ ", x, call. = FALSE)
```

This csv file is very simple (see snippet below). Why does `readr::read_csv` need timezone data and Olson database? This GitHub issue, appears to tracking down  `readr::read_csv` depending on `tzdata` but why? Naively, it doesn't seem necessary, and `read.csv` works fine on either server.

`.csv` snippet:
```
age,bmi,km5_time_seconds,km10_time_seconds,sex
25.0,21.6221160888672,NA,2798,female
41.0,23.905969619751,1210.0,NA,male
25.0,21.6407279968262,994.0,NA,male
35.0,23.5923233032227,1075.0,2135,male
34.0,22.7064037322998,1186.0,NA,male
45.0,42.0875434875488,3240.0,NA,female
33.0,22.5182952880859,1292.0,NA,male
58.0,25.2340793609619,NA,3420,male
```

The smallest reproducible example I can get down to is this: 

```
library(tidyverse)
default_locale()
```

which on the problematic server gives: 
```
Warning message in OlsonNames():
“no Olson database found”
Error: Unknown TZ UTC
Traceback:

1. default_locale()
2. locale()
3. check_tz(tz)
4. stop("Unknown TZ ", x, call. = FALSE)
```

So the problem likely stems from the [`read_*` functions depending on `default_locale()` for the `locale` argument by default](https://github.com/tidyverse/readr/blob/a0fbe94c742be204f2cc4d823a0ed37613906059/R/read_delim.R#L118). Is this really necessary? Naively, I think not, but I could be very wrong. Is there a way to say `locale = None/NA/etc`?

This is not just a problem for me, as I have come across others experiencing the same problem...
- https://github.com/swirldev/swirl/issues/603
- https://github.com/jupyter/docker-stacks/issues/502
- https://github.com/tidyverse/readr/issues/320

**Comment by jimhester** [comment]
Because readr reads date times using it. 

Why doesn't your system have an Olson database?

**Comment by ttimbers** [comment]
In our case, I think because it wasn't always part of the docker-stacks for jupyter? But that begs the question, is every machine `readr` is used on expected to have that? 

We can fix it on our machines, but I opened this issue because I am not the only one who seems to have come across this problem. Wonder if it would be nice/possible for `read_*` to not care about time zones if no date times are in the data being loaded? Or tell `read_*` not to read things as date/times and just as numbers/characters?

**Comment by jimhester** [comment]
Yes, every machine readr is used on is expected to have a olsen database.

**Comment by ttimbers** [comment]
Thanks for the prompt response and explanation @jimhester!

**Comment by wangshun1121** [comment]
In docker container, here is a solution:
```
# Ubuntu
apt install tzdata
# CentOS
yum install tzdata
```
