### ISSUE TITLE
write_* formats badly numbers over 1e15

### ISSUE THREAD

**Issue by Zack-83** [tidyverse/readr#957]
Hallo,
I have a tibble whose numeric columns contain values ranging over several magnitude orders, partly in exponential notation.
Upon saving with `write_delim` (or similar), all numbers higher than $10^15$ are written in a very unusual exponential notation, which refers to the position of the _last_ significant digit. This is yet correct in strict mathematical meaning, but goes again common scientific practice and creates some confusion when the saved file is opened with a text editor such as Notepad++.
A reproducible example:
```
library(tidyverse)
u <- tibble( name=c("Planck constant","Avogadro number","Loschmidt constant",
                    "Faraday constant"),
            numValue=c(6.62607015e-34,6.02214076e+23,2.65e+25,96485.33289),
            stdUncertainty=c(0,0,1.5e+19,5.9e-4) )
u           # the numbers are displayed correctly, apart from truncation
#> # A tibble: 4 x 3
#>   name               numValue stdUncertainty
#>   <chr>                 <dbl>          <dbl>
#> 1 Planck constant    6.63e-34       0.      
#> 2 Avogadro number    6.02e+23       0.      
#> 3 Loschmidt constant 2.65e+25       1.50e+19
#> 4 Faraday constant   9.65e+ 4       5.90e- 4
write_delim(u,"u1.tsv",delim="\t")
write.table(u,"u2.tsv",sep="\t",quote=FALSE,row.names=FALSE)
```
Here is the output of `write_delim`, opened with Notepad++:
> name               numValue       stdUncertainty
Planck constant    6.62607015e-34 0
Avogadro number    602214076e15   0
Loschmidt constant 265e23         15e18
Faraday constant   96485.33289    5.9e-4

whereas the old `write.table` correctly formats the numbers in scientific notation (even the zero values, which actually don't need!):
> name               numValue        stdUncertainty
Planck constant    6.62607015e-34  0e+00
Avogadro number    6.02214076e+23  0e+00
Loschmidt constant 2.65e+25        1.5e+19
Faraday constant   9.648533289e+04 5.9e-04

**Comment by Zack-83** [comment]
Possibly related to https://github.com/tidyverse/readr/issues/845#issue-321925537, https://github.com/tidyverse/readr/issues/671#issue-227711594

**Comment by jimhester** [comment]
This is the intended behavior, the outputs are designed to take the fewest characters while still producing the same IEEE double values.

If you want more control over the formatting I would suggest calling `format()`, `formatC()` or `prettyNum()` on your values before passing to readr.
