### ISSUE TITLE
read_csv assumes integer and deletes numeric values

### ISSUE THREAD

**Issue by oscci** [tidyverse/readr#969]
Here is an example of the problem; the DENOMINATOR column in this very large public database is mostly integer values, but there are some values with decimals. These are deleted if you use read_csv, but read ok with read.csv

```
library(arsenal) #for compare function

tef4file <- read_csv("https://ofslivefs.blob.core.windows.net/files/TEF%20data%20updated/Metrics/TEF_YearFour_AllMetrics.csv")
tef4afile<-read.csv("https://ofslivefs.blob.core.windows.net/files/TEF%20data%20updated/Metrics/TEF_YearFour_AllMetrics.csv")
compare(tef4file$DENOMINATOR,tef4afile$DENOMINATOR)
```

**Comment by jennybc** [comment]
I suggest you look at the `guess_max` argument. By default it is 1000, meaning if the first 1000 entries of a column look like integers, the column will be guessed as integer. If my hunch is right, you can either increase `guess_max` in order to "catch" some numbers with decimals or you can use `col_types` to transmit your knowledge of this column's desired type.

**Comment by oscci** [comment]
Thanks Jenny.
But do you agree that there isn't any warning or error message?: people on Twitter are saying I should have picked this up through an error message or warning.

And although it's good to know about guess, it really isn't helpful in my case, as I am reading in and trying to make sense of a government dataset that is poorly documented. So my prior knowledge of what to expect is zero.

Once I worked out what numerator and denominator represented, I would have expected both to be integer: it's rather odd that it isn't for about 7% of values. These are supposedly numbers of students - the only way to explain non-integer values is if they use 'full time equivalent' as a weighted sum of full and part-timers.

So this is a case where I don't think I could have been expected to anticipate the problem - I only did so when I summed all numerators and denominators for some categories only to find the ratio between them was more than 1. And given the size of the dataset, I had a fair old time tracking down the problem - I could pretty easily explore things in R, but then had to check across back to the original csv file in excel to confirm there was an inconsistency, which I just hadn't anticipated.

I greatly appreciate all you are doing with R, and the responsiveness to me raising this issue.

R

On 17 Feb 2019, at 01:40, Jennifer (Jenny) Bryan <notifications@github.com<mailto:notifications@github.com>> wrote:


I suggest you look at the guess_max argument. By default it is 1000, meaning if the first 1000 entries of a column look like integers, the column will be guessed as integer. If my hunch is right, you can either increase guess_max in order to "catch" some numbers with decimals or you can use col_types to transmit your knowledge of this column's desired type.

**Comment by jennybc** [comment]
What version of readr do you have? In my hands, `read_csv()` imports this column the same as `read.csv()`. I think you might be working with something older than the current CRAN version.

``` r
library(readr)

# url <- "https://ofslivefs.blob.core.windows.net/files/TEF%20data%20updated/Metrics/TEF_YearFour_AllMetrics.csv"
# fname <- basename(url)
# download.file(url, fname)

fname <- "TEF_YearFour_AllMetrics.csv"
tef4file <- read_csv(fname)
#> Parsed with column specification:
#> cols(
#>   PROVIDER_NAME = col_character(),
#>   PROVIDER_TEFUKPRNTF = col_double(),
#>   PROVIDER_MAJORITYMODE = col_character(),
#>   PROVIDER_SUITABLEMETRICS = col_character(),
#>   METRIC = col_character(),
#>   MODEOFSTUDY = col_character(),
#>   SPLIT_ID = col_character(),
#>   SPLIT_CATEGORY = col_character(),
#>   NUMERATOR = col_double(),
#>   DENOMINATOR = col_double(),
#>   INDICATOR = col_double(),
#>   BENCHMARK = col_double(),
#>   PERCENTCONTRIBUTIONTOBENCHMARK = col_double(),
#>   DIFFERENCE = col_double(),
#>   STANDARDDEVIATION = col_double(),
#>   ZSCORE = col_double(),
#>   FLAG = col_character(),
#>   ABSOLUTEVALUEMARKER = col_character(),
#>   ReasonNull = col_character()
#> )
tef4afile<-read.csv(fname)
arsenal::compare(tef4file$DENOMINATOR,tef4afile$DENOMINATOR)
#> Equal
```

<sup>Created on 2019-02-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.2 (2018-12-20)
#>  os       macOS Mojave 10.14.3        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_CA.UTF-8                 
#>  ctype    en_CA.UTF-8                 
#>  tz       America/Vancouver           
#>  date     2019-02-17                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                         
#>  arsenal       2.0.0      2019-01-16 [1] CRAN (R 3.5.2)                 
#>  assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.0)                 
#>  backports     1.1.3      2018-12-14 [1] CRAN (R 3.5.0)                 
#>  callr         3.1.1      2018-12-21 [1] CRAN (R 3.5.0)                 
#>  cli           1.0.1      2018-09-25 [1] CRAN (R 3.5.0)                 
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                 
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.0)                 
#>  devtools      2.0.1.9000 2019-02-14 [1] local                          
#>  digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.0)                 
#>  evaluate      0.13       2019-02-12 [1] CRAN (R 3.5.2)                 
#>  fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.0)                 
#>  glue          1.3.0.9000 2019-02-14 [1] Github (tidyverse/glue@8188cea)
#>  highr         0.7        2018-06-09 [1] CRAN (R 3.5.0)                 
#>  hms           0.4.2      2018-03-10 [1] CRAN (R 3.5.0)                 
#>  htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.0)                 
#>  knitr         1.21       2018-12-10 [1] CRAN (R 3.5.2)                 
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.0)                 
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                 
#>  pillar        1.3.1      2018-12-15 [1] CRAN (R 3.5.0)                 
#>  pkgbuild      1.0.2.9000 2018-12-06 [1] Github (r-lib/pkgbuild@6e4ebdf)
#>  pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.5.0)                 
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.0)                 
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.0)                 
#>  processx      3.2.1      2018-12-05 [1] CRAN (R 3.5.0)                 
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.5.0)                 
#>  R6            2.3.0      2018-10-04 [1] CRAN (R 3.5.0)                 
#>  Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.5.0)                 
#>  readr       * 1.3.1      2018-12-21 [1] CRAN (R 3.5.1)                 
#>  remotes       2.0.2.9000 2019-02-14 [1] Github (r-lib/remotes@dedcc06) 
#>  rlang         0.3.1.9000 2019-01-30 [1] Github (r-lib/rlang@7243c6d)   
#>  rmarkdown     1.11       2018-12-08 [1] CRAN (R 3.5.0)                 
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                 
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.1)                 
#>  stringi       1.3.1      2019-02-13 [1] CRAN (R 3.5.2)                 
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.5.2)                 
#>  testthat      2.0.1      2018-10-13 [1] CRAN (R 3.5.0)                 
#>  tibble        2.0.1      2019-01-12 [1] CRAN (R 3.5.2)                 
#>  usethis       1.4.0.9000 2019-02-11 [1] local                          
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.0)                 
#>  xfun          0.4        2018-10-23 [1] CRAN (R 3.5.0)                 
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.0)                 
#> 
#> [1] /Users/jenny/resources/R/library
#> [2] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

</details>

</br>

Regardless, it is definitely true that readr limits the number of rows consulted for guessing, whereas `read.csv()` does not. This is one of the reasons it is faster, i.e. it does have a purpose. So, when getting to know an important dataset for the first time, with no external knowledge, it is probably worth it to import with `guess_max = Inf` at least once and take a hard look at column types.

**Comment by jennybc** [comment]
This part of the v1.2.0 release notes is relevant:

https://github.com/tidyverse/readr/blob/master/NEWS.md#integer-column-guessing

> Integer column guessing
>
> readr functions no longer guess columns are of type integer, instead these columns are guessed as numeric. Because R uses 32 bit integers and 64 bit doubles all integers can be stored in doubles, guaranteeing no loss of information. This change was made to remove errors when numeric columns were incorrectly guessed as integers. If you know a certain column is an integer and would like to read them as such you can do so by specifying the column type explicitly with the col_types argument.

**Comment by oscci** [comment]
Many thanks for all your help.
You were right: have updated all packages and it now reads in OK.

I now am vowing to learn to use tidyverse better: these big government files need a lot of wrangling, and tidyverse has already been invaluable, but I am still doing a lot in a more clunky way.

best wishes

On 17 Feb 2019, at 17:35, Jennifer (Jenny) Bryan <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of readr do you have? In my hands, read_csv() imports this column the same as read.csv(). I think you might be working with something older than the current CRAN version.

library(readr)

# url <- "https://ofslivefs.blob.core.windows.net/files/TEF%20data%20updated/Metrics/TEF_YearFour_AllMetrics.csv"
# fname <- basename(url)
# download.file(url, fname)

fname <- "TEF_YearFour_AllMetrics.csv"
tef4file <- read_csv(fname)
#> Parsed with column specification:
#> cols(
#>   PROVIDER_NAME = col_character(),
#>   PROVIDER_TEFUKPRNTF = col_double(),
#>   PROVIDER_MAJORITYMODE = col_character(),
#>   PROVIDER_SUITABLEMETRICS = col_character(),
#>   METRIC = col_character(),
#>   MODEOFSTUDY = col_character(),
#>   SPLIT_ID = col_character(),
#>   SPLIT_CATEGORY = col_character(),
#>   NUMERATOR = col_double(),
#>   DENOMINATOR = col_double(),
#>   INDICATOR = col_double(),
#>   BENCHMARK = col_double(),
#>   PERCENTCONTRIBUTIONTOBENCHMARK = col_double(),
#>   DIFFERENCE = col_double(),
#>   STANDARDDEVIATION = col_double(),
#>   ZSCORE = col_double(),
#>   FLAG = col_character(),
#>   ABSOLUTEVALUEMARKER = col_character(),
#>   ReasonNull = col_character()
#> )
tef4afile<-read.csv(fname)
arsenal::compare(tef4file$DENOMINATOR,tef4afile$DENOMINATOR)
#> Equal

Created on 2019-02-17 by the reprex package<https://reprex.tidyverse.org/> (v0.2.1.9000)

Session info

devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 3.5.2 (2018-12-20)
#>  os       macOS Mojave 10.14.3
#>  system   x86_64, darwin15.6.0
#>  ui       X11
#>  language (EN)
#>  collate  en_CA.UTF-8
#>  ctype    en_CA.UTF-8
#>  tz       America/Vancouver
#>  date     2019-02-17
#>
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version    date       lib source
#>  arsenal       2.0.0      2019-01-16 [1] CRAN (R 3.5.2)
#>  assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.0)
#>  backports     1.1.3      2018-12-14 [1] CRAN (R 3.5.0)
#>  callr         3.1.1      2018-12-21 [1] CRAN (R 3.5.0)
#>  cli           1.0.1      2018-09-25 [1] CRAN (R 3.5.0)
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.0)
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.0)
#>  devtools      2.0.1.9000 2019-02-14 [1] local
#>  digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.0)
#>  evaluate      0.13       2019-02-12 [1] CRAN (R 3.5.2)
#>  fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.0)
#>  glue          1.3.0.9000 2019-02-14 [1] Github (tidyverse/glue@8188cea)
#>  highr         0.7        2018-06-09 [1] CRAN (R 3.5.0)
#>  hms           0.4.2      2018-03-10 [1] CRAN (R 3.5.0)
#>  htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.0)
#>  knitr         1.21       2018-12-10 [1] CRAN (R 3.5.2)
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.0)
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.0)
#>  pillar        1.3.1      2018-12-15 [1] CRAN (R 3.5.0)
#>  pkgbuild      1.0.2.9000 2018-12-06 [1] Github (r-lib/pkgbuild@6e4ebdf)
#>  pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.5.0)
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.0)
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.0)
#>  processx      3.2.1      2018-12-05 [1] CRAN (R 3.5.0)
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.5.0)
#>  R6            2.3.0      2018-10-04 [1] CRAN (R 3.5.0)
#>  Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.5.0)
#>  readr       * 1.3.1      2018-12-21 [1] CRAN (R 3.5.1)
#>  remotes       2.0.2.9000 2019-02-14 [1] Github (r-lib/remotes@dedcc06)
#>  rlang         0.3.1.9000 2019-01-30 [1] Github (r-lib/rlang@7243c6d)
#>  rmarkdown     1.11       2018-12-08 [1] CRAN (R 3.5.0)
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.1)
#>  stringi       1.3.1      2019-02-13 [1] CRAN (R 3.5.2)
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.5.2)
#>  testthat      2.0.1      2018-10-13 [1] CRAN (R 3.5.0)
#>  tibble        2.0.1      2019-01-12 [1] CRAN (R 3.5.2)
#>  usethis       1.4.0.9000 2019-02-11 [1] local
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.0)
#>  xfun          0.4        2018-10-23 [1] CRAN (R 3.5.0)
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.0)
#>
#> [1] /Users/jenny/resources/R/library
#> [2] /Library/Frameworks/R.framework/Versions/3.5/Resources/library


Regardless, it is definitely true that readr limits the number of rows consulted for guessing, whereas read.csv() does not. This is one of the reasons it is faster, i.e. it does have a purpose. So, when getting to know an important dataset for the first time, with no external knowledge, it is probably worth it to import with guess_max = Inf at least once and take a hard look at column types.

**Comment by jennybc** [comment]
OK glad it is sorted.
