### ISSUE TITLE
parse_* no longer useful for handling factors that represent numbers

### ISSUE THREAD

**Issue by djbirke** [tidyverse/readr#973]
2be9285a5a585e7b2dc4c662875f14f1b39eb606 breaks using `parse_*` as a way to collapse factor levels that represent numbers back into those numbers.

Here is a situation that is common in surveys: Via a drop-down menu ask for a number, where one of the options is "x or more". I then want to map that "x or more" into a number for analysis.

The working solution looks weird to me. I would expect that whenever `parse_integer` takes a factor, it converts the factor values according to their labels, and then parses those labels as integers.

So I want to ask if this the intended behavior of `parse_*`?

``` r
library(tidyverse)
x <- factor(c(4:6, '7 or more'))
x <- fct_collapse(x, '10' = '7 or more')

# Does not work
as.integer(x)
#> [1] 1 2 3 4
parse_integer(x)
#> Error in parse_vector(x, col_integer(), na = na, locale = locale, trim_ws = trim_ws): is.character(x) is not TRUE

# Works, but looks weird
parse_integer(as.character(x))
#> [1]  4  5  6 10
```

<sup>Created on 2019-03-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jimhester** [comment]
Yes, the parse functions are meant to parse only character vectors.

You don't really even need `parse_integer()` in this case, just `as.integer(as.character(x))`

**Comment by djbirke** [comment]
Got it - thanks a lot!
