### ISSUE TITLE
`recode_na` argument in `col_*` functions ?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/readr#978]
I'm working on a csv that has a column that is either missing or `1`. missing means `FALSE ` and `1` means `TRUE`.

It would have been convenient to be able to map these missing values to `FALSE ` directly in the `read_*` call for this specific column. As far as I understand this is not possible at the moment.

For character columns it can also be convenient to set specific values for missing.

Maybe something like this : 

```
read_csv(
  csv_path,
  col_types = cols(is_foo = col_logical(na_recode = FALSE),
                   bar = col_character(na_recode = "unknown bar"))
```

By the same token, these could have a parameter `na` that overrides the `na` parameter of `read_*` functions for specific columns ?

**Comment by jimhester** [comment]
I don't think it is worth adding complexity to readr, when `tidyr::replace_na()` exists that can handle this.
