### ISSUE TITLE
Feature request: read_csv skip lines till pattern match

### ISSUE THREAD

**Issue by jpwhitney** [tidyverse/readr#979]
I am trying to use “read_csv” to read in many (thousands) of csv files which have the same data structure but different length metadata at the beginning of the file. Some I need to skip 15 lines, others 19.
Consequently instead of using “read_csv” I am using “fread” (from a different package) since it allows skip = “Date” which skips to the first line of header names (which starts with “Date/Time”.

Is there a workaround for this issue so I can use read_csv? I’ve done extensive reading on the forums but so far have not found anything.

**Comment by jimhester** [comment]
You can write a simple helper function that will do this (code below assumes the Date is in the first 25 lines).

```r
find_skip <- function(file, pattern, n = 25) {
  min(grep(pattern, readr::read_lines(file, n)))
}

readr::read_csv(file, skip = find_skip(file, "^Date"))
```

And if you want to read all of the files into one tibble.

```r
my_reader <- function(file, pattern, ...) {
  readr::read_csv(file, skip = find_skip(file, "^Date"))
}

purrr::map_dfr(path_to_files, my_reader)
```

**Comment by jpwhitney** [comment]
Thanks @jimhester, this looks great, thanks for showing how to do that.
