### ISSUE TITLE
Error when reading from empty pipe

### ISSUE THREAD

**Issue by sfrenk** [tidyverse/readr#980]
version 1.3.1 of readr throws an error when reading data piped in from a file that contains a header row but no data rows. This does not happen with version 1.1.1. Here's a reproducible example:

```r
fh <- pipe("echo -e \"A\tB\"", open = "rb")

line1 <- readLines(fh, n = 1)

df <- readr::read_tsv(fh)

close(fh)
```

error message:
```
Error in guess_header_(datasource, tokenizer, locale) : 
  Cannot read file /tmp/RtmporleTx/file12d04ddd6: Invalid argument
```

**Comment by jimhester** [comment]
This seems to be fixed in the current devel version.
