### ISSUE TITLE
Allow read_csv() to determine column types using all rows

### ISSUE THREAD

**Issue by isaactpetersen** [tidyverse/readr#982]
I'm using `read_csv()` to read data files.  However, I receive parsing failures because `read_csv()` is trying to guess the column types based on the first 1000 rows (the default value for the `guess_max` argument).  This leads to parsing failures because my values in the later rows of the data frame (e.g., 2s and 3s) do not conform to the binary variable (0s/1s) that is guessed from the first 1000 rows.

Ideally, we'd be able to set `guess_max` to `Inf` or (automatically) to the number of rows in the dataframe.  But these are not an option&mdash;`read_csv()` throws an error when trying to set `guess_max` to `Inf`: see issue https://github.com/tidyverse/readr/issues/588.  A successful workaround is to manually set `guess_max` to an arbitrarily large number.  But this is not elegant, and it can lead to system crashing or errors if the value is too large (see issue https://github.com/tidyverse/readr/issues/588).  And it's not always practical to specify all column types manually.  It would also be nice not to have to use two steps (read in the data as characters and use `type_convert()`).

**Comment by jimhester** [comment]
I understand the concern, but due to the way guessing is implemented it is not trivial to support. For now using `type_convert()` is the proper way to handle this, e.g.

```r
x <- read_csv("file.csv", col_types = cols(.default = col_character())) %>% type_convert()
```
