### ISSUE TITLE
Feature request: could read_lines() accept negative n_max, to read from end of file

### ISSUE THREAD

**Issue by dan-reznik** [tidyverse/readr#983]
I would like to do:

```{r}
read_lines('fname.txt', n_max=-2) 
```

to read just the last line (since n_max=-1 currently reads the entire file). or

```{r}
read_lines('fname.txt', n_max=-N)
```

to read the last N-1 lines in the file. this way i don't have to know how many lines there are, skip them, etc.

**Comment by jimhester** [comment]
While interesting, I don't think this is likely to be implemented. I would suggest you use `tail(n = N, vroom::vroom_lines('fname.txt'))`

**Comment by dan-reznik** [comment]
the idea is that you don't bring the lines into memory. it would be crucial
if the file has a billion lines.

dan

**Comment by USMortality** [comment]
Possible workaround:

To get the number of lines in a file without reading all its contents into memory in R, you can use the count.fields() function. This function counts the number of fields (columns) in each line of a file and returns a vector with the count for each line. By taking the length of this vector, you can determine the number of lines in the file.

Here's an example of how to use count.fields() to get the number of lines in a file:

`line_count <- sum(count.fields("path/to/file.csv"))`

In this example, "path/to/file.csv" should be replaced with the actual path to your file.

Please note that count.fields() may read the file partially, but it does not load the entire file into memory. It only reads enough of the file to determine the number of fields in each line.
