### ISSUE TITLE
Fixed-width file import should have option to ignore single spaces

### ISSUE THREAD

**Issue by dhmontgomery** [tidyverse/readr#984]
`readr` has a number of helpful functions — `read_table()`, `read_table2()` and `fwf_empty()` — that can examine whitespace in a fixed-width file and estimate where column breaks should be. 

However, this can behave poorly in cases where columns contain unquoted strings with spaces in them. To give some common examples, "New York" or "Cook County". 

As an example, I've loaded the first few lines of a U.S. Census file showing county-to-county migration (original, very large file [here](https://www2.census.gov/programs-surveys/demo/tables/geographic-mobility/2016/county-to-county-migration-2012-2016/county-to-county-migration-flows/CtyxCty_US.txt)) into a [gist](https://gist.githubusercontent.com/dhmontgomery/b43b0bd09c80ac4ec0659aa8e8b0201b/raw/2d476575e02486d14cb263fd831bdf2c29e47fe1/fwf_text.txt). 

All three of the options below produce the same output: detecting the space in "Autauga County" as reflecting separate columns:

```r
url <- "https://gist.githubusercontent.com/dhmontgomery/b43b0bd09c80ac4ec0659aa8e8b0201b/raw/2d476575e02486d14cb263fd831bdf2c29e47fe1/fwf_text.txt"
read_table(url, col_names = FALSE)
read_table2(url, col_names = FALSE)
read_fwf(url, col_positions = fwf_empty(url))
```

Obviously there are some cases where we *want* these functions to treat a single space as reflecting separate columns in a fixed-width data. So changing the default behavior here would be bad. My thought was that the functions could be improved by adding an option to ignore single spaces when calculating columns.

**Comment by jimhester** [comment]
You can get what you want by pre-processing the lines and passing them to the `fwf_empty()` function. For the full dataset you only need to preprocess the first 100 lines, which is the default for `fwf_empty()`. In this case I transform the single spaces to the [ascii unit separator character](https://en.wikipedia.org/wiki/Delimiter#ASCII_delimited_text) before passing it to `fwf_empty()`

``` r
lines <- readr::read_lines("https://gist.githubusercontent.com/dhmontgomery/b43b0bd09c80ac4ec0659aa8e8b0201b/raw/2d476575e02486d14cb263fd831bdf2c29e47fe1/fwf_text.txt")
readr::read_fwf(lines, readr::fwf_empty(gsub("\\b \\b", "\x1F", head(lines, n = 100))))
#> # A tibble: 20 x 33
#>    X1     X2       X3    X4    X5    X6    X7    X8    X9   X10   X11   X12
#>    <chr>  <chr> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#>  2 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#>  3 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#>  4 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#>  5 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#>  6 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#>  7 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#>  8 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#>  9 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#> 10 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#> 11 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#> 12 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#> 13 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#> 14 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#> 15 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#> 16 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#> 17 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#> 18 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#> 19 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#> 20 00100… Auta… 54311   207 45906  1177  8284  1120  3753   933  2732   702
#> # … with 21 more variables: X13 <dbl>, X14 <dbl>, X15 <dbl>, X16 <chr>,
#> #   X17 <chr>, X18 <dbl>, X19 <dbl>, X20 <dbl>, X21 <dbl>, X22 <dbl>,
#> #   X23 <dbl>, X24 <dbl>, X25 <dbl>, X26 <dbl>, X27 <dbl>, X28 <dbl>,
#> #   X29 <dbl>, X30 <chr>, X31 <chr>, X32 <dbl>, X33 <dbl>
```

<sup>Created on 2019-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
