### ISSUE TITLE
no locale parameter for write_file()

### ISSUE THREAD

**Issue by dan-reznik** [tidyverse/readr#985]
while most readr 1.3.1 `read_*()` routines have a locale parameter, `write_file()` does not admit one. is this by design?

**Comment by cderv** [comment]
FWIW no other `write_*` functions in _readr_ have a _locale_ argument. They all write with UTF8 like as precised in `?write_delim`
> All columns are encoded as UTF-8

**Comment by jimhester** [comment]
It is, the write functions output formats designed to produce the same results regardless of locale.
