### ISSUE TITLE
read_lines() w/ non-zero skip gets out of sync for longer files.

### ISSUE THREAD

**Issue by dan-reznik** [tidyverse/readr#986]
when read_lines() is used with longish text files (1000s of lines), the use of skip and n_max is unreliable. to demonstrate this issue i created a github repository (since the demo needs a file). it's here: https://github.com/dan-reznik/read_lines_bug

I am also including a "reprex", but you will need to download [text_file.zip](https://github.com/dan-reznik/read_lines_bug/blob/master/test_file.zip) from the above github repo to reproduce it.

The text file within the .zip has some 31.6k lines, all well-formed (CR+LF at the end of every line). It is a UTF-8 file. Still, via binary search (see code below) we notice that for k>=7379, read_lines("text_file.zip", skip=k, n_max=1) no longer equals to read_lines("text_file.zip")[k+1], though they should!

After hrs on this issue, I have failed to identify what could be present in lines of the input file prior to the problem line (a ghost character of some kind) to cause read_lines w/ a nonzero skip to lose sync. In any case, read_lines() should not care, as its only separator is the end-of-line.

``` r
suppressMessages(library(tidyverse))

# Confirm UTF-8 encoding of included zip file (it contains a larger .txt)
fname <- "test_file.zip" # get it from: https://github.com/dan-reznik/read_lines_bug/blob/master/test_file.zip
guess_encoding(fname)
#> # A tibble: 4 x 2
#>   encoding     confidence
#>   <chr>             <dbl>
#> 1 UTF-8              1   
#> 2 Shift_JIS          1   
#> 3 windows-1252       0.68
#> 4 windows-1250       0.31

# Read all lines from zip (approx. 31.6k)
all_lines <- read_lines(fname)
length(all_lines)
#> [1] 31695

# Notice all lines have "well-formed" terminations with a carriage-return followed by a newline.
{
  s <- read_file(fname)
  print(s %>% str_count("\\r"))
  print(s %>% str_count("\\n"))
  print(s %>% str_count("\\r\\n"))
  print(s %>% str_count("\\n\\r"))
}
#> [1] 31695
#> [1] 31695
#> [1] 31695
#> [1] 0

# For this file, the separator is ";" (irrelevant for read_lines()), there should be 45 per line.
# However, notice a few lines have a non-standard number of separators (';'), namely: 46 and 48.
all_lines %>%
  str_count(";") %>%
  table
#> .
#>    45    46    48 
#> 31678    14     3

# List which lines have the wrong number of separators, as this will drive us to the bug.
all_lines %>%
  str_count(";") %>%
  {which(.!=45)}
#>  [1] 14579 24268 24269 26000 26792 26793 27535 29736 29737 29738 29755
#> [12] 29764 29936 29937 30383 30384 30385

# With `read_lines()`  read only the first line with the wrong number of separators,
# shown above to be line 14579. So "skip" that number minus one.
line1 <- read_lines(fname,
                    skip=14578,
                    n_max=1)

# Notice its content not only has a different number of separators,
# it's a different line altogether! (herein lies the bug)
all_lines[14579] %>% str_count(";")
#> [1] 48
line1 %>% str_count(";")
#> [1] 45
all_lines[14579] == line1
#> [1] FALSE

# BUG IS HERE: the line retrieved by `read_lines(skip=14578,n_max=1)` appears
# much later in the file, suggesting the reading under this skip+n_max has lost "sync".
(all_lines==line1)%>%which
#> [1] 17923

# find first line to cause loss of sync via binary search
find_weird_row <- function(n0,n_min,n_max) {
  l_skip <- read_lines(fname,skip=n0,n_max=1)
  l_all <- all_lines[n0+1]
  l_eq <- l_skip==l_all
  print(n0)
  #browser()
  if(n0%in%c(n_min,n_max)) {
    print(sprintf("line %d with l_eq=%s",
                  n0,
                  l_eq%>%as.character()))
    n0
  } else {
    if (!l_eq)
      find_weird_row(as.integer((n0+n_min)/2),n_min,n0)
    else
      find_weird_row(as.integer((n0+n_max)/2),n0,n_max)
  }
}

# IMPORTANT: binary search identifies that beyond line 7379, i.e.:
# read_lines(skip=7379,n_max=1) is no longer equal to all_lines[7380],
# recalling the latter is the complete read of the file via read_lines()
find_weird_row(15000,1,length(all_lines))
#> [1] 7379
```

Notes: 
- when skip and n_max are not defined (complete read), read_lines() works correctly
- this bug is not caused by the .zip (same behavior if started from the uncompressed txt)
- this is not related to encoding, in fact, I made sure the file inside the zip is UTF-8
- this issue seems to manifest itself with longer files only. potentially there's a character within this file being interpreted as a carriage return.
- this is an important bug to be solved because skip+n_max allows us to look at files progressively and debug problems without loading the entire file.

<sup>Created on 2019-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by juangomezduaso** [comment]
This file seems to have the problem reported in issue #991

**Comment by jimhester** [comment]
Closing in favor of #991
