### ISSUE TITLE
Build fails on IBM i due to invalid '-rpath' linker flag

### ISSUE THREAD

**Issue by ThePrez** [tidyverse/readr#992]
The linker on IBM i (and presumably AIX, since they use the same conventions) does not allow for the `-rpath` argument, so builds fail accordingly. This was seemingly introduced last August:
https://github.com/tidyverse/readr/commit/5e30b32ce22526ba1f227ad02aa6bc216ce182ea

If something like rpath is needed, the closest thing on AIX would be `-blibpath`

One could check UNAME for `OS400` (or `AIX`) and condition the `PKG_LIBS` syntax accordingly. 

I'd be willing to help develop/test a fix.

**Comment by ThePrez** [comment]
It is important to add that `-blibpath`, while "the closest thing we got," is still quite different from rpath. If we can jus omit the rpath option altogether that might be best, too. Older versions install just fine.

**Comment by jimhester** [comment]
I don't think there is a simple way to work around this, and IMB i and AIX are not systems we think most users will be using, however I will keep this in mind for future releases.

**Comment by ThePrez** [comment]
Would you welcome a PR if I (or someone on my team) took a stab and tested?

**Comment by jimhester** [comment]
The current devel version no longer relies on `-rpath`, so this should be fixed.
