### ISSUE TITLE
write_tsv() needs the option to never quote any fields

### ISSUE THREAD

**Issue by NikKrieger** [tidyverse/readr#993]
This is in the spirit of @cboettig's comment in #844:

> @jimhester I think this issue also impacts `write_tsv()`?  Looks like `readr` cannot write a IANA valid tsv file with quoted text, since there's not even an option(?) to not double-quote quotations?

Indeed, the main feature of the .tsv is that tab characters are disallowed in fields, thereby making quoting totally unnecessary.

So, I would argue that the problem isn't that `write_tsv()` needs an "option(?) to not double-quote quotations," but rather that `write_tsv()` needs an option to never quote anything. Setting `quote_escape = "none"` does not accomplish this, though I realize that this wasn't the intent behind it:

```r
library(tidyverse)

foo <- 
  tribble(
    ~name, ~catch_phrase,
    "Jane", 'I am 72" tall.',
    "John", '"No" means "no."'
  )

tmp <- tempfile()

write_tsv(foo, path = tmp, quote_escape = "none")

writeLines(readLines(tmp))

#> name	catch_phrase
#> Jane	"I am 72" tall."
#> John	""No" means "no.""
```

One has to resort to `write.table()` in order to obtain an IANA-compatible .tsv file out of a data frame like `foo`:

```r
tmp_base <- tempfile()
write.table(foo, file = tmp_base, quote = FALSE, sep = "\t", row.names = FALSE)
writeLines(readLines(tmp_base))

#> name	catch_phrase
#> Jane	I am 72" tall.
#> John	"No" means "no."
```

So for `write_tsv()`, there should be an option to never quote any fields. Perhaps there could also be an option to throw an error if a tab character is detected, but that's not my main concern in this issue.

**Comment by Ahhgust** [comment]
I am having what I believe is the same issue with the write_* family. Namely, if you write a (ragged) column, write_delim will quote the strings regardless if the parameter quote is set to FALSE or not.

e.g.,:
```
library(tidyverse)
library(stringr)

tibble(A=c("AA", "BBB", "CC"), B=c(1,1,2)) %>% 
   group_by(B) %>% 
   summarize(U=str_flatten(A, collapse="\t")) %>% 
   write_delim("foo", quote_escape=FALSE, delim="\t")

writeLines(readLines("foo"))
```

the last column in foo will contain quotation marks (sometimes). The attempt is to write a "ragged" TSV file, an attempt which fails when the file separator is the self-contained within the strings. One could argue that you shouldn't do this, but if quote=FALSE is supported I would argue that it should be consistently applied (and I personally like being able to write non-rectangular data even if it is somewhat outside of the scope of the project).
