### ISSUE TITLE
readr locales

### ISSUE THREAD

**Issue by Athanasiamo** [tidyverse/readr#998]
I was wondering where the specifications for the locales come from? 
While i always prefer to work in english locale, I some times need to set norwegian (nb) locale for files I am given from colleagues. 

But the output of `locale("nb")` does not give the expected outcome as what I am used to for Norwegian locales. Specifically, in Norway comma is decimal separator and dot/space is thousand separator. I know I can override this in locale, but should this not be default for both Norwegian locales?

``` r
library(readr)

locale("nb")
#> <locale>
#> Numbers:  123,456.78
#> Formats:  %AD / %AT
#> Timezone: UTC
#> Encoding: UTF-8
#> <date_names>
#> Days:   søndag (søn.), mandag (man.), tirsdag (tir.), onsdag (ons.),
#>         torsdag (tor.), fredag (fre.), lørdag (lør.)
#> Months: januar (jan.), februar (feb.), mars (mar.), april (apr.), mai
#>         (mai), juni (jun.), juli (jul.), august (aug.), september
#>         (sep.), oktober (okt.), november (nov.), desember (des.)
#> AM/PM:  a.m./p.m.

# Expected
locale("nb", decimal_mark = ",")
#> <locale>
#> Numbers:  123.456,78
#> Formats:  %AD / %AT
#> Timezone: UTC
#> Encoding: UTF-8
#> <date_names>
#> Days:   søndag (søn.), mandag (man.), tirsdag (tir.), onsdag (ons.),
#>         torsdag (tor.), fredag (fre.), lørdag (lør.)
#> Months: januar (jan.), februar (feb.), mars (mar.), april (apr.), mai
#>         (mai), juni (jun.), juli (jul.), august (aug.), september
#>         (sep.), oktober (okt.), november (nov.), desember (des.)
#> AM/PM:  a.m./p.m.
```

<sup>Created on 2019-05-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
If you look at the usage from `?locale`

```
Usage

     locale(date_names = "en", date_format = "%AD", time_format = "%AT",
       decimal_mark = ".", grouping_mark = ",", tz = "UTC",
       encoding = "UTF-8", asciify = FALSE)
```

The first argument of `locale()` is `date_names`, not a general locale setting. So `locale("nb")` only changes the the date names for a specific locale, we don't really have information on what the most common decimal separators and grouping marks are for every locale.

**Comment by Athanasiamo** [comment]
yes well, call my face palm! Sorry for ticketing something I should have noticed. So sorry.

**Comment by jimhester** [comment]
No worries, I agree it _would_ be nicer if we had this and you could just set the overall locale, but I don't know of any database that has this information.
